objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Custom_Design__c.object
<CustomObject>
    <description>Custom Object defining details of a CDS Form</description>
    <fields>
        <fullName>CDS_Status__c</fullName>
        <label>++ CDS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready for IDR</fullName>
                </value>
                <value>
                    <fullName>In DE</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>+(A) Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Custom_Design_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DIW_Opp_Control_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Opportunity of the related device</inlineHelpText>
        <label>Opp Control Number</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Custom_Design_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DIW_Option_Control_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It is an option of the related device</inlineHelpText>
        <label>++(O) Option Control Number</label>
        <referenceTo>Customer_Requirement__c</referenceTo>
        <relationshipLabel>Customer Design Specifications</relationshipLabel>
        <relationshipName>Customer_Design_Specifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Design Specification</label>
    <nameField>
        <displayFormat>CDS-{000000}</displayFormat>
        <label>Custom Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Design Specifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Requirement__c.object
<CustomObject>
    <description>This object is corresponding to DIW Option object.
Custom object Options defining detail of  Options for Deliverable Type Information.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Technical_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option_Stage__c</fullName>
        <label>~Option Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Engagement</fullName>
                    <default>true</default>
                    <label>Customer Engagement</label>
                </value>
                <value>
                    <fullName>Try for Fit</fullName>
                </value>
                <value>
                    <fullName>Bid and Quote</fullName>
                </value>
                <value>
                    <fullName>Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Design Execution</fullName>
                </value>
                <value>
                    <fullName>Prototype Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Customer Decision</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Placeholder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000000}</displayFormat>
        <label>Option ControlNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BnP_OptionUtilityTest.cls
/**
@Author <Cognizant Technology Solutions>
@name <BnP_OptionUtilityTest>
@CreateDate <14/10/2016>
@Description <Apex Test Class For BnP_OptionUtility>
@Version <>
@reference <>
*/
@isTest
public Class BnP_OptionUtilityTest 
{
    @TestSetup static void testdata() 
    {
        DataUtilTest.loadEnvironmentVariables();
    }
    Static TestMethod void GenericTr() 
    {
        List < RecordType > rt = [SELECT Description, DeveloperName, Id, IsActive, Name, SobjectType FROM RecordType where SobjectType = 'Customer_Requirement__c'];
        RecordType recordType = [Select Id from RecordType where Name = 'Customer' AND SObjectType = 'Account'];
        User thisUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        System.RunAs(thisUser) {}
        
        Map<String,Object> fieldValueAccMap = new Map<String,Object>();
        Account account1 = AccountDataFactory.createAccount(fieldValueAccMap);
        
        Map<String,Object> fieldValueOppMap = new Map<String,Object>();
        fieldValueOppMap.put('AccountId', account1.id);
        Opportunity opp1 = OpportunityDataFactory.createOpportunity(fieldValueOppMap);
        
        Map<String,Object> fieldValueOptionInfoMap = new Map<String,Object>();
        fieldValueOptionInfoMap.put('Opportunity__c',opp1.id);
        fieldValueOptionInfoMap.put('RecordTypeId',rt.get(1).Id);
        Customer_Requirement__c cr = BNP_DataFactory.createOption(fieldValueOptionInfoMap);
        
        Test.startTest();
        
        pagereference pag = page.BnP_OptionDeliverableType;
        pag.getParameters().put('Id', cr.id);
        Test.SetCurrentPage(pag);
        BnP_OptionUtility Generictr = new BnP_OptionUtility();
        List<Id> lstRecordId = new List<Id>();
        lstRecordId.add(cr.id);
        Generictr.updateOptionStages(lstRecordId, cr.Option_Stage__c);
        
        Test.stopTest();
    }
    Static TestMethod void GenericTrinvaliddata() 
    {    
        List < RecordType > rt = [SELECT Description, DeveloperName, Id, IsActive, Name, SobjectType FROM RecordType where SobjectType = 'Customer_Requirement__c'];
        RecordType recordType = [Select Id from RecordType where Name = 'Customer' AND SObjectType = 'Account'];
        User thisUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        System.RunAs(thisUser) {}
       
        Map<String,Object> fieldValueAccMap = new Map<String,Object>();
        Account account1 = AccountDataFactory.createAccount(fieldValueAccMap);
        
        Map<String,Object> fieldValueOppMap = new Map<String,Object>();
        fieldValueOppMap.put('AccountId', account1.id);
        Opportunity opp1 = OpportunityDataFactory.createOpportunity(fieldValueOppMap);
        
        Map<String,Object> fieldValueOptionInfoMap = new Map<String,Object>();
        fieldValueOptionInfoMap.put('Opportunity__c',opp1.id);
        fieldValueOptionInfoMap.put('RecordTypeId',rt.get(1).Id);
        Customer_Requirement__c cr = BNP_DataFactory.createOption(fieldValueOptionInfoMap);
        
        Test.startTest();
            pagereference pag = page.BnP_OptionDeliverableType;
            pag.getParameters().put('Id', cr.id);
            Test.SetCurrentPage(pag);
            BnP_OptionUtility Generictr = new BnP_OptionUtility();
            List<Id> lstRecordId = new List<Id>();
            lstRecordId.add(cr.id);
            Generictr.updateOptionStages(lstRecordId, 'abcd');
        Test.stopTest();
    }
    Static TestMethod void CDSStatus() 
    {
        List < RecordType > rt = [SELECT Description, DeveloperName, Id, IsActive, Name, SobjectType FROM RecordType where SobjectType = 'Customer_Requirement__c'];
        RecordType recordType = [Select Id from RecordType where Name = 'Customer' AND SObjectType = 'Account'];
        User thisUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        System.RunAs(thisUser) {}
        
        
        Map<String,Object> fieldValueAccMap = new Map<String,Object>();
        Account account1 = AccountDataFactory.createAccount(fieldValueAccMap);
        
        Map<String,Object> fieldValueOppMap = new Map<String,Object>();
        fieldValueOppMap.put('AccountId', account1.id);
        Opportunity opp1 = OpportunityDataFactory.createOpportunity(fieldValueOppMap);
        
        Map<String,Object> fieldValueOptionInfoMap = new Map<String,Object>();
        fieldValueOptionInfoMap.put('Opportunity__c',opp1.id);
        fieldValueOptionInfoMap.put('RecordTypeId',rt.get(1).Id);
        Customer_Requirement__c cr = BNP_DataFactory.createOption(fieldValueOptionInfoMap);
        
        Map<String,Object> fieldValueCustomDesignMap = new Map<String,Object>();
        fieldValueCustomDesignMap.put('Customer__c',account1.id);
        fieldValueCustomDesignMap.put('DIW_Opp_Control_Number__c',opp1.id);
        fieldValueCustomDesignMap.put('DIW_Option_Control_Number__c',cr.id);
        Custom_Design__c cd = CDS_DataFactory.createCDS(fieldValueCustomDesignMap);
        
        Test.startTest();
            pagereference pag = page.CDSViewPageFrame;
            pag.getParameters().put('Id',cd.id);
            Test.SetCurrentPage(pag);
            BnP_OptionUtility Generictr = new BnP_OptionUtility();
            List<Id> lstRecordId = new List<Id>();
            lstRecordId.add(cd.id);
            Generictr.updateCDSStatus(lstRecordId,cd.CDS_Status__c);
            Test.stopTest();
      }
      
       Static TestMethod void CDSStatusinvaliddata() 
    {    
        List < RecordType > rt = [SELECT Description, DeveloperName, Id, IsActive, Name, SobjectType FROM RecordType where SobjectType = 'Customer_Requirement__c'];
        RecordType recordType = [Select Id from RecordType where Name = 'Customer' AND SObjectType = 'Account'];
        User thisUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        System.RunAs(thisUser) {}
        
        Map<String,Object> fieldValueAccMap = new Map<String,Object>();
        Account account1 = AccountDataFactory.createAccount(fieldValueAccMap);
        
        Map<String,Object> fieldValueOppMap = new Map<String,Object>();
        fieldValueOppMap.put('AccountId', account1.id);
        Opportunity opp1 = OpportunityDataFactory.createOpportunity(fieldValueOppMap);
        
        Map<String,Object> fieldValueOptionInfoMap = new Map<String,Object>();
        fieldValueOptionInfoMap.put('Opportunity__c',opp1.id);
        fieldValueOptionInfoMap.put('RecordTypeId',rt.get(1).Id);
        Customer_Requirement__c cr = BNP_DataFactory.createOption(fieldValueOptionInfoMap);
        
        Map<String,Object> fieldValueCustomDesignMap = new Map<String,Object>();
        fieldValueCustomDesignMap.put('Customer__c',account1.id);
        fieldValueCustomDesignMap.put('DIW_Opp_Control_Number__c',opp1.id);
        fieldValueCustomDesignMap.put('DIW_Option_Control_Number__c',cr.id);
        Custom_Design__c cd = CDS_DataFactory.createCDS(fieldValueCustomDesignMap);
        
        Test.startTest();
            pagereference pag = page.CDSViewPageFrame;
            pag.getParameters().put('Id',cd.id);
            Test.SetCurrentPage(pag);
            BnP_OptionUtility Generictr = new BnP_OptionUtility();
            List<Id> lstRecordId = new List<Id>();
            lstRecordId.add(cd.id);
            Generictr.updateCDSStatus(lstRecordId,'abcd');
        Test.stopTest();
    }
    
}