objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account of the Opportunity this device is tied up. This is automatically populated during the Opportunity Program generation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Programs</relationshipLabel>
        <relationshipName>Opportunity_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program_Team_Member__c.object
<CustomObject>
    <description>The individual team members for Opportunity Program and Device records.</description>
    <fields>
        <fullName>Core_Team_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the the team member is from the account team which is considered core team and cannot be deleted on the UI.</description>
        <label>Core Team Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Device_Access__c</fullName>
        <description>The device access of the team member.</description>
        <label>Device Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalUserKeyField__c</fullName>
        <externalId>true</externalId>
        <label>ExternalUserKeyField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag_for_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag for Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_FAE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FAE ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Program_Access__c</fullName>
        <description>The opportunity program access of the team member.</description>
        <label>Opportunity Program Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <description>The parent Opportunity Program for the team member.</description>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Opportunity Program Team Members</relationshipLabel>
        <relationshipName>Opportunity_Program_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>The team role of the team member.</description>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Administrator</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Backup Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Business Planner</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Customer Tapeout Engineer</fullName>
                </value>
                <value>
                    <fullName>DE - Customer Support</fullName>
                </value>
                <value>
                    <fullName>DE - Enablements</fullName>
                </value>
                <value>
                    <fullName>DE - IP Technical</fullName>
                </value>
                <value>
                    <fullName>Design Win Team</fullName>
                </value>
                <value>
                    <fullName>DE - Tapeout</fullName>
                </value>
                <value>
                    <fullName>Fab Planner</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Primary Account Manager</fullName>
                </value>
                <value>
                    <fullName>Primary Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Primary Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Marketing</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Engineer</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Strategic Marketing</fullName>
                </value>
                <value>
                    <fullName>TD PI / YE</fullName>
                </value>
                <value>
                    <fullName>Field Design Center Engineer</fullName>
                </value>
                <value>
                    <fullName>Primary Factory AE</fullName>
                </value>
                <value>
                    <fullName>Physical Design Engineer</fullName>
                </value>
                <value>
                    <fullName>ASIC Packaging Applications Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The individual program team member.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Program Team Members</relationshipLabel>
        <relationshipName>Opportunity_Program_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Program Team Member</label>
    <nameField>
        <displayFormat>OPTM-{000000000}</displayFormat>
        <label>OPTM Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Program Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OppTeamMemberController.cls
/*
  Author: Anirban Roy
  Description: Opportunity Program Team Member controller class.
  History:
    ARoy  02182013  - code creation.
    VBharadwaj 06122013
*/

public class OppTeamMemberController {

        public List<OppProgramTeamMemberModel> OppProgramTMModelList{get;set;}
        public string contentIds{get;set;}
        public string OppProgramName{get;set;}
        public boolean editPer{get;set;}
        public final string Key;        
        Map<String, Opportunity_Program_Team_Member__c> opMap = new Map<String, Opportunity_Program_Team_Member__c>();
        public class OppProgramTeamMemberModel{
          public Opportunity_Program_Team_Member__c OPTM {get;set;}
        }
        
        public OppTeamMemberController(){
                
                
                OppProgramTMModelList=new List<OppProgramTeamMemberModel>();
                opMap = new Map<String, Opportunity_Program_Team_Member__c>();
                contentIds=apexpages.currentpage().getparameters().get('id');
            if(contentIds !=null)
            {
                Opportunity_Program__c oppPrg = [select name, Account__c from Opportunity_Program__c where id=:contentIds];
                OppProgramName = oppPrg.Name;
                key = oppPrg.Account__c;                
                for(Opportunity_Program_Team_Member__c oppPrgmTM : [SELECT Core_Team_Member__c,Device_Access__c,Id,Name,
                                        Opportunity_Program_Access__c,Opportunity_Program__c,SystemModstamp,Team_Role__c,
                                        User__c,User__r.Name,Flag_for_Delete__c,Is_FAE__c
                                        FROM Opportunity_Program_Team_Member__c 
                                        WHERE Opportunity_Program__c =:contentIds 
                                        ORDER BY Core_Team_Member__c desc])
                {
                 OppProgramTeamMemberModel optmMod = new OppProgramTeamMemberModel();
                 optmMod.OPTM=oppPrgmTM;
                 OppProgramTMModelList.add(optmMod);
                }
            }
            
            isEdit();
            if(editPer){
                addNewRow();
            }
                
        }
        
        public PageReference addNewRow(){
            Opportunity_Program_Team_Member__c optmTemp = new Opportunity_Program_Team_Member__c();
            OppProgramTeamMemberModel optmMod = new OppProgramTeamMemberModel();
            optmMod.OPTM=optmTemp;
            OppProgramTMModelList.add(optmMod);
            return null;
        }
        
        public void isEdit(){
            editPer = false;
            Id profileId = UserInfo.getProfileId();
            Profile prof = [select id,name from Profile where id = :profileId limit 1];
            /*Vixit to add the additional Profile as per Case No. 3229 */
            if(prof.Name=='System Administrator' || prof.Name=='GF System Admin' || prof.Name=='GF Global Admin' ){
                editPer = true;
            }
            else{               
                for(Opportunity_Program__Share oppPrgmSh : [select AccessLevel,Id,ParentId,RowCause,UserOrGroupId 
                                            from Opportunity_Program__Share
                                             where ParentId =:contentIds
                                                and UserOrGroupId= :UserInfo.getUserId()]){
                    if(oppPrgmSh!=null){
                        if(oppPrgmSh.AccessLevel=='Read'){
                            editPer=false;
                        }
                        else if(oppPrgmSh.AccessLevel=='Edit' || oppPrgmSh.AccessLevel=='All'){
                            editPer=true;
                        }
                    }
                    else{
                        editPer=false;
                    }
                                                
                }
            }
        }
    
    public PageReference Save(){
        
       try{
            opMap = new Map<String, Opportunity_Program_Team_Member__c>();
            PageReference opPage = new PageReference('/'+ contentIds);
            List<Opportunity_Program_Team_Member__c> optm = new List<Opportunity_Program_Team_Member__c>();
            List<Opportunity_Program_Team_Member__c> optmDel = new List<Opportunity_Program_Team_Member__c>();
            for(OppProgramTeamMemberModel optml :OppProgramTMModelList)
            {
                if(optml.OPTM.User__c !=null)
                {
                            if (optml.OPTM.Opportunity_Program_Access__c==null )
                            {
                                optml.OPTM.addError('Please specify Opportunity Program Access');
                            }
                        
                            if (optml.OPTM.Device_Access__c==null )
                            {
                                optml.OPTM.addError('Please specify Device Access');
                            }
                         
                            if (optml.OPTM.Team_Role__c==null )
                            {
                                optml.OPTM.addError('Please specify Team Role');
                                return null;                                
                            }                           
                        
                        if(optml.OPTM.Opportunity_Program__c ==null){
                                optml.OPTM.Opportunity_Program__c=contentIds;
                        }
            
                        optml.OPTM.ExternalUserKeyField__c = key  + '_' + optml.OPTM.User__c ;
                                    
                        if( optml.OPTM.Team_Role__c == 'Primary Account Manager' || 
                            optml.OPTM.Team_Role__c == 'Primary Customer Service Rep' || 
                            optml.OPTM.Team_Role__c == 'Backup Customer Service Rep' || 
                            optml.OPTM.Team_Role__c == 'Primary Field Engineer'){
                            if (opMap.containsKey(optml.OPTM.Team_Role__c+optml.OPTM.Opportunity_Program__c))
                            {
                                optml.OPTM.addError('Role and Seq duplicates.');
                                return null;
                            } 
                            else
                            {
                                opMap.put(optml.OPTM.Team_Role__c+optml.OPTM.Opportunity_Program__c, optml.OPTM);
                            }
                        }
                        
                        //------Start of duplicate check of user for same opportunity program----//
                        if(opMap.containsKey(optml.OPTM.User__c)){
                            optml.OPTM.addError('Duplicate User for same Opportunity Program');
                            return null;
                        }
                        else{
                            opMap.put(optml.OPTM.User__c,optml.OPTM);
                        }
                        //----End of duplicate check of user for same opportunity program----//
                                  
                        //Njain: reset the is FAE flag if the Role is changed from Account Manager
                        if( optml.OPTM != NULL && optml.OPTM.Id != NULL && 
                            optml.OPTM.Team_Role__c != 'Account Manager' && 
                            optml.OPTM.Team_Role__c != 'Primary Account Manager'){
                                optml.OPTM.Is_FAE__c = false;
                        }
                        
                        if(optml.OPTM.Flag_for_Delete__c){
                            optmDel.add(optml.OPTM);
                        }                                      
                        else{
                            optm.add(optml.OPTM);
                        }
                }    
            }
            if(optm!=null && optm.size()>0){
                upsert optm;
            }
            if(optmDel!=null && optmDel.size()>0){
                delete optmDel;
            }          
            return opPage;
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());  
            ApexPages.addMessage(myMsg);
        }
        return null;
    }
    
}