objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF( CONTAINS(Name, &apos;ADVANCED MICRO DEVICES&apos;) , &apos;AMD&apos;,  IF(CONTAINS(Name, &apos;BROADCOM&apos;) , &apos;Broadcom&apos;,  IF( CONTAINS(Name, &apos;QUALCOMM&apos;) , &apos;Qualcomm&apos;, &apos;Others&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Team_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Proxy</relationshipLabel>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fab_Assignment__c</fullName>
        <label>Fab Assignment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
                <value>
                    <fullName>ASIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_FAE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FAE ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Administrator</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Backup Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Business Planner</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Integration</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Customer Tapeout Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Engineer</fullName>
                </value>
                <value>
                    <fullName>DE - Customer Support</fullName>
                </value>
                <value>
                    <fullName>DE - Enablements</fullName>
                </value>
                <value>
                    <fullName>DE - IP Technical</fullName>
                </value>
                <value>
                    <fullName>Demand Planner</fullName>
                </value>
                <value>
                    <fullName>Design and Technology Support</fullName>
                </value>
                <value>
                    <fullName>Design Win Team</fullName>
                </value>
                <value>
                    <fullName>DE - Tapeout</fullName>
                </value>
                <value>
                    <fullName>Fab Planner</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Primary Account Manager</fullName>
                </value>
                <value>
                    <fullName>Primary Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Primary Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Marketing</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Engineer</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Strategic Marketing</fullName>
                </value>
                <value>
                    <fullName>TD PI / YE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Proxy</label>
    <nameField>
        <displayFormat>ATP-{000000}</displayFormat>
        <label>ATP Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Proxy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment_Variable__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Environment variables used across all custom codes.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Environment Variable</label>
</CustomObject>

objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will have the Customer Information of a Lot</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturing Lot</relationshipLabel>
        <relationshipName>Manufacturing_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device_ID_MES__c</fullName>
        <label>Device ID (MES)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab_Group__c</fullName>
        <label>Fab Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lot_Type__c</fullName>
        <description>Mapped to Lot_Type</description>
        <label>Lot Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QD_Email_Already_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QD Email Already Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QF_Email_Already_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QF Email Already Sent?</label>
        <type>Checkbox</type>
    </fields>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ManufacturingLotSendNotifications.cls
/*
    Author: Zymark Ambat
    Description: This Class is for Manufacturing Lot email notifications.
    History: 
        ZAmbat      12082014    - Code creation.
*/

public class ManufacturingLotSendNotifications {
    @future                
    public static void sendEmail(Set<Id> setMLIds) {
        List<Manufacturing_Lot__c> listML = [
            SELECT    Id
                      , Lot_Type__c
                      , Device_ID_MES__c
                      , QD_Email_Already_Sent__c
                      , QF_Email_Already_Sent__c
                      , Account_Name__c
                      , Account_Name__r.Name
                      , Fab_Group__c
            FROM      Manufacturing_Lot__c
            WHERE     Id IN :setMLIds
        ];
        
        Set<string> setQD = new Set<string>();
        Set<string> setQF = new Set<string>();
        for (Manufacturing_Lot__c m : [SELECT    Device_ID_MES__c
                                                 , QD_Email_Already_Sent__c
                                                 , QF_Email_Already_Sent__c
                                       FROM      Manufacturing_Lot__c
                                       WHERE     QD_Email_Already_Sent__c = true
                                                 OR QD_Email_Already_Sent__c = true]) {
            if (m.QD_Email_Already_Sent__c) {
                setQD.add(m.Device_ID_MES__c);
            }
            
            if (m.QF_Email_Already_Sent__c) {
                setQF.add(m.Device_ID_MES__c);
            }
        }
        
        List<Manufacturing_Lot__c> listUpdateML = new List<Manufacturing_Lot__c>();
        for (Manufacturing_Lot__c m : listML) {
            if (m.Lot_Type__c.startsWith('QD') && m.Device_ID_MES__c != null) {
                if (!setQD.contains(m.Device_ID_MES__c)) {
                    m.QD_Email_Already_Sent__c = true;
                    listUpdateML.add(m);
                }
            } else if (m.Lot_Type__c.startsWith('QF') && m.Device_ID_MES__c != null) {
                if (!setQF.contains(m.Device_ID_MES__c)) {
                    m.QF_Email_Already_Sent__c = true;
                    listUpdateML.add(m);
                }
            }
        }

        if (listUpdateML.size() > 0) {
            Set<Id> mlQDIds = new Set<Id>();
            Set<Id> mlQFIds = new Set<Id>();
            Set<Id> mlGShuttleIds = new Set<Id>();
            Map<Id, Manufacturing_Lot__c> mapML = new Map<Id, Manufacturing_Lot__c>();
            Set<Id> accountIds = new Set<Id>();
            for (Manufacturing_Lot__c m : listUpdateML) {
                if (m.Account_Name__r.Name == 'GLOBALSHUTTLE') {
                    mlGShuttleIds.add(m.Id);
                } else {
                    if (m.Lot_Type__c.startsWith('QD')) {
                        // Create Map for Manufacturing Lot - Account
                        mapML.put(m.Id, m);
                        accountIds.add(m.Account_Name__c);
                        mlQDIds.add(m.Id);
                    } else if (m.Lot_Type__c.startsWith('QF')) {
                        mlQFIds.add(m.Id);
                    }
                }
            }
            
            List<Messaging.SingleEmailMessage> listEmail = new List<Messaging.SingleEmailMessage>();
            
            // Get email template
            EmailTemplate et = [
                SELECT    Id
                FROM      EmailTemplate
                WHERE     DeveloperName = 'EPTS_Notification_VF_1'
            ];
    
            // QD
            if (mlQDIds.size() > 0) {
                // Create Map for Account - Account Team Proxy
                Map<Id, Account> mapATP = new Map<Id, Account>(); 
                mapATP = new Map<Id, Account>([SELECT Id
                                                   ,(SELECT User__c 
                                                          , User__r.Email
                                                          , Fab_Assignment__c
                                                          , Team_Role__c
                                                        FROM     Account_Team_Proxy__r 
                                                        WHERE    User__r.IsActive = true
                                                         AND (Team_Role__c IN ( 'Customer Engineer'
                                                                              , 'Field Application Engineer'
                                                                              , 'Field Technical Support'
                                                                              , 'Primary Field Technical Support'
                                                                              , 'Primary Field Application Engineer')
                                                            OR ( Team_Role__c = 'Account Manager' AND Is_FAE__c = TRUE)
                                                            OR ( Team_Role__c = 'Primary Account Manager' AND Is_FAE__c = TRUE) ))
                                                FROM  Account
                                                WHERE Id IN :accountIds]);
                
                // Contstruct the email
                for (Id i : mlQDIds) {
                    if (mapATP.get(mapML.get(i).Account_Name__c).Account_Team_Proxy__r.size() > 0) {
                        Map<Id, string> mapRecipients = new Map<Id, string>();
                        for (Account_Team_Proxy__c a : mapATP.get(mapML.get(i).Account_Name__c).Account_Team_Proxy__r) {
                            if (a.Team_Role__c == 'Customer Engineer') {
                                if (a.Fab_Assignment__c != null) {
                                    List<string> listFab = a.Fab_Assignment__c.split(';');
                                    Set<string> setFab = new Set<string>();
                                    setFab.addAll(listFab);
                                    if (setFab.contains(mapML.get(i).Fab_Group__c)) {
                                        mapRecipients.put(a.User__c, a.User__r.Email);
                                    }
                                }
                            } else {
                                mapRecipients.put(a.User__c, a.User__r.Email);
                            }
                        }
                        listEmail.add(ManufacturingLotSendNotifications.createEmail('QD', et.Id, i, mapRecipients));
                    }
                }
            }
            
            // QF
            if (mlQFIds.size() > 0) {
                for (Id i : mlQFIds) {
                    listEmail.add(ManufacturingLotSendNotifications.createEmail('QF', et.Id, i, null));
                }
            }
            
            // GlobalShuttle
            if (mlGShuttleIds.size() > 0) {
                for (Id i : mlGShuttleIds) {
                    listEmail.add(ManufacturingLotSendNotifications.createEmail('GS', et.Id, i, null));
                }
            }
            
            // Send Email
            if (listEmail.size() > 0 && !test.isRunningTest()) {
                Messaging.sendEmail(listEmail);
            }
            
            // Update
            ManufacturingLotTriggerStopper.hasExecuted = true;
            update listUpdateML;
        }
    }
    
    public static Messaging.SingleEmailMessage createEmail(string type, Id templateId, Id objectId, Map<Id, string> mapRecipients) {       
        // Send email to capture the template
        Messaging.reserveSingleEmailCapacity(type == 'QD' ? mapRecipients.size() : Environment_Variable__c.getInstance('EPTS_TO_ADDRESSES').Value__c.split(';').size());
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.templateId = templateId;
        
        List<Id> listUserId = new List<Id>();
        if (type == 'QD') {
            listUserId.addAll(mapRecipients.keySet());
        } else if (type == 'QF' || type == 'GS') {
            listUserId.add(Environment_Variable__c.getInstance('EPTS_TO_ADDRESSES').Value__c);
        }
        
        email.setTargetObjectId(listUserId[0]);
        if (type == 'QD') {
            mapRecipients.remove(listUserId[0]);
            if (mapRecipients.size() > 0) {
                email.setToAddresses(mapRecipients.values());                        
            }
        }
        email.setCCAddresses(Environment_Variable__c.getInstance('EPTS_CC_ADDRESSES').Value__c.split(';'));     
        email.setBCCAddresses(Environment_Variable__c.getInstance('EPTS_BCC_ADDRESSES').Value__c.split(';'));                       
        email.setWhatId(objectId);
        email.setSaveAsActivity(false);

        return email;
    }
}