objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Chip_Detail__c.object
<CustomObject>
    <fields>
        <fullName>PTRF__c</fullName>
        <description>PTRF associated to the chip</description>
        <label>PTRF</label>
        <referenceTo>PTRF__c</referenceTo>
        <relationshipLabel>Chip Details</relationshipLabel>
        <relationshipName>Chip_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chip Detail</label>
    <nameField>
        <label>Chip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chip Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Technology__c</fullName>
        <description>Computed value based on Process geometry.

Leading =&lt;32nm
Mainstream 40nm-90nm
Matured &gt;90nm</description>
        <formula>IF(  Process_Geometry_NM__c  &lt;=32, &quot;Leading Edge&quot;,
 IF(Process_Geometry_NM__c  &gt;=40  &amp;&amp; Process_Geometry_NM__c   &lt;=90 , &quot;Mainstream&quot;, 
  IF(Process_Geometry_NM__c  &gt;90, &quot;Matured&quot;, null   ) 
 
 ) 
)</formula>
        <inlineHelpText>Geometry Grouping of Leading Edge, Mainstream, Matured</inlineHelpText>
        <label>Process Technology</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active – Device is Active.
Inactive – Device EOL.  
Void – Cancel device.
On Hold - Device support activity On Hold. Reason is required.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DRT__c.object
<CustomObject>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated with the DRT</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>DRTs</relationshipLabel>
        <relationshipName>DRTs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Status of the DRT</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DRT</label>
    <nameField>
        <label>DRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRTs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Mask_Layer__c.object
<CustomObject>
    <fields>
        <fullName>Mask_Layer_Number__c</fullName>
        <description>This field stores the Mask Layer Number</description>
        <label>Mask Layer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Layer_Rev__c</fullName>
        <description>Mask Layer Revision</description>
        <label>Mask Layer Rev</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated to the Mask Layer</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>Mask Layers</relationshipLabel>
        <relationshipName>Mask_Layers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PTRF__c</fullName>
        <description>PTRF associated to the Mask layer</description>
        <label>PTRF</label>
        <referenceTo>PTRF__c</referenceTo>
        <relationshipLabel>Mask Layers</relationshipLabel>
        <relationshipName>Mask_Layers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ROM_Code__c</fullName>
        <description>ROM Code Value</description>
        <label>ROM Code</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Mask Layer</label>
    <nameField>
        <label>Mask Layer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Mask_Set_Title__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mask Set Title</label>
    <nameField>
        <label>Mask Set Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Set Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Opportunity Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pursuing</fullName>
                </value>
                <value>
                    <fullName>Design Won</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Loss</fullName>
                </value>
                <value>
                    <fullName>Dropped</fullName>
                </value>
                <value>
                    <fullName>In Production</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Process_Technology__c</fullName>
        <description>Computed value based on Process geometry.

Leading =&lt;32nm
Mainstream 40nm-90nm
Matured &gt;90nm</description>
        <formula>IF(  Process_Geometry_NM__c  &lt;=32, &quot;Leading Edge&quot;,
 IF(Process_Geometry_NM__c  &gt;=40  &amp;&amp; Process_Geometry_NM__c   &lt;=90 , &quot;Mainstream&quot;, 
  IF(Process_Geometry_NM__c  &gt;90, &quot;Matured&quot;, null   ) 
 
 ) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Process Technology</label>
        <type>Text</type>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Process_Technology__c.object
<CustomObject>
    <label>Process Technology</label>
    <nameField>
        <label>Process Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Technologies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PTRF__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Device associated</description>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>PTRF</relationshipLabel>
        <relationshipName>PTRF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <label>System MST</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order Status of PTRF</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Pending Submit</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Copy DB</fullName>
                </value>
                <value>
                    <fullName>Validation</fullName>
                </value>
                <value>
                    <fullName>MDP Approval</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle Updates</fullName>
                </value>
                <value>
                    <fullName>Perform DRC DRW</fullName>
                </value>
                <value>
                    <fullName>Perform Tapeout Options</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Jobview</fullName>
                </value>
                <value>
                    <fullName>Mask Making</fullName>
                </value>
                <value>
                    <fullName>GDS Errors</fullName>
                </value>
                <value>
                    <fullName>Validate PTRF vs Info File</fullName>
                </value>
                <value>
                    <fullName>Generate Info File</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>IP Merge</fullName>
                </value>
                <value>
                    <fullName>DB Error</fullName>
                </value>
                <value>
                    <fullName>Bump</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_Geo_Value__c</fullName>
        <label>Tech Geo Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PTRF</label>
    <nameField>
        <label>PTRF Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PTRF</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DRTCreateExtnTest.cls
/*
Author: Cognizant Technology Solutions
Company: 
Description:    This will be the controller class behind the Visualforce Page VFDRTCreate.
                This will also call the handler class DRTHandlerUtility which will contain
                all the business logic regarding the DRT Creation process. 
History:
    Cognizant     18032014     - Initial Version
    Cognizant     23032014     - Modified function saveFrameDRT change in save logic
    Cognizant     10052014     - Modified function populateChipDetails for null checking
*/

@istest(SeeAllData=false)
public class DRTCreateExtnTest 
{
    
    /**
    This method initialize data using throughout this test class.
    The create data method are: 
    - SwiftDataUtilityTest.customSystemData();
    @author     SWIFT TEAM
    @since      7-April-2015
    */
    @testSetup static void setup() {
        SwiftDataUtilityTest.customSystemData();
    }
    
   /*
   This test method tests the below functionality of the class DRTCreateExtn for PRIME DRT
    constructor 
    populateAccountOptions()
    populateMSTOptions()
    populateDrtTypeOptions()
    popuateTechGeoOptions()
    populateChipDetails()
    populateMaskLayers()
    addMaskLayers()
    saveAsActivate()  
  */  
  public static testMethod void TestDRTCreateExtn ()
  {
    Map<String,String> acctIdNameMap; 
    // comment-out, refactored with testSetup method setup()
    // SwiftDataUtilityTest.customSystemData();
                  
    Account acc = SwiftDataUtilityTest.createTestAccountForDRT();
      
    List<Mask_Set_Title__c> mstList=SwiftDataUtilityTest.maskSetTitleList(1);
    List<DRT__c> drtList=SwiftDataUtilityTest.createDRTList1(1,mstList[0],acc.Id);
    DRT__c drt=drtList[0];
    Opportunity oppr = SwiftDataUtilityTest.createOpportunityDRT(acc.Id);
    Opportunity_Program__c opprProg = SwiftDataUtilityTest.createOpportunityProgramDRT(acc.Id, oppr.Id);
    Process_Technology__c pt = SwiftDataUtilityTest.createProcessTechnologyForDRT();
    
    test.startTest();
    
    Device__c testDevice = SwiftDataUtilityTest.createDeviceWithPT(acc.Id,oppr.Id, opprProg.Id,pt.Id);
    PTRF__c ptrf=SwiftDataUtilityTest.createPTRF_ForDRT(mstList[0].Id, testDevice.Id,acc.id);
    Chip_Detail__c chip_Detail=SwiftDataUtilityTest.createChipDetailDRT(ptrf.Id);
    Mask_Layer__c maskLayer=SwiftDataUtilityTest.createMaskLayerDRT(ptrf);   
       
  ApexPages.currentPage().getParameters().put('retURL',System.Label.Internal_URL ) ;
  ApexPages.currentPage().getHeaders().put('Host',System.Label.Internal_URL );
  
  DRTCreateExtn objDRTCreateExtn= new DRTCreateExtn (new apexpages.StandardController(new DRT__c()));
  objDRTCreateExtn.drtName=drt.name;
  objDRTCreateExtn.populateAccountOptions();
  objDRTCreateExtn.acctIdNameMap.put(acc.Id,acc.Name);
  objDRTCreateExtn.selectedAccount=acc.id;
  objDRTCreateExtn.populateMSTOptions();
  system.assertNotEquals(objDRTCreateExtn.addRowMSTString,null);  // as addRowMSTString gets populated in the previous function       
  objDRTCreateExtn.baseMST=mstList[0].Id;
  system.assertNotEquals(objDRTCreateExtn.baseMSTName,null);
  boolean isGFEmployee = objDRTCreateExtn.isGFEmployee;
  boolean notSendEmail = objDRTCreateExtn.notSendEmail;
  
  objDRTCreateExtn.populateDrtTypeOptions(); 
   system.assertEquals(objDRTCreateExtn.drtTypeOptions.size(),3);  // as drt type gets populated in the previous function       
  system.assertNotEquals(objDRTCreateExtn.drtTypeOptions,null);  // as drt type gets populated in the previous function       
  
  objDRTCreateExtn.selectedDrtType='PRIME';
  objDRTCreateExtn.popuateTechGeoOptions();
  
  objDRTCreateExtn.selectedTechGeo = '0.02UM (20nm)';
  objDRTCreateExtn.populateChipDetails(); // proceed     
       
  objDRTCreateExtn.description='description';
  objDRTCreateExtn.populateMaskLayers();
 
  DRTHandlerUtility.MaskLayerWrapper maskLayerWrap = new DRTHandlerUtility.MaskLayerWrapper(maskLayer.Mask_Layer_Number__c,maskLayer.Mask_Layer_Rev__c,maskLayer.ROM_Code__c);
                   
  objDRTCreateExtn.selectedMaskLayerJSON = Json.serialize(new List<DRTHandlerUtility.MaskLayerWrapper>{maskLayerWrap});          
  DRTHandlerUtility.ChipWrapper cw = new DRTHandlerUtility.ChipWrapper(mstList[0].Id,chip_Detail.Name);          
  objDRTCreateExtn.mainTableChipListJSON = Json.serialize(new List<DRTHandlerUtility.ChipWrapper>{cw});
  objDRTCreateExtn.addMaskLayers();
  List<String> lstChipName =DRTCreateExtn.fetchChipNames(mstList[0].Id,'0.02UM');  
                    
    DRTCreateExtn.MainTableClass mtc=new DRTCreateExtn.MainTableClass(chip_Detail.Name,mstList[0].Id,ptrf.Id);
    List<DRTCreateExtn.MainTableClass> mtcList=new List<DRTCreateExtn.MainTableClass>();
    mtcList.add(mtc);
    String serializeMTC=Json.serialize(mtcList); 
   
    objDRTCreateExtn.mainTableJSON = serializeMTC;
    
    DRTCreateExtn.MaskLayerHeaderClass mlh1=new DRTCreateExtn.MaskLayerHeaderClass('111','TT','002');
    
    List<DRTCreateExtn.MaskLayerHeaderClass> mlhList=new List<DRTCreateExtn.MaskLayerHeaderClass>();
    mlhList.add(mlh1);
           
    String serializeMLH=Json.serialize(mlhList);  
   
    objDRTCreateExtn.maskLayerHeaderJSON = serializeMLH;
    
    DRTCreateExtn.MaskLayerContentClass mlc1=new DRTCreateExtn.MaskLayerContentClass('RM','RRC1');
    
    List<DRTCreateExtn.MaskLayerContentClass> mlcList=new List<DRTCreateExtn.MaskLayerContentClass>();
    mlcList.add(mlc1);
    
    List<List<DRTCreateExtn.MaskLayerContentClass>> lstMaskLayerContentData= new List<List<DRTCreateExtn.MaskLayerContentClass>>();
    lstMaskLayerContentData.add(mlcList);
    
    String serializeMLC=Json.serialize(lstMaskLayerContentData);
    objDRTCreateExtn.maskLayerContentJSON = serializeMLC;
 
    DRTCreateExtn.fetchChipLayerComboData(chip_Detail.Name,maskLayer.Mask_Layer_Number__c,mstList[0].Id,mstList[0].Id,ptrf.Tech_Geo_Value__c);
    
    DRTHandlerUtility.MaskLayerWrapper mlw = new DRTHandlerUtility.MaskLayerWrapper(maskLayer.Mask_Layer_Number__c,maskLayer.Mask_Layer_Rev__c,maskLayer.ROM_Code__c);
    String layerJSON = Json.serialize(new List<DRTHandlerUtility.MaskLayerWrapper>{mlw});
    
    DRTCreateExtn.fetchNewChipLayerData(chip_Detail.Name,layerJSON,mstList[0].Id,mstList[0].Id,ptrf.Tech_Geo_Value__c,1);
     
    Pagereference p1 = objDRTCreateExtn.saveAsActivate();
    if(p1 != null){
        String drtId=p1.getParameters().get('Id');
        DRT__c drtObj =[select id,name,Status__c from DRT__c where id = :drtId];
        system.assertEquals('MYMST0_PRIME_DRT_002.001', drtObj.Name);
        system.assertEquals('Active',drtObj.Status__c);
        } 
    
    test.stopTest();
  }
  
   /*
  This test method tests the below functionality of the class DRTCreateExtn PRIME DRT
    constructor 
    populateAccountOptions()
    populateMSTOptions()
    populateDrtTypeOptions()
    popuateTechGeoOptions()
    populateChipDetails()
    populateMaskLayers()
    addMaskLayers()
    saveAsDraft()  
  */
  public static testMethod void TestDRTCreateExtnSaveAsDraft ()
  {
    Map<String,String> acctIdNameMap; 
    // comment-out, refactor with testSetup method setup()
    // SwiftDataUtilityTest.customSystemData();
                  
    Account acc = SwiftDataUtilityTest.createTestAccountForDRT();
    List<Mask_Set_Title__c> mstList=SwiftDataUtilityTest.maskSetTitleList(1);
    List<DRT__c> drtList=SwiftDataUtilityTest.createDRTList1(1,mstList[0],acc.Id);
    DRT__c drt=drtList[0];
    Opportunity oppr = SwiftDataUtilityTest.createOpportunityDRT(acc.Id);
    Opportunity_Program__c opprProg = SwiftDataUtilityTest.createOpportunityProgramDRT(acc.Id, oppr.Id);
    Process_Technology__c pt = SwiftDataUtilityTest.createProcessTechnologyForDRT();
    
    test.startTest();
    
    Device__c testDevice = SwiftDataUtilityTest.createDeviceWithPT(acc.Id,oppr.Id, opprProg.Id,pt.Id);
    PTRF__c ptrf=SwiftDataUtilityTest.createPTRF_ForDRT(mstList[0].Id, testDevice.Id,acc.id);
    Chip_Detail__c chip_Detail=SwiftDataUtilityTest.createChipDetailDRT(ptrf.Id);
    Mask_Layer__c maskLayer=SwiftDataUtilityTest.createMaskLayerDRT(ptrf);   
       
  ApexPages.currentPage().getParameters().put('retURL',System.Label.Internal_URL ) ;
  ApexPages.currentPage().getHeaders().put('Host',System.Label.Internal_URL );
  
  DRTCreateExtn objDRTCreateExtn= new DRTCreateExtn (new apexpages.StandardController(new DRT__c()));
  objDRTCreateExtn.drtName=drt.name;
  objDRTCreateExtn.populateAccountOptions();
  objDRTCreateExtn.acctIdNameMap.put(acc.Id,acc.Name);
  objDRTCreateExtn.selectedAccount=acc.id;
  objDRTCreateExtn.populateMSTOptions();
  system.assertNotEquals(objDRTCreateExtn.addRowMSTString,null);  // as addRowMSTString gets populated in the previous function       
  objDRTCreateExtn.baseMST=mstList[0].Id;
  system.assertNotEquals(objDRTCreateExtn.baseMSTName,null);
  
  objDRTCreateExtn.populateDrtTypeOptions(); 
   system.assertEquals(objDRTCreateExtn.drtTypeOptions.size(),3);  // as drt type gets populated in the previous function       
  system.assertNotEquals(objDRTCreateExtn.drtTypeOptions,null);  // as drt type gets populated in the previous function       
  
  objDRTCreateExtn.selectedDrtType='PRIME';
  objDRTCreateExtn.popuateTechGeoOptions();
  
  objDRTCreateExtn.selectedTechGeo = '0.02UM (20nm)';
  objDRTCreateExtn.populateChipDetails(); // proceed     
       
  objDRTCreateExtn.description='description';
  objDRTCreateExtn.populateMaskLayers();
 
  DRTHandlerUtility.MaskLayerWrapper maskLayerWrap = new DRTHandlerUtility.MaskLayerWrapper(maskLayer.Mask_Layer_Number__c,maskLayer.Mask_Layer_Rev__c,maskLayer.ROM_Code__c);
                   
  objDRTCreateExtn.selectedMaskLayerJSON = Json.serialize(new List<DRTHandlerUtility.MaskLayerWrapper>{maskLayerWrap});          
  DRTHandlerUtility.ChipWrapper cw = new DRTHandlerUtility.ChipWrapper(mstList[0].Id,chip_Detail.Name);          
  objDRTCreateExtn.mainTableChipListJSON = Json.serialize(new List<DRTHandlerUtility.ChipWrapper>{cw});
  objDRTCreateExtn.addMaskLayers();
  List<String> lstChipName =DRTCreateExtn.fetchChipNames(mstList[0].Id,'0.02UM');  
          
                    
    DRTCreateExtn.MainTableClass mtc=new DRTCreateExtn.MainTableClass(chip_Detail.Name,mstList[0].Id,ptrf.Id);
    List<DRTCreateExtn.MainTableClass> mtcList=new List<DRTCreateExtn.MainTableClass>();
    mtcList.add(mtc);
    String serializeMTC=Json.serialize(mtcList); 
   
    objDRTCreateExtn.mainTableJSON = serializeMTC;
    
    DRTCreateExtn.MaskLayerHeaderClass mlh1=new DRTCreateExtn.MaskLayerHeaderClass('111','TT','002');
    
    List<DRTCreateExtn.MaskLayerHeaderClass> mlhList=new List<DRTCreateExtn.MaskLayerHeaderClass>();
    mlhList.add(mlh1);
           
    String serializeMLH=Json.serialize(mlhList);  
   
    objDRTCreateExtn.maskLayerHeaderJSON = serializeMLH;
    
    DRTCreateExtn.MaskLayerContentClass mlc1=new DRTCreateExtn.MaskLayerContentClass('RM','RRC1');
    
    List<DRTCreateExtn.MaskLayerContentClass> mlcList=new List<DRTCreateExtn.MaskLayerContentClass>();
    mlcList.add(mlc1);
    
    List<List<DRTCreateExtn.MaskLayerContentClass>> lstMaskLayerContentData= new List<List<DRTCreateExtn.MaskLayerContentClass>>();
    lstMaskLayerContentData.add(mlcList);
    
    String serializeMLC=Json.serialize(lstMaskLayerContentData);
    objDRTCreateExtn.maskLayerContentJSON = serializeMLC;
 
    DRTCreateExtn.fetchChipLayerComboData(chip_Detail.Name,maskLayer.Mask_Layer_Number__c,mstList[0].Id,mstList[0].Id,ptrf.Tech_Geo_Value__c);
    
    DRTHandlerUtility.MaskLayerWrapper mlw = new DRTHandlerUtility.MaskLayerWrapper(maskLayer.Mask_Layer_Number__c,maskLayer.Mask_Layer_Rev__c,maskLayer.ROM_Code__c);
    String layerJSON = Json.serialize(new List<DRTHandlerUtility.MaskLayerWrapper>{mlw});
    
    DRTCreateExtn.fetchNewChipLayerData(chip_Detail.Name,layerJSON,mstList[0].Id,mstList[0].Id,ptrf.Tech_Geo_Value__c,1);
     
    Pagereference p1 = objDRTCreateExtn.saveAsDraft();
    if(p1 != null){
        String drtId=p1.getParameters().get('Id');
        DRT__c drtObj =[select id,name,Status__c from DRT__c where id = :drtId];
        system.assertEquals('MYMST0_PRIME_DRT_002.001', drtObj.Name);
        system.assertEquals('Draft',drtObj.Status__c);
        } 
    
    test.stopTest();
  }
  
   /*
  This test method tests the below functionality of the class DRTCreateExtn FRAME DRT
    constructor 
    populateAccountOptions()
    populateMSTOptions()
    populateDrtTypeOptions()
    popuateTechGeoOptions()
    populateChipDetails()
    populateMaskLayers()
    addMaskLayers()
    saveAsActivate()  
  */
   public static testMethod void TestDRTCreateExtnForFrame ()
  {
        // comment-out, refactor with testSetup method setup()
        // SwiftDataUtilityTest.customSystemData();
        Account acc = SwiftDataUtilityTest.createTestAccountForDRT();
        List<Mask_Set_Title__c> mstList=SwiftDataUtilityTest.maskSetTitleList(1);
        List<DRT__c> drtList=SwiftDataUtilityTest.createDRTList1(1,mstList[0],acc.Id);
        DRT__c drt=drtList[0];  
        Opportunity oppr = SwiftDataUtilityTest.createOpportunityDRT(acc.Id);
        Opportunity_Program__c opprProg = SwiftDataUtilityTest.createOpportunityProgramDRT(acc.Id, oppr.Id); 
        Process_Technology__c pt = SwiftDataUtilityTest.createProcessTechnologyForDRT();
        
        test.startTest();
        
        Device__c testDevice = SwiftDataUtilityTest.createDeviceWithPT(acc.Id,oppr.Id, opprProg.Id,pt.Id);
        PTRF__c ptrf=SwiftDataUtilityTest.createPTRF_ForDRT(mstList[0].Id, testDevice.Id,acc.id);
        Chip_Detail__c chip_Detail=SwiftDataUtilityTest.createChipDetailDRT(ptrf.Id);
        Mask_Layer__c maskLayer=SwiftDataUtilityTest.createMaskLayerDRT(ptrf);   
       
        ApexPages.currentPage().getParameters().put('retURL',System.Label.Internal_URL ) ;
        ApexPages.currentPage().getHeaders().put('Host',System.Label.Internal_URL );
        
        //Frame DRT 
        
       DRTCreateExtn objDRTCreateExtn= new DRTCreateExtn (new apexpages.StandardController(new DRT__c()));
       objDRTCreateExtn.drtName=drt.name;
       objDRTCreateExtn.populateAccountOptions();
       objDRTCreateExtn.acctIdNameMap.put(acc.Id,acc.Name);
       objDRTCreateExtn.selectedAccount=acc.id;
       objDRTCreateExtn.populateMSTOptions();
       system.assertNotEquals(objDRTCreateExtn.addRowMSTString,null);  
       objDRTCreateExtn.baseMST=mstList[0].Id;
       system.assertNotEquals(objDRTCreateExtn.baseMSTName,null);
       objDRTCreateExtn.populateDrtTypeOptions();
       system.assertEquals(objDRTCreateExtn.drtTypeOptions.size(),3);  // as drt type gets populated in the previous function       
       system.assertNotEquals(objDRTCreateExtn.drtTypeOptions,null);  // as drt type gets populated in the previous function       
               
       objDRTCreateExtn.selectedDrtType='FRAME';
       objDRTCreateExtn.popuateTechGeoOptions();          
      
       objDRTCreateExtn.selectedTechGeo = '0.02UM (20nm)';
       objDRTCreateExtn.populateChipDetails(); // proceed          
       objDRTCreateExtn.description='description';
       objDRTCreateExtn.populateMaskLayers();     
       DRTCreateExtn.FrameTableClass ftc = new DRTCreateExtn.FrameTableClass(mstList[0].Id,maskLayer.Mask_Layer_Number__c,'AA','22',maskLayer.Mask_Layer_Number__c,maskLayer.ROM_Code__c);
       List<DRTCreateExtn.FrameTableClass> ftcList=new List<DRTCreateExtn.FrameTableClass>();
       ftcList.add(ftc);
        
       String serializeFTC=Json.serialize(ftcList);
       objDRTCreateExtn.frameTableJSON = serializeFTC;
       DRTCreateExtn.fetchLayerNos(mstList[0].Id,'0.02UM');            
       DRTCreateExtn.fetchMaskRevROMCode(mstList[0].Id,'111','0.02UM');
       objDRTCreateExtn.populateMSTOptions();
       system.assertNotEquals(objDRTCreateExtn.addRowMSTString,null);  
       objDRTCreateExtn.populateDrtTypeOptions();          
       system.assertEquals(objDRTCreateExtn.drtTypeOptions.size(),3);  // as drt type gets populated in the previous function       
       system.assertNotEquals(objDRTCreateExtn.drtTypeOptions,null);  // as drt type gets populated in the previous function       
     
       objDRTCreateExtn.popuateTechGeoOptions();
      
       objDRTCreateExtn.populateChipDetails(); // proceed
       objDRTCreateExtn.description='description';
       objDRTCreateExtn.populateMaskLayers();     
       
       list<string> lstMaskLayerNo = new list<string>();
       lstMaskLayerNo.add((String.valueOf(maskLayer.Mask_Layer_Number__c)));
       DRTCreateExtn.fetchChipNames(mstList[0].Id,'0.02UM');
          
          
       DRTCreateExtn.MainTableClass mtc=new DRTCreateExtn.MainTableClass(chip_Detail.Name,mstList[0].Id,ptrf.Id);
       List<DRTCreateExtn.MainTableClass> mtcList=new List<DRTCreateExtn.MainTableClass>();
       mtcList.add(mtc);
       String serializeMTC=Json.serialize(mtcList);
       objDRTCreateExtn.mainTableJSON = serializeMTC;
       
       DRTCreateExtn.MaskLayerHeaderClass mlh1=new DRTCreateExtn.MaskLayerHeaderClass('111','TT','002');
       List<DRTCreateExtn.MaskLayerHeaderClass> mlhList=new List<DRTCreateExtn.MaskLayerHeaderClass>();
       mlhList.add(mlh1);
       
       String serializeMLH=Json.serialize(mlhList);
       objDRTCreateExtn.maskLayerHeaderJSON = serializeMLH;
       
       DRTCreateExtn.MaskLayerContentClass mlc1=new DRTCreateExtn.MaskLayerContentClass('RM','RRC1');
        List<DRTCreateExtn.MaskLayerContentClass> mlcList=new List<DRTCreateExtn.MaskLayerContentClass>();
        mlcList.add(mlc1);
        
        List<List<DRTCreateExtn.MaskLayerContentClass>> lstMaskLayerContentData= new List<List<DRTCreateExtn.MaskLayerContentClass>>();
        lstMaskLayerContentData.add(mlcList);
        
        String serializeMLC=Json.serialize(lstMaskLayerContentData);
        objDRTCreateExtn.maskLayerContentJSON = serializeMLC;
        objDRTCreateExtn.baseMST=mstList[0].Id;
        objDRTCreateExtn.baseMSTName=mstList[0].name;
        objDRTCreateExtn.selectedDrtType='FRAME';
        objDRTCreateExtn.saveAsActivate(); 
        objDRTCreateExtn.refreshPage();
        test.stopTest();
  }
}