objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Profile__c</fullName>
        <inlineHelpText>Choose the Account Profile that best describe the Customer</inlineHelpText>
        <label>Account Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fabless - Emerging</fullName>
                </value>
                <value>
                    <fullName>Fabless - Medium (&gt;$10M SAM)</fullName>
                </value>
                <value>
                    <fullName>Fabless - Large (&gt;$100M SAM)</fullName>
                </value>
                <value>
                    <fullName>IDM FabLite - (&gt;50%outsourced)</fullName>
                </value>
                <value>
                    <fullName>IDM - (&lt;50% outsources)</fullName>
                </value>
                <value>
                    <fullName>System - (end-product manu.)</fullName>
                </value>
                <value>
                    <fullName>Reseller - (Channel and ASIC)</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Account_Number__c</fullName>
        <inlineHelpText>Add Leading Zero if number is less than 6 digit</inlineHelpText>
        <label>SAP Account Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Short Name</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Management_System__c.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_Number__c</fullName>
        <formula>Customer_Name__r.SAP_Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account Number</label>
        <type>Text</type>
    </fields>
    <label>Form Management System (FMS)</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Form Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Management Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FMSDirectionClassTest.cls
/*
 * @ Author :- Abhita Bansal
 * @ Description :- contains the test logic for FMSDirectionClass Class.
 * @ Date :- 06/08/2017
 * @ Change History :-  
 **/
@isTest
public class FMSDirectionClassTest {
    
    @testSetup
    static void testDataSetup(){
        DataUtilTest.loadEnvironmentVariables();

        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();

        Map<String,Object> fieldValueAccMap = new Map<String,Object>();
        fieldValueAccMap.put('Name', 'Test Account1');            
        fieldValueAccMap.put('stage__c', 'Unqualified');        
        fieldValueAccMap.put('sub_type__c', 'Direct');
        fieldValueAccMap.put('site_department__c', 'Test Department');          
        fieldValueAccMap.put('transaction_type__c', 'transactional');                          
        fieldValueAccMap.put('region__c', 'APJ');        
        fieldValueAccMap.put('Corporate_Address_1__c', 'Test Address 1');          
        fieldValueAccMap.put('Corporate_City__c', 'Lee');                
        fieldValueAccMap.put('Corporate_Country__c', 'Japan');
        fieldValueAccMap.put('Bill_To_Address_1__c', 'Test Address 1');          
        fieldValueAccMap.put('Bill_To_City__c', 'Test City');            
        fieldValueAccMap.put('Bill_To_Country__c', 'Singapore');        
        fieldValueAccMap.put('recordtypeid', rt); 
        fieldValueAccMap.put('short_name__c', 'TestAcct1');
        fieldValueAccMap.put('SAP_Account_Number__c', '001234');
        fieldValueAccMap.put('account_profile__c', 'Fabless - Emerging');
        fieldValueAccMap.put('Process_Tech_Interested__c', 'Mature (> 0.11um)');
        fieldValueAccMap.put('Sales_Territory__c', 'Japan Korea');
        fieldValueAccMap.put('financial_territory__c', 'Japan Korea');
        fieldValueAccMap.put('Organization_Unit__c', 'GF Investment LLC OU');
        fieldValueAccMap.put('Fab_9_10__c', 'Yes');

        User thisUser = DeviceChecklistTestDataUtils.createUserWithDCAdmin('System Administrator');  
        System.runAs(thisUser){
            try{
                Account accobj = AccountDataFactory.createAccount(fieldValueAccMap);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }
        }
    }

    static Account getAccount(String name){
        Account acc = [select id, Name from Account where name = :name];
        return acc;
    }

    static Map<String,Object> CreatefieldValueFormMap(Account accObj, Id mainformId) {
        Map<String,Object> fieldValueFormMap = new Map<String,Object>();
        fieldValueFormMap.put('Customer_Name__c', accObj.Id);
        fieldValueFormMap.put('Main_Form_Id__c', mainformId);
        fieldValueFormMap.put('Parent_Form_Id__c', mainformId);
        fieldValueFormMap.put('Customer__c', accObj.Name);
        return fieldValueFormMap;
    }

    static Map<String,Object> CreatefieldValueFormMapSP(Account accObj, Id mainformId) {
        Map<String,Object> fieldValueFormMap = new Map<String,Object>();
        fieldValueFormMap.put('Customer_Name__c', accObj.Id);
        fieldValueFormMap.put('Main_Form_Id__c', mainformId);
        fieldValueFormMap.put('Customer__c', accObj.Name);
        return fieldValueFormMap;
    }

    static testMethod void redirectToTest() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.RIT, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();

            PageReference pageRef = Page.FMSDirectionEditPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectTo();

            System.assert(pr.getUrl().contains('/apex/FMSRITFormNewEditPage1?id='+fmsRec.id+'&pageNo=1'));

            Test.stopTest();
        }
    }
      
    static testMethod void redirectToTest1() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest1()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.IMC, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest1()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionEditPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectTo();

            System.assert(pr.getUrl().contains('/apex/FMSIMCFormPage?id='+fmsRec.id+'&pageNo=1'));

            Test.stopTest();
        }
    }
      
    static testMethod void redirectToTest2() {

        Account accobj = getAccount('Test Account1');
        
        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsDDRRec;
            Form_Management_System__c fmsRec;
            Form_Management_System__c fmsMainRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest2()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.RIT, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest2()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
                    
            Map<String,Object> fieldValueCFormMap1 = CreatefieldValueFormMap(accobj, fmsRec.Id);
            try {
                fmsDDRRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap1, FMSDataFactory.FormType.DDR, true);     
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest2()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            PageReference pageRef = Page.FMSDirectionEditPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsDDRRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsDDRRec));
            PageReference pr = directExt.redirectTo();

            System.assert(pr.getUrl().contains('/apex/FMSDDRFormPage?id='+fmsDDRRec.id)); 

            Test.stopTest();
        }       
    }

    static testMethod void redirectToTest3() {

        Account accobj = getAccount('Test Account1');
        
        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsRec;
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsDDRRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest3()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.RIT, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest3()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
           
            Map<String,Object> fieldValueCFormMap1 = CreatefieldValueFormMap(accobj, fmsRec.Id);
            try {
                fmsDDRRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap1, FMSDataFactory.FormType.DDR, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest3()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            PageReference pageRef = Page.FMSDirectionViewPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsDDRRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsDDRRec));
            PageReference pr = directExt.redirectToView();

            System.assert(pr.getUrl().contains('/apex/FMSDDRFormViewPage?id='+fmsDDRRec.id)); 

            Test.stopTest();
        }    
        
    }

    static testMethod void redirectToTest4() {  

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest4()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.RIT, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest4()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionViewPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectToView();

            System.assert(pr.getUrl().contains('/apex/FMSRITFormViewPage?id='+fmsRec.id+'&pageNo=1'));
            
            Test.stopTest();
        }
    }
      
    static testMethod void redirectToTest5() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest5()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMap(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.IMC, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest5()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionViewPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectToView();

            System.assert(pr.getUrl().contains('/apex/FMSIMCFormViewPage?id='+fmsRec.id+'&pageNo=1'));
            
            Test.stopTest();
        }
    }

    static testMethod void redirectToTest6() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest6()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionEditPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsMainRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsMainRec));
            PageReference pr = directExt.redirectTo();

            System.assert(pr.getUrl().contains('/apex/FMSmainFormCreationPg1?id='+fmsMainRec.id+'&pageNo=1'));
            
            Test.stopTest();
        }
    }

    static testMethod void redirectToTest7() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest7()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionViewPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsMainRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsMainRec));
            PageReference pr = directExt.redirectToView();

            System.assert(pr.getUrl().contains('/apex/FMSmainFormViewPage?id='+fmsMainRec.id+'&pageNo=1'));
            
            Test.stopTest();
        }
    }

    static testMethod void redirectToTest8() {

        Account accobj = getAccount('Test Account1');
        
        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest8()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMapSP(accobj, fmsMainRec.Id);
            //try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.SP, true);
            /*} catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest8()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }*/

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionViewPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectToView();

            System.assert(pr.getUrl().contains('/apex/FMSStepPlanFormView?id='+fmsRec.id));
            
            Test.stopTest();
        }
    }

    static testMethod void redirectToTest9() {

        Account accobj = getAccount('Test Account1');

        system.runAs(FMSDataFactory.testUser){
            Form_Management_System__c fmsMainRec;
            Form_Management_System__c fmsRec;

            Map<String,Object> fieldValueMFormMap = CreatefieldValueFormMap(accobj, null);
            try {
                fmsMainRec = FMSDataFactory.createFMSRecord(fieldValueMFormMap, FMSDataFactory.FormType.Main, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest9()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Map<String,Object> fieldValueCFormMap = CreatefieldValueFormMapSP(accobj, fmsMainRec.Id);
            try {
                fmsRec = FMSDataFactory.createFMSRecord(fieldValueCFormMap, FMSDataFactory.FormType.SP, true);
            } catch(Exception e){
                UtilityCls.saveExceptionLog(FMSDirectionClassTest.class.getName(), 'redirectToTest9()', '', 'Bug', '', '', 'Error', e.getTypeName(), 'FMS', e, 0);
            }

            Test.startTest();
            
            PageReference pageRef = Page.FMSDirectionEditPage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', fmsRec.id);
            
            FMSDirectionClass directExt = new FMSDirectionClass(new ApexPages.StandardController(fmsRec));
            PageReference pr = directExt.redirectTo();

            System.assert(pr.getUrl().contains('/apex/FMSStepPlanEditForm?id='+fmsRec.id));

            Test.stopTest();
        }
    }

}