objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <inlineHelpText>Enter one or more Market Segments that the Customer participates.</inlineHelpText>
        <label>Market Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Compute, Connect, Store (CCS)</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial,Medical &amp;Scientific</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device_Sourcing__c</fullName>
        <description>Identify device sourcing. 1st Source, 2nd Source
Do not pick NONE.</description>
        <inlineHelpText>Identify device sourcing. 1st Source, 2nd Source
Do not pick NONE.</inlineHelpText>
        <label>Device Sourcing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Source</fullName>
                </value>
                <value>
                    <fullName>First Source</fullName>
                </value>
                <value>
                    <fullName>Second Source</fullName>
                </value>
                <value>
                    <fullName>Multi Source</fullName>
                </value>
                <value>
                    <fullName>NONE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Application__c</fullName>
        <description>To identify the End Application of the device</description>
        <inlineHelpText>To identify the End Application of the device</inlineHelpText>
        <label>End Application</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Body</fullName>
                </value>
                <value>
                    <fullName>Powertrain</fullName>
                </value>
                <value>
                    <fullName>Driver Information</fullName>
                </value>
                <value>
                    <fullName>Safety &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Others - Automotive</fullName>
                </value>
                <value>
                    <fullName>Broadband Client</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Others - CCS</fullName>
                </value>
                <value>
                    <fullName>Desktop PC</fullName>
                </value>
                <value>
                    <fullName>Set Top Box</fullName>
                </value>
                <value>
                    <fullName>Video Games</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>Others - Consumer</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Security &amp; Energy</fullName>
                </value>
                <value>
                    <fullName>Smart Card</fullName>
                </value>
                <value>
                    <fullName>Others - IMS</fullName>
                </value>
                <value>
                    <fullName>Cell Handset</fullName>
                </value>
                <value>
                    <fullName>Mobile PC</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>Others - Mobility</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
                <value>
                    <fullName>Others - AD</fullName>
                </value>
                <value>
                    <fullName>Machine Learning</fullName>
                </value>
                <value>
                    <fullName>IoT - Automotive</fullName>
                </value>
                <value>
                    <fullName>IoT - Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_Device_Geometry__c</fullName>
        <description>The Geometry field is created for Internal Device.</description>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.060UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.086UM</fullName>
                </value>
                <value>
                    <fullName>0.09UM</fullName>
                </value>
                <value>
                    <fullName>0.11UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.14UM</fullName>
                </value>
                <value>
                    <fullName>0.152UM</fullName>
                </value>
                <value>
                    <fullName>0.153UM</fullName>
                </value>
                <value>
                    <fullName>0.15UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.17UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.20UM</fullName>
                </value>
                <value>
                    <fullName>0.22UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.30UM</fullName>
                </value>
                <value>
                    <fullName>0.32UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <inlineHelpText>If unsure, refer Opportunity or Opportunity Program objects.</inlineHelpText>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Compute, Connect, Store (CCS)</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial,Medical &amp;Scientific</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <inlineHelpText>Identify Tapeout type. Do not pick Retrofit.</inlineHelpText>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>Full Layer Retrofit</fullName>
                </value>
                <value>
                    <fullName>TD Test Chip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <recordTypes>
        <fullName>Device</fullName>
        <active>true</active>
        <description>Unsorted Wafer Device</description>
        <label>Device</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Compute, Connect, Store (CCS)</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial,Medical &amp;Scientific</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account of the Opportunity this device is tied up. This is automatically populated during the Opportunity Program generation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Programs</relationshipLabel>
        <relationshipName>Opportunity_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>The Opportunity Market Segment.</description>
        <formula>TEXT(Opportunity__r.Market_Segment__c)</formula>
        <inlineHelpText>Read-Only Field : Only editable at the Opportunity level</inlineHelpText>
        <label>Market Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>HCM_Login_ID__c</fullName>
        <description>Updated from the HCM Employee record</description>
        <label>HCM Login ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProposalSharingTest.cls
/*
  Author: Shivam Sharma
  Description: This is the test class for the class "ProposalSharing"
  History:
    SSharma        12-12-2016    - code creation.              
*/
@isTest(SeeAllData=false)
public class ProposalSharingTest{

    private static User u;
    private static Account acc;
    private static Device__c device;
    
    private static void initialize(){
        
        DataUtilTest.loadEnvironmentVariables();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        u = new User(Alias = 'staCPQ', Email='standarduserCPQ@testorg.com',
        EmailEncodingKey='UTF-8', LastName='TestingCPQ', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='standarduserCPQ@testorg.com', HCM_Login_Id__c = 'Test');
        insert u;
        
            acc = new Account(Name = 'Test Account');
            insert acc;
            System.assert(acc.id != null);
            Opportunity_Program__c op = new Opportunity_Program__c();
            insert op;
            System.assert(op.id != null);
            device = new Device__c(Name = 'Test_Device', Account__c = acc.Id, Tapeout_Type__c = 'Test', Device_Sourcing__c = 'Test', End_Application__c = 'Test', Market_Segment__c = 'Test', Opportunity_Program__c = op.id, Internal_Device_Geometry__c = 'Test', Internal_Device_Process_Family__c = 'Test');
            insert device;
            System.assert(device.id != null);
    }
    
    static testMethod void test_insertWithoutAccountnDevice(){
        initialize();
        Test.startTest();
                Apttus_Proposal__Proposal__c newProposal = new Apttus_Proposal__Proposal__c();
                insert newProposal;
                System.assert(newProposal.id != null);
        Test.stopTest();
    }        
    static testMethod void test_insertWithAccount(){
        initialize();
        Test.startTest();
                Apttus_Proposal__Proposal__c newProposal = new Apttus_Proposal__Proposal__c();
                newProposal.Apttus_Proposal__Account__c = acc.Id;
                insert newProposal;
            Test.stopTest();
    }
       
   static testMethod void test_insertWithDevice(){
        initialize();
        Test.startTest();
                Apttus_Proposal__Proposal__c newProposal = new Apttus_Proposal__Proposal__c();
                newProposal.Device__c = device.id;
                newProposal.Apttus_Proposal__Account__c = acc.Id;
                newProposal.Apttus_Proposal__Opportunity__c = createOpportunityNew(acc.Id);
                insert newProposal;
                NPCCopyConfigurationController.InsideNPCCopyConfig = true;
                update newProposal;
            Test.stopTest();
    }
    /*
            Test.startTest();
                newProposal.Device__c = null;
                update newProposal;
            Test.stopTest();
            
                newProposal.Apttus_Proposal__Account__c = null;
                update newProposal;
            */
    //}
    static ID createOpportunityNew(ID testAcctID) {
        // Create Opportunity
        Opportunity testOppty = new Opportunity(
            name = 'Test Opportunity',
            accountID = testAcctID,
            stageName = '1. Discovery',
            closeDate = Date.Today().addDays(10),
            target_process_node__c = '14XM',
            market_segment__c = 'Mobility',
            process_platform__c = 'GF Baseline',
            fab_split__c = 100,
            process_geometry__c = '0.055UM',
            process_family__c = 'Generic / Nominal'
        );
        
        Insert testOppty;        
        return testOppty.ID;
    }
    
}