objects/Account.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Valid_NDA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is set to true if any of the account in the hierarchy has a valid NDA agreement irrespective of tech geometries.</description>
        <label>Has Valid NDA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Geo_Granted__c</fullName>
        <description>This field contains manually provisioned Technology Geometries. This field is selected irrespective of valid NDA for the chosen tech geometries.</description>
        <label>Tech Geo Granted</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.060UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.086UM</fullName>
                </value>
                <value>
                    <fullName>0.08UM</fullName>
                </value>
                <value>
                    <fullName>0.09UM</fullName>
                </value>
                <value>
                    <fullName>0.11UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.14UM</fullName>
                </value>
                <value>
                    <fullName>0.152UM</fullName>
                </value>
                <value>
                    <fullName>0.153UM</fullName>
                </value>
                <value>
                    <fullName>0.15UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.17UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.20UM</fullName>
                </value>
                <value>
                    <fullName>0.22UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.30UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_Tech_Geos__c</fullName>
        <label>Valid Tech Geos</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.060UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.086UM</fullName>
                </value>
                <value>
                    <fullName>0.08UM</fullName>
                </value>
                <value>
                    <fullName>0.09UM</fullName>
                </value>
                <value>
                    <fullName>0.11UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.14UM</fullName>
                </value>
                <value>
                    <fullName>0.152UM</fullName>
                </value>
                <value>
                    <fullName>0.153UM</fullName>
                </value>
                <value>
                    <fullName>0.15UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.17UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.20UM</fullName>
                </value>
                <value>
                    <fullName>0.22UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.30UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Short_Name__c.object
<CustomObject>
    <description>Account short name object is used to maintain the uniqueness of account short name when an account is created. A trigger will be executed to check against this table.</description>
    <fields>
        <fullName>Account_Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Short Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Short Name</label>
    <nameField>
        <displayFormat>ASN-{000000}</displayFormat>
        <label>ASN Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Short Name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Design_Spec__c.object
<CustomObject>
    <description>FV2.0: Iteration  2 - Document Provisioning (Information coming from OpenText through Integration)</description>
    <fields>
        <fullName>Technology_Geometry__c</fullName>
        <label>Technology Geometry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Specification</label>
    <nameField>
        <label>Document Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Document_Provisioning__c.object
<CustomObject>
    <description>FV2: This object will contain the provisioning information for each document. Each user whoever gets access on a document will be maintained in this object.</description>
    <fields>
        <fullName>Account_Short_Name__c</fullName>
        <formula>User__r.Parent_Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>FV2.0: Iteration 2 - This field is required for provisioning.</description>
        <formula>IF(OR(ISNULL(User__c),ISBLANK(User__c)),CASESAFEID(AccountID__c),CASESAFEID(User__r.Contact.AccountId))</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Comments__c</fullName>
        <label>Approval Process Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>approved</fullName>
                </value>
                <value>
                    <fullName>rejected</fullName>
                </value>
                <value>
                    <fullName>submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Design_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Design Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Document Provisionings</relationshipLabel>
        <relationshipName>Document_Provisionings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design_Spec__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specification</label>
        <referenceTo>Design_Spec__c</referenceTo>
        <relationshipLabel>Document Provisionings</relationshipLabel>
        <relationshipName>Document_Provisionings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_User_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final User Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NDA_Coverage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NDA Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
                <value>
                    <fullName>De-Provisioned</fullName>
                </value>
                <value>
                    <fullName>Sent For Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Provisioning In Progress</fullName>
                </value>
                <value>
                    <fullName>De-Provisioning In Progress</fullName>
                </value>
                <value>
                    <fullName>IPLAProvision</fullName>
                </value>
                <value>
                    <fullName>IPLADeprovision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_PDK__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PDK</label>
        <referenceTo>Sub_PDK__c</referenceTo>
        <relationshipLabel>Document Provisionings</relationshipLabel>
        <relationshipName>Document_Provisionings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Geo_Granted_to_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field specifies if Technology Geometry for the document being provisioned has its corresponding Technology Geometry granted at account level.</description>
        <label>Tech Geo Granted to Account</label>
        <type>Checkbox</type>
    </fields>
    <label>Document Provisioning</label>
    <nameField>
        <displayFormat>DP-{000000}</displayFormat>
        <label>Document Provisioning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Provisionings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FV_PDKProvisioningRetriggerBatchCls.cls
/*
*@ Author       :- Navneet Rajput 
*@ Company      :- Cognizant technology
*@ Date         :- 30/10/2014
*@ Description  :- #CR : Batch will execute after every 1 hr and it will process all DP (document provisioning) records 
                        which will not be skipped by document provisioning trigger
                        Criteria :- If DP status is Provisioned and TechGeo Granted is false and Valid NDA false and Final User 
                        Access is false 
*@ History      :- 
*/


global class FV_PDKProvisioningRetriggerBatchCls implements Database.Batchable<sObject>{

    public String pdkId = ''; 
    
    public FV_PDKProvisioningRetriggerBatchCls(String pId){
        this.pdkId = pId;
    } 
     
    public FV_PDKProvisioningRetriggerBatchCls(){
    
     }      

    global Database.querylocator start(Database.BatchableContext BC){
       /* 
        if(pdkId!=null && pdkId!=''){        
            return Database.getQueryLocator([SELECT ID,
                                                    Status__c,
                                                    NDA_Coverage__c,
                                                    Final_User_Access__c,
                                                    Tech_Geo_Granted_to_Account__c,
                                                    Design_Spec__c,
                                                    Sub_PDK__c,
                                                    Design_Package__c,
                                                    Account__c,
                                                    Account_Short_Name__c,
                                                    Approval_Process_Comments__c,
                                                    Approval_Status__c
                                             FROM   Document_Provisioning__c
                                             WHERE  Status__c='Provisioned'
                                             AND    Sub_PDK__c =: pdkId                                                 
                                             AND    NDA_Coverage__c=false
                                             AND    Final_User_Access__c=false
                                             AND    Tech_Geo_Granted_to_Account__c=false]);
       }  else {
        */    
             return Database.getQueryLocator([SELECT ID,
                                                    Status__c,
                                                    NDA_Coverage__c,
                                                    Final_User_Access__c,
                                                    Tech_Geo_Granted_to_Account__c,
                                                    Design_Spec__c,
                                                    Sub_PDK__c,
                                                    Design_Package__c,
                                                    Account__c,
                                                    Account_Short_Name__c,
                                                    Approval_Process_Comments__c,
                                                    Approval_Status__c
                                             FROM   Document_Provisioning__c
                                             WHERE  Status__c='Provisioned'
                                             AND    NDA_Coverage__c=false
                                             AND    Final_User_Access__c=false
                                             AND    Tech_Geo_Granted_to_Account__c=false]);
       
         //}                                  
    }

    // Execute document provisioning request
    global void execute(Database.BatchableContext BC, List<sObject> listOfDPRecords){
        
        system.debug('Inside execute >>>>>>>');        
        set<id> accIds=new set<id>();
        set<id> specIds=new set<id>();
        set<id> pdkIds=new set<id>();
        set<id> packageIds=new set<id>();
        map<id,account> mapacc=new map<id,account>();
        map<id,design_spec__c> mapSpec=new map<id,design_spec__c>();
        map<id,sub_pdk__c> mapPDK=new map<id,sub_pdk__c>();
        map<id,package__c> mapPackage=new map<id,package__c>();
        List<Document_Provisioning__c> listOfDpToUpdate = new List<Document_Provisioning__c>();
            
        if (listOfDPRecords!= null && !listOfDPRecords.isEmpty()){
            for(Document_Provisioning__c dp : (List<Document_Provisioning__c>)listOfDPRecords){
                if(dp.account__c!=null)
                    accids.add(dp.account__c);
                if(dp.Design_Spec__c!=null)
                    specIds.add(dp.Design_Spec__c);    
                if(dp.Sub_PDK__c!=null)
                    pdkIds.add(dp.Sub_PDK__c);
                /*if(dp.Design_package__c!=null)
                    packageIds.add(dp.Design_package__c);*/
            }
            
            if(accids!=null && !accids.isEmpty()){
            for(account acc:[select id,Tech_Geo_Granted__c,Valid_Tech_Geos__c,Has_Valid_NDA__c from account where id in :accids]){
                mapacc.put(acc.id,acc);        
            }
            }
            if(!specIds.isEmpty()){
                for(design_spec__c ds:[select id,technology_geometry__c,specification_type__c from design_spec__c where id in :specIds]){
                    mapSpec.put(ds.id,ds);            
                }
            }
            if(!pdkIds.isEmpty()){
                for(sub_pdk__c pdk:[select id,tech_geometry__c from sub_pdk__c where id in :pdkIds]){
                    mappdk.put(pdk.id,pdk);            
                }
            }
           /* if(!packageIds.isEmpty()){
                for(package__c pkg:[select id,tech_geometry__c from package__c where id in :packageIds]){
                    mappackage.put(pkg.id,pkg);            
                }
            }*/
            
            for(Document_Provisioning__c dp : (List<Document_Provisioning__c>)listOfDPRecords){
            // Check for NDA coverage of Technology geometries                
                if(dp.Design_Spec__c!=null){ 
                    //Asolito - bypass NDA check if spec type is white papers
                    if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).specification_type__c == 'White Papers'){
                        dp.NDA_Coverage__c=true;    
                    } else {                  
                        if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).technology_geometry__c!=null ){
                            for(string s:mapSpec.get(dp.Design_Spec__c).technology_geometry__c.split(';')){
                                if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Valid_Tech_Geos__c!=null && (mapacc.get(dp.account__c).Valid_Tech_Geos__c.contains(s)|| mapacc.get(dp.account__c).Valid_Tech_Geos__c.contains(s.substring(0,6)))){
                                    dp.NDA_Coverage__c=true;    
                                }
                                
                            }
                        }
                        else if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).technology_geometry__c==null){
                            if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Has_Valid_NDA__c==true){
                                dp.NDA_Coverage__c=true;    
                            }  
                       } 
                   }                     
                }
                else if(dp.sub_pdk__c!=null){
                    if(mappdk!=null && mappdk.containskey(dp.sub_pdk__c) && mappdk.get(dp.sub_pdk__c).tech_geometry__c!=null ){
                        for(string s:mappdk.get(dp.sub_pdk__c).tech_geometry__c.split(';')){
                            if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Valid_Tech_Geos__c!=null && (mapacc.get(dp.account__c).Valid_Tech_Geos__c.contains(s) || mapacc.get(dp.account__c).Valid_Tech_Geos__c.contains(s.substring(0,6)))){
                                dp.NDA_Coverage__c=true;    
                            }                           
                        }
                    }
                    else if(mappdk!=null && mappdk.containskey(dp.sub_pdk__c) && mappdk.get(dp.sub_pdk__c).tech_geometry__c==null){
                        if(mapacc!=null && mapacc.containskey(dp.account__c)  && mapacc.get(dp.account__c).Has_Valid_NDA__c==true){
                            dp.NDA_Coverage__c=true;    
                        }  
                   }  
                    
                }
                // Check TechGeo Granted flag
                // Check if Technology geometries is manually granted at account level.
                if(dp.Design_Spec__c!=null){
                    //Asolito - bypass NDA check if spec type is white papers
                    if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).specification_type__c == 'White Papers'){
                        dp.Tech_Geo_Granted_to_Account__c=true;    
                    } else {
                        if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).technology_geometry__c!=null ){
                            for(string s:mapSpec.get(dp.Design_Spec__c).technology_geometry__c.split(';')){
                                if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Tech_Geo_Granted__c!=null && (mapacc.get(dp.account__c).Tech_Geo_Granted__c.contains(s) || mapacc.get(dp.account__c).Tech_Geo_Granted__c.contains(s.substring(0,6)))){
                                    dp.Tech_Geo_Granted_to_Account__c=true;    
                                }
                                
                            }
                        }
                        else if(mapSpec!=null && mapSpec.containskey(dp.Design_Spec__c) && mapSpec.get(dp.Design_Spec__c).technology_geometry__c==null){
                            if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Has_Valid_NDA__c==true){
                                dp.Tech_Geo_Granted_to_Account__c=true;    
                            }  
                       } 
                   }                     
                }
                else if(dp.sub_pdk__c!=null){
                    if(mappdk!=null && mappdk.containskey(dp.sub_pdk__c) && mappdk.get(dp.sub_pdk__c).tech_geometry__c!=null ){
                        for(string s:mappdk.get(dp.sub_pdk__c).tech_geometry__c.split(';')){
                            if(mapacc!=null && mapacc.containskey(dp.account__c) && mapacc.get(dp.account__c).Tech_Geo_Granted__c!=null && (mapacc.get(dp.account__c).Tech_Geo_Granted__c.contains(s) || mapacc.get(dp.account__c).Tech_Geo_Granted__c.contains(s.substring(0,6)))){
                                dp.Tech_Geo_Granted_to_Account__c=true;    
                            }                           
                        }
                    }
                    else if(mappdk!=null && mappdk.containskey(dp.sub_pdk__c) && mappdk.get(dp.sub_pdk__c).tech_geometry__c==null){
                        if(mapacc!=null && mapacc.containskey(dp.account__c)  && mapacc.get(dp.account__c).Has_Valid_NDA__c==true){
                            dp.Tech_Geo_Granted_to_Account__c=true;    
                        }  
                   }  
                    
                }
                system.debug('DP Record >>>>>>>>>'+dp);                
                // Add DP records to update
                if(dp.NDA_Coverage__c || dp.Tech_Geo_Granted_to_Account__c){                
                    listOfDpToUpdate.add(dp);
                }
                system.debug('listOfDpToUpdate>>>>>>>>>>>'+listOfDpToUpdate);                
            } // End of second for loop
            
            if(listOfDpToUpdate!=null && listOfDpToUpdate.size()>0){
                try{
                    update listOfDpToUpdate;
                    //DesignSpecTriggerHandler.addAccountProvisionedTo(listOfDpToUpdate);
                } catch (Exception e){
                    system.debug('Exception :: '+e.getMessage());
                }
            }
        }
    }
    // Send email notification as well as track failures of document provisioning   
    global void finish(Database.BatchableContext BC){
        
    }
        
}