objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region_Head__c</fullName>
        <label>Region Head</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_SVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales SVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Access_Impact__c</fullName>
        <label>Access Impact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Environment Impact</fullName>
                </value>
                <value>
                    <fullName>Quality / Reliability Impact</fullName>
                </value>
                <value>
                    <fullName>Safety Impact</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Request_Date__c</fullName>
        <label>Customer Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description_Return_Particulars__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description_of_Reason_s__c</fullName>
        <inlineHelpText>Enter the justification for the RMA to be raised</inlineHelpText>
        <label>Reason for RMA</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition_of_Wafers__c</fullName>
        <label>Disposition of Wafers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Return to GF</fullName>
                </value>
                <value>
                    <fullName>Return to GF and to Scrap at Customer Site</fullName>
                </value>
                <value>
                    <fullName>To Scrap at Customer Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification_CAR__c</fullName>
        <label>Justification (CAR)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_FOC__c</fullName>
        <label>Justification (FOC)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_Fab_Validation__c</fullName>
        <label>Justification</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_Field_Reliability_Failure__c</fullName>
        <label>Justification (if beyond warranty)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_PRF__c</fullName>
        <label>Justification (PRF)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lot_Device_To_Return__c</fullName>
        <label>Lot/Device (To Return)</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Impact_Wafers__c</fullName>
        <label>Potential Impact Wafers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMA_Category__c</fullName>
        <label>RMA Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Failure Analysis</fullName>
                </value>
                <value>
                    <fullName>Technical/ Turnkey</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RMA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_SVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales SVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RMA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RMA</label>
    <nameField>
        <label>RMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Audit_log__c.object
<CustomObject>
    <description>This object is used to log all the events that occur in RMA process flow i.e. from the stage RMA raised till the closure of RMA.</description>
    <fields>
        <fullName>Cc__c</fullName>
        <label>Cc</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <description>Audit logs are captured for each RMA. This field acts as a reference to RMA.</description>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>Audit log</relationshipLabel>
        <relationshipName>RMA_Audit_logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>This field is used in mail log to capture subject of mail.</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>RMA Audit log</label>
    <nameField>
        <displayFormat>RMA-Audit-{0000000000}</displayFormat>
        <label>RMA Audit log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Audit logs</pluralLabel>
    <recordTypes>
        <fullName>Mail_Log</fullName>
        <active>true</active>
        <label>Mail Log</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMA_UtilityTest.cls
/**
 * Author: Surendranadh Nune
 * Company: GlobalFoundries,India
 * Project: Return Material Authorization
 * Description: This is a test class for RMA_Utility,RMA_UserLocaleDateTimeFormatterCtrl,RMA_CycleTimeHistoryExt, RMA_MailLogInboundEmailHandler 
 * History:
 *    SurendranadhNune 23122015  -   Created.
 *                            
 **/
@isTest
public class RMA_UtilityTest {

    Static RMA__c rmaRec;
    static Account acc;
    @TestSetup
    static void loadTestData(){
         DataUtilTest.loadEnvironmentVariables();
         prepareTestRecords();
    }
    
    static void prepareTestRecords(){
        acc = RMA_TestDataUtility.createAccount();
        rmaRec = RMA_TestDataUtility.createRMA(1, acc);     
    }
    
    static testmethod void testRMA_CycleTimeHistoryExt(){
        rmaRec = [select id,Fab__c from RMA__c limit 1][0];
        Test.startTest();
            Test.setCurrentPage(Page.RMA_CycleTimeHistory);
            RMA_CycleTimeHistoryExt Ext = new RMA_CycleTimeHistoryExt(new ApexPages.StandardController(rmaRec));
        Test.stopTest();
    }
    
    //Tests RMA_CycleTimeHistoryExt, RMA_MailLogInboundEmailHandler
    static testmethod void testRMA_Mail_LogTest(){
        
       rmaRec = [select id,name from RMA__c limit 1][0];
       User testUser = [select Id from User where isActive = true and Profile.Name = 'System Administrator' limit 1];
              
       system.runAs(testUser){       
           Test.startTest();    
               RMA_UserLocaleDateTimeFormatterCtrl localectrl = new RMA_UserLocaleDateTimeFormatterCtrl();  
               localectrl.dateTimeValue = datetime.now();
               localectrl.getTimeZoneValue();
               
               // Create a new email, envelope object and Attachment
               Messaging.InboundEmail email = new Messaging.InboundEmail();
               Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
            
               email.subject = rmaRec.Name;
               env.fromAddress = 'user@acme.com';
               email.toAddresses = new String[]{'test1@gmail.com', 'test2@gmail.com'};
               email.ccAddresses = new String[]{'test3@gmail.com', 'test4@gmail.com'};
               email.htmlbody = 'Test email';
            
               // call the class and test it with the data in the testMethod
               RMA_MailLogInboundEmailHandler emailServiceObj = new RMA_MailLogInboundEmailHandler();
               emailServiceObj.handleInboundEmail(email, env );
               rma_audit_log__c mailLog= [select id,to__c,cc__c,Subject__c,Email_Body__c,RMA__c
                                          from rma_audit_log__c 
                                          where recordtypeId=: RMA_Utility.getRecordTypeId('RMA_Audit_log__c', RMA_Constants.MAIL_LOG)][0]; 
                
               Test.setCurrentPage(Page.RMA_Mail_Log_Resend);
               RMA_Mail_Log_ResendCtrl ctrl = new RMA_Mail_Log_ResendCtrl(new ApexPages.StandardController(mailLog));
               ctrl.addCC = 'testuser5@gmail.com';
               ctrl.resend();
			   ctrl.hasAdminPriv();
           Test.stopTest();
       }
    }
    
    static testmethod void testUtilityMethods(){
        acc = [select id from account limit 1];
        rmaRec = [select id,name from RMA__c limit 1][0];
        Test.startTest();
            RMA_TestDataUtility.createRMAReturnInvoice(rmaRec, acc); 
            rma_utility.getTabFromShortName(RMA_CONSTANTS.tabName_DISPOSITION_OF_WAFER);
            rma_utility.getTabFromShortName(RMA_CONSTANTS.tabName_FAB_VALIDATION);
            rma_utility.getTabFromShortName(RMA_CONSTANTS.tabName_RMA_INFORMATION);
            rma_utility.getTabFromShortName('test');
            rma_utility.getPickListValues('rma__c', 'Status__c');
            RMA_Utility.retrieveRMAEmailServiceAddress('RMA Mail log Service');
            RMA_utility.getRMAtotalSystemMode(rmaRec.id);
            RMA_utility.QueryLineItemsSystemMode(rmaRec.id);
            
            
            //updating RMA with mandatory fields
            rmaRec.Access_Impact__c = 'Safety Impact';
            rmaRec.Description_Return_Particulars__c = 'test';
            rmaRec.Description_of_Reason_s__c = 'test';
            rmaRec.RMA_Category__c = 'Technical/ Turnkey';
            rmaRec.Disposition_of_Wafers__c = 'Return to GF';
            rmaRec.Customer_Request_Date__c = System.TODAY()-1;
            rmaRec.Justification_Fab_Validation__c = 'test';
            rmaRec.Justification_PRF__c = 'test';
            rmaRec.Justification_CAR__c = 'test';
            rmaRec.Justification_FOC__c = 'test';
            rmaRec.Justification_Field_Reliability_Failure__c = 'test';
            rmaRec.Potential_Impact_Wafers__c = 20;
            rmaRec.Lot_Device_To_Return__c = 'testLot1-123456;';
            rmaRec.Region_Head__c = UserInfo.getUserId();
            rmaRec.Sales_SVP__c = UserInfo.getUserId();
            rmaRec.ownerId = [select Id, Name from Group where Name LIKE 'RMA Fab Director- FAB 1' and Type = 'Queue'][0].id;
            update rmaRec;
            
            //Submitting RMA for Approval
            ApexPages.StandardController sc = new ApexPages.StandardController(rmaRec);
            PageReference pageRef = Page.RMA_view;
            pageRef.getParameters().put('id', String.valueOf(rmaRec.Id));
            Test.setCurrentPage(pageRef);
            RMA_Edit_Extension obj2 = new RMA_Edit_Extension(sc);
            Test.setCurrentPage(pageRef);
            obj2.sumbitForApproval();
            RMA_utility.checkApprover(rmaRec.id);
        Test.stopTest();            
    }
    
    static testmethod void testMoveToLibrary(){
        //Creating a Content Document
        ContentVersion contentVersionObj = new ContentVersion();
        contentVersionObj.Title = 'Test';
        contentVersionObj.PathOnClient = 'TestFile.txt';
        contentVersionObj.VersionData = Blob.valueOf('Test Content');
        contentVersionObj.IsMajorVersion = true;
        insert contentVersionObj;
        ContentVersion testContent = [SELECT ContentDocumentId FROM ContentVersion where Id = :contentVersionObj.Id];
        RMA_utility.moveToLibrary(testContent.ContentDocumentId);
    }
    
    static testmethod void testRMA_Mail_LogTest2(){
        
       rmaRec = [select id,name from RMA__c limit 1][0];
       User testUser = [select Id, isActive, Profile.Name from User where isActive = true and Profile.Name = 'GF System Admin' limit 1];
       
       system.runAs(testUser){
       
           Test.startTest();    
               RMA_UserLocaleDateTimeFormatterCtrl localectrl = new RMA_UserLocaleDateTimeFormatterCtrl();  
               localectrl.dateTimeValue = datetime.now();
               localectrl.getTimeZoneValue();
               
               // Create a new email, envelope object and Attachment
               Messaging.InboundEmail email = new Messaging.InboundEmail();
               Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
            
               email.subject = rmaRec.Name;
               env.fromAddress = 'user@acme.com';
               email.toAddresses = new String[]{'test1@gmail.com', 'test2@gmail.com'};
               email.ccAddresses = new String[]{'test3@gmail.com', 'test4@gmail.com'};
               email.htmlbody = 'Test email';
            
               // call the class and test it with the data in the testMethod
               RMA_MailLogInboundEmailHandler emailServiceObj = new RMA_MailLogInboundEmailHandler();
               emailServiceObj.handleInboundEmail(email, env );
               rma_audit_log__c mailLog = new rma_audit_log__c();
               List<rma_audit_log__c> lstmailLog= [select id,to__c,cc__c,Subject__c,Email_Body__c, RMA__c
                                              from rma_audit_log__c 
                                              where recordtypeId=: RMA_Utility.getRecordTypeId('RMA_Audit_log__c', RMA_Constants.MAIL_LOG)]; 
               if(lstmailLog != NULL && !lstmailLog.isEmpty()){
                   mailLog = lstmailLog[0];
                   Test.setCurrentPage(Page.RMA_Mail_Log_Resend);
                   RMA_Mail_Log_ResendCtrl ctrl = new RMA_Mail_Log_ResendCtrl(new ApexPages.StandardController(mailLog));
                   ctrl.addCC = 'testuser5@gmail.com';
                   ctrl.resend();
                   ctrl.hasAdminPriv();
               }
           Test.stopTest();
            
       }
    }
}