objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>GLOBALFOUNDRIES_Internal</fullName>
        <active>true</active>
        <description>Internal Account : GLOBALSHUTTLE, TD, DE-IP, FABs</description>
        <label>GLOBALFOUNDRIES Internal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The device record the retrofit/revision device was based.</description>
        <inlineHelpText>Reference Device ID used during creation of retrofit/revision device</inlineHelpText>
        <label>Base Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device_Mask_Set_Title__c</fullName>
        <description>MaskSetTitle populated from PTRF</description>
        <inlineHelpText>Mask Set Title has different validation rules for different tapeout type.For GlobalShuttle &amp; CustomizedShuttle MPW, Device Mask Set Title must be same as MPW Train Number.</inlineHelpText>
        <label>Device Mask Set Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enabled_via_previous_MPW_1__c</fullName>
        <label>Enabled via previous MPW</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>Indicate Fab where this device produce</description>
        <inlineHelpText>Indicate Fab where this device produce</inlineHelpText>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reticle_Type__c</fullName>
        <inlineHelpText>To indicate the reticle type of this tapeout. SLR, MLR etc. For GlobalShuttle &amp; CustomizedShuttle MPW, Reticle Type will be auto populated.</inlineHelpText>
        <label>Reticle Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Multi Layer Reticle (MLR)</fullName>
                </value>
                <value>
                    <fullName>Multi Node Reticle (MNR)</fullName>
                </value>
                <value>
                    <fullName>Single Layer Reticle (SLR)</fullName>
                </value>
                <value>
                    <fullName>Small Field Reticle (SFR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <recordTypes>
        <fullName>Device</fullName>
        <active>true</active>
        <description>Unsorted Wafer Device</description>
        <label>Device</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Device</fullName>
        <active>true</active>
        <description>Internal Device</description>
        <label>Internal Device</label>
    </recordTypes>
    <recordTypes>
        <fullName>Solutioning</fullName>
        <active>true</active>
        <description>The default record type for device. This was created because we cannot change available pick list for master record type.</description>
        <label>Solutioning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mask__c.object
<CustomObject>
    <fields>
        <fullName>Layer__c</fullName>
        <label>Layer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modified_Mask__c</fullName>
        <label>Modified Mask</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Part_Creation_Form__c</fullName>
        <label>New Part Creation Form</label>
        <referenceTo>New_Part_Creation_Form__c</referenceTo>
        <relationshipLabel>Masks</relationshipLabel>
        <relationshipName>Masks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Mask__c</fullName>
        <label>Original Mask</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Mask</label>
    <nameField>
        <displayFormat>MASK-{0000000000}</displayFormat>
        <label>Mask</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Masks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/New_Part_Creation_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>New_Part_Creation_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BASE_Device__c</fullName>
        <inlineHelpText>System will copy the basic Device information like Process Id, Export Control, IP Declaration, Mask Set Title, Automotive Device, etc. based on the selected SFDC Reference Device.</inlineHelpText>
        <label>SFDC Base Device</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Device__c.Device_Type__c</field>
                <operation>equals</operation>
                <value>Base</value>
            </filterItems>
            <filterItems>
                <field>Device__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>NPC Forms</relationshipLabel>
        <relationshipName>New_Part_Creation_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CRM_DID__c</fullName>
        <label>CRM DID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Mask_Set_Title__c</fullName>
        <formula>BASE_Device__r.Device_Mask_Set_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Device Mask Set Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPC_Form_Status__c</fullName>
        <label>NPC Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending CE Approval</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Pending Resubmission</fullName>
                </value>
                <value>
                    <fullName>Pending PID Reassignment</fullName>
                </value>
                <value>
                    <fullName>Pending Mask Layer Addition by FE</fullName>
                </value>
                <value>
                    <fullName>Pending Submission</fullName>
                    <default>true</default>
                    <label>Pending Submission</label>
                </value>
                <value>
                    <fullName>Pending Litho Verification</fullName>
                </value>
                <value>
                    <fullName>Pending AM Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Part_ID__c</fullName>
        <label>New Part ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>System will copy the basic Device information like Process Id, Export Control, IP Declaration, Mask Set Title, Automotive Device, etc. based on the selected SFDC Reference Device.</inlineHelpText>
        <label>Device ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Device__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>NPC Forms (Originating Device)</relationshipLabel>
        <relationshipName>NPC_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_New_Part__c</fullName>
        <inlineHelpText>SFDC creates a new device record only for &quot;Retrofit&quot;, &quot;Retrofit + Add ROM Code&quot; and &quot;Others + Do you require to create a New Part? = Yes&quot; options.</inlineHelpText>
        <label>Reason for New Part</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Retrofit</fullName>
                    <default>true</default>
                    <label>Retrofit</label>
                </value>
                <value>
                    <fullName>Add ROM Code</fullName>
                </value>
                <value>
                    <fullName>Retrofit + Add ROM Code</fullName>
                </value>
                <value>
                    <fullName>CustomerNameChange</fullName>
                </value>
                <value>
                    <fullName>Fab to Fab Transfer</fullName>
                </value>
                <value>
                    <fullName>Change in PID</fullName>
                </value>
                <value>
                    <fullName>New Probe Card Flow</fullName>
                </value>
                <value>
                    <fullName>StartingMaterialChange</fullName>
                </value>
                <value>
                    <fullName>BackgrindThicknessChange</fullName>
                </value>
                <value>
                    <fullName>ShortLoop Flow</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Device Reactivation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tapeout_Required__c</fullName>
        <inlineHelpText>PTRF Submission Required value should be set to &quot;Yes&quot; if you are going to submit PTRF.</inlineHelpText>
        <label>PTRF Submission Required</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_for_New_Part__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NPC Form</label>
    <nameField>
        <displayFormat>NPC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>New Part Creation Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPC Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account of the Opportunity this device is tied up. This is automatically populated during the Opportunity Program generation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Programs</relationshipLabel>
        <relationshipName>Opportunity_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NPCFormApprovalProcessControllerTest1.cls
/*
    Author: Zymark Ambat
    Description: This serves as the test class for NPCFormApprovalProcessController.
    History: 
        ZAmbat      02142014    - Code creation.
        ZAmbat      04282014    - Updated code to SeeAllData=false as fix for SFDC test limitations.
        Vijay       16012015    - Updated the Device Stage 'Solutioning' to 'Design In' as Device will be created in 
                                  'Design In' directly and added mandatory fields.
        DBiswal     04132015    - Updated code for refactoring of test class.
        Vijay       05012015    - added the test methods for Internal Device and updated existing test methods.
*/
@isTest(SeeAllData=false)
public class NPCFormApprovalProcessControllerTest1 {
    
     @testSetup static void setupInternalDeviceData(){
        DataUtilTest.loadEnvironmentVariables();
        List<RecordType> recordTypeList = [Select Id from RecordType where sObjectType ='Account' and developerName = 'GLOBALFOUNDRIES_Internal'];

        Account account = InternalDeviceTestUtil.createAccount('Test Account1', 'Unqualified', 'TestAccount1', 'Site', 'Direct', 'transactional', 'Fabless - Emerging',
                                             'Mature (> 0.11um)', 'APJ', 'APJ-FE-CHINA', 'APJ-China', 'APJ-China', true, '50 water', 'Bijing', 'China',  '50', 'GF Investment LLC OU', 
                                             100);
                                        
        if(!recordTypeList.isEmpty()){                      
            account.RecordTypeId = recordTypeList[0].Id;
        }
        //insert account;
        System.debug('account====='+account);
        List<RecordType> deviceRecTypeList = [Select Id from RecordType where sObjectType ='Device__c' and developerName = 'Internal_Device'];
        Device__c device = InternalDeviceTestUtil.createDevice('TestInternalDevice', 'Fab 2', 'Design In', 'Active', '100', System.today(), 
                                                                '1234567890', 'Single Product',  account.Id, '0.028UM', 'Super Low Power');
        if(!deviceRecTypeList.isEmpty()){                       
            device.RecordTypeId = deviceRecTypeList[0].Id;
        }
        Device.Device_Mask_Set_Title__c ='VMSTV';
        Device.Enabled_via_previous_MPW_1__c ='No';
        Device.Reticle_Type__c ='Multi Layer Reticle (MLR)';
        insert device;
    }
    
          
    static New_Part_Creation_Form__c createNPCForm1(Id accountId, Id deviceId) {
        New_Part_Creation_Form__c npc = new New_Part_Creation_Form__c();
        npc.Account__c = accountId;
        npc.BASE_Device__c = deviceId;
        npc.Originating_Device__c = deviceId;
        npc.New_Part_ID__c = 'NPCTEST5';
        npc.CRM_DID__c = 'CDID12345';
        npc.Fab__c = 'FAB 2';
        npc.Tapeout_Required__c = 'No';
        
        insert npc;
        
        return npc;
    }
    
    static New_Part_Creation_Form__c createNPCForm2(Id accountId, Id deviceId) {
        New_Part_Creation_Form__c npc = new New_Part_Creation_Form__c();
        npc.Account__c = accountId;
        npc.BASE_Device__c = deviceId;
        npc.Originating_Device__c = deviceId;
        npc.New_Part_ID__c = 'NPCTEST6';
        npc.CRM_DID__c = 'CDID12345';
        npc.Fab__c = 'FAB 2';
        npc.Tapeout_Required__c = 'No';
        npc.Reason_for_New_Part__c = 'New Probe Card Flow' ;
        npc.NPC_Form_Status__c = 'Pending Submission';
        
        insert npc;
        
        return npc;
    }
    
      static New_Part_Creation_Form__c createNPCForm3(Id accountId, Id deviceId) {
        New_Part_Creation_Form__c npc = new New_Part_Creation_Form__c();
        npc.Account__c = accountId;
        npc.BASE_Device__c = deviceId;
        npc.Originating_Device__c = deviceId;
        npc.New_Part_ID__c = 'NPCTEST7';
        npc.CRM_DID__c = 'CDID12345';
        npc.Fab__c = 'FAB 3';
        npc.Tapeout_Required__c = 'No';
        npc.NPC_Form_Status__c = 'Pending Submission';
        
        insert npc;
        
        return npc;
    }
    
    static Id createNPCMasks(Id npcId) {
        Mask__c m = new Mask__c();
        m.New_Part_Creation_Form__c = npcId;
        m.Layer__c = 'TestLayer';
        m.Modified_Mask__c = 'TestLayerMask';
        m.Original_Mask__c = 'TestLayerMask';
        
        insert m;
        
        return m.Id;
    }
    
    //test method for Internal Device
    static testMethod void testSubmitNPCForm(){
        Account account = null;
        Device__c device = null;
        New_Part_Creation_Form__c npcForm = null;
        System.runAs(new User(Id = UserInfo.getUserId())){
            Test.startTest();
            account = [Select Id From Account Where Name = 'Test Account1' Limit 1];
            device = [Select Id From Device__c Where Name='TestInternalDevice' Limit 1];
            npcForm = createNPCForm1(account.Id, device.Id);
            PageReference pageRef = Page.NPCFormVF;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('id', npcForm.Id);
            NPCFormApprovalProcessController n = new NPCFormApprovalProcessController();
            n.submitNPCForm();
       }
       Test.stopTest();
    }
    
    
    static testMethod void testNPCFormApprovalProcessController_GFFAEFTS1() {
        Account account = null;
        Opportunity_Program__c oppProgram = null;
        User gfFAEFTS = null;
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())){
        account = [Select Id From Account Where Name = 'Test Account1'];
            gfFAEFTS= [
                SELECT    Id
                FROM      User
                WHERE     Profile.Name = 'GF FAE/FTS'
                          AND IsActive = true
                LIMIT 1
            ];
            AccountShare as1 = new AccountShare();
            as1.AccountAccessLevel = 'Edit';
            //as1.RowCause = 'Manual';
            as1.AccountId = account.Id;
            as1.UserOrGroupId = gfFAEFTS.Id;
            as1.OpportunityAccessLevel = 'Edit';
            as1.CaseAccessLevel = 'Edit';
            insert as1;
            
        }
        system.runAs(gfFAEFTS) {
            List<RecordType> deviceRecTypeList = [Select Id from RecordType where sObjectType ='Device__c' and developerName = 'Internal_Device'];
            Device__c device = InternalDeviceTestUtil.createDevice('TestInternalDevice1', 'Fab 2', 'Design In', 'Active', '100', System.today(), 
                                                                '11111111111', 'Single Product',  account.Id, '0.028UM', 'Super Low Power');
            if(!deviceRecTypeList.isEmpty()){                       
                device.RecordTypeId = deviceRecTypeList[0].Id;
            } 
            Device.Device_Mask_Set_Title__c ='VMSTML';
            Device.Enabled_via_previous_MPW_1__c ='No';
            Device.Reticle_Type__c ='Multi Layer Reticle (MLR)';
            insert device;
            New_Part_Creation_Form__c testNPC = createNPCForm2(account.Id, device.Id);
            createNPCMasks(testNPC.Id);
            PageReference pageRef = Page.NPCFormVF;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('id', testNPC.Id);
            NPCFormApprovalProcessController n = new NPCFormApprovalProcessController();
            
            n.submitNPCForm();
        }
        test.stopTest();
    }
     
     static testMethod void testNPCFormApprovalProcessController_GFFAEFTS2() {
        Account account = null;
        Opportunity_Program__c oppProgram = null;
        User gfFAEFTS = null;
        Test.startTest();
        System.runAs(new User(Id = UserInfo.getUserId())){
            account = [Select Id From Account Where Name = 'Test Account1'];
            gfFAEFTS= [
                SELECT    Id
                FROM      User
                WHERE     Profile.Name = 'GF FAE/FTS'
                          AND IsActive = true
                LIMIT 1
            ];
             AccountShare as1 = new AccountShare();
            as1.AccountAccessLevel = 'Edit';
            //as1.RowCause = 'Manual';
            as1.AccountId = account.Id;
            as1.UserOrGroupId = gfFAEFTS.Id;
            as1.OpportunityAccessLevel = 'Edit';
            as1.CaseAccessLevel = 'Edit';
            insert as1;
       }
        system.runAs(gfFAEFTS) {
            List<RecordType> deviceRecTypeList = [Select Id from RecordType where sObjectType ='Device__c' and developerName = 'Internal_Device'];
            Device__c device = InternalDeviceTestUtil.createDevice('TestInternalDevice2', 'Fab 2', 'Design In', 'Active', '100', System.today(), 
                                                                '2222222222', 'Single Product',  account.Id, '0.028UM', 'Super Low Power');
            if(!deviceRecTypeList.isEmpty()){                       
                device.RecordTypeId = deviceRecTypeList[0].Id;
            }
            //Device.Device_Mask_Set_Title__c ='VMSTV';
            Device.Enabled_via_previous_MPW_1__c ='No';
            Device.Reticle_Type__c ='Multi Layer Reticle (MLR)';
            insert device;
            New_Part_Creation_Form__c testNPC = createNPCForm3(account.Id, device.Id);
            createNPCMasks(testNPC.Id);
            PageReference pageRef = Page.NPCFormVF;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('id', testNPC.Id);
            NPCFormApprovalProcessController n = new NPCFormApprovalProcessController();
            
            n.submitNPCForm();
        }
        test.stopTest();
    }
    
     static testMethod void testCancel(){
     test.startTest();
            PageReference pageRef = Page.NPCFormVF;
            Test.setCurrentPageReference(pageRef);
            NPCFormApprovalProcessController n = new NPCFormApprovalProcessController();
            n.cancel();
        test.stopTest();
    }
    
}