objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region_Head__c</fullName>
        <label>Region Head</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_SVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales SVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Access_Impact__c</fullName>
        <label>Access Impact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Environment Impact</fullName>
                </value>
                <value>
                    <fullName>Quality / Reliability Impact</fullName>
                </value>
                <value>
                    <fullName>Safety Impact</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Category__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carrier_Vendor_Account_Number__c</fullName>
        <label>Carrier Vendor Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier_Vendor__c</fullName>
        <label>Carrier Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPS Blue</fullName>
                </value>
                <value>
                    <fullName>UPS Ground</fullName>
                </value>
                <value>
                    <fullName>UPS Int&apos;l Standard</fullName>
                </value>
                <value>
                    <fullName>UPS Int&apos;l Expedited</fullName>
                </value>
                <value>
                    <fullName>FedEx Standard Overnight</fullName>
                </value>
                <value>
                    <fullName>UPS Int&apos;l Express</fullName>
                </value>
                <value>
                    <fullName>Geodis Transportation Operation Center</fullName>
                </value>
                <value>
                    <fullName>Nippon Express</fullName>
                </value>
                <value>
                    <fullName>CEVA</fullName>
                </value>
                <value>
                    <fullName>Panalpina</fullName>
                </value>
                <value>
                    <fullName>Geodis Wilson</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Type__c</fullName>
        <label>Compensation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RMA_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Credit with charged replacement</fullName>
                </value>
                <value>
                    <fullName>No Compensation</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Return_Particulars__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description_of_Reason_s__c</fullName>
        <inlineHelpText>Enter the justification for the RMA to be raised</inlineHelpText>
        <label>Reason for RMA</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition_of_Wafers__c</fullName>
        <label>Disposition of Wafers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Return to GF</fullName>
                </value>
                <value>
                    <fullName>Return to GF and to Scrap at Customer Site</fullName>
                </value>
                <value>
                    <fullName>To Scrap at Customer Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification_CAR__c</fullName>
        <label>Justification (CAR)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_FOC__c</fullName>
        <label>Justification (FOC)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_Fab_Validation__c</fullName>
        <label>Justification</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_Field_Reliability_Failure__c</fullName>
        <label>Justification (if beyond warranty)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Justification_PRF__c</fullName>
        <label>Justification (PRF)</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lot_Device_To_Return__c</fullName>
        <label>Lot/Device (To Return)</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Impact_Wafers__c</fullName>
        <label>Potential Impact Wafers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Line</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RMA_Category__c</fullName>
        <label>RMA Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Failure Analysis</fullName>
                </value>
                <value>
                    <fullName>Technical/ Turnkey</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReasonCode__c</fullName>
        <label>Return Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RMA_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>R10</fullName>
                </value>
                <value>
                    <fullName>R20</fullName>
                </value>
                <value>
                    <fullName>R25</fullName>
                </value>
                <value>
                    <fullName>R30</fullName>
                </value>
                <value>
                    <fullName>R35</fullName>
                </value>
                <value>
                    <fullName>R50</fullName>
                </value>
                <value>
                    <fullName>R55</fullName>
                </value>
                <value>
                    <fullName>R80</fullName>
                </value>
                <value>
                    <fullName>R81</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RMA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Return_Estimated_Date__c</fullName>
        <label>Return Estimated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Return_Location__c</fullName>
        <label>Return Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Burlington</fullName>
                </value>
                <value>
                    <fullName>APLC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_SVP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales SVP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RMA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_from_Address__c</fullName>
        <label>Ship from Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warranty__c</fullName>
        <inlineHelpText>Enter number of months for customer warranty.</inlineHelpText>
        <label>Warranty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workflow_Stage__c</fullName>
        <label>Workflow Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <label>RMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Business_Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CMOS Platforms</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>RF</fullName>
    </customValue>
    <customValue>
        <fullName>A&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>SiPh</fullName>
    </customValue>
    <customValue>
        <fullName>Foundry</fullName>
        <isActive>false</isActive>
        <label>Foundry</label>
    </customValue>
    <description>GLOBALFOUNDRIES Business Unit
CMOS Platforms
ASIC
Foundry
RF
A&amp;D</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Line.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Leading Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Mainstream</fullName>
    </customValue>
    <customValue>
        <fullName>Mature</fullName>
    </customValue>
    <customValue>
        <fullName>IBM</fullName>
    </customValue>
    <customValue>
        <fullName>Packaging / Hetero-Integration</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>SiPh</fullName>
    </customValue>
    <customValue>
        <fullName>RF</fullName>
    </customValue>
    <description>GLOBALFOUNDRIES Product Line
Leading Edge
Mainstream
Mature
IBM
Packaging / Hetero-Integration
ASIC
SiPh
RF</description>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

classes/RMA_GetPDFContent_Test.cls
@isTest(SEEALLDATA = false)
private class RMA_GetPDFContent_Test {
    @TestSetup
    static void loadTestData(){
         DataUtilTest.loadEnvironmentVariables();
         Account acc = RMA_TestDataUtility.createAccountForFab9();
         RMA__c rmaRec = RMA_TestDataUtility.createRMAForFab9(1, acc);                                       
    }
    
    static testmethod void testMethod1(){
        RMA__c rmaRec = [select id from RMA__c limit 1]; 
        Account acc = [select id from Account limit 1];
        Test.startTest();//updating RMA with mandatory fields
            RMA_TestDataUtility.createRMAReturnInvoiceForFab9(rmaRec, acc);
            RMA_TestDataUtility.createInvoicesForFab9(1,acc);
         
            rmaRec.Compensation_Type__c = 'Credit';
            rmaRec.OwnerId = userInfo.getUserId();
            rmaRec.Access_Impact__c = 'Safety Impact';
            rmaRec.Description_Return_Particulars__c = 'test';
            rmaRec.Description_of_Reason_s__c = 'test';
            rmaRec.RMA_Category__c = 'Technical/ Turnkey';
            rmaRec.Disposition_of_Wafers__c = 'Return to GF';
            rmaRec.Justification_Fab_Validation__c = 'test';
            rmaRec.Justification_PRF__c = 'test';
            rmaRec.Justification_CAR__c = 'test';
            rmaRec.Justification_FOC__c = 'test';
            rmaRec.Justification_Field_Reliability_Failure__c = 'test';
            rmaRec.Potential_Impact_Wafers__c = 20;
            rmaRec.Lot_Device_To_Return__c = 'testLot1;';
            rmaRec.Region_Head__c = UserInfo.getUserId();
            rmaRec.Sales_SVP__c = UserInfo.getUserId();
            rmaRec.Status__c = 'Draft';
            rmaRec.Workflow_Stage__c = 'RMA Raised';
            rmaRec.Business_Unit__c = 'ASIC';
            rmaRec.Product_Line__c = 'ASIC';
            rmaRec.Business_Category__c = 'ASIC';
            rmaRec.Warranty__c = 24;
            rmaRec.ReasonCode__c = 'R20';
            rmaRec.Return_Location__c = 'Burlington';
            rmaRec.Carrier_Vendor__c = 'CEVA';
            rmaRec.Carrier_Vendor_Account_Number__c = 'AAA';
            rmaRec.Return_Estimated_Date__c = System.Today()+2;
            rmaRec.Disposition_of_Wafers__c = 'Return to GF';
            rmaRec.Lot_Device_To_Return__c  = 'testLot1;';
            rmaRec.Ship_from_Address__c = 'test address';
            update rmaRec;
            
            UtilClassToGetAllFields util = new UtilClassToGetAllFields();
            String f = util.getAllFields('RMA__c');
            String query = 'select '+f+' from RMA__c limit 1';
            List<RMA__c> rmalist = database.query(query);
            RMA__c rmaRec1 = rmaList[0];
        
        list<EmailTemplate> template  = [select id from EmailTemplate limit 1];
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/sendPDFEmail/';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response= res;

        RMA_GetPDFContent.sendEmail('manvendra.rathore@cognizant.com','manvendra.rathore@cognizant.com',rmaRec1.Id,template[0].id,'CustPerf');              
        Test.stopTest();
    }
    
    static testmethod void testMethod2(){
        RMA__c rmaRec = [select id from RMA__c limit 1]; 
        Account acc = [select id from Account limit 1];
        Test.startTest();//updating RMA with mandatory fields
            RMA_TestDataUtility.createRMAReturnInvoiceForFab9(rmaRec, acc);
            RMA_TestDataUtility.createInvoicesForFab9(1,acc);
         
            rmaRec.Compensation_Type__c = 'Credit';
            rmaRec.OwnerId = userInfo.getUserId();
            rmaRec.Access_Impact__c = 'Safety Impact';
            rmaRec.Description_Return_Particulars__c = 'test';
            rmaRec.Description_of_Reason_s__c = 'test';
            rmaRec.RMA_Category__c = 'Technical/ Turnkey';
            rmaRec.Disposition_of_Wafers__c = 'Return to GF';
            rmaRec.Justification_Fab_Validation__c = 'test';
            rmaRec.Justification_PRF__c = 'test';
            rmaRec.Justification_CAR__c = 'test';
            rmaRec.Justification_FOC__c = 'test';
            rmaRec.Justification_Field_Reliability_Failure__c = 'test';
            rmaRec.Potential_Impact_Wafers__c = 20;
            rmaRec.Lot_Device_To_Return__c = 'testLot1;';
            rmaRec.Region_Head__c = UserInfo.getUserId();
            rmaRec.Sales_SVP__c = UserInfo.getUserId();
            rmaRec.Status__c = 'Draft';
            rmaRec.Workflow_Stage__c = 'RMA Raised';
            rmaRec.Business_Unit__c = 'ASIC';
            rmaRec.Product_Line__c = 'ASIC';
            rmaRec.Business_Category__c = 'ASIC';
            rmaRec.Warranty__c = 24;
            rmaRec.ReasonCode__c = 'R20';
            rmaRec.Return_Location__c = 'Burlington';
            rmaRec.Carrier_Vendor__c = 'CEVA';
            rmaRec.Carrier_Vendor_Account_Number__c = 'AAA';
            rmaRec.Return_Estimated_Date__c = System.Today()+2;
            rmaRec.Disposition_of_Wafers__c = 'Return to GF';
            rmaRec.Lot_Device_To_Return__c  = 'testLot1;';
            rmaRec.Ship_from_Address__c = 'test address';
            update rmaRec;
            
            UtilClassToGetAllFields util = new UtilClassToGetAllFields();
            String f = util.getAllFields('RMA__c');
            String query = 'select '+f+' from RMA__c limit 1';
            List<RMA__c> rmalist = database.query(query);
            RMA__c rmaRec1 = rmaList[0];
        
        list<EmailTemplate> template  = [select id from EmailTemplate limit 1];
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/sendPDFEmail/';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        RestContext.request = req;
        RestContext.response= res;

        RMA_GetPDFContent.sendEmail('manvendra.rathore@cognizant.com','manvendra.rathore@cognizant.com',rmaRec1.Id,template[0].id,'ReturnScrap'); 
    }

}