objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF( CONTAINS(Name, &apos;ADVANCED MICRO DEVICES&apos;) , &apos;AMD&apos;,  IF(CONTAINS(Name, &apos;BROADCOM&apos;) , &apos;Broadcom&apos;,  IF( CONTAINS(Name, &apos;QUALCOMM&apos;) , &apos;Qualcomm&apos;, &apos;Others&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Short_Name__c.object
<CustomObject>
    <description>Account short name object is used to maintain the uniqueness of account short name when an account is created. A trigger will be executed to check against this table.</description>
    <fields>
        <fullName>Account_Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Short Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Short Name</label>
    <nameField>
        <displayFormat>ASN-{000000}</displayFormat>
        <label>ASN Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Short Name</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wavier_Collaborator__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Short_Name__c</fullName>
        <label>Account Short Name</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Shortname__c</fullName>
        <label>Created By Shortname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCustomerAcceptsRisk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer Accepts Risk?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCustomerAgreeToFix__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer Agree To Fix?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsGfAcceptsRisk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exceptional Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_releasedToCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is releasedToCustomer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PTSR_Number__c</fullName>
        <externalId>true</externalId>
        <label>PTSR Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTSR_Status__c</fullName>
        <label>PTSR Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_AM__c</fullName>
        <label>Selected AM</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Customers__c</fullName>
        <label>Selected Customers</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submitted_By_Shortname__c</fullName>
        <label>Submitted By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiver_Status__c</fullName>
        <label>Aggregated Waiver Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved,Exceptional arrangement</fullName>
                </value>
                <value>
                    <fullName>Approved,Customer agree to take risk</fullName>
                </value>
                <value>
                    <fullName>WEA</fullName>
                </value>
                <value>
                    <fullName>WCR</fullName>
                </value>
                <value>
                    <fullName>FCF</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PW</fullName>
                </value>
                <value>
                    <fullName>pWO</fullName>
                </value>
                <value>
                    <fullName>pOC</fullName>
                </value>
                <value>
                    <fullName>FD</fullName>
                </value>
                <value>
                    <fullName>VCP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workflow_Status__c</fullName>
        <formula>IF(OR(ISPICKVAL(PTSR_Status__c,&apos;Approved&apos;), ISPICKVAL(PTSR_Status__c,&apos;Open&apos;)), &apos;Pending&apos;,Text(PTSR_Status__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Waiver Collaborator</label>
    <nameField>
        <displayFormat>Collaborator-{0000}</displayFormat>
        <label>Waiver Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiver Collaborator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WaiverCollaboratorEmailNotificationBatch.cls
/*
* @ Author :- Navneet rajput
* @ Description :- 
* @ Date :-
* @ Change History :-  
**/
global class WaiverCollaboratorEmailNotificationBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC){ 
    	
    	Date previousDate = date.Today().addDays(-2);
    	
         return Database.getQueryLocator([SELECT Id,Name,IsCustomerAcceptsRisk__c,Workflow_Status__c,Account_Short_Name__c,Account_Name__c,
         										Created_By_Shortname__c,Submitted_By_Shortname__c,Selected_AM__c,Selected_Customers__c,
         										IsCustomerAgreeToFix__c,IsGfAcceptsRisk__c,Is_releasedToCustomer__c,PTSR_Number__c,Waiver_Status__c
        								  FROM 	Wavier_Collaborator__c
        								  WHERE LastModifiedDate <= : previousDate
        								  AND IsCustomerAcceptsRisk__c=false
        								  AND IsCustomerAgreeToFix__c=false
        								  AND IsGfAcceptsRisk__c=false
        								  AND Waiver_Status__c='Rejected'
        								  AND PTSR_Status__c!='Closed'
        								]);
       
    }
    
    global void execute(Database.BatchableContext BC, List<Wavier_Collaborator__c> waiverList){
   		system.debug('Inside execute >>>>>>>>>> '+waiverList);     
        //Map<String,Set<Id>> mapOfCustNameUserIds = new Map<String,Set<Id>>();
        Map<Id,Set<Id>> mapOfFAEs = new Map<Id,Set<Id>>();
        Map<Id,Wavier_Collaborator__c> mapOfWaiverReport = new Map<Id,Wavier_Collaborator__c>();
        Map<Id,Set<Id>> mapOfPortalUsers = new Map<Id,Set<Id>>();
        List<Messaging.SingleEmailMessage> lstOfEmails = new List<Messaging.SingleEmailMessage>(); 
        List<String> uRoles = new List<String>{'Field Application Engineer','Primary Field Application Engineer'};
        List<String> atpManagers = new List<String>{'Primary Account Manager','Account Administrator','Account Manager'};  
		//Set<Id> AM_Users = DfmUtilityCls.getATPUsersByRole(collaborator.Account_Short_Name__c,atpManagers);
        
        if (waiverList<>NULL && !waiverList.isEmpty()){
            
            for (Wavier_Collaborator__c waiver : waiverList){
                
                mapOfWaiverReport.put(waiver.Id,waiver);
                Set<Id> setOfFAEs = DfmUtilityCls.getATPUsersByRole(waiver.Account_Short_Name__c,uRoles);
				Set<Id> setOfAMasFAE = DfmUtilityCls.getATPUsersByRoleFAEflag(waiver.Account_Short_Name__c);
                if(setOfAMasFAE != NULL && !setOfAMasFAE.isEmpty()){
                    setOfFAEs.addAll(setOfAMasFAE);
                }
				
                Set<Id> setOfPortalUsers = new Set<Id>(); //= DfmUtilityCls.getCustomers(waiver.Created_By_Shortname__c,waiver.Submitted_By_Shortname__c);
                Set<Id> setOfAM = DfmUtilityCls.getATPUsersByRole(waiver.Account_Short_Name__c,atpManagers);
                
                if (waiver.Selected_Customers__c<>NULL && !String.isEmpty(waiver.Selected_Customers__c)){
					for (String str : waiver.Selected_Customers__c.split(';')){
						setOfPortalUsers.add(Id.valueOf(str));
					}
				}  
                if (waiver.Is_releasedToCustomer__c == false){
                	sendEmailReminderToFAE4releaseToCustomer(waiver,setOfFAEs);
                }
                if (waiver.Is_releasedToCustomer__c == true){
                	sendReminderEmailToCustomer(waiver,setOfPortalUsers);
                	sendReminderEmailToFAE(waiver,setOfFAEs,setOfAM);
                }
            }
  
        }
       
    }
    
    // Send reminder email notification to customer
    private void sendReminderEmailToCustomer(Wavier_Collaborator__c waiver,Set<Id> customers){
    	
    	String primeDieName = DfmUtilityCls.getPrimeDieName(waiver.Id);
		String subject='Reminder: Your Response is required: '+waiver.Name+','+waiver.PTSR_Number__c+', '+primeDieName+' DFM Waiver Collaboration,'+waiver.Account_Name__c;
		List<String> toAddresses = DfmUtilityCls.getEmailIds(customers);
		List<String> ccAddresses = null;
		List<String> bccAddresses = new List<String>{'Gfv.do.not.reply@globalfoundries.com'};
		DfmEmailUtility emailUtil = new DfmEmailUtility(toAddresses,ccAddresses,bccAddresses);
		
		String body = '<html><body>'
						+'<h3>Title: Reminder for Your Response to Waiver Rejection Notification</h3><br>'
						+'Your request of DFM waiver for '+ primeDieName+' has been rejected.<br>'
						+'<p>Your prompt choice of action is required in the Design Waiver Collaborator:<p><br>'
						+System.Label.DFM_Customer_URL+'/' + waiver.Id+'<br>'
						+'<b>Issue Title:</b> DFM Waiver Collaboration File> '+waiver.PTSR_Number__c+'<br>'
						+'<b>Aggregated Waiver Review Status:</b> '+waiver.Waiver_Status__c+'<br>'
						+'<b>Collaborator Workflow Status:</b> '+waiver.Workflow_Status__c+'<br>'
						+'<b>Access the following URL to see DFM Waiver File: </b>'
						+System.Label.DFM_Customer_URL+'/' + waiver.Id+'<br><br>'
					+'</html></body>';	 
		//send plain text body
		emailUtil.htmlBody(body)
			 	 .senderDisplayName(UserInfo.getFirstName()+' '+UserInfo.getLastName())
			 	 .subject(subject)
			 	 .sendEmail();
		
    } 
    // Take appropriate action of DFM reminder email to FAE
    private void sendReminderEmailToFAE(Wavier_Collaborator__c waiver,set<Id> FAEs,set<Id> AM){
    	
    	String primeDieName = DfmUtilityCls.getPrimeDieName(waiver.Id);
		String subject='Reminder: Your action is required:'+waiver.Name+','+waiver.PTSR_Number__c+', '+primeDieName+' DFM Waiver Collaboration,'+waiver.Account_Name__c;
		List<String> toAddresses = DfmUtilityCls.getEmailIds(FAEs);
		List<String> ccAddresses = DfmUtilityCls.getEmailIds(AM);
		List<String> bccAddresses = new List<String>{'Gfv.do.not.reply@globalfoundries.com'};
		DfmEmailUtility emailUtil = new DfmEmailUtility(toAddresses,ccAddresses,bccAddresses);
		
		String body = '<html><body>'
						+'<h3>Title: FAE Action Notification for Customer Response</h3><br>'
						+'<p>The DFM waiver for '+ primeDieName+' has been rejected and customer has not been responding to agree to design fixes or accepting risk.' 
						+'Please proceed to discuss with AM and the customer. If no positive response, you may trigger for foundry-to-risk approval in the Design Waiver Design Waiver Collaborator<br>'
						+ URL.getSalesforceBaseUrl().toExternalForm() +'/' + waiver.Id+'</p>'
						+'<b>Issue Title:</b> DFM Waiver Collaboration File '+waiver.PTSR_Number__c+'<br>'
						+'<b>Aggregated Waiver Review Status:</b> '+waiver.Waiver_Status__c+'<br>'
						+'<b>Collaborator Workflow Status:</b>'+waiver.Workflow_Status__c+'<br>'
						+'<b>Access the following URL to see DFM Waiver File: </b>'
						+URL.getSalesforceBaseUrl().toExternalForm() +'/' + waiver.Id+'<br><br>'
						+'</html></body>';	 
		//send plain text body
		emailUtil.htmlBody(body)
			 	 .senderDisplayName(UserInfo.getFirstName()+' '+UserInfo.getLastName())
			 	 .subject(subject)
			 	 .sendEmail();
    	
    }
    // release waiver report to customer reminder email
    private void sendEmailReminderToFAE4releaseToCustomer(Wavier_Collaborator__c waiver,set<Id> FAEs){
		
			String primeDieName = DfmUtilityCls.getPrimeDieName(waiver.Id);
			String subject='Reminder: Your Approval is required: '+waiver.Name+','+waiver.PTSR_Number__c+', '+primeDieName+' DFM Waiver Collaboration,'+waiver.Account_Name__c;
			List<String> toAddresses = DfmUtilityCls.getEmailIds(FAEs);
			List<String> ccAddresses = null;
			List<String> bccAddresses = new List<String>{'Gfv.do.not.reply@globalfoundries.com'};
			DfmEmailUtility emailUtil = new DfmEmailUtility(toAddresses,ccAddresses,bccAddresses);
			
			String body = '<html><body>'
							+'<h3>Title: Reminder for Approval for Waiver Rejection Notification to Customer</h3><br>'
							+'The DFM waiver for '+ primeDieName+' has been rejected by '+UserInfo.getFirstName()+' '+UserInfo.getLastName()+'<br>'
							+'<p> Action Required: Waiver report is pending your review and approval to release to customer for design fixes / accepting risk in the Design Waiver Collaborator:<p><br>'
							+URL.getSalesforceBaseUrl().toExternalForm() +'/' + waiver.Id+'<br>'
							+'<font color="red">Proceed to release </font> = Trigger Collaborator to release the waiver rejection report and email notify the customer <br>'
							+'<b>Issue Title:</b> DFM Waiver Collaboration File '+waiver.PTSR_Number__c+'<br>'
							+'<b>Aggregated Waiver Review Status:</b> '+waiver.Waiver_Status__c+'<br>'
							+'<b>Collaborator Workflow Status:</b> '+waiver.Workflow_Status__c+'<br>'
							+'<b>Access the following URL to see DFM Waiver File: </b>'
							+URL.getSalesforceBaseUrl().toExternalForm() +'/' + waiver.Id+'<br><br>'
						+'</html></body>';	 
			//send plain text body
			emailUtil.htmlBody(body)
				 	 .senderDisplayName(UserInfo.getFirstName()+' '+UserInfo.getLastName())
				 	 .subject(subject)
				 	 .sendEmail();    
				 	 	
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}