objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF( CONTAINS(Name, &apos;ADVANCED MICRO DEVICES&apos;) , &apos;AMD&apos;,  IF(CONTAINS(Name, &apos;BROADCOM&apos;) , &apos;Broadcom&apos;,  IF( CONTAINS(Name, &apos;QUALCOMM&apos;) , &apos;Qualcomm&apos;, &apos;Others&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Team_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Proxy</relationshipLabel>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fab_Assignment__c</fullName>
        <label>Fab Assignment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
                <value>
                    <fullName>ASIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Proxy</label>
    <nameField>
        <displayFormat>ATP-{000000}</displayFormat>
        <label>ATP Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Proxy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>Indicate Fab where this device produce</description>
        <inlineHelpText>Indicate Fab where this device produce</inlineHelpText>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <inlineHelpText>Identify Tapeout type. Do not pick Retrofit.</inlineHelpText>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>Full Layer Retrofit</fullName>
                </value>
                <value>
                    <fullName>TD Test Chip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will have the Customer Information of a Lot</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturing Lot</relationshipLabel>
        <relationshipName>Manufacturing_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Type__c</fullName>
        <description>Mapped to Lot_Type</description>
        <label>Lot Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Yield_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Yield Feedback</relationshipLabel>
        <relationshipName>Yield_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Device__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Yield Feedback</relationshipLabel>
        <relationshipName>Yield_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manufacturing_Lot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Lot</label>
        <referenceTo>Manufacturing_Lot__c</referenceTo>
        <relationshipLabel>Yield Feedback</relationshipLabel>
        <relationshipName>Yield_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_QD_Reminder__c</fullName>
        <formula>IF(NOT(ISBLANK(Manufacturing_Lot__r.Last_Ship_Date__c)), IF(NOT(OR(ISPICKVAL(Functional__c, &apos;Yes&apos;),ISPICKVAL(Functional__c, &apos;No&apos;))), IF((Manufacturing_Lot__r.Last_Ship_Date__c + 3) == TODAY(), true, false), false), false)</formula>
        <label>Send QD Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_QF_Reminder__c</fullName>
        <formula>IF(NOT(ISBLANK(Manufacturing_Lot__r.Last_Ship_Date__c)) ,

IF(NOT(ISBLANK(Yield_Feedback_Due_Date_Modified__c)), 

IF(NOT(OR(ISPICKVAL(Functional__c, &apos;Yes&apos;),ISPICKVAL(Functional__c, &apos;No&apos;))), IF(OR((Yield_Feedback_Due_Date_Modified__c - 1) ==   TODAY(), (Yield_Feedback_Due_Date_Modified__c - 15) == TODAY(), (Yield_Feedback_Due_Date_Modified__c - 30) == TODAY()), true, false), false), 

IF(NOT(OR(ISPICKVAL(Functional__c, &apos;Yes&apos;),ISPICKVAL(Functional__c, &apos;No&apos;))), IF(OR((Yield_Feedback_Due_Date__c - 1) == TODAY(), (Yield_Feedback_Due_Date__c - 15) == TODAY(), (Yield_Feedback_Due_Date__c - 30) == TODAY()), true, false), false)

)

, false

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Send QF Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Yield Feedback</label>
    <nameField>
        <displayFormat>YF-{000000000}</displayFormat>
        <label>Yield Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yield Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/YieldFeedbackRemindersBatch.cls
/*
    Author: Zymark Ambat
    Description: This is a batch class to send email reminders for Yield Feedback.
    History: 
        ZAmbat      1211204    - Code creation.
*/

global class YieldFeedbackRemindersBatch implements Database.Batchable<sObject> {
    global EmailTemplate template1 {get;set;}
    global EmailTemplate template2 {get;set;}
    global string soql {get;set;}
    
    global YieldFeedbackRemindersBatch() {
        this.template1 = [
            SELECT    Id
            FROM      EmailTemplate
            WHERE     DeveloperName = 'EPTS_Notification_VF_2'
        ];
        
        this.template2 = [
            SELECT    Id
            FROM      EmailTemplate
            WHERE     DeveloperName = 'EPTS_Notification_VF_3'
        ];
        
        this.soql = 'SELECT Id, Account__c, Device__r.Tapeout_Type__c, Device__r.Fab__c, Manufacturing_Lot__r.Account_Name__c, Manufacturing_Lot__r.Lot_Type__c, Send_QD_Reminder__c, Send_QF_Reminder__c ' +
                    'FROM Yield_Feedback__c ' + 
                    'WHERE Send_QD_Reminder__c = true OR Send_QF_Reminder__c = true';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(this.soql);
    }
    
    global void execute(Database.BatchableContext ctx, List<Sobject> scope) {
        List<Yield_Feedback__c> listYieldFeedback = (List<Yield_Feedback__c>)scope; 
        
        // Get recipients map 
        Set<Id> accountIds = new Set<Id>();
        for (Yield_Feedback__c y : listYieldFeedback) {
            accountIds.add(y.Account__c);
        }

        // Create Map for Account - Account Team Proxy
        Map<Id, Account> mapATP = new Map<Id, Account>(); 
        mapATP = new Map<Id, Account>([SELECT    Id
                                                 , (SELECT   User__c 
                                                             , User__r.Email
                                                             , Fab_Assignment__c
                                                             , Team_Role__c
                                                    FROM     Account_Team_Proxy__r 
                                                    WHERE    User__r.IsActive = true
                                                             AND (Team_Role__c IN ('Customer Engineer'
                                                                                  , 'Field Application Engineer'
                                                                                  , 'Field Technical Support'
                                                                                  , 'Primary Field Technical Support'
                                                                                  , 'Primary Field Application Engineer')
                                                                  OR ( Team_Role__c = 'Account Manager' AND Is_FAE__c = TRUE)
                                                                  OR ( Team_Role__c = 'Primary Account Manager' AND Is_FAE__c = TRUE))
                                                  )
                                       FROM      Account
                                       WHERE     Id IN :accountIds]);
        
        User u = [
            SELECT    Id
                      , Email
            FROM      User
            WHERE     Name = :Environment_Variable__c.getInstance('EPTS_QF_CE_NAME').Value__c
        ];
        
        // Construct the email
        List<Messaging.SingleEmailMessage> listEmail = new List<Messaging.SingleEmailMessage>();
        for (Yield_Feedback__c y : listYieldFeedback) {    
            if (mapATP.get(y.Account__c).Account_Team_Proxy__r.size() > 0) {
                Map<Id, string> mapRecipients = new Map<Id, string>();
                if (y.Device__r.Tapeout_Type__c == 'GlobalShuttle MPW') {
                    mapRecipients.put(u.Id, u.Email);
                }
                
                for (Account_Team_Proxy__c a : mapATP.get(y.Account__c).Account_Team_Proxy__r) {
                    if (a.Team_Role__c == 'Customer Engineer') {
                        if (y.Device__r.Tapeout_Type__c != 'GlobalShuttle MPW') {
                            if (a.Fab_Assignment__c != null) {
                                List<string> listFab = a.Fab_Assignment__c.split(';');
                                Set<string> setFab = new Set<string>();
                                setFab.addAll(listFab);
                                if (setFab.contains(y.Device__r.Fab__c)) {
                                    mapRecipients.put(a.User__c, a.User__r.Email);
                                }
                            }
                        }
                    } else {
                        mapRecipients.put(a.User__c, a.User__r.Email);
                    }
                }
                
                string templateId;
                if (y.Send_QD_Reminder__c) {
                    templateId = this.template1.Id;     
                } else if (y.Send_QF_Reminder__c) {
                    templateId = this.template2.Id;
                }
               
                listEmail.add(createEmail(templateId, y.Id, mapRecipients));
            }

        }
        
        // Send email
        if (listEmail.size() > 0 && !test.isRunningTest()) {
            Messaging.sendEmail(listEmail);
        }
    }
    
    global void finish(Database.BatchableContext BC) {}
    
    global Messaging.SingleEmailMessage createEmail(Id templateId, Id recordId, Map<Id, string> mapRecipients) {       
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.templateId = templateId;
        
        List<Id> listUserId = new List<Id>();
        listUserId.addAll(mapRecipients.keySet());
        
        email.setTargetObjectId(listUserId[0]);
        mapRecipients.remove(listUserId[0]);
        if (mapRecipients.size() > 0) {
            email.setToAddresses(mapRecipients.values());                        
        }
        email.setCCAddresses(Environment_Variable__c.getInstance('EPTS_CC_ADDRESSES').Value__c.split(';'));
        email.setBCCAddresses(Environment_Variable__c.getInstance('EPTS_BCC_ADDRESSES').Value__c.split(';'));                        
        email.setWhatId(recordId);
        email.setSaveAsActivity(false);

        return email;
    }
}