objects/Account.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Suppliers</fullName>
        <active>true</active>
        <description>FV2 : It controls the picklist value of Stage.Stage - Unqualified,Inactive</description>
        <label>Suppliers</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <description>FV2: Used for storing the Department values of Contact</description>
        <inlineHelpText>This field is optional; when filled in it provides default access to GFV applications for one or more predefined roles (Design, Engineering, Quality, Procurement, Supply Chain, Legal).</inlineHelpText>
        <label>Department (GFV Access)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supplier Services</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Portal_Tab_Access__c.object
<CustomObject>
    <description>FV2 : Used for storing the visibility information of a portal user on the different gadgets (tabs)</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>FV2 : lookup to account object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Access Setup</relationshipLabel>
        <relationshipName>Portal_Tab_Access</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Access Setup</relationshipLabel>
        <relationshipName>Access_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Access Setup</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Access Setup No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Setup</pluralLabel>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TabAccessCreatePageController.cls
/**
* Author        :   Yash
* Company       :   IBM India.
* Description   :   New Functionality added according to account Recordtype to visible Supplier section.
* History       :
        Initials        Date                Description
-----------------------------------------------------------------------------------------
        Ykumar          11/02/2014          Created the Class
        
**/

public class TabAccessCreatePageController
{
    public TabAccessCreatePageController(ApexPages.StandardController controller){}
    
    public static Boolean SupplierSection
    {
        get
        {
            if(SupplierSection==NULL)
                if(PTARec<>NULL)
                    if(PTARec.Account__r.RecordType.DeveloperName=='Suppliers')
                        SupplierSection=true;
                     else
                        SupplierSection=false;    
            return SupplierSection;            
        }
        set;
    }
    
    
    public static Boolean NotSupplierSection
    {
        get
        {
            if(NotSupplierSection==NULL)
                if(PTARec<>NULL)
                    if(PTARec.Account__r.RecordType.DeveloperName<>'Suppliers')
                        NotSupplierSection=true;
                     else
                        NotSupplierSection=false;    
            return NotSupplierSection;            
        }
        set;
    }
    
    public static Boolean isVendorPortalUser
    {
        get
        {
            Set<String> DeptValues=new Set<String>();
            if(isVendorPortalUser==NULL)
                if(PTARec<>NULL)
                    if(PTARec.Contact__r.Department__c <>NULL)
                        {
                            System.debug('logic is here=');
                            DeptValues.addAll(String.valueof(PTARec.Contact__r.Department__c).split(';'));                            
                            if(DeptValues.contains('Vendor Services'))
                                isVendorPortalUser=true;
                            else
                                isVendorPortalUser=false;    
                        }
                          
             return isVendorPortalUser;                   
        }
        set;
    }
 
    public static Id AccessId
    {
        get
        {
            AccessId=NULL;
            if(AccessId==NULL) AccessId=(Id)ApexPages.currentPage().getParameters().get('id');
            if(AccessId<>NULL) return AccessId;
            return AccessId;
        }
        
        set;
    }
    public static Portal_Tab_Access__c PTARec
    {
        get
        {
            if(PTARec==NULL)
            {
                PTARec=new Portal_Tab_Access__c();
                if(AccessId !=null) PTARec=[select id,Account__r.RecordType.DeveloperName,Contact__r.Department__c from Portal_Tab_Access__c where id=:AccessId limit 1][0];
            }
            return  PTARec;
            
        }
        set;
    }
    
    
}