objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Clip_Level_Exemption__c.object
<CustomObject>
    <description>This object is used to for Clip Level Exemption, where selected accounts are exempted from Deal Grading</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Clip_Level_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field to make the field active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ASIC</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>Leading Edge</fullName>
                </value>
                <value>
                    <fullName>Mainstream</fullName>
                </value>
                <value>
                    <fullName>Mature</fullName>
                </value>
                <value>
                    <fullName>Packaging / Hetero-Integration</fullName>
                </value>
                <value>
                    <fullName>RF</fullName>
                </value>
                <value>
                    <fullName>SiPh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LTR_Min__c</fullName>
        <label>LTR Min</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Process_Node__c</fullName>
        <label>Target Process Node</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>&lt;28nm Other</fullName>
                </value>
                <value>
                    <fullName>&gt;0.18um Other</fullName>
                </value>
                <value>
                    <fullName>&gt;0.25um</fullName>
                </value>
                <value>
                    <fullName>0.007UM (7nm)</fullName>
                </value>
                <value>
                    <fullName>0.11G</fullName>
                </value>
                <value>
                    <fullName>0.11LP</fullName>
                </value>
                <value>
                    <fullName>0.11TS</fullName>
                </value>
                <value>
                    <fullName>0.13BCD</fullName>
                </value>
                <value>
                    <fullName>0.13BCDlite</fullName>
                </value>
                <value>
                    <fullName>0.13EE</fullName>
                </value>
                <value>
                    <fullName>0.13G</fullName>
                </value>
                <value>
                    <fullName>0.13LP</fullName>
                </value>
                <value>
                    <fullName>0.13um RF SOI</fullName>
                </value>
                <value>
                    <fullName>0.14EEPROM</fullName>
                </value>
                <value>
                    <fullName>0.14G</fullName>
                </value>
                <value>
                    <fullName>0.152IC</fullName>
                </value>
                <value>
                    <fullName>0.153G</fullName>
                </value>
                <value>
                    <fullName>0.15G</fullName>
                </value>
                <value>
                    <fullName>0.16IC</fullName>
                </value>
                <value>
                    <fullName>0.18BCD</fullName>
                </value>
                <value>
                    <fullName>0.18BCDlite_IC</fullName>
                </value>
                <value>
                    <fullName>0.18BCDlite_ULL</fullName>
                </value>
                <value>
                    <fullName>0.18HV</fullName>
                </value>
                <value>
                    <fullName>0.18IC</fullName>
                </value>
                <value>
                    <fullName>0.18MCU</fullName>
                </value>
                <value>
                    <fullName>0.18ULL</fullName>
                </value>
                <value>
                    <fullName>0.18um - 65nm Other</fullName>
                </value>
                <value>
                    <fullName>0.20G</fullName>
                </value>
                <value>
                    <fullName>0.22G</fullName>
                </value>
                <value>
                    <fullName>0.22HV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Exception__c</fullName>
        <label>Type of Exception</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client Exemption</fullName>
                </value>
                <value>
                    <fullName>Clip level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Grading Clip Level</label>
    <nameField>
        <label>Clip Level Exemption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Grading Clip Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOM LOGIC</fullName>
                </value>
                <value>
                    <fullName>CUSTOM PROCESSORS</fullName>
                </value>
                <value>
                    <fullName>SERVICES</fullName>
                </value>
                <value>
                    <fullName>SPECIALTY FOUNDRY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Grading_status__c</fullName>
        <label>Deal Grading status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Resubmission</fullName>
                </value>
                <value>
                    <fullName>Deal Grading Review</fullName>
                </value>
                <value>
                    <fullName>Complete - Proceed to Quote</fullName>
                </value>
                <value>
                    <fullName>Complete - Review Not Required</fullName>
                </value>
                <value>
                    <fullName>Complete - No Bid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LTR_Rev__c</fullName>
        <formula>Opportunity1__r.LTR_Rev_M__c</formula>
        <label>LTR Rev ($M)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>&gt; Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Grading (Opportunity)</relationshipLabel>
        <relationshipName>Deal_Grading9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Product Line from Opportunity</description>
        <formula>TEXT( Opportunity1__r.Product_Line__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product Line is the unit which has the profit and loss for the oppty.</inlineHelpText>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proceed to Bid</fullName>
                </value>
                <value>
                    <fullName>No Bid - Business Rejected</fullName>
                </value>
                <value>
                    <fullName>Decision Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Proceed to Sizing / Review with Brand Prior to Release</fullName>
                </value>
                <value>
                    <fullName>PTQ  In Menu - Proceed to Quote with In Menu IP Only</fullName>
                </value>
                <value>
                    <fullName>PTQ - Proceed to Quote with full requested client support </fullName>
                </value>
                <value>
                    <fullName>PTS SQT (Proceed to Sizing - SQT Only)</fullName>
                </value>
                <value>
                    <fullName>Deal Grading Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Process_Node__c</fullName>
        <description>Target Process Node from Opportunity</description>
        <formula>TEXT(Opportunity1__r.Target_Process_Node__c)</formula>
        <label>Target Process Node</label>
        <type>Text</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Field created to store IBM information</description>
        <label>Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Grading_Status__c</fullName>
        <label>Deal Grading Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process_Geometry__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Line</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Process_Node__c</fullName>
        <description>Not integrated with the PLM. This is the general marketing definition of the process nodes.
Change Log
4/2 : Mike Chen - Remove 10XM and replace with 10LPP
6/9 : Add 14SOI IBM Process
1/30/16 : Added Fab 9,10 process nodes Case 00051248</description>
        <inlineHelpText>Select the process node that best describe the target process.</inlineHelpText>
        <label>Target Process Node</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process_Geometry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0.007UM (7nm)</fullName>
                </value>
                <value>
                    <fullName>10LPP</fullName>
                </value>
                <value>
                    <fullName>14HP</fullName>
                </value>
                <value>
                    <fullName>14LPE</fullName>
                </value>
                <value>
                    <fullName>14LPP</fullName>
                </value>
                <value>
                    <fullName>14LPX</fullName>
                </value>
                <value>
                    <fullName>14SOI</fullName>
                </value>
                <value>
                    <fullName>14XM</fullName>
                </value>
                <value>
                    <fullName>20LPM</fullName>
                </value>
                <value>
                    <fullName>22FDSOI</fullName>
                </value>
                <value>
                    <fullName>28A</fullName>
                </value>
                <value>
                    <fullName>28FDSOI</fullName>
                </value>
                <value>
                    <fullName>28HPM</fullName>
                </value>
                <value>
                    <fullName>28HPP</fullName>
                </value>
                <value>
                    <fullName>28LPH</fullName>
                </value>
                <value>
                    <fullName>28LPH-N</fullName>
                </value>
                <value>
                    <fullName>28LPQ</fullName>
                </value>
                <value>
                    <fullName>28LPS</fullName>
                </value>
                <value>
                    <fullName>28-LP-TI</fullName>
                </value>
                <value>
                    <fullName>28RMG-IMC</fullName>
                </value>
                <value>
                    <fullName>28SHP</fullName>
                </value>
                <value>
                    <fullName>28SLP</fullName>
                </value>
                <value>
                    <fullName>28SLP_RF</fullName>
                </value>
                <value>
                    <fullName>28SLP-ST</fullName>
                </value>
                <value>
                    <fullName>28U</fullName>
                </value>
                <value>
                    <fullName>32SOI</fullName>
                </value>
                <value>
                    <fullName>40BCDlite</fullName>
                </value>
                <value>
                    <fullName>40G</fullName>
                </value>
                <value>
                    <fullName>40LP</fullName>
                </value>
                <value>
                    <fullName>40LP_RF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Product_Line.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Leading Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Mainstream</fullName>
    </customValue>
    <customValue>
        <fullName>Mature</fullName>
    </customValue>
    <customValue>
        <fullName>IBM</fullName>
    </customValue>
    <customValue>
        <fullName>Packaging / Hetero-Integration</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>SiPh</fullName>
    </customValue>
    <customValue>
        <fullName>RF</fullName>
    </customValue>
    <description>GLOBALFOUNDRIES Product Line
Leading Edge
Mainstream
Mature
IBM
Packaging / Hetero-Integration
ASIC
SiPh
RF</description>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

classes/DealGrading_ClipLevel.cls
/*
Type name: DealGrading_ClipLevel
Author: Vijay Vemuru

Description: This class evaluates the rules that are active in the below 2 conditions:

1.Client Level: if the client in the exemption matches with the client (Opp's account) in deal grading record, if match is found then result and deal grading status
is changed to 'NO Bid - deal Grading not required.
2.Clip level: If the the combination of 'Target Process Node', Min LTR, Product Line, matches with the current deal grading record in context
then result and deal grading status is changed to 'NO Bid - deal Grading not required'.

Test Class: DealGrading_CliplevelTest
History:    6/7/2016  Code creation
*/
public class DealGrading_ClipLevel {
    
    public void Implementcliplevel(List<Deal_Grading__c> dealgrading){
        List<Clip_Level_Exemption__c> rules     =       new List<Clip_Level_Exemption__c>();
        set<string> typeOfExceptions = new set<String>{'Client Exemption','Clip level'};
        set<id> oppIds = new set<id>();
        for(Deal_Grading__C dg : dealgrading){
           oppIds.add(dg.Opportunity1__c);
           
        }
        map<id,opportunity> oppMap = new map<id,opportunity>();
        try{
            oppMap = new map<id,opportunity>([SELECT accountId FROM Opportunity where id in:oppIds] );
        }catch(Exception excp){GlobalUtility.logMessage('Error','DealGrading_ClipLevel','Implementcliplevel','','Exception while getting the Opportunity data',String.valueof(excp.getMessage()),'','Deal Grading',excp,0);}
        try{                    
            rules = [SELECT Account__c,Account__r.id, Target_Process_Node__c, Brand__c, LTR_Min__c, Type_of_Exception__c 
                        FROM Clip_Level_Exemption__c WHERE Active__c =: True AND Type_of_Exception__c IN: typeOfExceptions];
        }catch(Exception excp){GlobalUtility.logMessage('Error','DealGrading_ClipLevel','Implementcliplevel','','Exception while getting the Clip Level data',String.valueof(excp.getMessage()),'','Deal Grading',excp,0);}
        for(Deal_Grading__c dg:dealgrading){
            String dg_Combination = dg.Target_Process_Node__c+dg.Product_Line__c;
            for(Clip_Level_Exemption__c rule1 : rules){
                String Rule_Combination = rule1.Target_Process_Node__c+rule1.Brand__c;
                
                //Clip Level Implementation   
                             
                if( (dg_Combination == rule_Combination) && (rule1.Type_of_Exception__c=='Clip level')  && (dg.LTR_Rev__c>rule1.LTR_Min__c)){
                        dg.Result__c                =   'Deal Grading Not Required';   
                        dg.Deal_Grading_status__c   =   'Bid - Review Not Required';
                }
                
                //Client Level Implementation
                
                 if(rule1.Type_of_Exception__c=='Client Exemption' && oppMap.get(dg.Opportunity1__c).AccountId  ==  Rule1.Account__c){ 
                    dg.Result__c                =   'Deal Grading Not Required';   
                     dg.Deal_Grading_status__c   =   'Bid - Review Not Required';
                 }               
             }  
              
         }
        
     }
    
 }