objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This field is used by the batch job that computes for adjustment between device forecast and quarterly revenue.</description>
        <formula>CASESAFEID(Opportunity_Program__r.Opportunity__c)</formula>
        <inlineHelpText>The Opportunity under which the Device resides</inlineHelpText>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Request_Information__c.object
<CustomObject>
    <description>Custom object defining detail of Request for Quote and Request for Information.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RFQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Device__c.Opportunity2__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Device__c</referenceTo>
        <relationshipName>RFQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FolderId__c</fullName>
        <label>FolderId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>RFQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RFQ__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>RFQs</relationshipLabel>
        <relationshipName>RFQs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFQs</relationshipLabel>
        <relationshipName>RFQs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFQ</label>
    <nameField>
        <displayFormat>{YYYY}-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RFQ_Routing__c.object
<CustomObject>
    <description>Custom object defining detail of Route related to RFQ and RFI</description>
    <fields>
        <fullName>Device__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; +RFQ__r.Customer_Requirement__r.Device__r.Id,  RFQ__r.Customer_Requirement__r.Device__r.Name  , &apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Device</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFQ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Information</label>
        <referenceTo>Request_Information__c</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>RFQ_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Routing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BNP_LockGoogleSheetCtrl.cls
/*
Type Name: BNP_LockGoogleSheetCtrl
Author: Deepti Narayan Biswal
Project Name: DIW Step Down Track 2 (BnP) 
Created Date: 08232016
Description: This class serves controller for BNP_LockGoogleSheet page.
Test Class: 
Change History:
*/
global class BNP_LockGoogleSheetCtrl{
    
    @remoteAction
    global static bnpwrapper getRFQDetail(string rIid){
        
        List<RFQ_Routing__c> rfqlist=[select id,Name,createddate,FileId__c,RFQ__c,RFQ__r.device__c,RFQ__r.Opportunity__c,RFQ__r.FolderId__c,RFQ__r.Account__r.Name,RFQ__r.Opportunity__r.Name from RFQ_Routing__c where RFQ__c=:rIid Order BY CreatedDate LIMIT 1];
        
        bnpwrapper routingwrap = new bnpwrapper(rfqlist[0]);
        return routingwrap;
        
    }
    
    global class bnpwrapper{
        global RFQ_Routing__c routing;
        global String mail;
        
        global bnpwrapper(RFQ_Routing__c rfqRout){
            routing = rfqRout;
            mail = UserInfo.getUserEmail();
        }
    }
}