objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Enablement Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALFOUNDRIES Internal</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Suppliers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Copy_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Corporate Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US SoCal1</fullName>
                </value>
                <value>
                    <fullName>EMEA-ROA</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Japan Korea</fullName>
                </value>
                <value>
                    <fullName>US NW</fullName>
                </value>
                <value>
                    <fullName>US SoCal2</fullName>
                </value>
                <value>
                    <fullName>US Central1</fullName>
                </value>
                <value>
                    <fullName>SEC-Foundry</fullName>
                </value>
                <value>
                    <fullName>MRVL</fullName>
                </value>
                <value>
                    <fullName>NVDA</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US Central2</fullName>
                </value>
                <value>
                    <fullName>US SW</fullName>
                </value>
                <value>
                    <fullName>US SoCal3</fullName>
                </value>
                <value>
                    <fullName>US NorCal</fullName>
                </value>
                <value>
                    <fullName>US NE1</fullName>
                </value>
                <value>
                    <fullName>US NE2</fullName>
                </value>
                <value>
                    <fullName>US SE</fullName>
                </value>
                <value>
                    <fullName>US West1</fullName>
                </value>
                <value>
                    <fullName>US West2</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>US NE3</fullName>
                </value>
                <value>
                    <fullName>ASIC-NA</fullName>
                </value>
                <value>
                    <fullName>ASIC-AP</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
                <value>
                    <fullName>ASIC-JP</fullName>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organization_Unit__c</fullName>
        <label>Organization Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GF Investment LLC OU</fullName>
                </value>
                <value>
                    <fullName>GF Netherlands Holding BV OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module One Admin GmbH OU</fullName>
                </value>
                <value>
                    <fullName>GF Americas Inc OU</fullName>
                </value>
                <value>
                    <fullName>GF Taiwan Ltd</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module Two GmbH &amp; Co. KG OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module One LLC</fullName>
                </value>
                <value>
                    <fullName>GF Netherlands B.V. OU</fullName>
                </value>
                <value>
                    <fullName>GF Singapore Pte Ltd OU (Fab 3E)</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module One LLC &amp; Co. KG OU</fullName>
                </value>
                <value>
                    <fullName>GF Inc (Cayman) OU</fullName>
                </value>
                <value>
                    <fullName>SMP Pte Lte/Lucent OU</fullName>
                </value>
                <value>
                    <fullName>GF Management Services LLC &amp; Co. KG OU</fullName>
                </value>
                <value>
                    <fullName>GF New York OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module Two LLC</fullName>
                </value>
                <value>
                    <fullName>GF (Netherlands) Cooperatief U.A. OU</fullName>
                </value>
                <value>
                    <fullName>GF Singapore Pte Ltd OU (Fab 6)</fullName>
                </value>
                <value>
                    <fullName>GF Japan Ltd</fullName>
                </value>
                <value>
                    <fullName>SMP Pte Ltd OU</fullName>
                </value>
                <value>
                    <fullName>GF U.S. Inc. OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module Two Admin GmbH OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module One Holding GMBH OU</fullName>
                </value>
                <value>
                    <fullName>GF Dresden Module Two Holding GmbH OU</fullName>
                </value>
                <value>
                    <fullName>GF Europe Ltd</fullName>
                </value>
                <value>
                    <fullName>GF Singapore Pte Ltd OU</fullName>
                </value>
                <value>
                    <fullName>GF Burlington OU</fullName>
                </value>
                <value>
                    <fullName>GF East Fishkill OU</fullName>
                </value>
                <value>
                    <fullName>GF (Chengdu) Integrated Circuit Mfg Co., Ltd. OU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Short Name</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PairingTableTriggerTest.cls
/*
    Author: Mallika Seth
    Description: This is the test class for the PairingTableTrigger.  
    History:
        MSeth     1122015    - code creation.
*/
@isTest(SeeAllData=false)
private class PairingTableTriggerTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
        
        Map<String,Object> fieldValueMap = new Map<String,Object>();       
        fieldValueMap.put('Name', 'testing701');
        fieldValueMap.put('Stage__c', 'Unqualified');
        fieldValueMap.put('Short_Name__c', 'test725');
        fieldValueMap.put('Site_Department__c', 'cts.com');
        fieldValueMap.put('Account_Type__c', 'Customer');
        fieldValueMap.put('Organization_Unit__c', 'sg;us');
        fieldValueMap.put('Copy_Address__c', true);
        fieldValueMap.put('Corporate_Address_1__c', 'test');
        fieldValueMap.put('Corporate_City__c', 'sg');
        fieldValueMap.put('Corporate_Country__c', 'sg');        
        fieldValueMap.put('Financial_Territory__c', 'Greater China');
        fieldValueMap.put('Region__c', 'APJ');
        fieldValueMap.put('Sub_Type__c', 'Direct');
        fieldValueMap.put('Transaction_Type__c', 'Transactional');
        fieldValueMap.put('Account_Profile__c', 'Fabless - Emerging');
        fieldValueMap.put('Corporate_Postal_Zip_Code__c', '700007');
        fieldValueMap.put('Fab_9_10__c', 'No');
        fieldValueMap.put('recordtypeid', EnvironmentVariable.get('ACCT_RT_ID_CUSTOMER'));       
        AccountDataFactory.createAccount(fieldValueMap);
    }
    static Id createAccount() {
        // Create Account
        Account testAcct = getAccount('testing701'); 
        return testAcct.Id;
    }
 
    static Id createMaskSetTtitle(){
        Mask_Set_Title__c mst = new Mask_Set_Title__c();
        mst.Name = 'MSTTRT';
        mst.Reticle_Type__c = 'Multi Layer Reticle (MLR)';
        insert mst;
        return mst.Id;
    }
    
    
  
    
    static testMethod void PairingTableTriggerTest1() {
                
        string acctId = PairingTableTriggerTest.createAccount();
        String MSTId = PairingTableTriggerTest.createMaskSetTtitle();
                
        test.startTest();
            // Create Pairing Table
           Pairing_Table__c PT = new Pairing_Table__c();
            PT.Name = 'TESTPT';
            PT.Mask_Set_Title_Text__c ='MSTTRT';
            PT.PRF_Number__c = 'MPRF_123';
            insert PT;
            
        test.stopTest();
    }
    
    private static Account getAccount(string AccountName)
            {
                Account testAcct= [SELECT Id, Name FROM Account Where Name =: AccountName];
        
                return testAcct;
            }  
   
}