objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Team_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Proxy</relationshipLabel>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch_Sync_Id__c</fullName>
        <description>Used by the batch process to send the outbound message. Updated by the batch process only.</description>
        <label>Batch Sync Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab_Assignment_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to track if User has edited the Fab Assigned on Account Proxy</description>
        <label>Fab Assignment Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fab_Assignment__c</fullName>
        <label>Fab Assignment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
                <value>
                    <fullName>ASIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab_Deleted__c</fullName>
        <label>Fab Deleted</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Administrator</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Backup Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Business Planner</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Integration</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Customer Tapeout Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Engineer</fullName>
                </value>
                <value>
                    <fullName>DE - Customer Support</fullName>
                </value>
                <value>
                    <fullName>DE - Enablements</fullName>
                </value>
                <value>
                    <fullName>DE - IP Technical</fullName>
                </value>
                <value>
                    <fullName>Demand Planner</fullName>
                </value>
                <value>
                    <fullName>Design and Technology Support</fullName>
                </value>
                <value>
                    <fullName>Design Win Team</fullName>
                </value>
                <value>
                    <fullName>DE - Tapeout</fullName>
                </value>
                <value>
                    <fullName>Fab Planner</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Primary Account Manager</fullName>
                </value>
                <value>
                    <fullName>Primary Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Primary Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Marketing</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Engineer</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Strategic Marketing</fullName>
                </value>
                <value>
                    <fullName>TD PI / YE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Proxy</label>
    <nameField>
        <displayFormat>ATP-{000000}</displayFormat>
        <label>ATP Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Proxy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Fab_Assigned__c</fullName>
        <label>Fab Assigned</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab_Assignment_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fab Assignment Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fab_Deleted__c</fullName>
        <label>Fab Deleted</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountTeamUpdateBatch.cls
/*
    Author: Anirban Roy
    Description: Batch class to extract and update Account Team Proxy records for Fab Assignment modification in User object. 
    History: 
        ARoy        04222013    - code creation.
        Asolito     06102013    - Added fab deleted update 
        ASinghal    06192013    - Updated Query to only include records with Fab Assignment Change as False on Account Proxy Records and update the Fab when it is changed on User.
		Tlai		14032014	- Updated initial query to add fields Fab_Assignment__c, User__r.Fab_Assigned__c and removed the query in execute method
								  Added code to check if the Fab removed from user is not anymore assigned on ATP
								  Updated logic to partially update user records if any error
								  
*/
global class AccountTeamUpdateBatch implements Database.Batchable<sObject>{
    
    static final string ACC_TEAM_PRXY_TM_RL_CE = EnvironmentVariable.get('ACT_TM_PRXY_TM_RL_CE');
    static final string ACC_TEAM_PRXY_TM_RL_FP = EnvironmentVariable.get('ACCT_TM_PRXY_TM_RL_FP');
    
    // Query to fetch the Account Team Proxy records for Users having Fab_Assignment_Change__c checked
    // and Team Role as Customer Engineer and Fab Planner
    global final String query = 'Select User__c,Batch_Sync_Id__c,Team_Role__c,Fab_Deleted__c,Fab_Assignment__c,User__r.fab_deleted__c,User__r.Fab_Assigned__c from Account_Team_Proxy__c where'+
                                        +' User__c in (select Id from User where Fab_Assignment_Change__c = true) and '
                                        +' Fab_Assignment_Change__c = false and '
                                        +'Team_Role__c in (\''+ AccountTeamUpdateBatch.ACC_TEAM_PRXY_TM_RL_CE + '\',\''
                                        + AccountTeamUpdateBatch.ACC_TEAM_PRXY_TM_RL_FP + 
                                        '\') order by account__c';
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    // Method to update the Account Team Proxy record so to fire the outbound message for Fab Assignment in Account Team Proxy
    global void execute(Database.BatchableContext ctx, List<Sobject>  scope){
        List<Account_Team_Proxy__c> atpList = (List<Account_Team_Proxy__c>)scope;

        //Tlai 14032014  - UserId set with successful update of ATP
        set<id> usrIdSet = new set<id>();
        for(Integer i = 0; i < atpList.size(); i++){
        	usrIdSet.add(atpList[i].user__c);
        	
            //check if fab deleted field is blank, AIA will not set the fab deleted field to blank if an error occurs
            if(UtilsString.isNotBlank(atpList[i].user__r.fab_deleted__c)){
                String finalVal = '';
                String atpDeletedFabs = atpList[i].fab_deleted__c;
                String atpAssignedFabs = atpList[i].Fab_Assignment__c;// current Fab assignment 
                List<String> userDeletedFabList = atpList[i].user__r.fab_deleted__c.split('\\;');
                
                for(String fab: userDeletedFabList){
                    
                    //Tlai 14030124 -- if removed Fab on User has been assigend on ATP, then remove it on ATP. otherwise no action
                    if(UtilsString.isNotBlank(atpList[i].fab_deleted__c)){
                    	// check assigned Fabs againts removed fab on user
                        if(!atpDeletedFabs.contains(fab) && atpAssignedFabs.contains(fab)){
	                        finalVal += ';' + fab;
	                    }  
	                                  
	                } else {
	                	// check assigned Fabs againts removed fab on user
	                	if(atpAssignedFabs.contains(fab)){
	                		finalVal += fab +';';
	                	}
	                }
                }
                
                if(!String.isblank(finalVal)){
                	if( finalVal.endswith(';')){
                		finalVal = finalVal.substring(0,finalVal.length()-1).trim();//remove the ending character ';'
                	}
                	
                	if(UtilsString.isNotBlank(atpList[i].fab_deleted__c)){
	                	atpList[i].fab_deleted__c += finalVal; 
	                }else {
	                	atpList[i].fab_deleted__c = finalVal; 
	                }
                }
            }
            
            // Assign the Batch_Sync_Id__c of the Account Team Proxy to current datetime and assign Fab from User Level
            atpList[i].Batch_Sync_Id__c = String.valueof(System.now());
            atpList[i].Fab_Assignment__c = atpList[i].User__r.Fab_Assigned__c;
        } //end for loop
        
        // Update the Account Team Proxy records to send the outbound message
        List<Database.SaveResult> atpSRList = Database.update(atpList, false);
        
        for(integer i = 0; i< atpSRList.size(); i++){
            if(!atpSRList[i].isSuccess()){      
                usrIdSet.remove(atpList[i].user__c);
            }
        }
        
        // update users with success update of ATPs
        if(usrIdSet.size() > 0){      
            // Retrieve the users for whom Fab_Assignment_Change__c is true
            List<User> usrList = [select Id, Fab_Assignment_Change__c from User where Fab_Assignment_Change__c = true and id  in:usrIdSet];
            
            if(usrList.size() > 0){
            	
            	// Assign the Fab_Assignment_Change__c to false
	            for(Integer i=0; i< usrList.size(); i++){
	                usrList[i].Fab_Assignment_Change__c  = false;
	                usrList[i].fab_deleted__c = null;
	            }
	            // Update the users records to set the Fab_Assignment_Change__c checkbox as false
	            List<Database.SaveResult> usrSRList = Database.update(usrList, false);	
	            for(Database.SaveResult sr: usrSRList){
	            	if(!sr.isSuccess()){
	            		system.debug(sr.getErrors()[0].getMessage());
	            	}
	            }
	        }
        }
    }
    
    global void finish(Database.BatchableContext BC){

    }
    
   
    
}