objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CuSR_Approval_Process__c.object
<CustomObject>
    <description>Child object to CuSR_Form__c which will store approver and fab details.</description>
    <fields>
        <fullName>CuSR_Form__c</fullName>
        <description>Master Record.</description>
        <label>CuSR Form</label>
        <referenceTo>CuSR_Form__c</referenceTo>
        <relationshipLabel>CuSR Approval Processes</relationshipLabel>
        <relationshipName>CuSR_Approval_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the approval.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CuSR Approval Process</label>
    <nameField>
        <displayFormat>CUSR-APPROVAL-{YY}-{00000}</displayFormat>
        <label>CuSR Approval Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuSR Approval Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CuSR_Form__c.object
<CustomObject>
    <description>The object will be used to create CuSR Forms.</description>
    <fields>
        <fullName>Actual_Requirement__c</fullName>
        <label>Actual Requirement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to select Account. Only active accounts will be available for selection.</description>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CuSR Forms</relationshipLabel>
        <relationshipName>CUSR_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Requestor_Email__c</fullName>
        <description>Auto-populated with the selected Contact&apos;s email by apex method.</description>
        <label>Customer Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Contact object. Will search contacts related to selected Account.</description>
        <label>Customer Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CuSR Forms</relationshipLabel>
        <relationshipName>CUSR_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAB_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to select scope as Fab 1.</description>
        <label>FAB 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAB_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to select Fab 2.</description>
        <label>FAB 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAB_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FAB 8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_one_time_requirement__c</fullName>
        <description>Field to select Yes or No.</description>
        <label>Is this a one time requirement?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification_for_Request__c</fullName>
        <description>Long Text Area to capture justification for the request.</description>
        <label>Justification for Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_Customer_after_Implementation__c</fullName>
        <description>If checked will send notify the selected contact once all implementation is done.</description>
        <label>Notify Customer after Implementation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Received_Date__c</fullName>
        <description>Date when the request is received.</description>
        <label>Request Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>Date when the request will be effective from.</description>
        <label>Requested Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scope_of_the_CuSR__c</fullName>
        <description>Multi-select picklist field to select the scope of the CuSR request.</description>
        <label>Scope of the CuSR</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RTP Parts</fullName>
                </value>
                <value>
                    <fullName>Engineering Parts</fullName>
                </value>
                <value>
                    <fullName>Risk Product Parts</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Requirement__c</fullName>
        <description>Long Text Area to capture any special requirements.</description>
        <label>Any Special Requirement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The field will be populated with the current status of the form by an apex class.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending PM Review</fullName>
                </value>
                <value>
                    <fullName>Pending AM Review</fullName>
                </value>
                <value>
                    <fullName>Pending Stakeholder Review</fullName>
                </value>
                <value>
                    <fullName>Pending Implementation</fullName>
                </value>
                <value>
                    <fullName>Implemented</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>CUSR Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AUTOMOTIVE</fullName>
                </value>
                <value>
                    <fullName>CAR/ 8D</fullName>
                </value>
                <value>
                    <fullName>CONTROL PLAN</fullName>
                </value>
                <value>
                    <fullName>CPK</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER AUDIT</fullName>
                </value>
                <value>
                    <fullName>DCC</fullName>
                </value>
                <value>
                    <fullName>ETEST</fullName>
                </value>
                <value>
                    <fullName>FMEA</fullName>
                </value>
                <value>
                    <fullName>FRONTSIDE LASERMARK</fullName>
                </value>
                <value>
                    <fullName>INTERNAL AUDIT</fullName>
                </value>
                <value>
                    <fullName>LOGISTICS</fullName>
                </value>
                <value>
                    <fullName>LOT ID NAMING CONVENTION</fullName>
                </value>
                <value>
                    <fullName>MES SYSTEM</fullName>
                </value>
                <value>
                    <fullName>MRB</fullName>
                </value>
                <value>
                    <fullName>OCR Requirements</fullName>
                </value>
                <value>
                    <fullName>OQA – INSPECTION</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>PACKAGING, SHIPPING &amp; LABELS</fullName>
                </value>
                <value>
                    <fullName>PCRB</fullName>
                </value>
                <value>
                    <fullName>PPAP</fullName>
                </value>
                <value>
                    <fullName>PROCESS QUALIFICATION</fullName>
                </value>
                <value>
                    <fullName>QUALITY AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>RECORDS RETENTION</fullName>
                </value>
                <value>
                    <fullName>RELIABILITY</fullName>
                </value>
                <value>
                    <fullName>REPORTS</fullName>
                </value>
                <value>
                    <fullName>REWORK</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>ROS</fullName>
                </value>
                <value>
                    <fullName>RTP</fullName>
                </value>
                <value>
                    <fullName>SCRAPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validity_Period_of_this_Request__c</fullName>
        <description>Picklist value to select validity period of the request on Days, Months, Year and EOF.</description>
        <label>Validity Period of this Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CuSR Form</label>
    <nameField>
        <displayFormat>CUSR-{YY}-{00000}</displayFormat>
        <label>CUSR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuSR Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CuSRApprovalViewFormExtensionTest.cls
/*
Author: Shyam Ravindra Nair
Description: Test class for  CuSRApprovalViewFormExtension class.
History:
SNair     11012015     - code creation
SNair     28042015     - modified
*/
@isTest(SeeAllData=false)
public class CuSRApprovalViewFormExtensionTest {
    
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }

    public static testMethod void myTestClass1(){
        User testUser = [select Id from User where Profile.Name = 'GF CE' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            
            CuSR_Form__c testCuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_1__c = true,
                FAB_2__c = true,
                FAB_8__c = true,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New'
            );
            insert testCuSRForm;
            
            User approver = [select Id from User where Id != :userInfo.getUserId() and Profile.Name = 'GF CE' and isActive = true limit 1];
            
            CuSR_Approval_Process__c dresdenApprover = new CuSR_Approval_Process__c(
                Type_of_Approver__c = 'FAB 1 Owner',
                Site__c= 'Dresden',
                No_of_Approvers__c = '1',
                Approver1__c = approver.Id,
                CuSR_Form__c = testCuSRForm.Id,
                Fab__c = 'FAB 1',
                Status__c = 'Pending Approval'
            );
            insert dresdenApprover;
            
            CuSR_Approval_Process__c singaporeApprover = new CuSR_Approval_Process__c(
                Type_of_Approver__c = 'FAB 2 Owner',
                Site__c= 'Singapore',
                No_of_Approvers__c = '1',
                Approver1__c = approver.Id,
                CuSR_Form__c = testCuSRForm.Id,
                Fab__c = 'FAB 2',
                Status__c = 'Pending Approval'
            );
            insert singaporeApprover;
            
            CuSR_Approval_Process__c maltaApprover = new CuSR_Approval_Process__c(
                Type_of_Approver__c = 'FAB 8 Owner',
                Site__c= 'Malta',
                No_of_Approvers__c = '1',
                Approver1__c = approver.Id,
                CuSR_Form__c = testCuSRForm.Id,
                Fab__c = 'FAB 8',
                Status__c = 'Pending Approval'
            );
            insert maltaApprover;
            
            CuSR_Approval_Process__c amApprver = new CuSR_Approval_Process__c(
                Type_of_Approver__c = 'AM',
                No_of_Approvers__c = '1',
                Approver1__c = approver.Id,
                CuSR_Form__c = testCuSRForm.Id,
                Status__c = 'Pending Approval'
            );
            insert amApprver;
            
            
            test.startTest();
            CuSRApprovalViewFormExtension controller1 = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(dresdenApprover));
            controller1.back();
            controller1.actionOnPageLoad();
            
            CuSRApprovalViewFormExtension controller2 = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(singaporeApprover));
            controller2.back();
            controller2.actionOnPageLoad();
            
            CuSRApprovalViewFormExtension controller3 = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(maltaApprover));
            controller3.back();
            controller3.actionOnPageLoad();
            
            CuSRApprovalViewFormExtension controller4 = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(amApprver));
            controller4.back();
            test.stopTest();
            
        }
    }
    
    static testMethod void myTestClass2(){
        User testUser = [select Id from User where Profile.Name = 'GF CE' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            
            CuSR_Form__c testCuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_1__c = true,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New'
            );
            insert testCuSRForm;
            
            testCuSRForm.Stakeholder_Approval_Completed__c = true;
            testCuSRForm.Any_Cost_Impact__c = 'Yes';
            testCuSRForm.PM_Comments__c = 'sample';
            testCuSRForm.Status__c = 'Pending PM Review';
            testCuSRForm.PM_Approved__c = true;
            update testCuSRForm;
            
            UtilClassToGetAllFields util = new UtilClassToGetAllFields();
            String queryFields = util.getAllFields('CuSR_Approval_Process__c');
            String query = 'select '+queryFields+' from CuSR_Approval_Process__c where CuSR_Form__c = \''+testCuSRForm.Id+'\' and Type_of_Approver__c = \'AM\'';
            CuSR_Approval_Process__c amApprover = Database.query(query);
            
            test.startTest();
            CuSRApprovalViewFormExtension controller = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(amApprover));
            controller.cusrApproval.Does_the_customer_agree_to_pay_for_CUSR__c = 'Yes';
            controller.cusrApproval.Will_GLOBALFOUNDRIES_charge_the_customer__c = 'Yes';
            controller.saveAMData();
            controller.cusrApproval.Does_the_customer_agree_to_pay_for_CUSR__c = 'No';
            controller.cusrApproval.Will_GLOBALFOUNDRIES_charge_the_customer__c = 'No';
            controller.saveAMData();         
            controller.cusrApproval.Does_the_customer_agree_to_pay_for_CUSR__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification__c = 'sample';
            controller.cusrApproval.Will_GLOBALFOUNDRIES_charge_the_customer__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification_2__c = 'sample';
            controller.saveAMData();
            controller.amApproved();
            test.stopTest();
        }
    }
    
    static testMethod void myTestClass3(){
        User testUser = [select Id from User where Profile.Name = 'GF CE' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            
            CuSR_Form__c testCuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_1__c = true,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New'
            );
            insert testCuSRForm;
            
            testCuSRForm.Stakeholder_Approval_Completed__c = true;
            testCuSRForm.Any_Cost_Impact__c = 'Yes';
            testCuSRForm.PM_Comments__c = 'sample';
            testCuSRForm.Status__c = 'Pending PM Review';
            testCuSRForm.PM_Approved__c = true;
            testCuSRForm.PM_Approved_By__c = testUser.Id;
            testCuSRFOrm.PM_Approved_On__c = date.today();
            update testCuSRForm;
            
            UtilClassToGetAllFields util = new UtilClassToGetAllFields();
            String queryFields = util.getAllFields('CuSR_Approval_Process__c');
            String query = 'select '+queryFields+' from CuSR_Approval_Process__c where CuSR_Form__c = \''+testCuSRForm.Id+'\' and Type_of_Approver__c = \'AM\'';
            CuSR_Approval_Process__c amApprover = Database.query(query);
            
            test.startTest();
            CuSRApprovalViewFormExtension controller = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(amApprover));
            controller.amRejected();
            controller.cusrApproval.Does_the_customer_agree_to_pay_for_CUSR__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification__c = 'sample';
            controller.cusrApproval.Will_GLOBALFOUNDRIES_charge_the_customer__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification_2__c = 'sample';
            controller.amRejected();
            test.stopTest();
        }
    }
    
    static testMethod void myTestClass4(){
        try{
        User testUser = [select Id from User where Profile.Name = 'GF CE' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            
            CuSR_Form__c testCuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_1__c = true,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New'
            );
            insert testCuSRForm;
            
            testCuSRForm.Stakeholder_Approval_Completed__c = true;
            testCuSRForm.Any_Cost_Impact__c = 'No';
            //testCuSRForm.PM_Comments__c = 'sample';
            testCuSRForm.Status__c = 'Pending PM Review';
            testCuSRForm.PM_Approved__c = true;
            testCuSRForm.PM_Approved_By__c = testUser.Id;
            testCuSRFOrm.PM_Approved_On__c = date.today();            
            update testCuSRForm;
            
            
            UtilClassToGetAllFields util = new UtilClassToGetAllFields();
            String queryFields = util.getAllFields('CuSR_Approval_Process__c');
            String query = 'select '+queryFields+' from CuSR_Approval_Process__c where CuSR_Form__c = \''+testCuSRForm.Id+'\' and Type_of_Approver__c = \'AM\'';
            CuSR_Approval_Process__c amApprover = Database.query(query);
            
            test.startTest();
            CuSRApprovalViewFormExtension controller = new CuSRApprovalViewFormExtension(new ApexPages.Standardcontroller(amApprover));
            controller.amRejected();
            controller.cusrApproval.Does_the_customer_agree_to_pay_for_CUSR__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification__c = 'sample';
            controller.cusrApproval.Will_GLOBALFOUNDRIES_charge_the_customer__c = 'No';
            controller.cusrApproval.If_No_Please_provide_justification_2__c = 'sample';
            controller.amRejected();
            test.stopTest();
        }
    }catch (Exception e) {
         Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.CUSR_Approval_Error) ? true : false;
        System.AssertEquals(expectedExceptionThrown, true);
       
    }
    }

}