objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_2__c</fullName>
        <label>Address Line 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_3__c</fullName>
        <label>Address Line 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_4__c</fullName>
        <label>Address Line 4</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bill_To_Postal_Zip_Code__c</fullName>
        <label>Bill To Postal/Zip Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Bill_To_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Alternative_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternative Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA (Alternative Customer)</relationshipLabel>
        <relationshipName>RMA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.Stage__c</field>
                <operation>equals</operation>
                <value>Qualified, Authorized, Unqualified</value>
            </filterItems>
            <filterItems>
                <field>Account.Customer_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Account.SAP_Account_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA</relationshipLabel>
        <relationshipName>RMA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Device_Requires_Scrap_Certificate__c</fullName>
        <label>Lot/Device (Requires Scrap Certificate)</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lot_Device_To_Return__c</fullName>
        <label>Lot/Device (To Return)</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReasonCode__c</fullName>
        <label>Return Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RMA_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>R10</fullName>
                </value>
                <value>
                    <fullName>R20</fullName>
                </value>
                <value>
                    <fullName>R25</fullName>
                </value>
                <value>
                    <fullName>R30</fullName>
                </value>
                <value>
                    <fullName>R35</fullName>
                </value>
                <value>
                    <fullName>R50</fullName>
                </value>
                <value>
                    <fullName>R55</fullName>
                </value>
                <value>
                    <fullName>R80</fullName>
                </value>
                <value>
                    <fullName>R81</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Receiver_Address__c</fullName>
        <label>Receiver Address</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <label>RMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RMA_Certificate_Extension.cls
public without sharing class RMA_Certificate_Extension {

    public RMA__c RMARecord = new RMA__c();
    public List<String> lstAddress{get;set;}
    public String productNo{get;set;}
    public List<String> lstReturnAddress{get;set;}
    public List<RMA_Utility.LineItemWrapper> lstInvoicesReturnWrapper{get;set;}
    public List<RMA_Utility.LineItemWrapper> lstInvoicesScrapWrapper{get;set;}
    public decimal amountReturnInvoices{get;set;}
    public decimal amountScrapInvoices{get;set;}
    
    public RMA_Certificate_Extension(ApexPages.StandardController con){
        RMARecord = (RMA__c)con.getRecord();
        
        if(ApexPages.CurrentPage().getParameters().get('type') == 'scrap'){
            Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=ScrapCertificate_'+RMArecord.Name+'.pdf');
        }else if(ApexPages.CurrentPage().getParameters().get('type') == 'proforma'){
            Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=CustomerProforma_'+RMArecord.Name+'.pdf');
        }
        lstAddress = new List<String>();
        productNo = '';
        
        lstReturnAddress = new List<String>();
        if(RMARecord.Receiver_Address__c != NULL && RMARecord.Receiver_Address__c != ''){
            for(String addr: RMARecord.Receiver_Address__c.split('\n')){
                lstReturnAddress.add(addr);
            }
        }
        
        List<Account> lstAccount = new List<Account>();
        String accId = ''; 
        if(RMARecord.ReasonCode__c == 'R81'){
            accId = RMARecord.Alternative_Customer__c;
        }
        else{
            accId = RMARecord.Customer__c;
        } 
        
        lstAccount = [select Name,Bill_To_Address_1__c,Bill_To_Address_2__c,Bill_To_Address_3__c,Bill_To_Address_4__c,Bill_To_City__c,Bill_To_Country__c,
                        Bill_To_Postal_Zip_Code__c,Bill_To_State__c from Account where Id =: accId limit 1];
                        
        if(!lstAccount.isEmpty()){
            for(Account acc : lstAccount){
                for(Schema.FieldSetMember member : SObjectType.Account.FieldSets.BillToAddress.getFields()){
                    if(acc.get(member.getFieldPath()) != NULL){
                        lstAddress.add((String)acc.get(member.getFieldPath()));
                    }
                }   
            }
        }   
        
        //For separating lots belonging to Scrap and Return disposition respectively
        lstInvoicesReturnWrapper = new List<RMA_Utility.LineItemWrapper>();        
        lstInvoicesScrapWrapper  = new List<RMA_Utility.LineItemWrapper>();
        Set<String> setPartNumber = new Set<String>();
        amountReturnInvoices = 0;
        amountScrapInvoices = 0;
        
        List<RMA_Utility.LineItemWrapper> lstLineItemWrapper = new List<RMA_Utility.LineItemWrapper>();
        lstLineItemWrapper = RMA_Utility.prepareLineItemWrapper(RMARecord.Id);
        
        if(!lstLineItemWrapper.isEmpty()){
            for(RMA_Utility.LineItemWrapper invoiceWrap: lstLineItemWrapper){
                setPartNumber.add(invoiceWrap.invoice.Device__c);
                
                string lotInvoice = invoiceWrap.invoice.Lot_Number__c + '-' + invoiceWrap.invoice.Invoice_Number__c;
                if(invoiceWrap.invoice.RMA__r.Lot_Device_To_Return__c != NULL && 
                   invoiceWrap.invoice.RMA__r.Lot_Device_To_Return__c.contains(lotinvoice)){
                    lstInvoicesReturnWrapper.add(invoiceWrap);
                    amountReturnInvoices += invoiceWrap.ItemValue;
                }else if(invoiceWrap.invoice.RMA__r.Lot_Device_Requires_Scrap_Certificate__c != NULL && 
                         invoiceWrap.invoice.RMA__r.Lot_Device_Requires_Scrap_Certificate__c.contains(lotinvoice)){
                    lstInvoicesScrapWrapper.add(invoiceWrap);
                    amountScrapInvoices += invoiceWrap.ItemValue;
                }
            }
        }
        
        if(!setPartNumber.isEmpty()){
            for(String prt : setPartNumber){
                productNo += prt+',';   
            }
        }
        
        if(productNo != ''){
            productNo = productNo.removeEnd(',');
        }
        
    }

}