objects/Account.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lot_Instruction__c.object
<CustomObject>
    <description>Junction Object to relate the Lot Request Object to the Manufacturing Lot. Prrovides instructions for the lot.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Lot_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_CSD_ML_at_time_of_Submission__c</fullName>
        <label>Current CSD(ML) at CSR Submission</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lot_Request__c</fullName>
        <label>Lot Request</label>
        <referenceTo>Lot_Request__c</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Request_to_Lot_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Lot__c</fullName>
        <inlineHelpText>Manufacturing Lot Tagged for Request</inlineHelpText>
        <label>Lot ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. Please refine your search.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Manufacturing_Lot__c.Account_Name__c</valueField>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Last_Ship_Date__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Active_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Lot Ids are filtered based on the Account selection at Lot Instruction level and which are not yet shipped.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Manufacturing_Lot__c</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Request_to_Lot_Tags</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Customer_Requested_Date_CRD_CSR__c</fullName>
        <formula>Lot_Request__r.New_Customer_Requested_Date_CRD_CSR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New CRD (CSR)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Lot_Request__r.Stage__c)</formula>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <label>Lot Instruction</label>
    <nameField>
        <displayFormat>LotInstr-{000000}</displayFormat>
        <label>Lot Instructions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lot_Request__c.object
<CustomObject>
    <description>This Object is used to manage lot requests to include expedite, but eventually other instructions as well.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lot_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Backup_CSR_CSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Backup CSR (CSR)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lot_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_CSR_CSR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>CSR identifies the primary CSR working on this Lot Request. Email Notifications will be sent to the CSR. It may be reassigned as necessary.</inlineHelpText>
        <label>Assigned Primary CSR (CSR)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lot_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSR_Comments__c</fullName>
        <label>CSR Comments</label>
        <length>10000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Customer_Instructions__c</fullName>
        <description>Provide Description of Customer&apos;s Request</description>
        <inlineHelpText>Provide Description of Customer&apos;s Request</inlineHelpText>
        <label>Customer&apos;s Instructions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Requested_Lot_Qty__c</fullName>
        <label>Customer Requested Lot Quantity</label>
        <summaryForeignKey>Lot_Instruction__c.Lot_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer_Requested_Wafer_Qty__c</fullName>
        <label>Customer Requested Wafer Quantity</label>
        <summarizedField>Lot_Instruction__c.Current_Wafer_Quantity_in_the_Lot_ML__c</summarizedField>
        <summaryForeignKey>Lot_Instruction__c.Lot_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Does_Customer_Accept_Standard_Pricing__c</fullName>
        <label>Does Customer Accept Standard Pricing ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lot_Request_Type__c</fullName>
        <inlineHelpText>The type of action that is being requested for the lot.</inlineHelpText>
        <label>Lot Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Expedite</fullName>
                </value>
                <value>
                    <fullName>Fast Track - Lot CSD Pull In</fullName>
                </value>
                <value>
                    <fullName>Fast Track - Account Preapproved for Expedite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Customer_Requested_Date_CRD_CSR__c</fullName>
        <inlineHelpText>New Customer Request Date (CRD) based upon the customer&apos;s expedite request.</inlineHelpText>
        <label>New CRD (CSR)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                    <default>true</default>
                    <label>New Request</label>
                </value>
                <value>
                    <fullName>Acknowledged by CSR</fullName>
                </value>
                <value>
                    <fullName>Submitted by CSR</fullName>
                </value>
                <value>
                    <fullName>Submitted for Review by Expedite Manager</fullName>
                </value>
                <value>
                    <fullName>Resubmitted by CSR</fullName>
                </value>
                <value>
                    <fullName>Resubmitted by Expedite Manager</fullName>
                </value>
                <value>
                    <fullName>Fully Approved</fullName>
                </value>
                <value>
                    <fullName>Under Execution</fullName>
                </value>
                <value>
                    <fullName>Closed - Fully Executed</fullName>
                </value>
                <value>
                    <fullName>Closed - Partially Executed</fullName>
                </value>
                <value>
                    <fullName>Closed - Failed to Execute</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled by Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled Internally</fullName>
                </value>
                <value>
                    <fullName>Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Void (Mistaken Entry)</fullName>
                </value>
                <value>
                    <fullName>Pending Planner Response</fullName>
                </value>
                <value>
                    <fullName>Closed-Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lot Service Request</label>
    <nameField>
        <displayFormat>LReq-{0000000}</displayFormat>
        <label>Lot Service Request Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will have the Customer Information of a Lot</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturing Lot</relationshipLabel>
        <relationshipName>Manufacturing_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ACTIVE_FLAG</description>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Scheduled_Date_CSD__c</fullName>
        <description>Mapped to (CSD)</description>
        <label>Current Scheduled Date(CSD)</label>
        <type>Date</type>
    </fields>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LotApprovalProcessUtil.cls
/**
* Author        :   Ravikiran Nadella
* Description   :  this class has Logic to exceute from Void button and also Submit for Approaval button
                   related to Lot Service request object .
* History       :
        Initials        Date                Description
-----------------------------------------------------------------------------------------
             
        RNadella        31/08/2015          Created the class     
        Rnadella        30/05/2016          Added CSD at submission  		
**/

global class LotApprovalProcessUtil {
   
    
    /* This method has a logic to show a message  
      when lot instructions are assocaited to inActive ML 
       */
    webService static String activeMLonLotinstr(Id lsrId) { 
        string message='';
        string rMessage='';
        List<Lot_Instruction__c>ltList = new List<Lot_Instruction__c>();
        for(Lot_Request__c lsrList  :[select Id,(select id,name, Manufacturing_Lot__r.Active_Flag__c,Manufacturing_Lot__r.name,Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c from Request_to_Lot_Tags__r) from Lot_Request__c 
                                      WHERE id =: lsrId]){
                                          if(!lsrList.Request_to_Lot_Tags__r.isEmpty()){
                                              for(Lot_Instruction__c ltinst : lsrList.Request_to_Lot_Tags__r ){
                                                  ltinst.Current_CSD_ML_at_time_of_Submission__c=ltinst.Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c;
                                                  ltList.add(ltinst);
                                                  if(ltinst.Manufacturing_Lot__r.Active_Flag__c!=true){
                                                      message +=ltinst.name + '-->'+ ltinst.Manufacturing_Lot__r.name +'\r\n';
                                                      
                                                  }
                                              }
                                          }  
                                      }
        update ltList;
        if(message.contains('Lot')){
            rMessage=system.label.LotActiveML +'\r\n'+ message;
            
        }
        
        return rMessage;
    }
    
       /* This method has a logic to send an Emails to the   
        approvers upon recall or closed void.
       */
    Public Static Void sendEmailtoApprovers(list<Lot_Request__c >lrrList){
        set<string> actorIdSet = new set<string>();
        set<id>userIdSet = new set<id>();
        set<id>nonUserIdSet = new set<id>();
        set<id>nonUserIdSet1 = new set<id>();
        set<id>lrSet= (new Map<Id,SObject>(lrrList)).keySet();
        list<Lot_Request__c>lrList =[Select id,Account__r.name,name,Fab__c,Lot_Request_Type__c,New_Customer_Requested_Date_CRD_CSR__c,Assigned_Backup_CSR_CSR__c,Assigned_CSR_CSR__c,
                                      Customer_Requested_Lot_Qty__c,Customer_Requested_Wafer_Qty__c,Customer_Instructions__c,Does_Customer_Accept_Standard_Pricing__c,CSR_Comments__c,
                                      Stage__c,lastModifiedBy.name from Lot_Request__c where id in :lrSet];
      
      for(ProcessInstance pins :[Select Id,(Select originalactorid,actorid,StepStatus  from StepsAndWorkitems) 
                                   from ProcessInstance where targetobjectid in :lrSet]){
                                       //system.debug('ProcessInstance'+pins.StepsAndWorkitems);
                                       if(!pins.StepsAndWorkitems.isEmpty()){
                                           for(ProcessInstanceHistory stwi : pins.StepsAndWorkitems){
                                               actorIdSet.add(stwi.originalactorid);                                               
                                           }                                           
                                       }                                       
                                   }

        
        if(!actorIdSet.isEmpty()){
            for(string userId :actorIdSet){
              
                if(userId.startsWith('005')){
                   
                    userIdSet.add(userId);                    
                }else{
                    nonUserIdSet.add(userId);                  
                }
            } 
          
        }else {
            for(Lot_Request__c lrst : lrList){
                
                userIdSet.add(lrst.Assigned_Backup_CSR_CSR__c);
                userIdSet.add(lrst.Assigned_CSR_CSR__c);
                
            }
            
        }
        
     
        if(!nonUserIdSet.isEmpty()){
            for(GroupMember gm:[select UserOrGroupId From GroupMember where groupId in:nonUserIdSet]){
                string str = string.valueof(gm.UserOrGroupId);
                if(str.startsWith('005')){
                    userIdSet.add(gm.UserOrGroupId);                    
                }else{
                    nonUserIdSet1.add(gm.UserOrGroupId);                    
                }
            }
        }
        

      if(!nonUserIdSet1.isEmpty()){
                  for(GroupMember gm:[select UserOrGroupId From GroupMember where groupId in:nonUserIdSet1]){
                string str = string.valueof(gm.UserOrGroupId);
                if(str.startsWith('005')){
                    userIdSet.add(gm.UserOrGroupId);                    
                }                
            }
        }
     
         list<string> sendTo = new list<string>();
         for(user usr:[select email from user where id in :userIdSet]){
          sendTo.add(usr.email);
         }
         
         String body = 'Dear Lot Request Team'+ ',' + '\r\n'+ '\r\n';
      body += 'This is to inform you that a new Lot Request submission has been recalled. Please do not proceed with the Lot Request.'+ '\r\n'+ '\r\n';
      body += 'Lot Request Number :'+ lrList[0].Name + '\r\n'+ '\r\n';
      body += 'Account : ' + lrList[0].Account__r.name+ '\r\n'+ '\r\n'; 
      body += 'Fab :' +lrList[0].Fab__c + '\r\n'+ '\r\n';
      body += 'Lot Request Type :' + lrList[0].Lot_Request_Type__c+ '\r\n'+ '\r\n'; 
      body += 'Record Last Modified by :' +lrList[0].LastModifiedBy.name + '\r\n'+ '\r\n';
      body += 'Customer Requested Ship Date: ' +lrList[0].New_Customer_Requested_Date_CRD_CSR__c + '\r\n' + '\r\n';
      body += 'Customer Requested Lots :'+ lrList[0].Customer_Requested_Lot_Qty__c+ '\r\n' + '\r\n';
      body += 'Customer Requested Wafers :' + lrList[0].Customer_Requested_Wafer_Qty__c + '\r\n' + '\r\n';
      body += 'Customer Instructions :' + lrList[0].Customer_Instructions__c+ '\r\n'+ '\r\n'; 
      body += 'Customer Accepts Standard Pricing:' +lrList[0].Does_Customer_Accept_Standard_Pricing__c + '\r\n'+ '\r\n';
      body += 'Lot Request Type :' + lrList[0].Lot_Request_Type__c + '\r\n'+ '\r\n';
      body += 'CSR Comments :' +lrList[0].CSR_Comments__c+ '\r\n'+ '\r\n'; 
      body += 'Lot Request Stage :' +lrList[0].Stage__c  + '\r\n'+ '\r\n';
      body +='To access the Lot Request, click the following url below: ' + '\r\n'+ '\r\n';
      body +=URL.getSalesforceBaseUrl().toExternalForm() + '/' + lrList[0].Id+ '\r\n'+ '\r\n';
      body +='Thank You'+ ','+ '\r\n';
      body +='System Admin'+ '\r\n';
        
         if(!userIdSet.isEmpty() && null<>userIdSet ){
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
         mail.setToAddresses(sendTo);
         mail.setSubject('Lot Request Recalled:'+lrList[0].Account__r.name+' ' +'for' +' '+lrList[0].Fab__c);
         mail.setPlainTextBody(body);
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        
         }
    }
    
    public Static string recallCheck(){
      string rMessage='';
    rMessage='Recalled Sucessfully';
     return rMessage;
    
    }

}