objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <description>FV2: Used for storing the Department values of Contact</description>
        <inlineHelpText>This field is optional; when filled in it provides default access to GFV applications for one or more predefined roles (Design, Engineering, Quality, Procurement, Supply Chain, Legal).</inlineHelpText>
        <label>Department (GFV Access)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supplier Services</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GF_Meeting_Occurrence__c.object
<CustomObject>
    <description>Fv2:It will be child object for team room Meeting. The multiple occurrences of a team room meeting will be managed via this custom object.</description>
    <fields>
        <fullName>Team_Room_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FV2 : It looks up to the Team Room Meeting record.</description>
        <label>Team Room Meeting</label>
        <referenceTo>Team_Room_Meeting__c</referenceTo>
        <relationshipLabel>GF Meeting Occurrence</relationshipLabel>
        <relationshipName>GF_Meeting_Occurrence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GF Meeting Occurrence</label>
    <nameField>
        <displayFormat>TMO-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GF Meeting Occurrence</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/GF_Task__c.object
<CustomObject>
    <description>FV2 : This object is used for GF Tasks.</description>
    <fields>
        <fullName>Team_Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FV2:Look up to Team Room object</description>
        <label>Team Room</label>
        <referenceTo>Team_Room__c</referenceTo>
        <relationshipLabel>GF Tasks</relationshipLabel>
        <relationshipName>GF_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GF Task</label>
    <nameField>
        <label>GF Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GF Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Room_Meeting__c.object
<CustomObject>
    <description>FV2 : This is used to create the Team Room Meeting Event record.</description>
    <fields>
        <fullName>Team_Room__c</fullName>
        <description>FV2 : It looks up to the Team Room record.</description>
        <label>Team Room</label>
        <referenceTo>Team_Room__c</referenceTo>
        <relationshipLabel>Team Room Meetings</relationshipLabel>
        <relationshipName>Team_Room_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Team Room Meeting</label>
    <nameField>
        <displayFormat>TRM-{YYYY}-{MM}-{DD}-{000}</displayFormat>
        <label>Team Room Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Room Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Room_Member__c.object
<CustomObject>
    <fields>
        <fullName>Team_Room__c</fullName>
        <description>Parent Team Room to which member belongs</description>
        <inlineHelpText>Team Room</inlineHelpText>
        <label>Team Room</label>
        <referenceTo>Team_Room__c</referenceTo>
        <relationshipLabel>Team Room Members</relationshipLabel>
        <relationshipName>Team_Room_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Team Room Member</label>
    <nameField>
        <displayFormat>TRM-{0000000000}</displayFormat>
        <label>Team Room Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Room Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clsActivityHistoryGFCalProviderTest.cls
/*
 Type Name: clsActivityHistoryGFCalProviderTest 
 Author: Cognizant Technology Solutions
 Created Date: 11-July-2013
 Reason: This is the test class for 'clsActivityHistoryGFCalActivityProvider' class.
 Change History:
 Author: 
 Modified Date: 
 Reason: 
 …….. 
 ……..
    Nbustillos  10122013    - Added call to loadEnvironmentVariables() method.
    Ashwini     05132015    - Updated code for refactoring of test class.
*/

@isTest
private class clsActivityHistoryGFCalProviderTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    static testMethod void testclsActivityHistoryGFCalProvider() {
        
        // Load Environment Variables   
        //DataUtilTest.loadEnvironmentVariables();
        
            Profile profileObj = [Select Name,Id from Profile where Name = 'System Administrator'];
            User userObj = new User();
            Account acctObj = new Account();
            Contact conobj=new Contact();
            Team_Room__c teamRoomObj = new Team_Room__c();
            
            Team_Room_Meeting__c teamRoomMeetingObj = new Team_Room_Meeting__c();
            
            GF_Meeting_Occurrence__c gfMeetingOccrOpenObj = new GF_Meeting_Occurrence__c();
            GF_Meeting_Occurrence__c gfMeetingOccrCloseObj = new GF_Meeting_Occurrence__c();
            Team_Room_Member__c teamRoomMemberObj = new Team_Room_Member__c();
            GF_Task__c  gfTaskOpenObj = new GF_Task__c ();
            GF_Task__c  gfTaskClosedObj = new GF_Task__c ();
            
            acctObj.Name='TestAccount';
            acctObj.Site_Department__c = 'Site1';
            acctObj.Sub_Type__c = 'Direct';
            acctObj.Transaction_Type__c = 'Transactional';
            acctObj.Region__c = 'APJ';
            acctObj.Bill_To_Address_1__c='KOL';
            acctObj.Bill_To_City__c = 'KOL';
            acctObj.Bill_To_Country__c = 'INDIA';
            acctObj.Corporate_Address_1__c = 'Street';
            acctObj.Corporate_City__c = 'KOL';
            acctObj.Corporate_Country__c = 'INDIA';
            
            insert acctObj;
            
            
            conobj.FirstName='Mr';
            conobj.LastName='Testcon1';
            conobj.AccountId=acctObj.Id;
            conobj.Email='con1@gf.com';
            conobj.Department__c='Design';
                                      
            insert conobj;
            
            
            userObj.Alias = 'Jimmy2';
            userObj.Email='Jimmy2058@test.com'; 
            userObj.EmailEncodingKey='UTF-8'; 
            userObj.LastName='Gadha';
            userObj.LanguageLocaleKey='en_US'; 
            userObj.LocaleSidKey='en_US';
            userObj.ProfileId = profileObj.Id;
            userObj.TimeZoneSidKey='America/Los_Angeles'; 
            userObj.UserName='Jimmy2058@test.com';
            //userObj.Portal_Login__c = 'xyz1';
            //userObj.contactId = conobj.Id;
            userObj.IsActive = true;
                        
            insert userObj;
            
            teamRoomObj.Team_Room_Administrator__c = userObj.Id;
            teamRoomObj.Name ='Team Room 1';
            teamRoomObj.Team_Room_Description__c = 'Team Room Description';
            teamRoomObj.Primary_Account__c= acctObj.id;
            teamRoomObj.Terms_n_Conditions_Accepted__c = true;
            
            insert teamRoomObj;
            
            teamRoomMemberObj.Team_Room__c = teamRoomObj.id;
            teamRoomMemberObj.User__c = userObj.id;
            
            insert teamRoomMemberObj;
            
            teamRoomMeetingObj.Team_Room__c = teamRoomObj.id;
            teamRoomMeetingObj.Status__c='Open';
            teamRoomMeetingObj.Description__c='Test Team Room';
            teamRoomMeetingObj.Start_DateTime__c = System.today();
            
            insert teamRoomMeetingObj;
            
            
            gfTaskClosedObj.Name='Closed Task';
            gfTaskClosedObj.Team_Room__c=teamRoomObj.id;
            gfTaskClosedObj.subject__c='GF task Meeting';
            gfTaskClosedObj.Due_Date__c = System.today();
            gfTaskClosedObj.assignTo__c = userObj.id;
            gfTaskClosedObj.Status__c ='Completed';
            
            insert gfTaskClosedObj;

            gfTaskOpenObj.Name='Open Task';
            gfTaskOpenObj.Team_Room__c=teamRoomObj.id;
            gfTaskOpenObj.subject__c='GF task Meeting';
            gfTaskOpenObj.Due_Date__c = System.today().addDays(+1);
            gfTaskOpenObj.assignTo__c = userObj.id;
            gfTaskOpenObj.Status__c ='In Progress';
            
            insert gfTaskOpenObj;
            
            
            gfMeetingOccrOpenObj.Start_Time__c=System.today().addDays(+1);
            gfMeetingOccrOpenObj.Status__c='Open';
            gfMeetingOccrOpenObj.End_Time__c=System.today().addDays(+2);
            gfMeetingOccrOpenObj.Team_Room_Meeting__c=teamRoomMeetingObj.id;
            
            insert gfMeetingOccrOpenObj;

            gfMeetingOccrCloseObj.Start_Time__c=System.today().addDays(+1);
            gfMeetingOccrCloseObj.Status__c='Closed';
            gfMeetingOccrCloseObj.End_Time__c=System.today();
            gfMeetingOccrCloseObj.Team_Room_Meeting__c=teamRoomMeetingObj.id;
            
            insert gfMeetingOccrCloseObj;
            
            System.runAs(userObj)
            {
            
                Test.startTest();
                
                clsActivityHistoryGFCalActivityProvider clsActivityHistoryGFCalActivityProviderObj = new clsActivityHistoryGFCalActivityProvider();
                clsActivityHistoryGFCalActivityProviderObj.findActivities(userObj.id);
                clsActivityHistoryGFCalActivityProviderObj.getActivityTypes();
                Test.stopTest();    
            
            }        
        
    }
}