objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRMDID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Auto generated by the system using the following format: CDIDAAAAAAA.NN

Where:
- CDID is a prefix (from the generated CDID field)
- AAAAAA is 7 numeric characters. Generation will be sequential starting from the last number from Siebel. (from the generated CDID field)
- NN is version number. Generation will be sequential starting from ‘00’</description>
        <externalId>true</externalId>
        <inlineHelpText>CRM assign Device ID , use as unique ID reference by all systems.
Auto populated by system.</inlineHelpText>
        <label>CRMDID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Current_Forecast_Tapeout_Date__c</fullName>
        <description>This field is auto populated with the Original Forecasted Tapeout Date if its not entered during creation.</description>
        <inlineHelpText>Revised forecast tapeout date. Entered by FAE/FTS, reference by forecast lot start date</inlineHelpText>
        <label>Current Forecast Tapeout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device_Mask_Set_Title__c</fullName>
        <description>MaskSetTitle populated from PTRF</description>
        <inlineHelpText>Mask Set Title has different validation rules for different tapeout type.For GlobalShuttle &amp; CustomizedShuttle MPW, Device Mask Set Title must be same as MPW Train Number.</inlineHelpText>
        <label>Device Mask Set Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>Indicate Fab where this device produce</description>
        <inlineHelpText>Indicate Fab where this device produce</inlineHelpText>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geometry_NM__c</fullName>
        <formula>TEXT(VALUE(LEFT(Geometry__c,FIND(&quot;UM&quot;,Geometry__c)-1))*1000) &amp; &quot;NM&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geometry (NM)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <description>Geometry in Device inherited from Opportunity.Geometry</description>
        <formula>IF(ISBLANK(Opportunity2__c), Text(Internal_Device_Geometry__c), Text(Opportunity2__r.Process_Geometry__c))</formula>
        <inlineHelpText>Geometry in Device inherited from Opportunity.Geometry</inlineHelpText>
        <label>Geometry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <inlineHelpText>Identify Tapeout type. Do not pick Retrofit.</inlineHelpText>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>Full Layer Retrofit</fullName>
                </value>
                <value>
                    <fullName>TD Test Chip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <recordTypes>
        <fullName>Tapeout</fullName>
        <active>false</active>
        <label>Tapeout</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account of the Opportunity this device is tied up. This is automatically populated during the Opportunity Program generation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Programs</relationshipLabel>
        <relationshipName>Opportunity_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program_Team_Member__c.object
<CustomObject>
    <description>The individual team members for Opportunity Program and Device records.</description>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <description>The parent Opportunity Program for the team member.</description>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Opportunity Program Team Members</relationshipLabel>
        <relationshipName>Opportunity_Program_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Program Team Member</label>
    <nameField>
        <displayFormat>OPTM-{000000000}</displayFormat>
        <label>OPTM Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Program Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PTRF__c.object
<CustomObject>
    <fields>
        <fullName>CRMDID__c</fullName>
        <formula>Device__r.CRMDID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CRMDID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account associated</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PTRF</relationshipLabel>
        <relationshipName>PTRF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Device associated</description>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>PTRF</relationshipLabel>
        <relationshipName>PTRF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fab1</fullName>
                </value>
                <value>
                    <fullName>Fab8</fullName>
                </value>
                <value>
                    <fullName>Fab7</fullName>
                </value>
                <value>
                    <fullName>Fab6</fullName>
                </value>
                <value>
                    <fullName>Fab5</fullName>
                </value>
                <value>
                    <fullName>Fab3E</fullName>
                </value>
                <value>
                    <fullName>Fab3</fullName>
                </value>
                <value>
                    <fullName>Fab2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FoundryFEName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FoundryFEName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTRF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frame_Tapeout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Frame Tapeout</description>
        <label>Frame Tapeout</label>
        <type>Checkbox</type>
    </fields>
    <label>PTRF</label>
    <nameField>
        <label>PTRF Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PTRF</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DevicePTRFReminderBatch.cls
/*
    Author: Zymark Ambat
    Description: This batch class is created for sending email reminders for Devices without PTRF Frame Tapeout.
    History: 
        ZAmbat      04082014    - Code creation.
        ZAmbat      05152014    - Added condition: Status = 'Active'.
        Gopi Koka   06042016    - Added condition: Stage  = 'Design In';
		Yash        03052017    - Added new condition for Fab FAB 9, FAB 10 line no 30
*/

global class DevicePTRFReminderBatch implements Database.Batchable<sObject> {
    string oneWeek = DateTime.newInstance(date.today().addDays(7).year(), date.today().addDays(7).month(), date.today().addDays(7).day()).format('yyyy-MM-dd'); 
    string twoWeeks = DateTime.newInstance(date.today().addDays(14).year(), date.today().addDays(14).month(), date.today().addDays(14).day()).format('yyyy-MM-dd');
    global final string query = 'SELECT     Id ' +
                                '           , Name ' +
                                '           , Geometry_NM__c ' +
                                '           , Opportunity_Program__c ' +
                                '           , Current_Forecast_Tapeout_Date__c ' + 
                                '           , Account__c ' +
                                '           , CRMDID__c ' +
                                '           , Tapeout_Type__c ' +
                                '           , Fab__c ' +
                                '           , Geometry__c ' +
                                '           , Device_Mask_Set_Title__c ' +
                                '           , (SELECT Id FROM PTRF__r WHERE Frame_Tapeout__c = true AND Status__c = \'Active\') ' +
                                'FROM       Device__c ' +
                                'WHERE      Tapeout_Type__c NOT IN (\'GlobalShuttle MPW\', \'Retrofit\') ' +
                                '           AND Stage__c IN (\'Design In\') ' + 
                                '           AND (Current_Forecast_Tapeout_Date__c = ' + oneWeek  + ' ' +
                                '                OR Current_Forecast_Tapeout_Date__c = ' + twoWeeks + ') ' + 
								'           AND Fab__c not IN ( \'FAB 9\',\'FAB 10\') ' +
                                '           AND Status__c = \'Active\'';

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext ctx, List<Sobject> scope) {
        Set<Id> opptyProgramIds = new Set<Id>(); 
        Set<Id> deviceIds = new Set<Id>(); 
        List<Device__c> listDevice = new List<Device__c>(); 
        for (Device__c d : (List<Device__c>)scope) {
            deviceIds.add(d.Id);
            opptyProgramIds.add(d.Opportunity_Program__c);
            listDevice.add(d);
        }
        
        if (listDevice.size() > 0) {
            // Get Email template
            EmailTemplate et = [
                SELECT      Id
                FROM        EmailTemplate
                WHERE       Name = :Environment_Variable__c.getInstance('DEVICE_PTRF_MAIL_TEMPLATE').Value__c
                LIMIT 1
            ];
            
            // Create Map of FAE per Opportunity Program
            Map<Id, List<string>> mapFAE = new Map<Id, List<string>>();
            integer recipientSize = 0;
            for (Opportunity_Program_Team_Member__c optm : [SELECT      User_Email__c
                                                                        , Opportunity_Program__c
                                                            FROM        Opportunity_Program_Team_Member__c
                                                            WHERE       Opportunity_Program__c IN :opptyProgramIds
                                                                        AND (Team_Role__c IN ('Field Application Engineer',
                                                                                             'Primary Field Application Engineer', 
                                                                                             'Primary Field Technical Support', 
                                                                                             'Field Technical Support')
                                                                             OR ( Team_Role__c = 'Account Manager' AND Is_FAE__c = TRUE)
                                                                             OR ( Team_Role__c = 'Primary Account Manager' AND Is_FAE__c = TRUE) )
                                                                        AND User_Email__c != null
                                                                        AND User__r.IsActive = true]) { 
                List<string> tempList = new List<string>();
                if (mapFAE.containsKey(optm.Opportunity_Program__c)) {  
                    tempList = mapFAE.get(optm.Opportunity_Program__c);
                    tempList.add(optm.User_Email__c);
                    mapFAE.put(optm.Opportunity_Program__c, tempList);
                } else {
                    tempList.add(optm.User_Email__c);
                    mapFAE.put(optm.Opportunity_Program__c, tempList);
                }
                recipientSize++;
            }
            
            try {
                Messaging.reserveSingleEmailCapacity(recipientSize + listDevice.size());
                // Retrieve dummy recipient
                Contact c = [
                    SELECT      Id
                                , Email
                    FROM        Contact
                    WHERE       Email != null
                    LIMIT 1
                ];
                
                List<Messaging.SingleEmailMessage> listMail = new List<Messaging.SingleEmailMessage>();
                for (Device__c d : listDevice) {
                    // Create dummy email
                    List<Messaging.SingleEmailMessage> tempList = new List<Messaging.SingleEmailMessage>();
                    Messaging.SingleEmailMessage tempEmail = new Messaging.SingleEmailMessage();
                    tempEmail.TemplateId = et.Id;
                    tempEmail.setTargetObjectId(c.id);
                    tempEmail.setWhatId(d.Id);
                    tempEmail.setSaveAsActivity(false);
                    tempList.add(tempEmail);
                    
                    // Rollback to get the email template data
                    Savepoint sp = Database.setSavepoint();      
                    if (!test.isRunningTest()) {
                        Messaging.sendEmail(tempList);        
                    }
                    Database.rollback(sp);
                    
                    // Create the actual email
                    List<string> toAddresses = new List<string>();
                    integer geometryNM = integer.valueOf(d.Geometry_NM__c.replace('NM', ''));
                    if (mapFAE.containsKey(d.Opportunity_Program__c)
                        && (geometryNM >= 55
                            || (geometryNM >= 28 && geometryNM <= 40)
                            || (geometryNM >= 14 && geometryNM <= 20))) { 
                            toAddresses.addAll(mapFAE.get(d.Opportunity_Program__c));
                    }
                    
                    if (geometryNM >= 28 && geometryNM <= 40) {
                        toAddresses.addAll(Environment_Variable__c.getInstance('DEVICE_TDTI').Value__c.split(';'));
                        toAddresses.add(Environment_Variable__c.getInstance('DEVICE_TA').Value__c);
                    } else if (geometryNM >= 14 && geometryNM <= 20) {
                        toAddresses.addAll(Environment_Variable__c.getInstance('DEVICE_TDTI').Value__c.split(';'));
                    }
                    
                    if (toAddresses.size() > 0) {
                        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                        email.setSubject(tempList[0].Subject);
                        email.setHtmlBody(tempList[0].HtmlBody);
                        email.setPlainTextBody(tempList[0].PlainTextBody);
                        email.setToAddresses(toAddresses);
                        listMail.add(email);
                    }
                }
                
                if (listMail.size() > 0) {
                    if (!test.isRunningTest()) {
                        Messaging.sendEmail(listMail);
                    }   
                }
            } catch (Exception e) {
                system.debug('Error ==========================> ' + e.getMessage());
            }   
        }   
    }
    global void finish(Database.BatchableContext BC){}
}