objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PWCA_Attachments__c.object
<CustomObject>
    <fields>
        <fullName>PWCA_Publication__c</fullName>
        <label>PWCA Publication</label>
        <referenceTo>PWCA_publication__c</referenceTo>
        <relationshipLabel>PWCA Attachments</relationshipLabel>
        <relationshipName>PWCA_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PWCA Attachments</label>
    <nameField>
        <displayFormat>PWCA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PWCA Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PWCA_publication__c.object
<CustomObject>
    <description>PWCA (product wafer compliance analysis) report Publication to Foundryview</description>
    <fields>
        <fullName>PWCA_Publication__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PWCA Publication</label>
        <type>Text</type>
    </fields>
    <label>PWCA Publication</label>
    <nameField>
        <displayFormat>PWCA-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>PWCA Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PWCA Publication</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/PWCAAssociated_Customers__c.object
<CustomObject>
    <fields>
        <fullName>PWCA_Publication__c</fullName>
        <label>PWCA Publication</label>
        <referenceTo>PWCA_publication__c</referenceTo>
        <relationshipLabel>Associated Customers</relationshipLabel>
        <relationshipName>Associated_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Customers</label>
    <nameField>
        <displayFormat>PWCA-AL-{00000}</displayFormat>
        <label>Associated Customers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QS_PWCAPublicationTriggerHandlerTest.cls
@isTest
private class QS_PWCAPublicationTriggerHandlerTest{
    
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    static Account account;
    static Contact contact;
    static User portalUser;
    static PWCA_publication__c pwcaPublication;
    static PWCAAssociated_Customers__c pwcaAssodcatedCustomer;
    static PWCA_Attachments__c pwcaAttachment;
    
    static void setupData(){
        //DataUtilTest.loadEnvironmentVariables();
        /*Error_Codes__c errorCode = QS_TestUtil.createErrorCode('ACCT_TM_DUP_USER_ROLE_ERROR', 'There are duplicate users or roles in the form. Please review the form and update assignment as necessary.');
        insert errorCode;
        List<Environment_Variable__c> envList = new List<Environment_Variable__c> (); 
        envList.add(QS_TestUtil.createENVariable('ACCT_TM_PRXY_TM_RL_AM','Account Manager'));
        envList.add(QS_TestUtil.createENVariable('ACCT_TM_PRXY_TM_RL_TS','Technical Support'));
        envList.add(QS_TestUtil.createENVariable('ACCT_TM_PRXY_TM_RL_AE','Application Engineer'));
        envList.add(QS_TestUtil.createENVariable('ACCT_TM_PRXY_TM_RL_CSR','Customer Service Rep'));
        insert envList;*/
        Schema.DescribeSObjectResult descSobjResult = Schema.SObjectType.Account; 
        Map<String, Schema.RecordtypeInfo> recordTypeMap = descSobjResult.getRecordTypeInfosByName();// = Schema.SObjectType.Account.getRecordTypeInfosByName();
      
        /*account = QS_TestUtil.createAccount('Test Account', 'Qualified', 'TestAccount', 'Site', 'Direct', 'transactional', 'Fabless - Emerging',
                                             'Mature (> 0.11um)', 'APJ', 'APJ-FE-CHINA', 'APJ-China', 'APJ-China', true, '50 water', 'Bijing', 'China',  '50', 'GF Investment LLC OU', 
                                             100);
        insert account; */
        
        Map<String,Object>  fieldValueMap = new Map<String,Object>();
        fieldValueMap.put('Name', 'TestAccount1');            
        fieldValueMap.put('stage__c', 'Unqualified');        
        fieldValueMap.put('sub_type__c', 'Direct');
        fieldValueMap.put('site_department__c', 'test dept');          
        fieldValueMap.put('transaction_type__c', 'transactional');                          
        fieldValueMap.put('region__c', 'APJ');        
        fieldValueMap.put('Corporate_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Corporate_City__c', 'Test City');                
        fieldValueMap.put('Corporate_Country__c', 'Singapore');
        fieldValueMap.put('Bill_To_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Bill_To_City__c', 'Test City');            
        fieldValueMap.put('Bill_To_Country__c', 'Singapore');        
        fieldValueMap.put('Fab_9_10__c','no');
        fieldValueMap.put('recordtypeid', EnvironmentVariable.get('ACCT_RT_ID_CUSTOMER'));
        AccountDataFactory.createAccount(fieldValueMap);
        Account acc= getAccount('TestAccount1');    
        
        contact = QS_TestUtil.createContact('Test Contact', 'Test Contact', acc.Id, 'test@test.com', 'Customers My Device Admin; Primary Account Admin', 
                                            'Design; Engineering; Quality; Procurement; Supply Chain; Legal', true, true);
        insert contact;
        
        pwcaPublication = QS_TestUtil.createPWCAPublication( '1', System.today() + 5, 'AL','PFOS', '0.20um', 'Al', 'AP', '6', '546', '2',
                                                            'B', 'Preliminary', '4543', acc.Id);
        insert pwcaPublication;
        
        pwcaAssodcatedCustomer = QS_TestUtil.createPWCAAssociatedCustomer(acc.Id, pwcaPublication.Id);
        
        insert pwcaAssodcatedCustomer;
        
        pwcaAttachment = QS_TestUtil.createPWCAAttachment(pwcaPublication.Id, 'Test.Doc');
        insert pwcaAttachment;
        System.debug('pwcaAttachment========='+pwcaAttachment);
        
        
    }
    
    static testMethod void testOnAfterUpdate(){
       setUpdata();
       Profile[] profiles = [Select p.name, p.id From Profile p where p.UserLicense.Name like '%Customer Portal%' LIMIT 1];
        if(profiles != null && !profiles.isEmpty()){
            portalUser =  QS_TestUtil.createPortalUser('test1', 'test1@test1.com', 'test1 Contact', 'Test1 Contact', profiles[0].Id, contact.Id, 'test1@test1.com');
            Profile pp = [Select Id from Profile where Name='System Administrator']; 
            User ur = [Select Id, Name,IsActive from User where IsActive=true AND userRoleId != null and ContactId = null and ProfileID=:pp.Id Limit 1];
            system.runas(ur){
                insert portalUser;
            }
        }
        Test.startTest();
            QS_PWCAPublicationTriggerHandler.isExecuted = false;
            pwcaPublication.Document_Status__c = 'Approved';
            pwcaPublication.Ready_To_Publish__c = true;
            update pwcaPublication;
        Test.stopTest();
        List<PWCA_Attachments__c> pwcaAttachmentList = [SELECT Id, ready_to_Publish__c FROM PWCA_Attachments__c WHERE Id = :pwcaAttachment.Id LIMIT 1];
        System.assertEquals(true, pwcaAttachmentList[0].ready_to_Publish__c);
    }

    private static Account getAccount(string AccountName){
        Account testAcct= [SELECT Id, Name FROM Account Where Name =: AccountName];        
        return testAcct;
    }      
}