objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CuSR_Cost__c.object
<CustomObject>
    <fields>
        <fullName>CuSR_Form__c</fullName>
        <label>CuSR Form</label>
        <referenceTo>CuSR_Form__c</referenceTo>
        <relationshipLabel>CuSR Cost</relationshipLabel>
        <relationshipName>CuSR_Cost</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Labour_Cost__c</fullName>
        <label>Labour Cost Per Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CuSR Cost</label>
    <nameField>
        <displayFormat>CuSR-Cost-Name-{0000}</displayFormat>
        <label>CuSR Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuSR Cost</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CuSR_Form__c.object
<CustomObject>
    <description>The object will be used to create CuSR Forms.</description>
    <fields>
        <fullName>Actual_Requirement__c</fullName>
        <label>Actual Requirement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to select Account. Only active accounts will be available for selection.</description>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CuSR Forms</relationshipLabel>
        <relationshipName>CUSR_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Requestor_Email__c</fullName>
        <description>Auto-populated with the selected Contact&apos;s email by apex method.</description>
        <label>Customer Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Contact object. Will search contacts related to selected Account.</description>
        <label>Customer Requestor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CuSR Forms</relationshipLabel>
        <relationshipName>CUSR_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAB_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to select scope as Fab 1.</description>
        <label>FAB 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAB_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FAB 5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAB_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FAB 8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_this_a_one_time_requirement__c</fullName>
        <description>Field to select Yes or No.</description>
        <label>Is this a one time requirement?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Justification_for_Request__c</fullName>
        <description>Long Text Area to capture justification for the request.</description>
        <label>Justification for Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_Customer_after_Implementation__c</fullName>
        <description>If checked will send notify the selected contact once all implementation is done.</description>
        <label>Notify Customer after Implementation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Received_Date__c</fullName>
        <description>Date when the request is received.</description>
        <label>Request Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>Date when the request will be effective from.</description>
        <label>Requested Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scope_of_the_CuSR__c</fullName>
        <description>Multi-select picklist field to select the scope of the CuSR request.</description>
        <label>Scope of the CuSR</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RTP Parts</fullName>
                </value>
                <value>
                    <fullName>Engineering Parts</fullName>
                </value>
                <value>
                    <fullName>Risk Product Parts</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Requirement__c</fullName>
        <description>Long Text Area to capture any special requirements.</description>
        <label>Any Special Requirement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The field will be populated with the current status of the form by an apex class.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending PM Review</fullName>
                </value>
                <value>
                    <fullName>Pending AM Review</fullName>
                </value>
                <value>
                    <fullName>Pending Stakeholder Review</fullName>
                </value>
                <value>
                    <fullName>Pending Implementation</fullName>
                </value>
                <value>
                    <fullName>Implemented</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>CUSR Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AUTOMOTIVE</fullName>
                </value>
                <value>
                    <fullName>CAR/ 8D</fullName>
                </value>
                <value>
                    <fullName>CONTROL PLAN</fullName>
                </value>
                <value>
                    <fullName>CPK</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER AUDIT</fullName>
                </value>
                <value>
                    <fullName>DCC</fullName>
                </value>
                <value>
                    <fullName>ETEST</fullName>
                </value>
                <value>
                    <fullName>FMEA</fullName>
                </value>
                <value>
                    <fullName>FRONTSIDE LASERMARK</fullName>
                </value>
                <value>
                    <fullName>INTERNAL AUDIT</fullName>
                </value>
                <value>
                    <fullName>LOGISTICS</fullName>
                </value>
                <value>
                    <fullName>LOT ID NAMING CONVENTION</fullName>
                </value>
                <value>
                    <fullName>MES SYSTEM</fullName>
                </value>
                <value>
                    <fullName>MRB</fullName>
                </value>
                <value>
                    <fullName>OCR Requirements</fullName>
                </value>
                <value>
                    <fullName>OQA – INSPECTION</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>PACKAGING, SHIPPING &amp; LABELS</fullName>
                </value>
                <value>
                    <fullName>PCRB</fullName>
                </value>
                <value>
                    <fullName>PPAP</fullName>
                </value>
                <value>
                    <fullName>PROCESS QUALIFICATION</fullName>
                </value>
                <value>
                    <fullName>QUALITY AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>RECORDS RETENTION</fullName>
                </value>
                <value>
                    <fullName>RELIABILITY</fullName>
                </value>
                <value>
                    <fullName>REPORTS</fullName>
                </value>
                <value>
                    <fullName>REWORK</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>ROS</fullName>
                </value>
                <value>
                    <fullName>RTP</fullName>
                </value>
                <value>
                    <fullName>SCRAPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validity_Period_of_this_Request__c</fullName>
        <description>Picklist value to select validity period of the request on Days, Months, Year and EOF.</description>
        <label>Validity Period of this Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Days</fullName>
                </value>
                <value>
                    <fullName>Months</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CuSR Form</label>
    <nameField>
        <displayFormat>CUSR-{YY}-{00000}</displayFormat>
        <label>CUSR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CuSR Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CuSR_Labour_Cost_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Labour_Cost__c</fullName>
        <label>Labour Cost</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <label>CuSR Labour Cost Settings</label>
</CustomObject>

classes/CuSRNewEditCostExtensionTest.cls
/*
Author: Shyam Ravindra Nair
Description: Test class to calculate code coverage for CuSRNewEditCostExtension class.
History:
SNair     09012015     - code creation
SNair     10012015     - added more test cases.
SNair     28042015     - modified.
*/
@isTest(SeeAllData=false)
public class CuSRNewEditCostExtensionTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    public static testMethod void myTestMethod(){
        User testUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            CuSR_Form__c testCuSRForm1 = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_1__c = true,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New',
                OwnerId = testUser.Id
            );
            insert testCuSRForm1;
            
            CuSR_Form__c testCuSRForm2 = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_5__c = true,
                Technology__c = 'ANA 0.18UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New',
                OwnerId = testUser.Id
            );
            insert testCuSRForm2;
            
            CuSR_Form__c testCuSRForm3 = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_8__c = true,
                Technology__c = 'XM 0.010UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'New',
                OwnerId = testUser.Id
            );
            insert testCuSRForm3;
            
            User assignee = [select Id from User where Id != :UserInfo.getUserId() and Profile.Name = 'GF CE' and isActive = true limit 1];
            
            List<CuSR_Labour_Cost_Settings__c> cusrLabourCostList = new List<CuSR_Labour_Cost_Settings__c>();
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Dresden', Labour_Cost__c = 45.19230769));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Singapore', Labour_Cost__c = 37.01923077));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Malta', Labour_Cost__c = 61.05769231));
            insert cusrLabourCostList;
            
            Map<String, CuSR_Labour_Cost_Settings__c> cusrLabourCostSetting = CuSR_Labour_Cost_Settings__c.getAll();
            
            CuSR_Cost__c testCuSRCost1 = new CuSR_Cost__c(
                CuSR_Form__c = testCuSRForm1.Id,
                Fab__c = 'FAB 1',
                Site__c = 'Dresden',
                Labour_Cost__c = cusrLabourCostSetting.get('Dresden').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            insert testCuSRCost1;
            
            CuSR_Cost__c testCuSRCost2 = new CuSR_Cost__c(
                CuSR_Form__c = testCuSRForm2.Id,
                Fab__c = 'FAB 5',
                Site__c = 'Singapore',
                Labour_Cost__c = cusrLabourCostSetting.get('Singapore').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            insert testCuSRCost2;
            
            CuSR_Cost__c testCuSRCost3 = new CuSR_Cost__c(
                CuSR_Form__c = testCuSRForm3.Id,
                Fab__c = 'FAB 8',
                Site__c = 'Malta',
                Labour_Cost__c = cusrLabourCostSetting.get('Singapore').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            insert testCuSRCost3;
            
            test.startTest();
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',testCuSRForm1.Id);
            System.currentPageReference().getParameters().put('Site','Dresden');
            CuSRNewEditCostInfoExtension controller1 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',testCuSRForm2.Id);
            System.currentPageReference().getParameters().put('Site','Singapore');
            CuSRNewEditCostInfoExtension controller5 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',testCuSRForm3.Id);
            System.currentPageReference().getParameters().put('Site','Malta');
            CuSRNewEditCostInfoExtension controller6 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            
            CuSRNewEditCostInfoExtension controller2 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(testCuSRCost1));
            controller2.cusrCost.Implementation__c = Date.newInstance(2015,1,31);
            controller2.Save();
            controller2.Cancel();
            controller2.DeleteCost();
            
            CuSRNewEditCostInfoExtension controller3 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(testCuSRCost2));
            controller3.cusrCost.Implementation__c = Date.newInstance(2015,1,31);
            controller3.Save();
            controller3.Cancel();
            controller3.DeleteCost();
            
            CuSRNewEditCostInfoExtension controller4 = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(testCuSRCost3));
            controller4.cusrCost.Implementation__c = Date.newInstance(2015,1,31);
            controller4.Save();
            controller4.Cancel();
            controller4.DeleteCost();
            
            test.stopTest();
        }
    }
    
    public static testMethod void testRun2(){
        User testUser = [select Id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        
        system.runAs(testUser){
            Account testAccount = eWSRUtilityTestDataClass.getAccount();
            
            Contact testContact = new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                AccountId = testAccount.Id,
                Email = 'shyamravindra.nair@cognizant.com'
            );
            insert testContact;
            
            List<CuSR_Form__c> cusrFormList = new List<CuSR_Form__c>();
            CuSR_Form__c fab9CuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_9__c = true,
                Additional_FAB_9__c = TRUE,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'Implemented',
                OwnerId = testUser.Id
            );
            cusrFormList.add(fab9CuSRForm);
            
            CuSR_Form__c fab10CuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                FAB_10__c = true,
                Additional_FAB_10__c = TRUE,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'Implemented',
                OwnerId = testUser.Id
            );
            cusrFormList.add(fab10CuSRForm);
            
            CuSR_Form__c asicCuSRForm = new CuSR_Form__c(
                Request_Received_Date__c = Date.today(),
                ASIC__c = true,
                Additional_ASIC__c = TRUE,
                Technology__c = 'CA 0.045UM',
                Customer_Name__c = testAccount.Id,
                System__c = 'CPK',
                Customer_Requestor__c = testContact.Id,
                Customer_Requestor_Email__c = testContact.Email,
                Notify_Customer_after_Implementation__c = 'No',
                Requested_Effective_Date__c = Date.newInstance(2015,1,31),
                Validity_Period_of_this_Request__c = 'EOL',
                Actual_Requirement__c = 'Test Requirement',
                Justification_for_Request__c = 'Test Justification',
                Scope_of_the_CuSR__c = 'RTP Parts',
                Is_this_a_one_time_requirement__c = 'Yes',
                Special_Requirement__c = 'Test Special Requirements',
                Status__c = 'Implemented',
                OwnerId = testUser.Id
            );
            cusrFormList.add(asicCuSRForm);
            insert cusrFormList;
            
            User assignee = [select Id from User where Id != :UserInfo.getUserId() and Profile.Name = 'GF CE' and isActive = true limit 1];
            
            List<CuSR_Labour_Cost_Settings__c> cusrLabourCostList = new List<CuSR_Labour_Cost_Settings__c>();
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Dresden', Labour_Cost__c = 45.19230769));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Singapore', Labour_Cost__c = 37.01923077));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Malta', Labour_Cost__c = 61.05769231));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'Essex Junction', Labour_Cost__c = 61.05769231));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'East Fishkill', Labour_Cost__c = 61.05769231));
            cusrLabourCostList.add(new CuSR_Labour_Cost_Settings__c(Name = 'ASIC', Labour_Cost__c = 61.05769231));
            insert cusrLabourCostList;
            
            Map<String, CuSR_Labour_Cost_Settings__c> cusrLabourCostSetting = CuSR_Labour_Cost_Settings__c.getAll();
            
            List<CuSR_Cost__c> cusrCostList = new List<CuSR_Cost__c>();
            CuSR_Cost__c fab9CuSRCost = new CuSR_Cost__c(
                CuSR_Form__c = fab9CuSRForm.Id,
                Fab__c = 'FAB 9',
                Site__c = 'Essex Junction',
                Labour_Cost__c = cusrLabourCostSetting.get('Essex Junction').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            cusrCostList.add(fab9CuSRCost);
            
            CuSR_Cost__c fab10CuSRCost = new CuSR_Cost__c(
                CuSR_Form__c = fab10CuSRForm.Id,
                Fab__c = 'FAB 10',
                Site__c = 'East Fishkill',
                Labour_Cost__c = cusrLabourCostSetting.get('East Fishkill').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            cusrCostList.add(fab10CuSRCost);
            
            CuSR_Cost__c asicCuSRCost = new CuSR_Cost__c(
                CuSR_Form__c = asicCuSRForm.Id,
                Fab__c = 'ASIC',
                Site__c = 'ASIC',
                Labour_Cost__c = cusrLabourCostSetting.get('ASIC').Labour_Cost__c,
                Labour_Hours__c = 2,
                Comments_Labour_Cost__c = 'Sample',
                Software_Cost__c = 15,
                Comments_Software_Cost__c = 'Sample',
                Hardware_Cost__c = 20,
                Comments_Hardware_Cost__c  = 'Sample',
                Other_Cost__c = 5,
                Comments_Other_Cost__c = 'Sample',
                Implementation__c = Date.newInstance(2015,1,26),
                Implementation_Comments__c = 'Test'
            );
            cusrCostList.add(asicCuSRCost);
            insert cusrCostList;
            
            test.startTest();
            
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',fab9CuSRForm.Id);
            System.currentPageReference().getParameters().put('Site','Essex Junction');
            CuSRNewEditCostInfoExtension fab9Controller = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            fab9Controller.Save();
            fab9Controller.Cancel();
            fab9Controller.DeleteCost();
            fab9Controller.disableEditDeleteMethod();
            System.assertEquals(fab9Controller.disableEditDelete, TRUE);
            
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',fab10CuSRForm.Id);
            System.currentPageReference().getParameters().put('Site','East Fishkill');
            CuSRNewEditCostInfoExtension fab10Controller = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            fab10Controller.Save();
            fab10Controller.Cancel();
            fab10Controller.DeleteCost();
            fab10Controller.disableEditDeleteMethod();
            System.assertEquals(fab10Controller.disableEditDelete, TRUE);
            
            Test.setCurrentPageReference(new PageReference('Page.CuSRNewEditCostInfo'));
            System.currentPageReference().getParameters().put('CuSRForm',asicCuSRForm.Id);
            System.currentPageReference().getParameters().put('Site','ASIC');
            CuSRNewEditCostInfoExtension asicController = new CuSRNewEditCostInfoExtension(new ApexPages.Standardcontroller(new CuSR_Cost__c()));
            asicController.Save();
            asicController.Cancel();
            asicController.DeleteCost();
            asicController.disableEditDeleteMethod();
            System.assertEquals(asicController.disableEditDelete, TRUE);
            
            test.stopTest();
        }
    }
}