objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Reticle__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_Debit_Note_Date__c</fullName>
        <label>Pending Debit Note Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ROS_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ROS Cycle</label>
        <referenceTo>ROS_Cycle__c</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reticle_workflow_Status__c</fullName>
        <label>Reticle Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending to Notify Customer</fullName>
                </value>
                <value>
                    <fullName>Pending for Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Pending Witness Arrival Date</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form,Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for Fab&apos;s Follow-up</fullName>
                </value>
                <value>
                    <fullName>Pending Debit Note</fullName>
                </value>
                <value>
                    <fullName>Pending for Shipment</fullName>
                </value>
                <value>
                    <fullName>Shipped Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending HS Code Assignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reticle</label>
    <nameField>
        <label>Reticle Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ROS_Cycle__c.object
<CustomObject>
    <label>ROS Cycle</label>
    <nameField>
        <label>ROS Cycle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROS Cycles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ROS_DebitNoteReminderBatch.cls
/*
This is batch class runs on every Monday
and sends an email to CSRs about Debit Note
Author: Ravikiran Nadella
Version 1.0
*/
global class ROS_DebitNoteReminderBatch implements database.batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext info){
        return Database.getQueryLocator([Select id,Account__c,Account__r.name,ROS_Cycle__r.name,name,Pending_Debit_Note_Date__c,Reticle_workflow_Status__c
                                         from reticle__c where Reticle_workflow_Status__c='Pending Debit Note'
                                         and Pending_Debit_Note_Date__c !=null ]);
        
    }
    
    global void execute(Database.BatchableContext info, List<reticle__c> scope){
        
        Ros_reticleHandler ros = new Ros_reticleHandler ();
        ros.intiateEmails(scope);
    }
    
    global void finish(Database.BatchableContext info){
        
    }  
    
    
    
}