objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Satsfaction__c.object
<CustomObject>
    <description>Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
    <fields>
        <fullName>Customer_Satisfaction_Unique_Check__c</fullName>
        <label>Customer Satisfaction Unique Check</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_Satisfaction_yearly_score__c</fullName>
        <formula>Merit_Index_for_customers__r.Account__r.Name + &quot; &quot; +  Text( Quarter_New__c ) + &quot; &quot; +  Score_Year__c</formula>
        <label>Customer Satisfaction yearly score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dissatisfaction_Report_Date__c</fullName>
        <defaultValue>$System.OriginDateTime</defaultValue>
        <inlineHelpText>If this date fall within past 60 days, it will be shown in the Key Areas of Dissatisfaction Report.</inlineHelpText>
        <label>Dissatisfaction Report Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Merit_Index_for_customers__c</fullName>
        <description>Merit Index Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Merit Index for customers</label>
        <referenceTo>Merit__c</referenceTo>
        <relationshipLabel>Customer Satisfaction</relationshipLabel>
        <relationshipName>Customer_Satsfaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quarter_New__c</fullName>
        <label>Quarter</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
                <value>
                    <fullName>Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Score_Year__c</fullName>
        <description>score year Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Score Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Customer Satisfaction</label>
    <nameField>
        <label>Customer Satisfaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Satisfactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CustomerSatisfaction__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CustomerSatisfaction</label>
</CustomObject>

objects/Merit__c.object
<CustomObject>
    <description>Merit index for customer satisfaction value to set for score.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Enablement Partner, Reseller</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Merit Index for customers</relationshipLabel>
        <relationshipName>Merit_Index_for_customers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Merit Index for customers</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merit Index for customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Next_QBR__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Satisfaction__c</fullName>
        <label>Customer Satisfaction</label>
        <referenceTo>Customer_Satsfaction__c</referenceTo>
        <relationshipLabel>Next QBRS</relationshipLabel>
        <relationshipName>Next_QBRS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Next QBR</label>
    <nameField>
        <displayFormat>NQBR-{0000}</displayFormat>
        <label>Next QBR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Next QBRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomerSatisfactionCloneExtention.cls
/*************************************************************************************************************************************************************
@ Class:          CustomerSatisfactionBarChartExtention
@ Version:        1.0
@ Author:         Sandesh Singh
@ Purpose:        Helper class to clone parent and its children sObjects
--------------------------------------------------------------------------------------------------------------------------------------------------------------
@ Change history: 24.08.2017 / Sandesh Singh / Created the class.
                : 06.02.2018 / Sandesh Singh / Line 80 To display Merit Index in clone section where user can have flexiblity to chnage Merit Index 
                                             /Added by Customer Satisfaction 2.4 enhancment
**************************************************************************************************************************************************************/

public without sharing class CustomerSatisfactionCloneExtention {
    public String sObjectId {get;set;}
    public Customer_Satsfaction__c customerSat {get;set;}
    
    public CustomerSatisfactionCloneExtention(ApexPages.StandardController controller){
        customerSat = new Customer_Satsfaction__c();
        if (!Test.isRunningTest())
        	controller.addFields(new List<String>{'Merit_Index_for_customers__c','Customer_Satisfaction_yearly_score__c','Quarter_New__c','Score_Year__c'});
        sObjectId = controller.getId();
        customerSat = (Customer_Satsfaction__c)controller.getRecord();
        
        //customerSat.id = sObjectId;
    }
   
    private Boolean isRecordDuplicate(){
        Set<String> setUniqueCheck = new Set<String>();
        for(Customer_Satsfaction__c cs : [Select Id, Name, Quarter_New__c,Score_Year__c, Merit_Index_for_customers__r.Account__r.Name,
                                          Customer_Satisfaction_yearly_score__c
                                          From Customer_Satsfaction__c
                                          Where Merit_Index_for_customers__c =:customerSat.Merit_Index_for_customers__c])
        {
            if(setUniqueCheck.contains(cs.Merit_Index_for_customers__r.Account__r.Name  + ' ' + customerSat.Quarter_New__c + ' ' + customerSat.Score_Year__c)){
            	return true;
            }
            else{
            	setUniqueCheck.add(cs.Merit_Index_for_customers__r.Account__r.Name + ' ' + cs.Quarter_New__c + ' ' + cs.Score_Year__c);
            }
        }
        return false;
    }
    
    /**
    * @description Clone parent and its children
    * @param id of the parent sObject
    * @return String Serialized result
    */
    public PageReference cloneRecord () {
        List<Customer_Satsfaction__c> parentSObjects;
        Customer_Satsfaction__c parent;
        CustomerSatisfaction__c envObj;
        List<Next_QBR__c> children = new List<Next_QBR__c>();
        
		// Parent query
        String query = String.format(
            'SELECT {0} FROM {1} WHERE Id = \'\'{2}\'\'',
            new String[] {
                String.join(
                    new List<String>(
                        Customer_Satsfaction__c.SObjectType.getDescribe().fields.getMap().keySet()
                    ),
                    ','
                ),
                String.valueOf(Customer_Satsfaction__c.SObjectType),
                sObjectId
           }
        );
        try {
            // Query and gets results
            parentSObjects = Database.query(query); 
            
            // Clone the original object. Here you can change anything without affecting the original sObject
            parent = parentSObjects[0].clone(false, true, false, false);
            String s1 = parent.Name;
			String s2 = s1.substringBefore(' ');
            
            system.debug('--isRecordDuplicate--' + isRecordDuplicate());
            if(isRecordDuplicate()){
                envObj = CustomerSatisfaction__c.getValues('Customer_Satisfaction_Clone_Error');
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, envObj.Value__c));
                PageReference page = new PageReference('/apex/CustomerSatisfactionClone?id='+ sObjectId);
                return page;                                                                              
             }
            
            //To display Merit Index in clone section where user can have flexiblity to chnage Merit Index 
            //Added by Customer Satisfaction 2.4 enhancment
            parent.Merit_Index_for_customers__c = customerSat.Merit_Index_for_customers__c;
            parent.Quarter_New__c = customerSat.Quarter_New__c;
            parent.Score_Year__c = customerSat.Score_Year__c;
            parent.Name = s2 + ' ' + customerSat.Score_Year__c + ' ' + customerSat.Quarter_New__c;
            parent.Customer_Satisfaction_Unique_Check__c = '';
            parent.Dissatisfaction_Report_Date__c = Date.Today();
            Database.insert(parent);
       
        } catch (DmlException error) {
            envObj = CustomerSatisfaction__c.getValues('Customer_Satisfaction_Clone_Error');
            GlobalUtility.logMessage('Error','CustomerSatisfactionCloneExtention','cloneRecord','',envObj.Value__c,String.valueof(error.getMessage()),'','Customer Satisfaction',error,0);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, envObj.Value__c));
            ApexPages.addMessages(error);
            PageReference page = new PageReference('/apex/CustomerSatisfactionClone?id='+ sObjectId);
            return page; 
        }
        // Children query  
        query = String.format(
            'SELECT {0} FROM {1} WHERE Customer_Satisfaction__c = \'\'{2}\'\'',
            new String[] {
                String.join(
                    new List<String>(
                        Next_QBR__c.SObjectType.getDescribe().fields.getMap().keySet()
                    ),
                    ','
                ),
                String.valueOf(Next_QBR__c.SObjectType),
                sObjectId
           }
        );
        
        try {
            
            // Query and clone the children. Here you can change anything without affecting the original sObject
            for (Next_QBR__c child:(List<Next_QBR__c>)Database.query(query)) {
                children.add(child.clone(false,true,false,false));
            }
			// Set the parent's Id
            for (Next_QBR__c child : children) {
                child.Customer_Satisfaction__c = parent.Id;
                child.Order__c = child.Order__c;
            }
            Database.insert(children);
            
        }  catch(DMLException error) {
            envObj = CustomerSatisfaction__c.getValues('Customer_Satisfaction_Child_Error'); 
            GlobalUtility.logMessage('Error','CustomerSatisfactionCloneExtention','cloneRecord','',envObj.Value__c,String.valueof(error.getMessage()),'','Customer Satisfaction',error,0);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, envObj.Value__c));
            ApexPages.addMessages(error);
            PageReference page = new PageReference('/apex/CustomerSatisfactionClone?id='+ sObjectId);
            return page; 
        }
        PageReference page = new PageReference('/'+ parent.Id + '/e?retURL=%2F'+ parent.Id);
        return page;
    }
}