objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab_9_10__c</fullName>
        <label>Fab 9/10</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>CASE(TEXT ( Select_Status__c ), 
&quot;Green trending Up&quot;, Image(&quot;/resource/Account_G_trending_Up&quot;,&quot;&quot;,25,37)+&quot;G-U&quot;, 
&quot;Green trending Sideways&quot;, Image(&quot;/resource/Account_G_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;G-S&quot;, 
&quot;Green trending Down&quot;, Image(&quot;/resource/Account_G_trending_Down&quot;,&quot;&quot;,25,37)+&quot;G-D&quot;, 
&quot;Yellow trending Up&quot;, Image(&quot;/resource/Account_Y_trending_Up&quot;,&quot;&quot;,25,37)+&quot;Y-U&quot;, 
&quot;Yellow trending Sideways&quot;, Image(&quot;/resource/Account_Y_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;Y-S&quot;, 
&quot;Yellow trending Down&quot;, Image(&quot;/resource/Account_Y_trending_Down&quot;,&quot;&quot;,25,37)+&quot;Y-D&quot;, 
&quot;Red trending Up&quot;, Image(&quot;/resource/Account_R_trending_Up&quot;,&quot;&quot;,25,37)+&quot;R-U&quot;, 
&quot;Red trending Sideways&quot;, Image(&quot;/resource/Account_R_trending_Sideways&quot;,&quot;&quot;,25,37)+&quot;R-S&quot;, 
&quot;Red trending Down&quot;, Image(&quot;/resource/Account_R_trending_Down&quot;,&quot;&quot;,25,37)+&quot;R-D&quot;, 
&quot;No Status Selected&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HCM_Employee__c.object
<CustomObject>
    <description>HCM Employee record table.  This table will be updated with data from the Global Foundries Employee management system.    All new Salesforce employee user records will be created through this interface.</description>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HCM Employee</label>
    <nameField>
        <displayFormat>HCM-{000000}</displayFormat>
        <label>HCM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCM Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HCMEmployeeSyncToContactTest.cls
/*
    Author: Nino Bustillos
    Description: Test class for HCMEmployeeSyncToContact Apex Trigger
    History:
        Nbustillos  01242013    - code creation.
        Nbustillos  10122013    - Added call to loadEnvironmentVariables() method.
        Ashwini     05152015    - Updated code for refactoring of test class.
 */
@isTest(SeeAllData=false)
private class HCMEmployeeSyncToContactTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
        
        Map<String,Object> fieldValueMap = new Map<String,Object>();
        fieldValueMap.put('Name', 'MYTEST ACCOUNT1');                           
        fieldValueMap.put('sub_type__c', 'Direct');
        fieldValueMap.put('site_department__c', 'test dept');          
        fieldValueMap.put('transaction_type__c', 'transactional');                          
        fieldValueMap.put('region__c', 'US');        
        fieldValueMap.put('Corporate_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Corporate_City__c', 'Test City');                
        fieldValueMap.put('Corporate_Country__c', 'India');
        fieldValueMap.put('Bill_To_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Bill_To_City__c', 'Test City');            
        fieldValueMap.put('Bill_To_Country__c', 'India');        
        fieldValueMap.put('Fab_9_10__c','No');

        AccountDataFactory.createAccount(fieldValueMap);
    }
    static testMethod void myUnitTest() {
        
        // Load Environment Variables   
        //DataUtilTest.loadEnvironmentVariables();
        
        Test.startTest();
        
        // create GF account and add to environment variables
        Account gfAccount = getAccount('MYTEST ACCOUNT1');
        EnvironmentVariable.put('HCM Emp AccountId',gfAccount.Id);
        
        // create test HCM Employees
        List<HCM_Employee__c> hcmEmployees = new List<HCM_Employee__c>();
        Integer ctr = 0;
        do{
            hcmEmployees.add(new HCM_Employee__c(First_Name__c='Test', Last_Name__c='HCM Emp',
                                                 Email_Address__c='test' + ctr + '@test.com',Status__c='Active',
                                                 Employee_ID__c='RC1000'+ctr,Login_ID__c='RC1000'+ctr));
            ctr++;
        }while(ctr<5);
        insert hcmEmployees;
        
        // update HCM Employee Names
        ctr = 0;
        List<HCM_Employee__c> hcmEmployeesUpdate = new List<HCM_Employee__c>();
        Set<Id> hcmEmployeeIDs = new Set<Id>();
        Map<Id,String> hcmEmpFirstName = new Map<Id,String>();
        do{
            HCM_Employee__c hcmEmployee = hcmEmployees.get(ctr);
            hcmEmployee.First_Name__c = 'Test'+ctr;
            hcmEmployeesUpdate.add(hcmEmployee);
            ctr++;
            
            hcmEmpFirstName.put(hcmEmployee.Id,hcmEmployee.First_Name__c);
        }while(ctr<5);
        update hcmEmployeesUpdate;
        
        // retrieve contacts and check size
        List<Contact> equivalentContacts = [select firstname,HCM_Record_ID__c from Contact 
                                            where HCM_Record_ID__c in :hcmEmpFirstName.keySet()];
        system.assertEquals(5,equivalentContacts.size());
        
        // check updated firstname
        for(Contact contactRec : equivalentContacts){
            system.assertEquals(contactRec.firstname,hcmEmpFirstName.get(contactRec.HCM_Record_ID__c));
        }
        
        Test.stopTest();
    }
    
    private static Account getAccount(string AccountName)
    {
        Account acct = [SELECT Id, Name FROM Account Where Name =: AccountName];
        
        return acct;
    }
}