objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>IF( CONTAINS(Name, &apos;ADVANCED MICRO DEVICES&apos;) , &apos;AMD&apos;,  IF(CONTAINS(Name, &apos;BROADCOM&apos;) , &apos;Broadcom&apos;,  IF( CONTAINS(Name, &apos;QUALCOMM&apos;) , &apos;Qualcomm&apos;, &apos;Others&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Short Name</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lot_Instruction__c.object
<CustomObject>
    <description>Junction Object to relate the Lot Request Object to the Manufacturing Lot. Prrovides instructions for the lot.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Lot_Instructions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Request__c</fullName>
        <label>Lot Request</label>
        <referenceTo>Lot_Request__c</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Request_to_Lot_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lot_Type__c</fullName>
        <label>Lot Type (ML)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Lot__c</fullName>
        <inlineHelpText>Manufacturing Lot Tagged for Request</inlineHelpText>
        <label>Lot ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. Please refine your search.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Manufacturing_Lot__c.Account_Name__c</valueField>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Last_Ship_Date__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Active_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Lot Ids are filtered based on the Account selection at Lot Instruction level and which are not yet shipped.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Manufacturing_Lot__c</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Request_to_Lot_Tags</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Customer_Requested_Date_CRD_CSR__c</fullName>
        <formula>Lot_Request__r.New_Customer_Requested_Date_CRD_CSR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New CRD (CSR)</label>
        <type>Date</type>
    </fields>
    <label>Lot Instruction</label>
    <nameField>
        <displayFormat>LotInstr-{000000}</displayFormat>
        <label>Lot Instructions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lot_Request__c.object
<CustomObject>
    <description>This Object is used to manage lot requests to include expedite, but eventually other instructions as well.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lot_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Fab__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.060UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.090UM</fullName>
                </value>
                <value>
                    <fullName>0.11UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.14UM</fullName>
                </value>
                <value>
                    <fullName>0.15UM</fullName>
                </value>
                <value>
                    <fullName>0.152UM</fullName>
                </value>
                <value>
                    <fullName>0.153UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.20UM</fullName>
                </value>
                <value>
                    <fullName>0.22UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.30UM</fullName>
                </value>
                <value>
                    <fullName>0.32UM</fullName>
                </value>
                <value>
                    <fullName>0.35UM</fullName>
                </value>
                <value>
                    <fullName>0.45UM</fullName>
                </value>
                <value>
                    <fullName>0.50UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Customer_Requested_Date_CRD_CSR__c</fullName>
        <inlineHelpText>New Customer Request Date (CRD) based upon the customer&apos;s expedite request.</inlineHelpText>
        <label>New CRD (CSR)</label>
        <type>Date</type>
    </fields>
    <label>Lot Service Request</label>
    <nameField>
        <displayFormat>LReq-{0000000}</displayFormat>
        <label>Lot Service Request Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will have the Customer Information of a Lot</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Manufacturing Lot</relationshipLabel>
        <relationshipName>Manufacturing_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ACTIVE_FLAG</description>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Device_Id__c</fullName>
        <description>This is mapped to CUSTOMER_PARTNO from DW</description>
        <label>Customer Device Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab_Group__c</fullName>
        <label>Fab Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Ship_Date__c</fullName>
        <label>Last Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lot_Type__c</fullName>
        <description>Mapped to Lot_Type</description>
        <label>Lot Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Number__c</fullName>
        <description>This is mapped to DW , Purchase Order Number</description>
        <label>Purchase Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <description>This column is mapped to SALES_ORDER_NUMBER of DW.</description>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LotInstruction_MassInsertController.cls
/**
* Author        :   Nikhil Jain
* Company       :   Cognizant Technologies PTE Ltd.
* Description   :   Functionality for Mass Insert of Lot Instructions on Lot Request.
* History       :
        Initials        Date                Description
-----------------------------------------------------------------------------------------
        NJain           10/09/2013          Created the Class
        NJain           31-Jul-2015         Removed unwanted codes. Added columns in query.
        RNadella        31/08/2015          Increased integer list size and also added Active flag condition 
                                            to the Query        
        RNadella        31/08/2015          Added Current CRD to the Query to the queryString                                   
**/

public class LotInstruction_MassInsertController{
     
    ApexPages.StandardSetController stdSetController;
    
    //Variable declaration
    public String LotReqId{get;set;}
    public String lotReqName{get;set;}
    public String AccountName{get;set;}
    public String AccountShortName{get;set;}
    public String FabName{get;set;}
    public List<LotInstructionWrapper> lstLotInstructionWrapper{get;set;}
    public Integer numberOfRowToRemove{get;set;}
    
    public boolean showMfgLotTable{get;set;}
    public boolean showLotInstructionTable{get;set;}
    public boolean isChecked{get;set;}
    public String fieldToSearch{get;set;}
    public String textToSearch{get;set;}
    public List<MfgLotWrapper> lstMfgLotWrapper{get;set;}
    
    //for Pagination
    private integer counter=0;  //keeps track of the offset
    private integer list_size=25; //sets the page size or number of rows 
    public integer total_size; //used to show user the total size of the list
        
    List<Manufacturing_Lot__c> lstManufacturingLots = new List<Manufacturing_Lot__c>();
    List<Id> lstExistingMfgLotId = new List<Id>();
    Lot_Request__c lotReqRec;
    
    //Constructor
    public LotInstruction_MassInsertController(ApexPages.StandardSetController stdSetController){
        this.stdSetController = stdSetController;
        showMfgLotTable = false;
        lstMfgLotWrapper = new List<MfgLotWrapper>();

        LotReqId = (Id)ApexPages.currentPage().getParameters().get('id');
        
        lstLotInstructionWrapper = new List<LotInstructionWrapper>();

        if(LotReqId !=null){
            lotReqRec = [SELECT Name,Fab__c, Account__c,Account__r.Name,Account__r.Short_Name__c,
                                New_Customer_Requested_Date_CRD_CSR__c,
                                (SELECT Id,Manufacturing_Lot__c from Request_to_Lot_Tags__r) 
                         FROM Lot_Request__c where id =:LotReqId ];
            lotReqName = lotReqRec.name;
            AccountName= lotReqRec.Account__r.Name;
            FabName    = lotReqRec.Fab__c;
            AccountShortName = lotReqRec.Account__r.Short_Name__c;
            
            for(Lot_Instruction__c existingLotInstrn:lotReqRec.Request_to_Lot_Tags__r){
                lstExistingMfgLotId.add(existingLotInstrn.Manufacturing_Lot__c);
            }
        }    
    }
    
    //Defining the wrapper for Lot Instruction Wrapper 
    public class LotInstructionWrapper{
        public Lot_Instruction__c lotInstrn{get;set;}
        public boolean checkbox{get;set;}
        public date currentCSD{get;set;}
    }        
    
    //Defining the wrapper for Manufacturing Lot Wrapper
    public class MfgLotWrapper{
        public boolean radioButton{get;set;}
        public Manufacturing_Lot__c mfgLotRec{get;set;}
        public MfgLotWrapper(Manufacturing_Lot__c c) {
            mfgLotRec = c;
            radioButton = false;
        }
    }       
    
    //Items on which the Searching can be made on Manufacturing Lot
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Purchase_Order_Number__c','PO#'));
        options.add(new SelectOption('Sales_Order_Number__c','SO#'));
        options.add(new SelectOption('Customer_Device_Id__c','Customer Device'));
        return options;
    }
    
    //Method for Searching the Manufacturing Lot records as per the search string passed.
    public PageReference searchLots() {
        try {
            lstMfgLotWrapper.clear();
            isChecked = false;
            
            if(textToSearch.trim()!=NULL && textToSearch.trim()!=''){
                
                String queryTotalSize;
                queryTotalSize = 'select id from Manufacturing_Lot__c where Fab_Group__c = \''+ lotReqRec.Fab__c + 
                                 '\' and Account_Name__c = \''+ lotReqRec.Account__c +'\' and ' + 
                                  fieldToSearch + ' like \'' + textToSearch+'%\''+ 
                                 ' and Last_Ship_Date__c = NULL '+
                                 ' and id not in :lstExistingMfgLotId' +
                                 ' and Active_Flag__c=true ';
                
                list<Manufacturing_lot__c> lst_total_size = database.Query(queryTotalSize);
                total_size = lst_total_size.size();
                String queryString;
                system.debug('###########Field To Search#########'+fieldToSearch );
                
                queryString = 'select id,name,Lot_Type__c,Geometry__c, Fab_Group__c,Purchase_Order_Number__c,Ship_to_Customer_Date__c,Last_Ship_Date__c,Account_Name__c,Remaining_Mask_Count__c,'+
                              'Sales_Order_Number__c, Customer_Device_Id__c,Current_Wafer_Quantity_In_Lot__c,Current_Scheduled_Date_CSD__c,Current_Customer_Request_Date_CRD__c  from Manufacturing_Lot__c where Fab_Group__c = \''+
                              lotReqRec.Fab__c + '\' and Account_Name__c = \''+ lotReqRec.Account__c + 
                              '\' and '+fieldToSearch + ' like \'' + textToSearch+'%\''+
                              ' and Last_Ship_Date__c = NULL '+
                              ' and id not in :lstExistingMfgLotId  ' + 
                              ' and Active_Flag__c=true limit  '+
                              string.valueOf(list_size) +' offset '+ string.valueOf(counter);
                
                system.debug('###########queryString #########'+queryString);
                lstManufacturingLots.clear();
                lstManufacturingLots = database.Query(queryString);
                
                for(Manufacturing_Lot__c mfgLot:lstManufacturingLots){
                    MfgLotWrapper mfgWrapperRec = new MfgLotWrapper(mfgLot);
                    lstMfgLotWrapper.add(mfgWrapperRec);
                }
                showMfgLotTable = false;
                if(!lstMfgLotWrapper.isEmpty()){
                    showMfgLotTable = true;
                }
                else{
                    showMfgLotTable = false;
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'No Matching Manufacturing Lots Found'));
                }
            }
            else{
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please provide some text'));
                 return null;
            }
            return null;
            
        } catch (QueryException e) {
            ApexPages.addMessages(e);   
            return null;
        }
        return null;
    }
    
    //User clicked beginning
    public PageReference Beginning() { 
      counter = 0;
      searchLots();
      return null;
    }

    //User clicked previous button
    public PageReference Previous() { 
      counter -= list_size;
      searchLots();
      return null;
    }
    
    //User clicked next button
    public PageReference Next() { 
      counter += list_size;
      searchLots();
      return null;
    }
    
    //User clicked end
    public PageReference End() {
      counter = total_size - math.mod(total_size, list_size);
      searchLots();
      return null;
    }
    
    //This will disable the previous and beginning buttons
    public Boolean getDisablePrevious() {
      if (counter>0) 
          return false; 
      else 
          return true;
    }
    
    //This will disable the next and end buttons
    public Boolean getDisableNext() { 
      if (counter + list_size < total_size) 
          return false; 
      else 
          return true;
    }
    
    //This is for total page size
    public Integer getTotal_size() {
      return total_size;
    }
    
    //This will display the current page number
    public Integer getPageNumber() {
      return counter/list_size + 1;
    }
    
    //This will display the total pages
    public Integer getTotalPages() {
      if (math.mod(total_size, list_size) > 0) {
         return total_size/list_size + 1;
      } else {
         return (total_size/list_size);
      }
    }

    //This is used for creating the Lot Instruction rows for the Manufacturing Lot records selected by the user
    public PageReference createRows(){
        boolean anySelected = false;
        for(MfgLotWrapper mfgWrapRec: lstMfgLotWrapper){
            if(mfgWrapRec.radioButton == True){
                Lot_Instruction__c lotInstructionRow = new Lot_Instruction__c();
                LotInstructionWrapper wrapperRec = new LotInstructionWrapper();
                wrapperRec.lotInstrn = lotInstructionRow;
                wrapperRec.lotInstrn.Lot_Request__c = LotReqId;
                wrapperRec.lotInstrn.Manufacturing_Lot__c = mfgWrapRec.mfgLotRec.id;
                wrapperRec.lotInstrn.Account__c = mfgWrapRec.mfgLotRec.Account_Name__c;
                wrapperRec.lotInstrn.Submitted_Customer_Request_Date_CRD__c = lotReqRec.New_Customer_Requested_Date_CRD_CSR__c;
                wrapperRec.checkbox = true;
                wrapperRec.currentCSD = mfgWrapRec.mfgLotRec.Current_Scheduled_Date_CSD__c;
                lstLotInstructionWrapper.add(wrapperRec);
                anySelected = true;
            }        
        }
        if(!anySelected){
            showMfgLotTable = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please select atleast one Manufacturing Lot'));
            return null;
        }
        if(!lstLotInstructionWrapper.isEmpty()){
            showLotInstructionTable = true;
            showMfgLotTable = false;
            lstMfgLotWrapper.clear();
        }
        else{
            showLotInstructionTable = false;
        }                
        return null;
    }
    
    //For adding an empty Lot Instruction row to the table.
    public PageReference addNewRow(){
        
        Lot_Instruction__c lotInstructionRow = new Lot_Instruction__c();
        LotInstructionWrapper wrapperRec = new LotInstructionWrapper();
        wrapperRec.lotInstrn = lotInstructionRow;
        wrapperRec.lotInstrn.Lot_Request__c = LotReqId;
        wrapperRec.checkbox = true;
        lstLotInstructionWrapper.add(wrapperRec);
        
        if(lstLotInstructionWrapper.size()== 1){
            lstLotInstructionWrapper[0].checkbox = false;
        }
        else{
            lstLotInstructionWrapper[0].checkbox = true;
        }
        return null;
    }
    
    //For removing the Lot Instruction row which has been added to the table.
    public PageReference removeNewObject(){
        if(lstLotInstructionWrapper.size()>1){
            lstLotInstructionWrapper.remove(numberOfRowToRemove);  
        }
        
        if(lstLotInstructionWrapper.size()== 1){
            lstLotInstructionWrapper[0].checkbox = false;
        }else{
            lstLotInstructionWrapper[0].checkbox = true;
        }
        
        showLotInstructionTable = false;
        if(!lstLotInstructionWrapper.isEmpty()){
            showLotInstructionTable = true;
        }
        else{
            showLotInstructionTable = false;
        }
        return null;
    }
    
    // For inserting the Lot Instruction records in one go for all the records selected by the user.
    
    public PageReference Save(){
    
        List<Lot_Instruction__c> lstLotInstrFinal = new List<Lot_Instruction__c>();
        Set<Id> userIds = new Set<Id>();
        
        for(LotInstructionWrapper liRec:lstLotInstructionWrapper){
           lstLotInstrFinal.add(liRec.lotInstrn);
        }      
        transient List<Database.upsertResult> upsertResults = new List<Database.upsertResult>();
        try{
            upsertResults.clear();
            upsertResults = database.upsert(lstLotInstrFinal,true);
            PageReference lotRequestPage = new PageReference('/'+ LotReqId);
            return lotRequestPage;
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getdmlMessage(0));  
            ApexPages.addMessage(myMsg);
            return null;
        }
        return null;
    }
}