objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Short Name</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/VoC__c.object
<CustomObject>
    <description>Voice of the Customer</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Account that was contacted</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>VoCs</relationshipLabel>
        <relationshipName>VoCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <inlineHelpText>Who was contacted?</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>VoCs</relationshipLabel>
        <relationshipName>VoCs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Feedback_Provided__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Provide date when contact was made.</inlineHelpText>
        <label>Date Feedback Provided</label>
        <type>Date</type>
    </fields>
    <label>VoC</label>
    <nameField>
        <displayFormat>VOC-{000000}</displayFormat>
        <label>VOC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VoCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VoC_Score__c.object
<CustomObject>
    <fields>
        <fullName>VoC__c</fullName>
        <label>VoC</label>
        <referenceTo>VoC__c</referenceTo>
        <relationshipName>Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>VoC Score</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VoC Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VoCScoreTriggerUtilTest.cls
@isTest
public class VoCScoreTriggerUtilTest{
     @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    static testMethod void manageTrendsInsert(){
        // Create Account
        RecordType rt = [
            SELECT      Id
            FROM        RecordType
            WHERE       SObjectType = 'Account'
                        AND Name = 'Customer'
        ];
        
        Account testAcct = new Account();
        testAcct.Name = 'Test Account';
        testAcct.Stage__c = 'Unqualified';
        testAcct.Site_Department__c = 'Test Department';
        testAcct.Sub_Type__c = 'Direct';
        testAcct.Transaction_Type__c = 'Transactional';
        testAcct.Region__c = 'APJ';
        testAcct.Bill_To_Address_1__c = 'Test Address 1';
        testAcct.Corporate_Address_1__c = 'Corporate Address 1';
        testAcct.Bill_To_City__c = 'Test City';
        testAcct.Corporate_City__c = 'Test City';
        testAcct.Bill_To_Country__c = 'Singapore';
        testAcct.Corporate_Country__c = 'Singapore';
        testAcct.RecordTypeId = rt.Id;      
        testAcct.Short_Name__c = 'TestAcct';
        
        insert testAcct;
        
        Contact testCon = new Contact();
        testCon.firstName = 'test';
        testCon.LastName = 'test';
        testCon.Email = 'test@gmail.com';
        testCon.accountId = testAcct.id;
        insert testCon;
        
        
        VoC__c testVoC= new VoC__c();
        testVoC.Account__c = testAcct.Id;
        testVoC.Contact__c = testCon.id;
        testVoC.Date_Feedback_Provided__c = system.today();
        testVoC.Schedule_Next_Follow_Up__c = system.today();
        testVoC.Action_Owner__c = userinfo.getUserId();
        insert testVoC;
        
        VoC_Score__c testVoCScore = new VoC_Score__c();
        testVoCScore.Area__c = 'Technology Roadmap';
        testVoCScore.Grade_5_best__c = '5';
        testVoCScore.Comments__c = 'test comments';
        testVoCScore.VoC__c = testVoC.id;
        insert testVoCScore;
        
        test.startTest();
        VoC_Score__c testVoCScore1 = new VoC_Score__c();
        testVoCScore1.Area__c = 'Technology Roadmap';
        testVoCScore1.Grade_5_best__c = '5';
        testVoCScore1.Comments__c = 'test comments';
        testVoCScore1.VoC__c = testVoC.id;
        insert testVoCScore1;
        
        testVoCScore1.Grade_5_best__c = '2';
        update testVoCScore1;
        test.stopTest();
        
    }
    
    static testMethod void manageTrendsDelete(){
        // Create Account
        RecordType rt = [
            SELECT      Id
            FROM        RecordType
            WHERE       SObjectType = 'Account'
                        AND Name = 'Customer'
        ];
        
        Account testAcct = new Account();
        testAcct.Name = 'Test Account';
        testAcct.Stage__c = 'Unqualified';
        testAcct.Site_Department__c = 'Test Department';
        testAcct.Sub_Type__c = 'Direct';
        testAcct.Transaction_Type__c = 'Transactional';
        testAcct.Region__c = 'APJ';
        testAcct.Bill_To_Address_1__c = 'Test Address 1';
        testAcct.Corporate_Address_1__c = 'Corporate Address 1';
        testAcct.Bill_To_City__c = 'Test City';
        testAcct.Corporate_City__c = 'Test City';
        testAcct.Bill_To_Country__c = 'Singapore';
        testAcct.Corporate_Country__c = 'Singapore';
        testAcct.RecordTypeId = rt.Id;      
        testAcct.Short_Name__c = 'TestAcct';
        
        insert testAcct;
        
        Contact testCon = new Contact();
        testCon.firstName = 'test';
        testCon.LastName = 'test';
        testCon.Email = 'test@gmail.com';
        testCon.accountId = testAcct.id;
        insert testCon;
        
        
        VoC__c testVoC= new VoC__c();
        testVoC.Account__c = testAcct.Id;
        testVoC.Contact__c = testCon.id;
        testVoC.Date_Feedback_Provided__c = system.today();
        testVoC.Schedule_Next_Follow_Up__c = system.today();
        testVoC.Action_Owner__c = userinfo.getUserId();
        insert testVoC;
        
        VoC_Score__c testVoCScore = new VoC_Score__c();
        testVoCScore.Area__c = 'Technology Roadmap';
        testVoCScore.Grade_5_best__c = '5';
        testVoCScore.Comments__c = 'test comments';
        testVoCScore.VoC__c = testVoC.id;
        insert testVoCScore;
        
        test.startTest();
        VoC_Score__c testVoCScore1 = new VoC_Score__c();
        testVoCScore1.Area__c = 'Technology Roadmap';
        testVoCScore1.Grade_5_best__c = '5';
        testVoCScore1.Comments__c = 'test comments';
        testVoCScore1.VoC__c = testVoC.id;
        insert testVoCScore1;
        
        testVoCScore1.Grade_5_best__c = '2';
        delete testVoCScore1;   
        delete testVoC;      
        test.stopTest();
        
    }
}