objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Visitation_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visitation Attendees</relationshipLabel>
        <relationshipName>Visitation_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visitations</relationshipLabel>
        <relationshipName>Visitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>Visitation__r.End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitation__c</fullName>
        <label>Visitation</label>
        <referenceTo>Visitation_Record__c</referenceTo>
        <relationshipLabel>Visitation Attendees</relationshipLabel>
        <relationshipName>Visitation_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visitation Attendee</label>
    <nameField>
        <label>Visitation Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitation Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visitation_Executive__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Visitation_Executive</label>
</CustomObject>

objects/Visitation_Record__c.object
<CustomObject>
    <description>Customer Visitation Application - Custom app for tracking and forecasting Customer Visitation (visits to and from customers).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is a required entry to allow linking to relevant Account record</description>
        <inlineHelpText>Please use the lookup icon to the right of the field to select the Customer Account. HINT: In the lookup dialog, enter the first 2 characters of the customer Account Name following by an asterisk (*), for example - Ad*.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visitations</relationshipLabel>
        <relationshipName>Customer_Visitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Status__c</fullName>
        <description>Visitation Stage</description>
        <inlineHelpText>There are 6 stages(Set Automatically):
0. Draft (any record saved but not submitted)
1.Regional Approval
2.Confirmed
3.Logistics Preparation
4.Logistics Completed
5.Closed-Cancelled
5.Closed-Completed
5.Closed-Rejected 5.Closed-Pending Survey</inlineHelpText>
        <label>Visitation Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0. Draft</fullName>
                    <default>true</default>
                    <label>0. Draft</label>
                </value>
                <value>
                    <fullName>1. Regional Approval</fullName>
                </value>
                <value>
                    <fullName>2. Confirmed</fullName>
                </value>
                <value>
                    <fullName>3. Logistics Preparation</fullName>
                </value>
                <value>
                    <fullName>4. Logistics Complete</fullName>
                </value>
                <value>
                    <fullName>5. Closed - Cancelled</fullName>
                </value>
                <value>
                    <fullName>5. Closed - Completed</fullName>
                </value>
                <value>
                    <fullName>5. Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>5. Closed-Pending Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>End date for visitation</description>
        <inlineHelpText>Required field (indicates last day of visitation). Choose date by clicking on built-in calendar function to the right of the field (in edit mode).</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>This field location to abbreviated form.</description>
        <formula>CASE(TEXT(Visit_Location__c), 
&quot;Dresden&quot;, &quot;DRS&quot;,
&quot;Malta&quot;, &quot;MLT&quot;,
&quot;Santa Clara&quot;, &quot;SC&quot;,
&quot;Singapore&quot;, &quot;SG&quot;,
&quot;Fishkil&quot;, &quot;FSK&quot;,
&quot;Williston&quot;, &quot;WIL&quot;,
&quot;Burlington&quot;, &quot;BTV&quot;,
&quot;GLOBALFOUNDRIES Other Site&quot;, &quot;GF Site&quot;,
&quot;Customer Location&quot;, &quot;Cust Site&quot;,
&quot;Public Event&quot;, &quot;Event&quot;,
&quot;Non-public Event (Offsite)&quot;, &quot;Event&quot;,
&quot;Partner Location&quot;, &quot;Partner&quot;,
&quot;Supplier Location&quot;, &quot;Supplier&quot;,
&quot;Vendor Location&quot;, &quot;Vendor&quot;
,&quot;&quot;)</formula>
        <inlineHelpText>This field location to abbreviated form.</inlineHelpText>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purposes__c</fullName>
        <description>Field to trim Purpose field for reports.</description>
        <formula>IF (INCLUDES( Purpose__c,&quot;Opportunity Management&quot; ), &quot;Opty Mngt -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Opportunity Generation&quot; ),&quot;New Opty -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Negotiations&quot; ),&quot;Neg -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;QBR&quot; ),&quot;QBR -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;QOR&quot; ),&quot;QOR -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Audit&quot; ),&quot;Audit -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Incident resolution&quot; ),&quot;Incid Resol -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;New customer introduction&quot; ),&quot;New Cust -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Technical meetings&quot; ),&quot;Technical -&quot;,&quot;&quot;)
&amp; IF (INCLUDES( Purpose__c,&quot;Other&quot; ),&quot;Other&quot;,&quot;&quot;)</formula>
        <inlineHelpText>Formula Field for Purpose used for reports.</inlineHelpText>
        <label>Purposes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Start date of visitation</description>
        <inlineHelpText>Required field (indicates first day of visitation). Choose date by clicking on built-in calendar function to the right of the field (in edit mode).</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visitation_Host__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Visitation Host</description>
        <inlineHelpText>Indicates which person is handling the details of the visit, including meeting invitations and minutes. For Fab Visits this will usually be the CE responsible for the account, for Visits to  Customer the AM. This is a required field, used in the workflow.</inlineHelpText>
        <label>Visitation Host / Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Visitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visitation</label>
    <nameField>
        <displayFormat>CVA-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Visitation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/VisitationReportController.cls
/*Author: Vijay Vemuru
    Description: Controller for Sending Executives Reports for Customer Visitation
    History:
    Created     -     Vijay Vemuru-    04/21/2016      - code creation.
*/
public class VisitationReportController {
    public list<Visitation_Executive__c> visitExecutiveList{get;set;}
    public List<Visitation_Attendee__c> visitationAttendeeList{get;set;}
    public map<id,string> requeststatusMap{get;set;}
    
    Map<string,Visitation_Executive__c> visitExcutives =  new Map<string,Visitation_Executive__c>();
        
    public VisitationReportController() {
        visitExecutiveList = new list<Visitation_Executive__c>();
        visitationAttendeeList = new List<Visitation_Attendee__c>();
        requeststatusMap = new map<id,string>();
        visitExcutives = Visitation_Executive__c.getAll();
    
        if(visitExcutives != null ) {
            for(Visitation_Executive__c exec : visitExcutives.values()) {
                visitExecutiveList.add(exec);
            } 
        }
        tableData();    
    }
    
    public void tableData() {
        Date tday= system.today();
        Date lastMonth = tday.addmonths(-1);
        set<string> customerStatus= new set<string>{'3. Logistics Preparation','4. Logistics Complete'};
        visitationAttendeeList = [SELECT id,Attendee__c,Request_Status__c,Attendee__r.name,Visitation__r.Account__r.name,
                              Visitation__r.Account__c,Visitation__r.Visitation_Host__r.name,Visitation__r.Start_Date__c,Visitation__r.End_Date__c,
                              Visitation__r.Location__c,visitation__r.Purposes__c,Visitation__r.name 
                              FROM Visitation_Attendee__c 
                              WHERE createddate>=: lastMonth AND Visitation__r.Customer_Status__c IN:customerStatus];
      
           for (Visitation_Attendee__c visit : visitationAttendeeList) {
            if(visitExcutives.containsKey(visit.Attendee__r.name)) {
                if(visit.Request_Status__c   == 'Requested') {
                    requeststatusMap.put(visit.id,'R');
                } else if(visit.Request_Status__c    == 'Declined') {
                    requeststatusMap.put(visit.id,'D');
                } else if(visit.Request_Status__c    == 'Confirmed') {
                    requeststatusMap.put(visit.id,'C');
                } 
                
            }
       
       }
    }
}