objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Team_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team Proxy</relationshipLabel>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Administrator</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Backup Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Business Planner</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Integration</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Customer Tapeout Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Quality Engineer</fullName>
                </value>
                <value>
                    <fullName>DE - Customer Support</fullName>
                </value>
                <value>
                    <fullName>DE - Enablements</fullName>
                </value>
                <value>
                    <fullName>DE - IP Technical</fullName>
                </value>
                <value>
                    <fullName>Demand Planner</fullName>
                </value>
                <value>
                    <fullName>Design and Technology Support</fullName>
                </value>
                <value>
                    <fullName>Design Win Team</fullName>
                </value>
                <value>
                    <fullName>DE - Tapeout</fullName>
                </value>
                <value>
                    <fullName>Fab Planner</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Primary Account Manager</fullName>
                </value>
                <value>
                    <fullName>Primary Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Primary Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Marketing</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Engineer</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Strategic Marketing</fullName>
                </value>
                <value>
                    <fullName>TD PI / YE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team_Proxy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team Proxy</label>
    <nameField>
        <displayFormat>ATP-{000000}</displayFormat>
        <label>ATP Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Proxy</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reticle__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Inactive_Formula__c</fullName>
        <description>This formula field calculates actual inactive days as a difference between TODAY and &apos;Inactive Days Start Date&apos;.</description>
        <formula>IF(NOT(ISBLANK(Inactive_Days_Start_Date__c)),
   (TODAY() - Inactive_Days_Start_Date__c),
   IF(NOT(ISBLANK(Day_Inactive__c)), 
      (TODAY() - (DATEVALUE(LastModifiedDate) - Day_Inactive__c)),
      (TODAY() - DATEVALUE(LastModifiedDate))
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inactive Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day_Inactive__c</fullName>
        <label>Inactive Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Device_ID__c</fullName>
        <label>Customer Device ID</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FabStr__c</fullName>
        <label>Fab</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GlobalFoundries_Device_ID__c</fullName>
        <label>GF Device ID</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HS_Code_Assigned__c</fullName>
        <formula>IF(OR(ISBLANK(HS_Code__c), ISBLANK(Item__c)), false, true)</formula>
        <label>HS Code Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROS_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ROS Cycle</label>
        <referenceTo>ROS_Cycle__c</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROS_Status__c</fullName>
        <label>Disposition Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Return</fullName>
                    <color>#FFFF66</color>
                    <label>Return</label>
                </value>
                <value>
                    <fullName>Scrap</fullName>
                    <color>#FF0000</color>
                    <label>Scrap</label>
                </value>
                <value>
                    <fullName>Keep</fullName>
                    <color>#33CC00</color>
                    <label>Keep</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reticle_Type__c</fullName>
        <label>Reticle Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADV BIN</fullName>
                </value>
                <value>
                    <fullName>BINARY</fullName>
                </value>
                <value>
                    <fullName>COG</fullName>
                </value>
                <value>
                    <fullName>EPSM</fullName>
                </value>
                <value>
                    <fullName>PSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reticle_workflow_Status__c</fullName>
        <label>Reticle Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending to Notify Customer</fullName>
                </value>
                <value>
                    <fullName>Pending for Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Pending Witness Arrival Date</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form,Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for Fab&apos;s Follow-up</fullName>
                </value>
                <value>
                    <fullName>Pending Debit Note</fullName>
                </value>
                <value>
                    <fullName>Pending for Shipment</fullName>
                </value>
                <value>
                    <fullName>Shipped Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending HS Code Assignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reticle</label>
    <nameField>
        <label>Reticle Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ROS_Cycle__c.object
<CustomObject>
    <label>ROS Cycle</label>
    <nameField>
        <label>ROS Cycle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROS Cycles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ROS_BATCH_CSRNotifications.cls
/*
    Author: Deepti Narayan Biswal
    Description: This Class is used to send Reminder Notifications for CSR users in ROS System.
    History:
        DBiswal     08192015    - Created.
        DBiswal     09042015    - Modified code according to code review.
*/
global class ROS_BATCH_CSRNotifications implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    Map<Id,List<Reticle__c>> csrPNCMap = new Map<Id,List<Reticle__c>>(); //Map for user and reticles with Pending to Notify Customer status
    Map<Id, List<Reticle__c>> csrPCFMap = new Map<Id, List<Reticle__c>>(); //Map for user and reticles with Pending for Customer Feedback status
    Map<Id, List<Reticle__c>> usrtradecompMap = new Map<Id, List<Reticle__c>>(); //Map for user and reticles for ROS Trade compliance Team
    Map<Id, List<Reticle__c>> cePWADMap = new Map<Id, List<Reticle__c>>(); //Map for user and reticles with pending witness arrival date status
    String currentrosCycle = '';
    String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        currentrosCycle = ROS_Util.getCurrentROSCycle();
        String stf='Pending for STF Obsolescence';
        String pfab='Pending for Fab\'s Follow-up';
        String query = 'SELECT Id,Name,Account__c,Account__r.Name,Reticle_Type__c,GlobalFoundries_Device_ID__c,Device_ID__c,FabStr__c,Day_Inactive__c,Day_Inactive_Formula__c,ROS_Status__c,Reticle_workflow_Status__c,ROS_Cycle__c,ROS_Cycle__r.Name,HS_Code_Assigned__c FROM Reticle__c ';
        String wherecond = ' WHERE (Reticle_workflow_Status__c = \'Pending to Notify Customer\' OR Reticle_workflow_Status__c = \'Pending for Customer Feedback\' OR Reticle_workflow_Status__c = \'Pending Witness Arrival Date\' OR Reticle_workflow_Status__c =: stf OR Reticle_workflow_Status__c =: pfab) AND ROS_Cycle__r.Name=:currentrosCycle ORDER BY Account__c';
        query = query+wherecond;
        return Database.getQueryLocator(query);
    }
    global void execute(SchedulableContext SC){
        Database.executeBatch(new ROS_BATCH_CSRNotifications());
    }
    global void execute(Database.BatchableContext BC, List<Reticle__c> scope){
        Map<Id,Reticle__c> retPNCMap = new Map<Id,Reticle__c>(); //Map for reticles with Pending to Notify Customer status
        Map<Id,Reticle__c> retPCFMap = new Map<Id,Reticle__c>(); //Map for reticles with Pending for Customer Feedback status
        Map<Id,Reticle__c> rettradecompMap = new Map<Id,Reticle__c>(); //Map for reticles with Pending for STF Obsolescence status
        Map<Id,Reticle__c> retPWADMap = new Map<Id,Reticle__c>(); //Map for reticles with pending witness arrival date status
        Set<Id> accIdset = new Set<Id>();
        for(Reticle__c ret : scope){
            if(ret.Reticle_workflow_Status__c == 'Pending to Notify Customer' || ret.Reticle_workflow_Status__c == 'Pending for Customer Feedback'){
                accIdset.add(ret.Account__c);
                if(ret.Reticle_workflow_Status__c == 'Pending to Notify Customer'){
                    retPNCMap.put(ret.Id, ret);
                } else if(ret.Reticle_workflow_Status__c == 'Pending for Customer Feedback'){
                    retPCFMap.put(ret.Id, ret);
                } 
        	} else if((ret.Reticle_workflow_Status__c == 'Pending for STF Obsolescence' || ret.Reticle_workflow_Status__c == 'Pending for Fab\'s Follow-up') && ret.ROS_Status__c == 'Return' && ret.HS_Code_Assigned__c == false){
                rettradecompMap.put(ret.Id, ret);
            } else if(ret.Reticle_workflow_Status__c == 'Pending Witness Arrival Date' && ret.ROS_Status__c == 'Scrap'){
                retPWADMap.put(ret.Id, ret);
            }        
        }
        
        Set<Id> csrUsrIdset = new Set<Id>();
        for(Account_Team_Proxy__c atp : [SELECT Id,Team_Role__c,User__c FROM Account_Team_Proxy__c WHERE Account__c IN: accIdset AND (Team_Role__c IN ('Primary Customer Service Rep','Backup Customer Service Rep','Customer Service Rep')) AND User__r.IsActive = true]){
            csrUsrIdset.add(atp.User__c);
        }
        
        List<GroupMember> ltradecompGM = [SELECT Id,Group.Name,UserOrGroupId FROM GroupMember WHERE Group.DeveloperName = 'ROS_Trade_Compliance_Team' AND Group.Type = 'Queue'];
        
        for(Reticle__Share rets : [SELECT Id,UserOrGroupId,ParentId,RowCause FROM Reticle__Share 
                                   WHERE ParentId IN: scope AND (RowCause = 'Sharing_with_CSR__c' OR RowCause = 'Sharing_with_Trade_Compliance__c' OR RowCause = 'Sharing_with_CE__c') ORDER BY RowCause]){
            if(rets.RowCause == 'Sharing_with_CSR__c'){
                if(csrUsrIdset.contains(rets.UserOrGroupId)){
                    if(retPNCMap.containsKey(rets.ParentId)){
                        if(!csrPNCMap.containsKey(rets.UserOrGroupId)){
                            csrPNCMap.put(rets.UserOrGroupId, new List<Reticle__c>{retPNCMap.get(rets.ParentId)});
                        } else {
                            csrPNCMap.get(rets.UserOrGroupId).add(retPNCMap.get(rets.ParentId));
                        }
                    }
                    if(retPCFMap.containsKey(rets.ParentId)){
                        if(!csrPCFMap.containsKey(rets.UserOrGroupId)){
                            csrPCFMap.put(rets.UserOrGroupId, new List<Reticle__c>{retPCFMap.get(rets.ParentId)});
                        } else {
                            csrPCFMap.get(rets.UserOrGroupId).add(retPCFMap.get(rets.ParentId));
                        }
                    }
            	}
            } else if(rets.RowCause == 'Sharing_with_Trade_Compliance__c'){
                if(rettradecompMap.containsKey(rets.ParentId)){
                    if(!ltradecompGM.isEmpty()){
                        for(GroupMember gm : ltradecompGM){
                            if(!usrtradecompMap.containsKey(gm.UserOrGroupId)){
                                usrtradecompMap.put(gm.UserOrGroupId, new List<Reticle__c>{rettradecompMap.get(rets.ParentId)});
                            } else {
                                usrtradecompMap.get(gm.UserOrGroupId).add(rettradecompMap.get(rets.ParentId));
                            }
                        }
                    }
                }
            } else if(rets.RowCause == 'Sharing_with_CE__c'){
                if(retPWADMap.containsKey(rets.ParentId)){
                    if(!cePWADMap.containsKey(rets.UserOrGroupId)){
                        cePWADMap.put(rets.UserOrGroupId, new List<Reticle__c>{retPWADMap.get(rets.ParentId)});
                    } else {
                        cePWADMap.get(rets.UserOrGroupId).add(retPWADMap.get(rets.ParentId));
                    }
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        Map<String,String> reportMap = new Map<String,String>();
        List<Report> reportlist = [SELECT Id,Name,DeveloperName FROM Report WHERE (DeveloperName = 'Reticles_Pending_for_Notify_Customer' OR DeveloperName = 'Reticles_Pending_for_Customer_Feedback' OR DeveloperName = 'Reticles_Pending_for_HS_Code_Assignment' OR DeveloperName = 'Reticles_Pending_for_Witness_Arrival_Date')];
        for(Report r : reportlist){
            if(r.DeveloperName == 'Reticles_Pending_for_Notify_Customer'){
                reportMap.put('notify customer', (String)r.Id);
            } else if(r.DeveloperName == 'Reticles_Pending_for_Customer_Feedback'){
                reportMap.put('customer feedback', (String)r.Id);
            } else if(r.DeveloperName == 'Reticles_Pending_for_HS_Code_Assignment'){
                reportMap.put('hs code assignment', (String)r.Id);
            } else if(r.DeveloperName == 'Reticles_Pending_for_Witness_Arrival_Date'){
                reportMap.put('witness arrival date', (String)r.Id);
            }
        }
        List<Messaging.SingleEmailMessage> csrmails = new List<Messaging.SingleEmailMessage>();
        if(!csrPNCMap.isEmpty()){
            String reportId = reportMap.get('notify customer');
            for(Id csrId : csrPNCMap.keySet()){
              Messaging.SingleEmailMessage mail1 = new Messaging.SingleEmailMessage();
                mail1.setSenderDisplayName('ROS System');
                mail1.setTargetObjectId(csrId);
                mail1.setHtmlBody('Dear Team,<br/><br/>A number of('+csrPNCMap.get(csrId).size()+') Reticles are pending for Customer Notification in the ROS system.<br/><br/>Request you to log into the system and process the reticles accordingly.<br/><br/><a href="'+baseUrl+'/'+reportId+'">Click here to view its Report.</a>');
                mail1.setSubject('(ROS '+currentrosCycle+'): Reticles Pending for the Customer Notification');
                mail1.setSaveAsActivity(false);
                csrmails.add(mail1);
            }
        }
        if(!csrPCFMap.isEmpty()){
            String reportId = reportMap.get('customer feedback');
            for(Id csrId : csrPCFMap.keySet()){
              Messaging.SingleEmailMessage mail1 = new Messaging.SingleEmailMessage();
                mail1.setSenderDisplayName('ROS System');
                mail1.setTargetObjectId(csrId);
                mail1.setHtmlBody('Dear Team,<br/><br/>A number of('+csrPCFMap.get(csrId).size()+') Reticles are pending for Customer Feedback in the ROS system.<br/><br/>Request you to log into the system and process the reticles accordingly.<br/><br/><a href="'+baseUrl+'/'+reportId+'">Click here to view its Report.</a>');
                mail1.setSubject('(ROS '+currentrosCycle+'): Reticles Pending for the Customer Feedback');
                mail1.setSaveAsActivity(false);
                csrmails.add(mail1);
            }
        }
        if(!usrtradecompMap.isEmpty()){
            String reportId = reportMap.get('hs code assignment');
            for(Id csrId : usrtradecompMap.keySet()){
              Messaging.SingleEmailMessage mail1 = new Messaging.SingleEmailMessage();
                mail1.setSenderDisplayName('ROS System');
                mail1.setTargetObjectId(csrId);
                mail1.setHtmlBody('Dear Team,<br/><br/>A number of('+usrtradecompMap.get(csrId).size()+') Reticles are pending for HS Code and Item Number Assignment in the ROS system.<br/><br/>Request you to log into the system and process the reticles accordingly.<br/><br/><a href="'+baseUrl+'/'+reportId+'">Click here to view its Report.</a>');
                mail1.setSubject('(ROS '+currentrosCycle+'): Reticles Pending for the HS Code and Item Numbers Assignment');
                mail1.setSaveAsActivity(false);
                csrmails.add(mail1);
            }
        }
        if(!cePWADMap.isEmpty()){
            String reportId = reportMap.get('witness arrival date');
            for(Id csrId : cePWADMap.keySet()){
              Messaging.SingleEmailMessage mail1 = new Messaging.SingleEmailMessage();
                mail1.setSenderDisplayName('ROS System');
                mail1.setTargetObjectId(csrId);
                mail1.setHtmlBody('Dear Team,<br/><br/>A number of('+cePWADMap.get(csrId).size()+') Reticles are pending for Witness Arrival Date in the ROS system.<br/><br/>Request you to log into the system and process the reticles accordingly.<br/><br/><a href="'+baseUrl+'/'+reportId+'">Click here to view its Report.</a>');
                mail1.setSubject('(ROS '+currentrosCycle+'): Reticles Pending for Witness Arrival Date');
                mail1.setSaveAsActivity(false);
                csrmails.add(mail1);
            }
        }
        if(!csrmails.isEmpty() && !Test.isRunningTest()){
            Messaging.sendEmail(csrmails);
        }
    }
}