objects/Account_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Hierarchy (Account Id)</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Hierarchy</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>Account Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CURRENCY__c</fullName>
        <label>CURRENCY</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cust_Part__c</fullName>
        <label>Customer part#</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOCDATE__c</fullName>
        <label>Order date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Doc_Number__c</fullName>
        <label>Sales order number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Itm_Number__c</fullName>
        <label>Line Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Part#</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NET_PRICE__c</fullName>
        <label>Price</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purch_No__c</fullName>
        <label>Purchase order number</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Req_Date__c</fullName>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Req_Qty__c</fullName>
        <label>Request Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Order_Schedule__c.object
<CustomObject>
    <description>Sales Order info from ICC SDA Track 3. Contains only Fab 9 /10 sales order as of De c 2016</description>
    <fields>
        <fullName>Confirmed_Date__c</fullName>
        <label>Confirmed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cum_Cf_Qty__c</fullName>
        <label>Confirmed Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line__c</fullName>
        <label>Sales Order Line</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Schedule</relationshipLabel>
        <relationshipName>Sales_Order_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Schedule</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sales Order Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Shipment__c.object
<CustomObject>
    <description>The main shipment object.(Header).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipment</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carrier_PRO__c</fullName>
        <label>Carrier tracking #</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Shipment_Line__c.object
<CustomObject>
    <description>Detail of shipment record</description>
    <fields>
        <fullName>Carrier_PRO__c</fullName>
        <description>Used for creating report.This is taken from shipment object</description>
        <formula>Shipment__r.Carrier_PRO__c</formula>
        <label>Carrier tracking #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cust_Shipto__c</fullName>
        <label>Ship to</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Num__c</fullName>
        <label>Billing Invoice #</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price__c</fullName>
        <label>Price</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Shipment Line</relationshipLabel>
        <relationshipName>Shipment_Line</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipFrom__c</fullName>
        <label>Ship From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_Qty__c</fullName>
        <label>Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Line</relationshipLabel>
        <relationshipName>Shipment_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Line</label>
    <nameField>
        <label>Shipment Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ICC_VF_ScheduleShipment_Details.cls
/*
Controller class for VF page report.
Author: Rahul Majumder
Version 1.0
*/

public class ICC_VF_ScheduleShipment_Details
{
    public Sales_Order_Line__c obj_SO {get;set;}
    public List<Sales_Order_Schedule__c> lst_Schedules {get;set;}
    public List<Shipment_Line__c> lst_ShipLines {get;set;}
    
    public ICC_VF_ScheduleShipment_Details()
    {
        String strSalesOrderID = System.currentPageReference().getParameters().get('soID');
        
        obj_SO = new Sales_Order_Line__c();
        lst_Schedules = new List<Sales_Order_Schedule__c>();
        lst_ShipLines = new List<Shipment_Line__c>();
        
        List<Sales_Order_Line__c> lstSOL = new List<Sales_Order_Line__c>();
        
        lstSOL = [Select Id, Doc_Number__c, Itm_Number__c, Material__c, Cust_Part__c, NET_PRICE__c, Req_Date__c, Req_Qty__c, Purch_No__c, DOCDATE__c,
                  CURRENCY__c, Account__r.Name
                  FROM Sales_Order_Line__c WHERE Id =: strSalesOrderID ];
        if(!lstSOL.isEmpty())
        {
            obj_SO = lstSOL.get(0);
        }
                  
        lst_Schedules = [Select Id, Confirmed_Date__c, Cum_Cf_Qty__c 
                         FROM Sales_Order_Schedule__c 
                         WHERE Sales_Order_Line__c =: strSalesOrderID ORDER BY Confirmed_Date__c];
                         
        lst_ShipLines = [Select Id, Delivery_Date__c, Ship_Qty__c, Invoice_Num__c, ShipFrom__c, Cust_Shipto__c, Shipment__r.Carrier__c, Shipment__r.Carrier_PRO__c 
                         FROM Shipment_Line__c 
                         WHERE Sales_Order__c =: strSalesOrderID ORDER BY Delivery_Date__c];
    }
}