objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_Country__c</fullName>
        <label>Corporate Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>New field part of Case Management 1.0</description>
        <label>Region Case Originated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Burlington</fullName>
                </value>
                <value>
                    <fullName>Fishkill</fullName>
                </value>
                <value>
                    <fullName>Malta</fullName>
                </value>
                <value>
                    <fullName>Santa Clara</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Korea</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Taiwan</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>Dresden</fullName>
                </value>
                <value>
                    <fullName>Munich</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>EMEA/Rest of Asia</fullName>
                </value>
                <value>
                    <fullName>China/Taiwan</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>Japan/Korea</fullName>
                </value>
                <value>
                    <fullName>Qualcomm</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <description>FV2: Used for storing the Department values of Contact</description>
        <inlineHelpText>This field is optional; when filled in it provides default access to GFV applications for one or more predefined roles (Design, Engineering, Quality, Procurement, Supply Chain, Legal).</inlineHelpText>
        <label>Department (GFV Access)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supplier Services</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClsCustomLookupControllerTest.cls
/*
 Type Name: ClsCustomLookupControllerTest
 Author: Cognizant Technology Solutions
 Created Date: 27-Nov-2013
 Reason: This is the test class for 'ClsCustomLookupController' class.
 Change History:
     ZAmbat      04282014    - Updated code to SeeAllData=true as fix for SFDC test limitations.
 Author: Cognizant
 Modified Date: 23-Jan-2014
 Reason: Case 00004324
 …….. 
 ……..
 Ashwini     04162015    - Updated code for making SeeAllData=false and refactoring of test class.
*/

@isTest(SeeAllData = false)
private class ClsCustomLookupControllerTest{
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
        
        Map<String,Object> fieldValueMap = new Map<String,Object>();
        fieldValueMap.put('Name', 'MYTEST ACCOUNT1');            
        fieldValueMap.put('stage__c', 'Unqualified');        
        fieldValueMap.put('sub_type__c', 'Direct');
        fieldValueMap.put('site_department__c', 'test dept');          
        fieldValueMap.put('transaction_type__c', 'transactional');                          
        fieldValueMap.put('region__c', 'APJ');        
        fieldValueMap.put('Corporate_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Corporate_City__c', 'Test City');                
        fieldValueMap.put('Corporate_Country__c', 'Singapore');
        fieldValueMap.put('Bill_To_Address_1__c', 'Test Address 1');          
        fieldValueMap.put('Bill_To_City__c', 'Test City');            
        fieldValueMap.put('Bill_To_Country__c', 'Singapore');        
        fieldValueMap.put('Fab_9_10__c','No');

        AccountDataFactory.createAccount(fieldValueMap);
        User portalUser =new User();
        User portalUser1 =new User();
        Account acctObj = new Account();
        Contact conobj = new Contact();
        Contact conobj1 = new Contact();
        Profile profileObj = [Select Name,Id from Profile where Name ='Customer Portal Admin'];
        User userobj =[Select Id,Name,Profile.Name,Contact.accountId from user where Id=:userinfo.getuserId()];        
        System.runas(userobj){ 
            
            acctObj = getAccount('MYTEST ACCOUNT1');
            
            conobj.FirstName='Mr';
            conobj.LastName='Testcon1';
            conobj.Email='con1@gf.com';
            conobj.Department__c='Design';
            conobj.AccountId=acctObj.Id;
            conobj.Is_Portal_User_Active__c = true;  
            conobj.UserFoundInOT__c=true;//added by cognizant for Case 00004324
            insert conobj;
            
            conobj1.FirstName='Mr';
            conobj1.LastName='Testcon2';
            conobj1.Email='con11@gf.com';
            conobj1.Department__c='Design';
            conobj1.AccountId=acctObj.Id;
            conobj1.Is_Portal_User_Active__c = true;  
            conobj1.UserFoundInOT__c=true;  //added by cognizant for Case 00004324 
             Test.startTest();                        
            insert conobj1;
             
          portalUser = new User( ProfileId = profileObj.Id,
                                            Username = 'portaluser@testorg.com',
                                            Alias = 'auser',
                                            Email='portaluser@testorg.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            ContactId=conobj.Id,
                                            isactive=true,
                                            TimeZoneSidKey='America/Chicago'
                                           );
                                      
         insert portalUser ;
         portalUser1 = new User( ProfileId = profileObj.Id,
                                            Username = 'portaluser1@testorg.com',
                                            Alias = 'auser1',
                                            Email='portaluser1@testorg.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce1',
                                            Lastname='Wayne1',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            ContactId=conobj1.Id,
                                            isactive=true,
                                            TimeZoneSidKey='America/Chicago'
                                           );
                                           
         insert portalUser1 ;            
        }
        Test.stopTest();     
    }
    static testMethod void ClsCustomLookupControllerTest() {
    
    
           
    User userobj =[Select Id,Name,Profile.Name,Contact.accountId from user where Id=:userinfo.getuserId()];
    
     
     List<User> userlist=new List<User>();
          
    
    /* System.runas(userobj)
     { 
            acctObj = getAccount('MYTEST ACCOUNT1');
            
            conobj.FirstName='Mr';
            conobj.LastName='Testcon1';
            conobj.Email='con1@gf.com';
            conobj.Department__c='Design';
            conobj.AccountId=acctObj.Id;
            conobj.Is_Portal_User_Active__c = true;  
            conobj.UserFoundInOT__c=true;//added by cognizant for Case 00004324
            insert conobj;
            
            conobj1.FirstName='Mr';
            conobj1.LastName='Testcon2';
            conobj1.Email='con11@gf.com';
            conobj1.Department__c='Design';
            conobj1.AccountId=acctObj.Id;
            conobj1.Is_Portal_User_Active__c = true;  
            conobj1.UserFoundInOT__c=true;  //added by cognizant for Case 00004324                      
            insert conobj1;
            
          portalUser = new User( ProfileId = profileObj.Id,
                                            Username = 'portaluser@testorg.com',
                                            Alias = 'auser',
                                            Email='portaluser@testorg.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce',
                                            Lastname='Wayne',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            ContactId=conobj.Id,
                                            isactive=true,
                                            TimeZoneSidKey='America/Chicago'
                                           );
                                           
         insert portalUser ;
         portalUser1 = new User( ProfileId = profileObj.Id,
                                            Username = 'portaluser1@testorg.com',
                                            Alias = 'auser1',
                                            Email='portaluser1@testorg.com',
                                            EmailEncodingKey='UTF-8',
                                            Firstname='Bruce1',
                                            Lastname='Wayne1',
                                            LanguageLocaleKey='en_US',
                                            LocaleSidKey='en_US',
                                            ContactId=conobj1.Id,
                                            isactive=true,
                                            TimeZoneSidKey='America/Chicago'
                                           );
                                           
         insert portalUser1 ;
         userlist.add(portalUser);
         userlist.add(portalUser1);
         } */
     User portalUser = [Select Id, Name from User where Email='portaluser@testorg.com'];
    System.runas(portalUser)
     {   
   
     Test.startTest();
     
     Test.setCurrentPageReference(new PageReference('Page.VFCustomUserLookup'));
     //System.currentPageReference().getParameters().put('searchvalue','Bruce'); 
     ClsCustomLookupController CustomLookupControllerobj= new ClsCustomLookupController ();
     
     CustomLookupControllerobj.searchText='Bruce';
	 system.assertEquals(CustomLookupControllerobj.searchText,'Bruce');
     ClsCustomLookupController.clsuser clsuserobj=new ClsCustomLookupController.clsuser();
     CustomLookupControllerobj.search();     
     }  
    Test.stopTest(); 
    }
    
    private static Account getAccount(string AccountName)
    {
        Account acct = [SELECT Id, Name FROM Account Where Name =: AccountName];
        
        return acct;
    }
}