objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_1__c</fullName>
        <label>Address Line 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Corporate_Address_1__c</fullName>
        <label>Corporate Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corporate_City__c</fullName>
        <label>Corporate City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>US-West</fullName>
                </value>
                <value>
                    <fullName>US-Majors</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>US-SoCal</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>ASIC-US</fullName>
                </value>
                <value>
                    <fullName>ASIC-EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Department__c</fullName>
        <inlineHelpText>Enter Site Location or Department if it is a BU</inlineHelpText>
        <label>Site/Department</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                    <default>true</default>
                    <label>Unqualified</label>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>ASIC Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>Assembly &amp; Test Partner</fullName>
                </value>
                <value>
                    <fullName>Design Service Partner</fullName>
                </value>
                <value>
                    <fullName>EDA Partner</fullName>
                </value>
                <value>
                    <fullName>IP Partner</fullName>
                </value>
                <value>
                    <fullName>Mask Partner</fullName>
                </value>
                <value>
                    <fullName>GLOBALSHUTTLE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DE - IP</fullName>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>Analysts</fullName>
                </value>
                <value>
                    <fullName>Investors</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>DE – IP</fullName>
                </value>
                <value>
                    <fullName>R&amp;D Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transactional</fullName>
                </value>
                <value>
                    <fullName>Non-Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Direct Sub Type : Direct Customer managed by AM; Indirect Sub Type : End customer buying from Resellers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <description>FV2: Used for storing the Department values of Contact</description>
        <inlineHelpText>This field is optional; when filled in it provides default access to GFV applications for one or more predefined roles (Design, Engineering, Quality, Procurement, Supply Chain, Legal).</inlineHelpText>
        <label>Department (GFV Access)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Supply Chain</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Supplier Services</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MDDFeedItemTest.cls
/* 
 Type Name: MDDFeedItemTest
 Author: JKTechnosoft
 Created Date: 13-July-2016
 Reason: Test class for MDDFeedItem controller
 
 */
@isTest
public class MDDFeedItemTest {
    public static testMethod void MDDFeedItemTestmethod(){
        DataUtilTest.loadEnvironmentVariables();
        RecordType rt = [SELECT  Id FROM RecordType WHERE SObjectType = 'Account'  AND Name = 'Customer'];
        user us = [Select ID from User where IsActive = true and UserRoleId != null and ContactId = null LIMIT 1];
        Contact conobj1;
        Account accntObj;
        System.runAs(us){
            Map<String,Object> fieldValueMap = New Map<String,Object>();
            fieldValueMap.put('Name','NamePvt company');
            fieldValueMap.put('Stage__c','Unqualified');
            fieldValueMap.put('Site_Department__c','Test Department1');
            fieldValueMap.put('Sub_Type__c','Direct');
            fieldValueMap.put('Transaction_Type__c','Transactional');
            fieldValueMap.put('Region__c','APJ');
            fieldValueMap.put('Bill_To_Address_1__c','Test Address 1');
            fieldValueMap.put('Corporate_Address_1__c','Corporate Address 1');
            fieldValueMap.put('Bill_To_City__c','Test City');
            fieldValueMap.put('Corporate_City__c','Test City');
            fieldValueMap.put('Bill_To_Country__c','Singapore');
            fieldValueMap.put('Corporate_Country__c','Singapore');
            fieldValueMap.put('RecordTypeId',rt.id);
            fieldValueMap.put('Short_Name__c','TestAcct');
            
            accntObj = AccountDataFactory.createAccount(fieldValueMap);
            conobj1=new Contact(FirstName='Mr',
                                LastName='Testcon1rr',
                                AccountId=accntObj.Id,
                                Email='con1@gf.com',
                                Department__c='Design;Engineering',
                                is_portal_user_active__c=false
                               ); 
            insert conObj1;
        }
        Part_Family__c f = new Part_Family__c();
        f.Name = 'test family';
        insert f;
        Part__c p = new Part__c();
        p.Part_Number__c = '0000000001';
        p.Part_Family__c = 'test family';
        p.Part_Type__c = 'FC PBGA';
        insert p;
        Account_Part_Map__c accP = new Account_Part_Map__c();
        accP.Account__c = accntObj.Id;
        accP.Part__c = p.Id;
        insert accP;
        Profile portalProfile = [SELECT Id,Name FROM Profile where Name= 'Overage Customer Portal Admin' Limit 1];
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' and Name like '%Customer%' Limit 1];
        User portalUser1 = new User(Username = 'portaluser1@testorg13.com',
                               Alias = 'auser',
                               Email='portaluser1@testorg.com',
                               EmailEncodingKey='UTF-8',
                               Firstname='Bruce3',
                               Lastname='Wayne4',
                               LanguageLocaleKey='en_US',
                               LocaleSidKey='en_US',
                               TimeZoneSidKey='America/Chicago',
                               ContactId=conobj1.Id,
                               IsActive = true ,ProfileId = portalProfile.Id
                              );
        ApexPages.StandardController sc = new ApexPages.StandardController(f);
        MDDFeedItem mdd = new MDDFeedItem(sc);
        Test.setCurrentPageReference(new PageReference('Page.myPage')); 
        system.currentPageReference().getParameters().put('Id', f.Id);
        mdd.fileName = 'test';
        mdd.fileBody = Blob.valueOf('test filebody');
        mdd.saveAttachment();
        mdd.fileName = 'test';
        mdd.saveAttachment();
    }
}