objects/Attribute_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Field_API_Name__c</fullName>
        <label>Attribute Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Field_Value__c</fullName>
        <label>Attribute Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Group_Name__c</fullName>
        <label>Attribute Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_MLGPLUS__c</fullName>
        <label>CPQ MLGPLUS</label>
        <referenceTo>CPQ_MLGPLUS__c</referenceTo>
        <relationshipLabel>Attribute Rules</relationshipLabel>
        <relationshipName>Attribute_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mask_Layers__c</fullName>
        <label>Mask Layers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attribute Rule</label>
    <nameField>
        <label>Attribute Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPQ_MLGPLUS__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bundle Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CPQ MLGPLUS</relationshipLabel>
        <relationshipName>CPQ_MLGPLUS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Catalog_Type__c</fullName>
        <label>Catalog Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Source</fullName>
                </value>
                <value>
                    <fullName>Multi Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.006UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.035UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.090UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.35UM</fullName>
                </value>
                <value>
                    <fullName>0.6UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Product_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Parent Product External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Product_Name__c</fullName>
        <label>Parent Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Technology__c</fullName>
        <description>Process Technology Number</description>
        <label>Process Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed_Version__c</fullName>
        <inlineHelpText>Processed MLG+ version</inlineHelpText>
        <label>Processed Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Pending Maintenance Jobs</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Ready to Load</fullName>
                </value>
                <value>
                    <fullName>Under Process</fullName>
                </value>
                <value>
                    <fullName>Unprocessed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CPQ MLGPLUS</label>
    <nameField>
        <displayFormat>MLG-{00000000}</displayFormat>
        <label>CPQ MLGPLUS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQ MLGPLUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MLG_Record__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Mask_s__c</fullName>
        <label>Additional Mask(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_MLGPLUS__c</fullName>
        <label>CPQ MLGPLUS</label>
        <referenceTo>CPQ_MLGPLUS__c</referenceTo>
        <relationshipLabel>MLG Records</relationshipLabel>
        <relationshipName>MLG_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Core_Voltage_V__c</fullName>
        <description>Core voltage</description>
        <label>Core Voltage (V)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEOL_BEOL__c</fullName>
        <label>FEOL/ BEOL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FEOL</fullName>
                </value>
                <value>
                    <fullName>BEOL</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feature_Description__c</fullName>
        <label>Feature Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Group__c</fullName>
        <description>Groups of MLG data</description>
        <label>Feature Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IO_Voltage_V__c</fullName>
        <description>IO Voltage</description>
        <label>IO Voltage (V)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MLG Record</label>
    <nameField>
        <displayFormat>MLG-{00000000}</displayFormat>
        <label>MLG Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MLG Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTPS_IP_Lifecycle__c</fullName>
        <label>IP Lifecycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Full Design Kit Qualified</fullName>
                </value>
                <value>
                    <fullName>Silicon Char Report Qualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTPS_IP_Type__c</fullName>
        <label>IP Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>IO</fullName>
                </value>
                <value>
                    <fullName>LOGIC</fullName>
                </value>
                <value>
                    <fullName>MEMORY</fullName>
                </value>
                <value>
                    <fullName>NVM</fullName>
                </value>
                <value>
                    <fullName>PHYS</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Catalog_Type__c</fullName>
        <label>Catalog Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Source</fullName>
                </value>
                <value>
                    <fullName>Multi Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.006UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.035UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.090UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.35UM</fullName>
                </value>
                <value>
                    <fullName>0.6UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Product External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CPQMetadataStatusControllerTest.cls
/**
*   Author: Prosenjit Saha
*   Description: This is the test class for CPQMetadataStatusController

*   History:
*       PSaha          05142015     - code creation.
*     
**/
@istest(SeeAllData=false)
public class CPQMetadataStatusControllerTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    } 
    /*
    * Method Name:     CPQMetadataTest
    * Return Type:     NA
    * Parameter  :     NA
    * Reason     :     This method handle all the Metadata related test for CPQMetadataStatusController class
    */
    static testmethod void CPQMetadataTest(){  
        Product2 ParentProduct = createProduct('PT00XXXX');
        CPQ_MLGPLUS__c mlgplus = getCPQMLG(ParentProduct.id);
        Apttus_Config2__ProductAttributeGroup__c ProdAttGroup = createProdAttributeGroup();
        createMlg(mlgplus.id,ProdAttGroup);
        ApexPages.StandardController sc = new ApexPages.StandardController(mlgplus);
        pageReference pageRef = page.CPQMetadataStatus ; 
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id',mlgplus.id);
        CPQMetadataStatusController controller = new CPQMetadataStatusController(sc);       
        controller.metadataLoad();
        
    }
    
    /*
    * Method Name:     createMlg
    * Return Type:     NA
    * Parameter  :     String mlgID
    * Reason     :     This method creates MLG Test Data. 
    */
    static void createMlg(String mlgplusID, Apttus_Config2__ProductAttributeGroup__c prodAttGroup){
        integer count = 1; 
         
         MLG_Record__c TempMlg0    = new MLG_Record__c(
            Additional_Mask_s__c    = '6K,7K,99',
            Core_Voltage_V__c       =  null,
            Feature_Description__c  = 'Base features',
            Feature_Group__c        = 'Always included',
            Model_Name__c           =  null,
            FEOL_BEOL__c            = 'FEOL',
            IO_Voltage_V__c         =  null,
            Serial_Number__c        = count ++ , 
            CPQ_MLGPLUS__c			= mlgplusID , 
            version__c				= '#1#'
        );
        
        MLG_Record__c TempMlg1    = new MLG_Record__c(
            Additional_Mask_s__c    = '05,06',
            Core_Voltage_V__c       = '1.08',
            Feature_Description__c  = '3LM',
            Feature_Group__c        = 'Metal Options',
            Model_Name__c           = '',
            FEOL_BEOL__c            = 'BEOL',
            IO_Voltage_V__c         = '1.5',
            Serial_Number__c        = count ++ , 
            CPQ_MLGPLUS__c			= mlgplusID,
            version__c				= '#1#'
        );
        
        MLG_Record__c TempMlg2    = new MLG_Record__c(
            Additional_Mask_s__c    = 'PV,SV',
            Core_Voltage_V__c       = '1.08',
            Feature_Description__c  = 'Test Dev1',
            Feature_Group__c        = 'BJT',
            Model_Name__c           = 'dev1',
            FEOL_BEOL__c            = 'FEOL',
            IO_Voltage_V__c         = '1.5',
            Serial_Number__c        = count ++ , 
            CPQ_MLGPLUS__c			= mlgplusID,
            version__c				= '#1#'
        );
        
        MLG_Record__c TempMlg3    = new MLG_Record__c(
            Additional_Mask_s__c    = 'PQ,SQ',
            Core_Voltage_V__c       = '1.08',
            Feature_Description__c  = 'Test Dev2',
            Feature_Group__c        = 'Varactor',
            Model_Name__c           = 'dev2',
            FEOL_BEOL__c            = 'FEOL',
            IO_Voltage_V__c         = '1.5',
            Serial_Number__c        = count ++ , 
            CPQ_MLGPLUS__c			= mlgplusID,
            version__c				= '#1#'
        );
        
        Attribute_Rule__c attributeRule 	= new Attribute_Rule__c(
        	Name							= 'Rule-01'
        	, Attribute_Field_API_Name__c	= 'Bump_for_FC__c'
        	, Attribute_Field_Value__c		= 'Cu Pillar'
        	, Attribute_Group_Name__c		= prodAttGroup.id
        	, Mask_Layers__c				= 'XY,MN'
        	, CPQ_MLGPLUS__c				= mlgplusID
        );                               
        List<MLG_Record__c> mlgList =  new List<MLG_Record__c>{TempMlg0, TempMlg1, TempMlg2, TempMlg3};
        insert mlgList;
    }
    
    /*
    * Method Name:     createProdAttributeGroup
    * Return Type:     Apttus_Config2__ProductAttributeGroup__c
    * Parameter  :     NA
    * Reason     :     This method returns new Product Attribute Groups
    */
    Static Apttus_Config2__ProductAttributeGroup__c createProdAttributeGroup (){
    	Apttus_Config2__ProductAttributeGroup__c prodAtt = new Apttus_Config2__ProductAttributeGroup__c(
    		Name 									= 'Packaging'
    		, Apttus_Config2__BusinessObject__c 	= 'Apttus_Config2__ProductAttributeValue__c'
    		, Product_Attribute_Group_External_Id__c= 'Test Packaging'
    	);
    	insert prodAtt;
    	return prodAtt;
    }
    
    /*
    * Method Name:     getCPQMLG
    * Return Type:     CPQ_MLGPLUS__c
    * Parameter  :     Product2
    * Reason     :     This method returns new CPQ MLG record
    */
    static CPQ_MLGPLUS__c getCPQMLG(String ParentProdID) {
        CPQ_MLGPLUS__c cpqmlgplus = new CPQ_MLGPLUS__c( Catalog_Type__c = 'First Source'
                                                        , Geometry__c = '0.065UM'
                                                        , Status__c = 'Ready to Load'
                                                        , Process_Technology__c = 'PT00XXXX'
                                                        , Bundle_Product__c = ParentProdID
                                                        , Parent_Product_External_ID__c = 'PT00XXXX'
                                                        , Parent_Product_Name__c = 'PT00XXXX'
                                                        , Processed_Version__c = '1');
        insert cpqmlgplus;
        return cpqmlgplus; 
    }
    /*
    * Method Name:     createParentProduct
    * Return Type:     NA
    * Parameter  :     NA
    * Reason     :     This method creates Parent Product. 
    */
    static Product2 createProduct(String PTnumber){
        Product2 TestProd = new Product2();
            TestProd.ProductCode                         = 'Test_'+PTnumber;
            TestProd.Product_External_ID__c              = 'Test_'+PTnumber;
            TestProd.APTPS_IP_Lifecycle__c               = 'Approved';
            //TestProd.APTPS_IP_Type__c                    = 'AMS';
            //TestProd.APTPS_IP_Vendors__c                 = 'GF';
            TestProd.Family                              = 'PTs';
            TestProd.Name                                = 'Test ' + PTnumber;
            TestProd.IsActive                            = TRUE;
            TestProd.Geometry__c                         = '0.028UM';
            TestProd.Apttus_Config2__ConfigurationType__c= 'Bundle'; 
            TestProd.PT_Number__c                        = PTnumber; 
             
        insert TestProd;
        Return TestProd;
    }
}