objects/Attribute_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Field_API_Name__c</fullName>
        <label>Attribute Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Field_Value__c</fullName>
        <label>Attribute Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_MLGPLUS__c</fullName>
        <label>CPQ MLGPLUS</label>
        <referenceTo>CPQ_MLGPLUS__c</referenceTo>
        <relationshipLabel>Attribute Rules</relationshipLabel>
        <relationshipName>Attribute_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HasChildRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasChildRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mask_Layers__c</fullName>
        <label>Mask Layers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Rule</label>
        <referenceTo>Attribute_Rule__c</referenceTo>
        <relationshipLabel>Child Rules</relationshipLabel>
        <relationshipName>Attribute_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attribute Rule</label>
    <nameField>
        <label>Attribute Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPQ_MLGPLUS__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bundle Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CPQ MLGPLUS</relationshipLabel>
        <relationshipName>CPQ_MLGPLUS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Product_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Parent Product External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Process_Technology__c</fullName>
        <description>Process Technology Number</description>
        <label>Process Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQ MLGPLUS</label>
    <nameField>
        <displayFormat>MLG-{00000000}</displayFormat>
        <label>CPQ MLGPLUS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQ MLGPLUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MLG_Record__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Mask_s__c</fullName>
        <label>Additional Mask(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPQ_MLGPLUS__c</fullName>
        <label>CPQ MLGPLUS</label>
        <referenceTo>CPQ_MLGPLUS__c</referenceTo>
        <relationshipLabel>MLG Records</relationshipLabel>
        <relationshipName>MLG_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Device_List__c</fullName>
        <label>Device List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEOL_BEOL__c</fullName>
        <label>FEOL/ BEOL</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FEOL</fullName>
                </value>
                <value>
                    <fullName>BEOL</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feature_Description__c</fullName>
        <label>Feature Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Group__c</fullName>
        <description>Groups of MLG data</description>
        <label>Feature Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MLG_External_ID__c</fullName>
        <description>For IP ONLY , the format is PT Number + &apos;_&apos; + IP Number</description>
        <externalId>true</externalId>
        <label>MLG+ External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Attribute_Rule_ID__c</fullName>
        <label>Parent Attribute Rule ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MLG Record</label>
    <nameField>
        <displayFormat>MLG-{00000000}</displayFormat>
        <label>MLG Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MLG Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Process_Technology__c.object
<CustomObject>
    <label>Process Technology</label>
    <nameField>
        <label>Process Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Technologies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CPQAttributeRuleTriggerHandler.cls
/**
*   Author: Prosenjit Saha
*   Description: This is Handler class for CPQAttributeRuleTrigger
*   History:
*       PSaha          05052015     - code creation.
*     
**/
public class CPQAttributeRuleTriggerHandler {
    public void upsertHandler(List<Attribute_Rule__c> triggeredRec){
        Map<String,String> CPQMLGProdExtMap = new Map<String,String>();
        List<MLG_Record__c> MLGRecList = new List<MLG_Record__c>();
        for(Attribute_Rule__c ARul : [select    id
                                                , name
                                                , CPQ_MLGPLUS__r.Parent_Product_External_ID__c
                                                , CPQ_MLGPLUS__r.Process_Technology__c
                                                , CPQ_MLGPLUS__c
                                                , CPQ_MLGPLUS__r.Bundle_Product__r.Productcode
                                      FROM      Attribute_Rule__c
                                      WHERE     id
                                      IN        :triggeredRec]){
            CPQMLGProdExtMap.put(ARul.id , ARul.CPQ_MLGPLUS__r.Bundle_Product__r.Productcode);
        }
        for(Attribute_Rule__c ARule: triggeredRec){
            if(ARule.HasChildRule__c == false){
                MLG_Record__c mlgrec = new MLG_Record__c();
                    mlgrec.Additional_Mask_s__c         = ARule.Mask_Layers__c ; 
                    mlgrec.Feature_Description__c       = ARule.name ; 
                    mlgrec.Feature_Group__c             = 'Attribute Rule'; 
                    mlgrec.FEOL_BEOL__c                 = 'BEOL' ; 
                    mlgrec.CPQ_MLGPLUS__c               = ARule.CPQ_MLGPLUS__c;
                    mlgrec.Version__c                   = null; 
                    mlgrec.Model_Name__c                = ARule.Attribute_Field_API_Name__c ; 
                    mlgrec.Device_List__c               = ARule.Attribute_Field_Value__c; 
                    mlgrec.MLG_External_ID__c           = CPQMLGProdExtMap.containsKey(ARule.id) && ARule.Parent_Rule__c == null ? CPQMLGProdExtMap.get(ARule.id)+'_'+ARule.Attribute_Field_API_Name__c: CPQMLGProdExtMap.get(ARule.id)+'_'+ARule.Attribute_Field_API_Name__c+ ARule.Parent_Rule__c; //added CPQ MLGPLUS Id in order to make the external field unique : change done for the Case# 49711 automation
                    mlgrec.Parent_Attribute_Rule_ID__c  = ARule.Parent_Rule__c ;
                MLGRecList.add(mlgrec);
            }
        }
        if(MLGRecList.size() > 0){
            upsert MLGRecList MLG_External_ID__c; 
        }
    }
    
    public void deleteHandler(List<Attribute_Rule__c> triggeredRec){
        List<String> ExtIdList = new List<String>();
        Map<String,String> CPQMLGProdExtMap = new Map<String,String>();
        for(Attribute_Rule__c ARul : [select    id
                                                , name
                                                , CPQ_MLGPLUS__r.Parent_Product_External_ID__c
                                                , CPQ_MLGPLUS__r.Process_Technology__c
                                                , CPQ_MLGPLUS__c
                                                , CPQ_MLGPLUS__r.Bundle_Product__r.Productcode
                                      FROM      Attribute_Rule__c
                                      WHERE     id
                                      IN        :triggeredRec
                                      AND       CPQ_MLGPLUS__r.Bundle_Product__c != null]){
            CPQMLGProdExtMap.put(ARul.id , ARul.CPQ_MLGPLUS__r.Bundle_Product__r.Productcode);
        }
        for(Attribute_Rule__c ARule :  triggeredRec){
             if(CPQMLGProdExtMap.containsKey(ARule.id)){
                 ExtIdList.add(CPQMLGProdExtMap.get(ARule.id)+'_'+ARule.Attribute_Field_API_Name__c ) ;
             }
             if(ARule.HasChildRule__c == TRUE){
                 ExtIdList.add(ARule.id);
             }
        }
        List<MLG_Record__c> DeleteMLGRec = new List<MLG_Record__c>();
        DeleteMLGRec = [select id,MLG_External_ID__c,Parent_Attribute_Rule_ID__c from MLG_Record__c where MLG_External_ID__c IN :ExtIdList OR Parent_Attribute_Rule_ID__c IN :ExtIdList ];
        if(DeleteMLGRec.size()>0){
            delete DeleteMLGRec;
        }
    }
    
}