objects/BnP_Finance_Quote_Document__c.object
<CustomObject>
    <description>Custom object defining detail of finance related document related to RFQ.</description>
    <fields>
        <fullName>BnP_Finance_Quote_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BnP Finance Quote Document</label>
        <referenceTo>Request_Information__c</referenceTo>
        <relationshipLabel>BnP Finance Quote Document</relationshipLabel>
        <relationshipName>BnP_Finance_Quote_Document</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Business_Type__c</fullName>
        <label>Document Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Costing</fullName>
                </value>
                <value>
                    <fullName>Branding</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Costing_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Costing Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Financial_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Financial Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_SQT_sheet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is SQT sheet</label>
        <type>Checkbox</type>
    </fields>
    <label>BnP Finance Quote Document</label>
    <nameField>
        <label>File Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BnP Finance Quote Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Information__c.object
<CustomObject>
    <description>Custom object defining detail of Request for Quote and Request for Information.</description>
    <fields>
        <fullName>Access_Preferred_Fab_Location_Table__c</fullName>
        <inlineHelpText>Provide the Access Preferred Fab Location Table Info</inlineHelpText>
        <label>Access Preferred Fab Location Table</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Sizing_Spreadsheet_Template__c</fullName>
        <formula>IF( ISPICKVAL(Customer_Requirement__r.Opportunity__r.Product_Line__c, &apos;ASIC&apos;) , HYPERLINK(&apos;https://globalfoundries--c.ap4.visual.force.com/apex/VFTeamRoomDetail?id=a0J6F00000xAxfQUAS&apos;, &apos;SQT Sheet&apos; ,&apos;_blank&apos;) , &apos;Available only for ASIC&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reference To Sizing Spreadsheet Template</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Backup_Request_Catcher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Request Catcher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Request_Information1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_preferred_Wafer_Fab_from_FMS__c</fullName>
        <inlineHelpText>Provide  the Client preferred Wafer Fab from FMS</inlineHelpText>
        <label>Client preferred Wafer Fab from FMS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Request__c</fullName>
        <label>Date of Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>If_other_please_specify__c</fullName>
        <inlineHelpText>If other, please specify</inlineHelpText>
        <label>If other, please specify</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Request_Catcher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>»Primary Request Catcher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Request_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Status__c</fullName>
        <inlineHelpText>Select the  the Quote Status</inlineHelpText>
        <label>»Quote Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFQ_Request_Number__c</fullName>
        <displayFormat>RFQ{00000000}</displayFormat>
        <label>RFQ Request Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_comments__c</fullName>
        <inlineHelpText>Provide the Request comments</inlineHelpText>
        <label>Request comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_status__c</fullName>
        <inlineHelpText>Select the Status Request</inlineHelpText>
        <label>Request status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_position_due_date__c</fullName>
        <label>Support position due date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Wafer_Fab_sourcing_location__c</fullName>
        <inlineHelpText>Select the Wafer Fab Sourcing Location</inlineHelpText>
        <label>Wafer Fab Sourcing Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Altis (200mm)</fullName>
                </value>
                <value>
                    <fullName>B323 (EFK) (300mm)</fullName>
                </value>
                <value>
                    <fullName>BTV (200mm)</fullName>
                </value>
                <value>
                    <fullName>GFFAB1DRS (300mm)</fullName>
                </value>
                <value>
                    <fullName>GFFAB2SGP (200mm)</fullName>
                </value>
                <value>
                    <fullName>GFFAB6SGP (200mm)</fullName>
                </value>
                <value>
                    <fullName>GFFAB7SGP (300mm)</fullName>
                </value>
                <value>
                    <fullName>GFFAB8MLT (300mm)</fullName>
                </value>
                <value>
                    <fullName>SAMSUNG (300mm)</fullName>
                </value>
                <value>
                    <fullName>SMIC (300mm)</fullName>
                </value>
                <value>
                    <fullName>SONY (300mm)</fullName>
                </value>
                <value>
                    <fullName>Supplied by client - 200mm (200mm)</fullName>
                </value>
                <value>
                    <fullName>Supplied by client - 300mm (300mm)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Information</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Information</pluralLabel>
    <recordTypes>
        <fullName>SR</fullName>
        <active>false</active>
        <label>Service Request (SR)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BnPRFQSRReadOnlyCtrl.cls
/*
Type Name: BnPRFQSRReadOnlyCtrl
Author: Poulami Saha
Project Name: DIW Step Down Track 2 (BnP) 
Created Date: 10/01/2017
Description: This class is call from 'Create SR' button on Decision page.
Test Class: 
Change History:Changed the query criteria to fetch BnP Finance quote Document records
*/
public class BnPRFQSRReadOnlyCtrl {
    public Request_Information__c rfqRecord { get; set; }
    //String reqInfoId;
    
    //Public attachment objAttachment{get; set;}
    Public List<attachment> finAttachList{get; set;}
    //Public Request_Information__c objApplicant{get; set;}
    Public BnP_Finance_Quote_Document__c bnpFinDoc{get; set;}
    Public transient List<BnP_Finance_Quote_Document__c> bnpFinanDocList{get; set;}
    Public List<Id> bnbFinDocIdList = new List<Id>();
    Public List<MyWrapper> wrapperList {get; set;}
    Public String rfqId {get; set;}
    
    public BnPRFQSRReadOnlyCtrl(ApexPages.StandardController ctrl) {
        rfqRecord = (Request_Information__c)ctrl.getRecord();
        
        rfqId = ApexPages.currentPage().getParameters().get('RFQId');
        
        if(rfqId == null || rfqId == '') 
            rfqId = rfqRecord.id;
            
        rfqRecord = queryRFQ(rfqId);
    }
    
    public Request_Information__c queryRFQ(String rfqId) {
        return [SELECT id, name, RFQ_Request_Number__c, Access_Preferred_Fab_Location_Table__c, Request_Type__c, Wafer_Fab_sourcing_location__c, Client_preferred_Wafer_Fab_from_FMS__c, If_other_please_specify__c, Date_of_Request__c, Support_position_due_date__c, Backup_Request_Catcher__c, Primary_Request_Catcher__c, Request_comments__c, Request_status__c, Quote_Status__c, Access_Sizing_Spreadsheet_Template__c FROM Request_Information__c where id = :rfqId];
    }
    
    /**
    *  The Purpose of this method is to display BnP Finance Quote Document, Attachment 
    *  @name <displatAttachment>
    *  @param <NA> 
    *  @return <Pagereference>
    *  @throws exception-<exception description>
    */
    public pageReference displatAttachment(){
        getwrapperList();
        return null;
    }
    
    /**
    *  The getter method used in the page to display BnP Finance Quote Document, Attachment
    *  @name <getwrapperList>
    *  @param <NA>
    *  @return <List <MyWrapper>>
    *  @throws exception-<exception description>
    */
    Public List <MyWrapper> getwrapperList(){
        wrapperList = new List<MyWrapper>();
        bnpFinanDocList = [Select id, Name, Document_Business_Type__c from BnP_Finance_Quote_Document__c where BnP_Finance_Quote_Document__c = :rfqId and Is_SQT_sheet__c = true and Is_Financial_Document__c = false and Is_Costing_Document__c = false];
        
        for(BnP_Finance_Quote_Document__c bnpFinDoc : bnpFinanDocList){
            bnbFinDocIdList.add(bnpFinDoc.id);
        }
        finAttachList = [Select id, Name, ContentType, BodyLength, Description, ParentId from attachment where ParentId IN :bnbFinDocIdList];
        
        for(BnP_Finance_Quote_Document__c bnpFinDoc : bnpFinanDocList){
            for(Attachment attFile : finAttachList){
                if(bnpFinDoc.id == attFile.ParentId){
                        MyWrapper myWrap = new MyWrapper();
                        System.debug('Inside if');
                        myWrap.attRec = attFile;
                        myWrap.bnpSQTSheetRec = bnpFinDoc;
                        wrapperList.add(myWrap);
                        
                }
            }
        }
        return wrapperList;
    }
    
    /**
    @name <MyWrapper>
    @Description <This class is handle mutliple object instances>
    @Version <>
    @reference <>
    */
    public class MyWrapper
    {
        public Attachment attRec {get; set;}
        public BnP_Finance_Quote_Document__c bnpSQTSheetRec {get; set;}
       
    }
}