objects/Bug_Team__c.object
<CustomObject>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bug__c</fullName>
        <label>Bug</label>
        <referenceTo>Bug__c</referenceTo>
        <relationshipLabel>Bug Teams</relationshipLabel>
        <relationshipName>Bug_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <label>Group ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Group Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bug_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bug Team</label>
    <nameField>
        <displayFormat>BTM-{0000000000}</displayFormat>
        <label>Bug Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bug Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CSforDefaultownerandteam__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Bug_BugTeam__c</fullName>
        <label>Bug BugTeam</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bug_Component__c</fullName>
        <label>Bug Component</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bug_Owner__c</fullName>
        <label>Bug Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_affected__c</fullName>
        <label>Product affected</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CSforDefaultownerandteam</label>
</CustomObject>

objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BugTeamMemberTest.cls
/*Author: Karthick D
 * Description: Test Class for Bug Team Trigger and Bug Manage Members controller (BugManageMembersCtrlExt)
 * History:
 */

@isTest(SeeAllData = false)
public class BugTeamMemberTest {
    public static testMethod void testBugTeam() {
        Test.startTest();
        //Test data creation 
        list < CSforDefaultownerandteam__c > clist = new list < CSforDefaultownerandteam__c > ();
        CSforDefaultownerandteam__c c = new CSforDefaultownerandteam__c();
        c.Name = 'cc1';
        c.Product_affected__c = 'CAD Environment';
        c.Bug_Component__c = 'Documentation';
        c.Bug_Owner__c = Userinfo.getUserId();

        c.Bug_BugTeam__c = Userinfo.getUserId();
        clist.add(c);
        insert clist;

        bug__c bteamtest = new bug__c();
        bteamtest.Bug_Title__c = 'test zzzz';
        bteamtest.Product_technology__c = 'CAD Environment';
        bteamtest.Component__c = 'Documentation';
        insert bteamtest;

        bug__c b = new bug__c();
        b.Bug_Title__c = 'test zzzz';
        b.Product_technology__c = 'CAD Environment';
        b.Component__c = 'Documentation';
        insert b;

        b = [select id, name from bug__c where id = : b.id][0];

        bug__c b1 = new bug__c();
        b1.Bug_Title__c = 'test zzzz';
        b1.Product_technology__c = 'CAD Environment';
        b1.Component__c = 'Documentation';
        insert b1;
        //Test data creation ends

        PageReference pageRef = new PageReference('/apex/BugManageMember?id=' + b.id);
        Test.setCurrentPage(pageRef);
        BugManageMembersCtrlExt BugManageMembersCtrlExtVar = new BugManageMembersCtrlExt();
        BugManageMembersCtrlExtVar.BugRoom = b;

        pageRef = new PageReference('/apex/BugManageMember?id=' + b.id);
        Test.setCurrentPage(pageRef);
        BugManageMembersCtrlExtVar = new BugManageMembersCtrlExt();
        BugManageMembersCtrlExtVar.BugRoom = b;
        BugManageMembersCtrlExtVar.addNewRow();
        Bug_Team__c bgteam = new bug_Team__c();
        Bug_Team__c bgteam1 = new bug_Team__c();
        Bug_Team__c bgteam2 = new bug_Team__c();
        Bug_Team__c bgteam3 = new bug_Team__c();

        bgteam1.Is_Group__c = false;
        bgteam1.Access__c = 'Read';
        bgteam1.user__c = null;
        bgteam1.bug__c = b.id;

        bgteam.Is_Group__c = false;
        bgteam.Access__c = null;
        bgteam.user__c = userinfo.getUserId();
        bgteam.bug__c = b.id;

        bgteam2.Is_Group__c = false;
        bgteam2.Access__c = 'Read';
        bgteam2.user__c = userinfo.getUserId();
        bgteam2.bug__c = b.id;

        bgteam3.Is_Group__c = false;
        bgteam3.Access__c = 'Read';
        bgteam3.user__c = userinfo.getUserId();
        bgteam3.bug__c = b.id;
        BugManageMembersCtrlExtVar.members = new list < bug_team__c > ();
        BugManageMembersCtrlExtVar.members.add(bgteam);
        BugManageMembersCtrlExtVar.Save();

        BugManageMembersCtrlExtVar.members = new list < bug_team__c > ();
        BugManageMembersCtrlExtVar.members.add(bgteam1);
        BugManageMembersCtrlExtVar.Save();

        delete[select id from bug_team__c where bug__c = : b.id];
        BugManageMembersCtrlExtVar.sTeamMember = new Set < String > ();
        BugManageMembersCtrlExtVar.members = new list < bug_team__c > ();
        BugManageMembersCtrlExtVar.members.add(bgteam2);
        BugManageMembersCtrlExtVar.Save();

        BugManageMembersCtrlExtVar.members = new list < bug_team__c > ();
        BugManageMembersCtrlExtVar.members.add(bgteam3);
        BugManageMembersCtrlExtVar.Save();

        BugManageMembersCtrlExtVar.deleteMember();

        pageRef = Page.BugTeamMembers;
        Test.setCurrentPage(pageRef);
        Apexpages.StandardController controller = new Apexpages.StandardController(bteamtest);
        BugTeamMembersControllerExt BugTeamMembersControllerExtVar = new BugTeamMembersControllerExt(controller);
        BugTeamMembersControllerExtVar.getTeamRoom();
        BugTeamMembersControllerExtVar.getTeamMembers();
        BugTeamMembersControllerExtVar.getAllTeamMembers();
        BugTeamMembersControllerExtVar.deleteMember();

        //Delete the bug team members of the bug.
        list < Bug_Team__c > bgshare = [SELECT Id, User__c, User__r.Name, User__r.ProfileId, User__r.UserRoleId, Access__c, Is_Group__c, Group_Selected__c, Group_ID__c, Group_Name__c
        FROM Bug_Team__c WHERE Bug__c = : b1.id];
        system.debug('bgushareeee' + Bgshare);
        delete[SELECT Id, User__c, User__r.Name, User__r.ProfileId, User__r.UserRoleId, Access__c, Is_Group__c, Group_Selected__c, Group_ID__c, Group_Name__c
        FROM Bug_Team__c WHERE Bug__c = : b1.id];
        Test.stopTest();
    }
}