objects/CaseAssignmentRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will hold the Category values where custom assignment process is not applicable.</description>
    <label>Case Assignment Rules</label>
</CustomObject>

objects/CasePermissions__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Setting will hold customer cases related permission for Case Comments. Profile &amp; Users User License equals to Salesforce only. Permission is not applicable for Non Salesforce license type.</description>
    <fields>
        <fullName>InternalCaseOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Case Permitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PublicCommentPermitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value will be checked if public comment applicable.</description>
        <label>Public Comment Permitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Permissions</label>
</CustomObject>

classes/CaseDataUtilTest.cls
/*
Author: Cognizant Case Management Team
Description: The purpose of this test utility class is to load/create generic records for test class execution related to Case
History:
 
*/
@isTest(SeeAllData = false)
public class CaseDataUtilTest{

     public static void loadCustomSettingVariables() {
     
        /********* Custom setting Insert ************/
        
        CasePermissions__c settings = CasePermissions__c.getInstance();
        settings = new CasePermissions__c();
        settings.PublicCommentPermitted__c = true;
        settings.InternalCaseOnly__c = true;
           
        insert settings;
        
        /********* CaseAssignmentRules__c Custom setting Insert ************/
        
        CaseAssignmentRules__c setting1 = new CaseAssignmentRules__c();
        setting1.Name = 'Tape Out';
        insert setting1;
        
        CaseAssignmentRules__c setting2 = new CaseAssignmentRules__c();
        setting2.Name = 'Tapeout';
        insert setting2;
        
     }    
    
}