objects/Charge_Info__c.object
<CustomObject>
    <description>Represents a functional reason for billing purposes for an Option.</description>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>&gt;&gt;Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Type__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>&gt;&gt;Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer PO Number</fullName>
                </value>
                <value>
                    <fullName>ICA Number</fullName>
                </value>
                <value>
                    <fullName>IPT Number</fullName>
                </value>
                <value>
                    <fullName>Marketing Area Number</fullName>
                </value>
                <value>
                    <fullName>Commitment Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Option__c</fullName>
        <label>&gt;&gt;Option</label>
        <referenceTo>Customer_Requirement__c</referenceTo>
        <relationshipLabel>Charge Info</relationshipLabel>
        <relationshipName>Charge_Info</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAP_Mask_Order__c</fullName>
        <label>&gt;&gt;SAP Mask Order#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DIW Charge Info</label>
    <nameField>
        <displayFormat>CH-{000000}</displayFormat>
        <label>Charge Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SAP_Order_Detail__c.object
<CustomObject>
    <description>Represents a billing entry in a Option life cycle for the specific functional reason/milestone</description>
    <fields>
        <fullName>Charge_Info__c</fullName>
        <label>Charge Info</label>
        <referenceTo>Charge_Info__c</referenceTo>
        <relationshipLabel>SAP Order Details</relationshipLabel>
        <relationshipName>SAP_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Follow - on</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Services - First Time Proto NRE Build</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Order_Number__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>SAP Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_SoldTo__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>SAP SoldTo #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Yield_Mngmnt_Data_Deliveryto__c</fullName>
        <inlineHelpText>Please complete &gt;&gt;fields to promote Option to Reconciliation</inlineHelpText>
        <label>Yield Mngmnt Data Deliveryto #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DIW Order Detail</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>SAP Order Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tech_Review_Summary__c.object
<CustomObject>
    <description>This is an application to be used for reconciliation of Option technical details post Design Win</description>
    <fields>
        <fullName>Charge_Number__c</fullName>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option</label>
        <referenceTo>Customer_Requirement__c</referenceTo>
        <relationshipLabel>Tech Reviews</relationshipLabel>
        <relationshipName>Tech_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tech Review</label>
    <nameField>
        <displayFormat>TR-{YYYY}-{MM}-{0000}</displayFormat>
        <label>Tech Review #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tech Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TechReview_ChargeOrderDetailUtility.cls
public with sharing class TechReview_ChargeOrderDetailUtility
{
    public Id OptionId {get; set;}
    public TechReview_ChargeOrderDetailUtility()
    {
        
    }
    
    public WrapperCls getDetailInformation()
    {
        WrapperCls objwrapperCls = new WrapperCls();
        if(OptionId != null)
        {
            Tech_Review_Summary__c TRS = new Tech_Review_Summary__c();
            TRS = [Select Option__c, Id from Tech_Review_Summary__c where Id =: OptionId];          
            //Get charge info related to option
            List<Charge_Info__c> chargeInfoList = [select Charge_Number__c, Charge_Type__c, Option__c, SAP_Mask_Order__c
                      from Charge_Info__c where Option__c = : TRS.Option__c Limit 1];
            
            if(chargeInfoList != null && chargeInfoList.size() > 0)
            {
                objwrapperCls.objChargeInfo = chargeInfoList[0];    
                // query sap order details related to charge info
                List<SAP_Order_Detail__c> SapOrderList = new List<SAP_Order_Detail__c>();
                SapOrderList = [Select Id,Name, Charge_Info__c, Order_Type__c, SAP_Order_Number__c, SAP_SoldTo__c, Yield_Mngmnt_Data_Deliveryto__c 
                             from SAP_Order_Detail__c where Charge_Info__c = :chargeInfoList[0].id];
                if(SapOrderList != null && SapOrderList.size() > 0)
                {
                    objwrapperCls.objOrderDetails = SapOrderList;
                }
            }
        }
        return objwrapperCls;
    }
   /**
   @name <WrapperCls>
   @Description <This class is handle mutliple object instances>
   @Version <>
   @reference <>
  */
    public class WrapperCls
    {
        public Charge_Info__c objChargeInfo{private set;get;}
        public List<SAP_Order_Detail__c> objOrderDetails{private set;get;}
    }
}