objects/Checklist_Container__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipName>Tasks_Containers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <formula>IF ( Parent__c = &quot;&quot;, 0 , 
IF ( Parent__r.Parent__c = &quot;&quot;, 1, 
IF ( Parent__r.Parent__r.Parent__c = &quot;&quot;, 2, 
IF (Parent__r.Parent__r.Parent__r.Parent__c = &quot;&quot;, 3, 
IF (Parent__r.Parent__r.Parent__r.Parent__r.Parent__c = &quot;&quot;, 4, 
IF (Parent__r.Parent__r.Parent__r.Parent__r.Parent__r.Parent__c = &quot;&quot;, 5, 
IF (Parent__r.Parent__r.Parent__r.Parent__r.Parent__r.Parent__r.Parent__c = &quot;&quot;, 6, 7)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hierarchy Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Tasks_Containers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Checklist Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This field is used by the batch job that computes for adjustment between device forecast and quarterly revenue.</description>
        <formula>CASESAFEID(Opportunity_Program__r.Opportunity__c)</formula>
        <inlineHelpText>The Opportunity under which the Device resides</inlineHelpText>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <recordTypes>
        <fullName>Device</fullName>
        <active>true</active>
        <description>Unsorted Wafer Device</description>
        <label>Device</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DeviceChecklistOpptyCtrlExt.cls
/*Author: Sreedhar Karukonda
    Description: This is a Controller Extension class for Opportunity object used in DeviceChecklistOpptyReportView Page.
    This page displays Opportunity related to Device Checklists statistics 
    
    History:
    Created     -     Sreedhar   -     05/14/2014     - code creation.
    Updated     -     Sreedhar   -     10/02/2014 - Removed TASKRAY Application Objects Dependency
*/
public without sharing class DeviceChecklistOpptyCtrlExt {
    public Opportunity opp {get; set;}  

    /*
    * Constructor as Opprtunity Statndard Controller Extension
    */
    public DeviceChecklistOpptyCtrlExt(ApexPages.StandardController stdController){
        this.opp = (Opportunity)stdController.getRecord();
    }

    /*
    * This holds reference to Report utility object
    */
    public DeviceChecklistReportsCtrlExt reportUtil {
        get{
            if(reportUtil == null) reportUtil = new DeviceChecklistReportsCtrlExt(null, this.opp.id);
            return reportUtil;
        }
        set;
    }

    /*
    * This Method calculates Opportunity related Checklists' statistics.
    */
    public List<DeviceChecklistReportsCtrlExt.ThisProjectStatus> getOpportunityChecklistsStatus(){
      return reportUtil.getOpportunityChecklistsStatus(opp.id);
    }

    /*
    *  This varibale holds reference to all device Checklist related to Opportunity.
    */
    public Map<id, Checklist_Container__c> allOpportunityDeviceChecklists{
        get{
            if(allOpportunityDeviceChecklists == null) {
                //allOpportunityDeviceChecklists = new Map<id, Checklist_Container__c>();
                allOpportunityDeviceChecklists = new Map<id, Checklist_Container__c>([select id, Name, Device__r.Name from Checklist_Container__c where 
                        Opportunity__c =: opp.id and Hierarchy_Level__c = 0 and Device__c != null]);
            }
            return allOpportunityDeviceChecklists;
        }
        set;
    }
}