objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Accepted_TC_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accepted T&amp;C Version</label>
        <referenceTo>Community_TC__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Comm_TC_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Cognizant (FV 2.0):This field denotes whether the contact has accepted the latest community terms &amp; conditions.</description>
        <label>Is Latest Community T&amp;C Accepted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clsCommunityTCAcceptedUpdateOnContact.cls
/*
Type Name: clsCommunityTCAcceptedUpdateOnContact
Company Name: Cognizant 
Created Date: 15-Oct-2014
Reason: Case 35076 -This Class is created to resolve the soql limit issue while creating community terms and condition record
Change History:
Author: Sunita Char
Modified Date: 
Reason: 
……..
……..
*/

public class clsCommunityTCAcceptedUpdateOnContact
{ 
  @future
     public static void updateCheckbox(Set<Id> contactId)
      {
      
      List<Contact> contactList=[select id,Accepted_TC_Version__c,Is_Comm_TC_Accepted__c from Contact where id In:contactId];
      List<Contact> contactUpdateList = new List<Contact>();
      try
       {
           if(contactList!=null && !(contactList.isEmpty()))
           {
              for(Contact cont: contactList)
              {
               cont.Is_Comm_TC_Accepted__c =false;
               contactUpdateList.add(cont);
              }
            }  
              
                   if(contactUpdateList!=null && !(contactUpdateList.isEmpty()))
                  {
                  update contactUpdateList;
                  }
        }
          catch(Exception e)
          {
           System.debug('An exception occurred: ' + e.getMessage());
          }
      }

}