objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MPW_Prime_Die__c.object
<CustomObject>
    <description>Prime Die MPW reservation by Customer</description>
    <fields>
        <fullName>Customer_Tapeout_Date__c</fullName>
        <formula>MPW_Form__r.Customer_Tapeout_Date__c</formula>
        <label>Customer Tapeout Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Qty_Die_Form__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <inlineHelpText>In multiple of 50 dies</inlineHelpText>
        <label>Delivery Qty Die Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fab_ID__c</fullName>
        <formula>MPW_Form__r.MPW_Train_Name__r.Fab__c</formula>
        <label>Fab_ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <formula>MPW_Form__r.Geometry_ID__c</formula>
        <label>Geometry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPW_Form__c</fullName>
        <label>MPW Form#</label>
        <referenceTo>MPW_Reservation__c</referenceTo>
        <relationshipLabel>MPW Prime Dies</relationshipLabel>
        <relationshipName>MPW_Prime_Dies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prime_Die_Name__c</fullName>
        <externalId>true</externalId>
        <label>Prime Die Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <formula>MPW_Form__r.Sales_Order__c</formula>
        <label>Sales Order</label>
        <type>Text</type>
    </fields>
    <label>MPW Prime Die</label>
    <nameField>
        <displayFormat>PD{0000000}</displayFormat>
        <label>MPW Prime Die</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPW Prime Dies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MPW_Reservation__c.object
<CustomObject>
    <label>MPW Reservation</label>
    <nameField>
        <label>FORM ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPW Reservations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/MPW_WIP_Lot__c.object
<CustomObject>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <formula>Manufacturing_Lot__r.Active_Flag__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bare_Die_Shipment_Forecast_Date_BL__c</fullName>
        <description>Bare Die Shipment Forecast Date (Base Line)</description>
        <formula>IF( 
	AND(NOT(ISNULL(Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c)), NOT(ISNULL(TEXT(Manufacturing_Lot__r.Fab_Group__c))), NOT(ISBLANK(Delivery_Qty_Die_Form__c))), 
	IF( 
		TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 1&apos;,  
		Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c + 14, 
		IF( 
			OR(TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 2&apos;, TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 3&apos;, TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 3E&apos;, TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 5&apos;, TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 6&apos;, TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 7&apos; ), 
			Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c + 10, 
			IF( 
				TEXT(Manufacturing_Lot__r.Fab_Group__c) == &apos;FAB 8&apos;, 
				Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c + 14, 
				NULL
			)
		) 
	),
	NULL
)</formula>
        <inlineHelpText>Bare Die Shipment Forecast Date (Base Line)</inlineHelpText>
        <label>Bare Die Shipment Forecast Date (BL)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bare_Die_Shipment_Forecast_Date_OR__c</fullName>
        <description>Bare Die Shipment Forecast Date (Override)</description>
        <inlineHelpText>Bare Die Shipment Forecast Date (Override)</inlineHelpText>
        <label>Bare Die Shipment Forecast Date (OR)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Lot_Location__c</fullName>
        <formula>Manufacturing_Lot__r.Current_Lot_Location__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Lot Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Mask_Layer__c</fullName>
        <formula>TEXT( Manufacturing_Lot__r.Current_Mask_Layer_Being_Processed__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Mask Layer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Scheduled_Date_CSD_OR__c</fullName>
        <description>Override CSD for MPW WIP Lot report for customer.</description>
        <label>Current Scheduled Date (OR)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Scheduled_Date_CSD__c</fullName>
        <formula>Manufacturing_Lot__r.Current_Scheduled_Date_CSD__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Scheduled Date(CSD)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Tapeout_Date__c</fullName>
        <formula>MPW_Prime_Die__r.Customer_Tapeout_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Tapeout Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Qty_Die_Form__c</fullName>
        <formula>IF( OR(ISNULL(MPW_Prime_Die__r.Delivery_Qty_Die_Form__c), ISBLANK(MPW_Prime_Die__r.Delivery_Qty_Die_Form__c),  TRIM(MPW_Prime_Die__r.Delivery_Qty_Die_Form__c) == &apos;0&apos; ) , &apos;&apos;, MPW_Prime_Die__r.Delivery_Qty_Die_Form__c)</formula>
        <label>Delivery Qty Die Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <formula>MPW_Prime_Die__r.Geometry__c</formula>
        <label>Geometry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot_Last_Modified_Date__c</fullName>
        <formula>Manufacturing_Lot__r.LastModifiedDate</formula>
        <label>Lot Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lot_State__c</fullName>
        <formula>TEXT( Manufacturing_Lot__r.Lot_State__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lot State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPW_Form_Customer_Account_Name__c</fullName>
        <formula>MPW_Prime_Die__r.Account_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MPW Form Customer Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPW_Prime_Die__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPW Prime Die</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MPW_Prime_Die__c.MPW_Form__r.Form_Status__c</field>
                <operation>equals</operation>
                <value>Accepted by MPW Tapeout</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MPW_Prime_Die__c</referenceTo>
        <relationshipLabel>MPW WIP Lot</relationshipLabel>
        <relationshipName>MPW_WIP_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MPW_Train_Name__c</fullName>
        <formula>MPW_Prime_Die__r.MPW_Train__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MPW Train Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPW_form__c</fullName>
        <formula>MPW_Prime_Die__r.MPW_Form__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MPW form#</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Lot_Id__c</fullName>
        <formula>Manufacturing_Lot__r.Manufacturing_Lot_Id__c</formula>
        <label>Manufacturing Lot Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Die_Name__c</fullName>
        <formula>MPW_Prime_Die__r.Prime_Die_Name__c</formula>
        <label>Prime Die Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Mask_Count__c</fullName>
        <formula>TEXT( Manufacturing_Lot__r.Remaining_Mask_Count__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Mask Count</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <formula>MPW_Prime_Die__r.MPW_Form__r.Sales_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <formula>Manufacturing_Lot__r.Stage_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology_Type__c</fullName>
        <formula>TEXT( Manufacturing_Lot__r.Technology_Type__c )</formula>
        <label>Technology Type</label>
        <type>Text</type>
    </fields>
    <label>MPW WIP Lot</label>
    <nameField>
        <displayFormat>MPWLOT-{00000}</displayFormat>
        <label>MPW WIP Lot No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPW WIP Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MPWCustomerWIPExcelController.cls
/**
* Author: Anil Kumar
* Company: JK Technosoft
* Project: MPW
* Description: Used to download Prime Die Assignment of Customer in Excel format
* History:
*    Anil Kumar 08/07/2016 - Created
**/
public without sharing class MPWCustomerWIPExcelController {

    public transient List<MPW_WIP_Lot__c> lstAssignments    {get; set;}
    public Date dtFromDate                                  {get; set;}
    public Date dtToDate                                    {get; set;}
    
    public MPWCustomerWIPExcelController(){
        lstAssignments = new List<MPW_WIP_Lot__c>();
        retrieveMPWAssignments();
    }
    
    /*
    * Description : Method to retrieve Manufacturing Lot Assignment based on logged in user.
    */
    private void retrieveMPWAssignments() {
        lstAssignments = new List<MPW_WIP_Lot__c>();
        String strAccountId = '';
        
        //Kanishk:1bf6628702622c8 parm is internal use only . request comes from Batch class to attach this report in email 
        String strUserName = ApexPages.currentPage().getParameters().get('1bf6628702622c8');
        
        User objLoggedInUser =null;
        if(strUserName!=null && strUserName!=''){
        	objLoggedInUser=[SELECT Id, Name, Email, Username FROM User WHERE Username =: strUserName];
        }else{
        	objLoggedInUser=[SELECT Id, Name, Email, Username FROM User WHERE Id =: UserInfo.getUserId()];
        }
         
        
        for(Contact objContact : [SELECT Id, User_Name__c, AccountId FROM Contact WHERE User_Name__c =: objLoggedInUser.Username LIMIT 1]) {
            strAccountId = objContact.AccountId;
        }
        
        String strQuery = 'SELECT Id, Name, Prime_Die_Name__c, Sales_Order__c, Geometry__c, Customer_Tapeout_Date__c, MPW_Train_Name__c, ';
        strQuery += 'MPW_Form_Customer_Account_Name__c, MPW_form__c, Current_Scheduled_Date_CSD__c, Current_Scheduled_Date_CSD_OR__c, ';
        strQuery += 'Current_Mask_Layer__c, Remaining_Mask_Count__c, Current_Lot_Location__c, Lot_Last_Modified_Date__c, Lot_State__c, ';
        strQuery += 'Stage_Name__c, Technology_Type__c, Active_Flag__c, Bare_Die_Shipment_Forecast_Date_BL__c, ';
        strQuery += 'Bare_Die_Shipment_Forecast_Date_OR__c, Delivery_Qty_Die_Form__c, MPW_Prime_Die__r.Fab_ID__c ';
        strQuery += 'FROM MPW_WIP_Lot__c WHERE MPW_Prime_Die__r.MPW_Form__r.Customer_Company_Name__c =: strAccountId AND Active_Flag__c = TRUE  ';
        
        String strFromDate = ApexPages.currentPage().getParameters().get('fromDt');
        String strToDate = ApexPages.currentPage().getParameters().get('toDt');
        
        try {
            if(strFromDate != null && strFromDate.trim() != '' && strFromDate.split('-').size() == 3) {
                dtFromDate = date.valueOf(strFromDate);
                strQuery += ' AND Customer_Tapeout_Date__c >=: dtFromDate ';
            }
            
            if(strToDate != null && strToDate.trim() != '' && strToDate.split('-').size() == 3) {
                dtToDate = date.valueOf(strToDate);
                strQuery += ' AND Customer_Tapeout_Date__c <=: dtToDate ';
            }
            
            strQuery += ' ORDER BY Manufacturing_Lot_Id__c NULLS LAST LIMIT 10000';
        
            for(MPW_WIP_Lot__c oMWL : database.query(strQuery)) {
                lstAssignments.add(oMWL);
            }
        }
        catch(exception ex) {       
            MPWExceptionHandler.exceptionHandler(ex, MPWCustomerWIPExcelController.class.getName(), 'retrieveMPWAssignments()', '', 'My MPW WIP Excel');
        }
    }
}