objects/CPQ_MLGPLUS__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_Type__c</fullName>
        <label>Catalog Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Source</fullName>
                </value>
                <value>
                    <fullName>Multi Source</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0.003UM</fullName>
                </value>
                <value>
                    <fullName>0.006UM</fullName>
                </value>
                <value>
                    <fullName>0.007UM</fullName>
                </value>
                <value>
                    <fullName>0.010UM</fullName>
                </value>
                <value>
                    <fullName>0.012UM</fullName>
                </value>
                <value>
                    <fullName>0.014UM</fullName>
                </value>
                <value>
                    <fullName>0.020UM</fullName>
                </value>
                <value>
                    <fullName>0.022UM</fullName>
                </value>
                <value>
                    <fullName>0.028UM</fullName>
                </value>
                <value>
                    <fullName>0.032UM</fullName>
                </value>
                <value>
                    <fullName>0.035UM</fullName>
                </value>
                <value>
                    <fullName>0.040UM</fullName>
                </value>
                <value>
                    <fullName>0.045UM</fullName>
                </value>
                <value>
                    <fullName>0.055UM</fullName>
                </value>
                <value>
                    <fullName>0.065UM</fullName>
                </value>
                <value>
                    <fullName>0.090UM</fullName>
                </value>
                <value>
                    <fullName>0.13UM</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>0.18UM</fullName>
                </value>
                <value>
                    <fullName>0.25UM</fullName>
                </value>
                <value>
                    <fullName>0.35UM</fullName>
                </value>
                <value>
                    <fullName>0.6UM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_Technology__c</fullName>
        <description>Process Technology Number</description>
        <label>Process Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Pending Maintenance Jobs</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Ready to Load</fullName>
                </value>
                <value>
                    <fullName>Under Process</fullName>
                </value>
                <value>
                    <fullName>Unprocessed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CPQ MLGPLUS</label>
    <nameField>
        <displayFormat>MLG-{00000000}</displayFormat>
        <label>CPQ MLGPLUS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQ MLGPLUS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Process_Technology__c.object
<CustomObject>
    <label>Process Technology</label>
    <nameField>
        <label>Process Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Technologies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CPQMLGPLUSEmailServiceTest.cls
/*
    Author: Anirban Roy
    Description: This is the test class for CPQReportBackupController.
    History: 
        ARoy     05062015    - Code creation.
*/

@istest(SeeAllData=false)
public class CPQMLGPLUSEmailServiceTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    // Test method for CPQ Email Service With no existing record
    static testMethod void CPQEmailServiceTestWithNoExistRec(){
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        // setup the data for the email  
        email.subject = 'PT00001|test mail';
        email.fromAddress = 'someaddress@globalfoundries.com';
        
        // add an Binary attachment  
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('my attachment text');
        attachment.fileName = 'textfileone.txt';
        attachment.mimeTypeSubType = 'text/plain';
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
        
        CPQMLGPLUSEmailService emailServ = new CPQMLGPLUSEmailService();
        emailServ.handleInboundEmail(email, env);
    }
    
    // Test method for CPQ Email Service With existing record
    static testMethod void CPQEmailServiceTestWithExistRec(){
        
        CPQ_MLGPLUS__c cpqmlgplus = new CPQ_MLGPLUS__c(Catalog_Type__c = 'First Source', Geometry__c = '0.010UM', Status__c = 'Unprocessed', Process_Technology__c = 'PT00002');
        insert cpqmlgplus;
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        // setup the data for the email  
        email.subject = 'PT00002|test mail';
        email.fromAddress = 'someaddress@globalfoundries.com';
        
        // add an Binary attachment  
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('my attachment text');
        attachment.fileName = 'textfileone.txt';
        attachment.mimeTypeSubType = 'text/plain';
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
        
        CPQMLGPLUSEmailService emailServ = new CPQMLGPLUSEmailService();
        emailServ.handleInboundEmail(email, env);
    }
    
    // Test method for CPQ Email Service With email having wrong subject
    static testMethod void CPQEmailServiceTestWithWrongSub(){
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        // setup the data for the email  
        email.subject = 'test mail';
        email.fromAddress = 'someaddress@globalfoundries.com';      
        
        CPQMLGPLUSEmailService emailServ = new CPQMLGPLUSEmailService();
        emailServ.handleInboundEmail(email, env);
    }
    
    // Test method for CPQ Email Service With email having no attachment
    static testMethod void CPQEmailServiceTestWithNoAttach(){
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        // setup the data for the email  
        email.subject = 'PT00002|test mail';
        email.fromAddress = 'someaddress@globalfoundries.com';              
        
        CPQMLGPLUSEmailService emailServ = new CPQMLGPLUSEmailService();
        emailServ.handleInboundEmail(email, env);
    }
    
}