objects/CRMDID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings holds the latest CRMDID base number and should be increase for each only for new device/copied devices and not from a Retrofit/Revision action.</description>
    <label>CRMDID</label>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRMDID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Auto generated by the system using the following format: CDIDAAAAAAA.NN

Where:
- CDID is a prefix (from the generated CDID field)
- AAAAAA is 7 numeric characters. Generation will be sequential starting from the last number from Siebel. (from the generated CDID field)
- NN is version number. Generation will be sequential starting from ‘00’</description>
        <externalId>true</externalId>
        <inlineHelpText>CRM assign Device ID , use as unique ID reference by all systems.
Auto populated by system.</inlineHelpText>
        <label>CRMDID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configurator ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expose_Device_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Expose Device record to customer portal. Beta GFV customer login to GFV to complete the forms. For non-Beta customer during transition, customer still expect to login FV1 to complete the online forms.</description>
        <inlineHelpText>Expose Device record to customer portal. Beta GFV customer login to GFV to complete the forms. For non-Beta customer during transition, customer still expect to login FV1 to complete the online forms.</inlineHelpText>
        <label>Expose Device to Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>Indicate Fab where this device produce</description>
        <inlineHelpText>Indicate Fab where this device produce</inlineHelpText>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IP_Declaration_Form_Count__c</fullName>
        <label>IP Declaration Form Count</label>
        <summaryForeignKey>IP_Declaration_Form__c.Device__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Requested_from_Configuration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator whether IP Declaration Form is initiated from Configuration Page.</description>
        <label>Requested from Configuration</label>
        <type>Checkbox</type>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <recordTypes>
        <fullName>Device</fullName>
        <active>true</active>
        <description>Unsorted Wafer Device</description>
        <label>Device</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/IP_Declaration_Form__c.object
<CustomObject>
    <description>Device Manager&apos;s IP Declaration Form</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Device__r.Account__c</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Configuration</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>IP Declaration Form</relationshipLabel>
        <relationshipName>IP_Declaration_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Device__r.Account__r.Name</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>IP Declaration Form</relationshipLabel>
        <relationshipName>IP_Declaration_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <formula>TEXT(Device__r.Fab__c)</formula>
        <label>Fab</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Status__c</fullName>
        <formula>IF(ISPICKVAL(Status__c,&apos;Undeclared&apos;),&apos;Draft&apos;,Text(Status__c))</formula>
        <label>IP Status</label>
        <type>Text</type>
    </fields>
    <label>IP Declaration Form</label>
    <nameField>
        <displayFormat>IPD{YYYY}{MM}{000000}</displayFormat>
        <label>IP Declaration Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Declaration Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConfigToIPDeclaration.cls
/**********************************************************************************************************************************
Class:         ConfigToIPDeclaration
-----------------------------------------------------------------------------------------------------------------------------------
Author:        Monalisa Mohapatra
Description: <Brief description of the apex class or trigger>
History:
Monalisa     05122014     - Code Creation
***********************************************************************************************************************************/

public class ConfigToIPDeclaration{
    
    public string devId {get;set;}
    public string acntId {get;set;}
    public boolean showExposedDevice {get;set;}
    public boolean showConfig {get;set;}
    public boolean showErrorMessage {get;set;}
    public boolean showIPForm {get;set;}
    public Apttus_Proposal__Proposal__c config {get;set;}
    public Device__c device {get;set;}
    public IP_Declaration_Form__c IpForm {get;set;}
    
    public ConfigToIPDeclaration() {    
        this.config = new Apttus_Proposal__Proposal__c();
        this.config = [SELECT Id
                        , Apttus_Proposal__Account__c
                        , Apttus_Proposal__Opportunity__c
                        , Apttus_Proposal__Proposal_Name__c
                        , Device__c
                        , Name
                        , APTPS_Primary__c   
                        , Apttus_Proposal__Approval_Stage__c
                            
                        FROM        Apttus_Proposal__Proposal__c
                        WHERE       Id = :ApexPages.currentPage().getParameters().get('proposalId')
                        LIMIT 1
                    ];
        
        showConfig = true;
        devId = this.config.Device__c;
        
        if(devId!= null){
            retriveDevice();
        }else{
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please associate a device to get IP declaration from customer.'));
                    this.showErrorMessage = true;
                showExposedDevice = true;
                showIPForm = false;
        }
    }
    
    public void retriveDevice(){
        try{
            //Retrieving Device detail
            this.device = new Device__c();
            this.device = [SELECT   Id
                                , Name
                                , CRMDID__c
                                , Account__c
                                , Requested_from_Configuration__c
                                , Expose_Device_to_Customer__c
                                , IP_Declaration_Form_Count__c
                                
                                FROM     Device__c
                                WHERE    Id =: devId
                        ];
            if(this.device != null){
                showExposedDevice = true;
                showErrorMessage =false;
                    if(!this.device.Requested_from_Configuration__c){
                        this.device.Requested_from_Configuration__c = true; 
                    }
                // Retrieving IP Declaration Form 
                
                if(this.device.Expose_Device_to_Customer__c && this.device.IP_Declaration_Form_Count__c==1){
                    this.IpForm = new IP_Declaration_Form__c();
                    this.IpForm = [SELECT   Id
                                            , Name
                                            , Fab__c
                                            , IP_Status__c
                                            , Customer_Name__c
                                            , Device__c
                                            , Configuration__c
                                            FROM     IP_Declaration_Form__c
                                            WHERE    Device__c =: devId];
                    showIPForm = true;              
                }else{
                	if(config.Apttus_Proposal__Approval_Stage__c == 'Draft'){
                		ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please submit/approve the configuration to create IP declaration form for customer.'));
                		showExposedDevice = FALSE; 
                	}
                	else{
                    	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please expose device to create IP declaration form for customer.'));
                	}
                    this.showErrorMessage = true;
                    showIPForm = false;
                }   
            }
            //update this.device;
        }catch (Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
            this.showErrorMessage = true;
        }   
    }
    public PageReference cancel() {
        PageReference pageRef = new PageReference('/' + this.config.Id);
        return pageRef;
    }
    
    /*
    @Method Name:    exposeDeviceToCustomer
    @Return Type:    PageReference 
    @parameter:      NA
    @Reason:         Calling exsisting Expose Device functionality
    @Author:         Prosenjit Saha
    @Created Date:   12092014
    @Change History: ..
                     ..
    */
    public PageReference exposeDeviceToCustomer (){
        update this.device;
        return (new pagereference('/apex/DeviceExposeToCustomerVF?deviceId='+this.device.id));
    }
}