objects/Customer_Satsfaction__c.object
<CustomObject>
    <description>Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
    <fields>
        <fullName>Merit_Index_for_customers__c</fullName>
        <description>Merit Index Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Merit Index for customers</label>
        <referenceTo>Merit__c</referenceTo>
        <relationshipLabel>Customer Satisfaction</relationshipLabel>
        <relationshipName>Customer_Satsfaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Product_Color__c</fullName>
        <inlineHelpText>Amber - Need Attention
Green - On track
Red - Need Immediate Attention</inlineHelpText>
        <label>New Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status_In_Color</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Technology_Color__c</fullName>
        <inlineHelpText>Amber - Need Attention
Green - On track
Red - Need Immediate Attention</inlineHelpText>
        <label>New Technology</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status_In_Color</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter_New__c</fullName>
        <label>Quarter</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
                <value>
                    <fullName>Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Score_Year__c</fullName>
        <description>score year Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Score Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Customer Satisfaction</label>
    <nameField>
        <label>Customer Satisfaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Satisfactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CustomerSatisfaction__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CustomerSatisfaction</label>
</CustomObject>

objects/Next_QBR__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <label>Actual</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area_of_Excellence__c</fullName>
        <label>Area of Excellence</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Satisfaction__c</fullName>
        <label>Customer Satisfaction</label>
        <referenceTo>Customer_Satsfaction__c</referenceTo>
        <relationshipLabel>Next QBRS</relationshipLabel>
        <relationshipName>Next_QBRS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Forecast__c</fullName>
        <description>This is for next quarter forecast</description>
        <label>Forecast</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Next QBR</label>
    <nameField>
        <displayFormat>NQBR-{0000}</displayFormat>
        <label>Next QBR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Next QBRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Status_In_Color.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>RED</fullName>
    </customValue>
    <customValue>
        <fullName>GREEN</fullName>
    </customValue>
    <customValue>
        <fullName>YELLOW</fullName>
    </customValue>
    <masterLabel>Status In Color</masterLabel>
</GlobalValueSet>

classes/CustomerSatisfactionCloneExtentionTest.cls
/*
    Author: Sandesh Singh
    Description: This is the test class for CustomerSatisfactionCloneExtention class 
    History:
        Sandesh 24/10/2017    - code creation.
*/
@isTest(SeeAllData=false)
private class CustomerSatisfactionCloneExtentionTest {

    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    private static Customer_Satsfaction__c getCustomerSat(){
        Map<String,Object> cusSatMap = new Map<String,Object>();
        cusSatMap.put('Quarter_New__c', 'Q2');
        cusSatMap.put('New_Product_Color__c', 'RED');
        cusSatMap.put('New_Technology_Color__c', 'YELLOW');
        /*List<Map<String,Object>> fieldValueMaps = new List<Map<String,Object>>();
        fieldValueMaps.add(cusSatMap);*/
        CustomerSatisfactionDataFactory.createCustomerSatisfaction(cusSatMap);
        
        return [Select Id,Name,Merit_Index_for_customers__c,Quarter_New__c,Score_Year__c
                From Customer_Satsfaction__c LIMIT 1];
    }
    
    private static List<Next_QBR__c> getNextQBR(){
        Map<String,Object> nextQBRs = new Map<String,Object>();
        nextQBRs.put('Customer_Satisfaction__c', getCustomerSat().Id);
        nextQBRs.put('Weight__c', 20);
        List<Map<String,Object>> fieldValueMaps = new List<Map<String,Object>>();
        fieldValueMaps.add(nextQBRs);
        NextQBRDataFactory.getNextQBRs(fieldValueMaps,1);
        
        return [Select Id, Name, Actual__c,Area_of_Excellence__c, Forecast__c, Order__c, Target__c From Next_QBR__c];
    }
    
    static testMethod void testCloneRecord(){
        Customer_Satsfaction__c cus = getCustomerSat();
        List<Next_QBR__c> nextQBRs = getNextQBR();
        ApexPages.StandardController stcontroller = new ApexPages.StandardController(cus);
        CustomerSatisfactionCloneExtention csClone = new CustomerSatisfactionCloneExtention(stcontroller);
        
        csClone.customerSat.Score_Year__c = '2016';
        csClone.customerSat.Quarter_New__c = 'Q3';
        csClone.cloneRecord();
        List<Customer_Satsfaction__c> lstcustSat =[Select Id,Name,Merit_Index_for_customers__c,Quarter_New__c,Score_Year__c
                									From Customer_Satsfaction__c ];
        system.assert(!lstcustSat.isEmpty());
        system.assert(lstcustSat.size()==2);
    }
    static testMethod void testDuplicateCloneRecord(){
       CustomerSatisfaction__c cuSett = new CustomerSatisfaction__c(Name ='Customer_Satisfaction_Clone_Error', 
                                                                     Value__c ='An error occurred while cloning the Parent object. The selected Year and Quarter are existed');
        
		insert cuSett;
        Map<String,Object> cusSatMap = new Map<String,Object>();
        cusSatMap.put('New_Product_Color__c', 'GREEN');
        cusSatMap.put('New_Technology_Color__c', 'RED');
        List<Map<String,Object>> fieldValueMaps = new List<Map<String,Object>>();
        fieldValueMaps.add(cusSatMap);
        List<Customer_Satsfaction__c> satisfacs = new List<Customer_Satsfaction__c>();
        satisfacs = CustomerSatisfactionDataFactory.createCustomerSatisfactions(fieldValueMaps,1);
        
        List<Next_QBR__c> nextQBRs = getNextQBR();
        ApexPages.StandardController stcontroller = new ApexPages.StandardController(satisfacs[0]);
        CustomerSatisfactionCloneExtention csClone = new CustomerSatisfactionCloneExtention(stcontroller);
        
        csClone.customerSat.Score_Year__c = '2016';
        csClone.customerSat.Quarter_New__c = 'Q1';
        csClone.cloneRecord();
        List<Customer_Satsfaction__c> lstcustSat =[Select Id,Name,Merit_Index_for_customers__c,Quarter_New__c,Score_Year__c
                									From Customer_Satsfaction__c ];
        system.assert(!lstcustSat.isEmpty());
        system.assertEquals(2, lstcustSat.size());
        
    }
}