objects/Customer_Satsfaction__c.object
<CustomObject>
    <description>Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
    <fields>
        <fullName>Merit_Index_for_customers__c</fullName>
        <description>Merit Index Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Merit Index for customers</label>
        <referenceTo>Merit__c</referenceTo>
        <relationshipLabel>Customer Satisfaction</relationshipLabel>
        <relationshipName>Customer_Satsfaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Product__c</fullName>
        <defaultValue>0</defaultValue>
        <description>New Product Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>New Product</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Technology__c</fullName>
        <defaultValue>0</defaultValue>
        <description>New Technology Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>New Technology</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q1_Rank__c</fullName>
        <description>Q Rank Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>QBR Rank</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Q1_Score__c</fullName>
        <label>QBR Score</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q1__c</fullName>
        <description>Q Score %  Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>QBR Score %</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter_New__c</fullName>
        <label>Quarter</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
                <value>
                    <fullName>Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Score_Year__c</fullName>
        <description>score year Customer Satisfaction to generate reports based on score per quarter for each customer.</description>
        <label>Score Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Customer Satisfaction</label>
    <nameField>
        <label>Customer Satisfaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Satisfactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CustomerSatisfaction__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CustomerSatisfaction</label>
</CustomObject>

objects/Merit__c.object
<CustomObject>
    <description>Merit index for customer satisfaction value to set for score.</description>
    <fields>
        <fullName>GREEN__c</fullName>
        <description>Merit GREEN Merit index for customer satisfaction value to set for score.</description>
        <label>Merit GREEN(&gt;=)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RED__c</fullName>
        <description>Merit red Merit index for customer satisfaction value to set for score.</description>
        <label>Merit RED(&lt;)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Merit Index for customers</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merit Index for customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CustSatisfaction_SCardControllerTest.cls
/** Author : Ravikiran Nadella 

*  Created Date : 26/10/2017
*  Description : test class for Custom controller class CustSatisfaction_SCardController 
**/

@isTest(SeeAllData=false)
private class CustSatisfaction_SCardControllerTest{
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
        CustomerSatisfaction__c cuSett = new CustomerSatisfaction__c(Name ='Title',  Value__c ='ScoreCard');
        insert cuSett;
        CustomerSatisfaction__c cuSett1 = new CustomerSatisfaction__c(Name ='Displayed Years',  Value__c ='2010,2015');
        insert cuSett1;
        
    }
    
    private static Customer_Satsfaction__c getCustomerSat(String CustomerSatName){
        Map<String,Object> cusSatMap = new Map<String,Object>();
        Customer_Satsfaction__c cs = new Customer_Satsfaction__c();
        cusSatMap.put('New_Technology__c', 10);
        cusSatMap.put('New_Product__c', 12);
        cusSatMap.put('New_Technology__c', 10);
        CustomerSatisfactionDataFactory.createCustomerSatisfaction(new Map<String,Customer_Satsfaction__c>());
        
        return [Select Id,Name,Merit_Index_for_customers__c,Quarter_New__c,Score_Year__c
                From Customer_Satsfaction__c limit 1];
    }
    
    static testMethod void  testLoadData(){
        List<Map<String,Object>> fieldValueMaps = new List<Map<String,Object>>();
       
        Map<String,Object> cusSatMap = new Map<String,Object>();
        cusSatMap.put('New_Product__c', 12);
        cusSatMap.put('New_Technology__c', 10);
        fieldValueMaps.add(cusSatMap);
        
        Map<String,Object> cusSatMap1 = new Map<String,Object>();
        cusSatMap1.put('Quarter_New__c','Q4');
        cusSatMap1.put('Score_Year__c', '2015');
        fieldValueMaps.add(cusSatMap1);
        
        Map<String,Object> cusSatMap2 = new Map<String,Object>();
        cusSatMap2.put('Quarter_New__c', 'Q3');
        cusSatMap2.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap2);
        
        Map<String,Object> cusSatMap3 = new Map<String,Object>();
        cusSatMap3.put('Quarter_New__c', 'Q2');
        cusSatMap3.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap3);
        
        Map<String,Object> cusSatMap4 = new Map<String,Object>();
        cusSatMap4.put('Quarter_New__c', 'Q1');
        cusSatMap4.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap4);
        
        List<Customer_Satsfaction__c> satisfacs = new List<Customer_Satsfaction__c>();
        satisfacs = CustomerSatisfactionDataFactory.createCustomerSatisfactions(fieldValueMaps,5);
        
        Merit__c mrt = new Merit__c (id=satisfacs[0].Merit_Index_for_customers__c);
        mrt.GREEN__c=90;
        mrt.RED__c=80;
        update mrt;
        
        satisfacs[0].Q1_Score__c=85;
        satisfacs[0].Q1__c=85;
        satisfacs[0].Q1_Rank__c='2 out of 5';
        
        satisfacs[1].Q1_Score__c=20;
        satisfacs[1].Quarter_New__c='Q4';
        satisfacs[1].Score_Year__c='2015';
        
        satisfacs[2].Q1__c=60;
        satisfacs[2].Quarter_New__c='Q3';
        satisfacs[2].Score_Year__c='2015';
        
        satisfacs[3].Q1_Rank__c='3 out of 5';
        satisfacs[3].Quarter_New__c='Q2';
        satisfacs[3].Score_Year__c='2015';
        
        satisfacs[4].Q1_Score__c=85;
        satisfacs[4].Quarter_New__c='Q1';
        satisfacs[4].Score_Year__c='2015';
        
        update satisfacs;
        
        // Put Id into the current page Parameters
        PageReference myVfPage = Page.CustSatisfaction_SCardN;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('year','2016');
        ApexPages.currentPage().getParameters().put('quater','3');
        
        CustSatisfaction_SCardController csController = new CustSatisfaction_SCardController();
        csController.getyrs();
        csController.getQtrs();
        csController.getData();
        
        //validate page parameter
        system.assertEquals('ScoreCard', csController.Title);
        system.assertEquals('2016', csController.year);
        
        
    }    
    
    static testMethod void  testLoadData1(){
        List<Map<String,Object>> fieldValueMaps = new List<Map<String,Object>>();
       
        Map<String,Object> cusSatMap = new Map<String,Object>();
        cusSatMap.put('New_Product__c', 12);
        cusSatMap.put('New_Technology__c', 10);
        fieldValueMaps.add(cusSatMap);
        
        Map<String,Object> cusSatMap1 = new Map<String,Object>();
        cusSatMap1.put('Quarter_New__c','Q4');
        cusSatMap1.put('Score_Year__c', '2015');
        fieldValueMaps.add(cusSatMap1);
        
        Map<String,Object> cusSatMap2 = new Map<String,Object>();
        cusSatMap2.put('Quarter_New__c', 'Q3');
        cusSatMap2.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap2);
        
        Map<String,Object> cusSatMap3 = new Map<String,Object>();
        cusSatMap3.put('Quarter_New__c', 'Q2');
        cusSatMap3.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap3);
        
        Map<String,Object> cusSatMap4 = new Map<String,Object>();
        cusSatMap4.put('Quarter_New__c', 'Q1');
        cusSatMap4.put('Score_Year__c','2015');
        fieldValueMaps.add(cusSatMap4);
        
        List<Customer_Satsfaction__c> satisfacs = new List<Customer_Satsfaction__c>();
        satisfacs = CustomerSatisfactionDataFactory.createCustomerSatisfactions(fieldValueMaps,5);
        
        Merit__c mrt = new Merit__c (id=satisfacs[0].Merit_Index_for_customers__c);
        mrt.GREEN__c=90;
        mrt.RED__c=80;
        update mrt;
        
        satisfacs[0].Q1_Score__c=85;
        satisfacs[0].Q1__c=85;
        satisfacs[0].Q1_Rank__c='2 out of 5';
        
        satisfacs[1].Q1_Score__c=20;
        satisfacs[1].Quarter_New__c='Q4';
        satisfacs[1].Score_Year__c='2015';
        
        satisfacs[2].Q1__c=60;
        satisfacs[2].Quarter_New__c='Q3';
        satisfacs[2].Score_Year__c='2015';
        
        satisfacs[3].Q1_Rank__c='3 out of 5';
        satisfacs[3].Quarter_New__c='Q2';
        satisfacs[3].Score_Year__c='2015';
        
        satisfacs[4].Q1_Score__c=85;
        satisfacs[4].Quarter_New__c='Q1';
        satisfacs[4].Score_Year__c='2015';
        
        update satisfacs;
        
        // Put Id into the current page Parameters
        PageReference myVfPage = Page.CustSatisfaction_SCardN;
        Test.setCurrentPage(myVfPage);
        ApexPages.currentPage().getParameters().put('sfdc.tabName','00112121212');
        CustSatisfaction_SCardController csController = new CustSatisfaction_SCardController();
        csController.getyrs();
        csController.getQtrs();
        csController.getData();
        csController.getCsites();
        
        //validate page parameter
        system.assertEquals('ScoreCard', csController.Title);
        system.assertEquals(string.valueOf(system.today().year()), csController.year);
        
        
    }
    
}