objects/Custom_Design__c.object
<CustomObject>
    <description>Custom Object defining details of a CDS Form</description>
    <fields>
        <fullName>CDS_Status__c</fullName>
        <label>++ CDS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready for IDR</fullName>
                </value>
                <value>
                    <fullName>In DE</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Design Specification</label>
    <nameField>
        <displayFormat>CDS-{000000}</displayFormat>
        <label>Custom Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Design Specifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CDS_DataFactory.cls
/**
* Author: Cognizant Technology Solutions
* Project: DIW 
* Description: This data factory class will be used to CDS data in different Test classes
**/

@isTest
public class CDS_DataFactory{

     public static Custom_Design__c createCDS(Map<String,Object> fieldValueMap)
     {
        // Create Custom Design with default data that is required, this will handle cases where required fields are not set
        
        Custom_Design__c  CD = new Custom_Design__c();
        cd.CDS_Status__c = 'Draft';
        
        for(String CustomDesignfieldName:fieldValueMap.keySet())
        {
          CD.put(CustomDesignfieldName, fieldValueMap.get(CustomDesignfieldName));        
        }
       system.debug('Customer Design' +CD);
       insert CD;
       return CD;
     
     }
}