objects/Deal_Grading__c.object
<CustomObject>
    <description>Deal Grading related to Opportunities</description>
    <fields>
        <fullName>Sales_Contact_FSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Contact (FSE)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Grading</label>
    <nameField>
        <displayFormat>DG-{00000}</displayFormat>
        <label>Deal Grading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Grading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Device_Export_Control_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Device - Export Control Junctions</relationshipLabel>
        <relationshipName>Device_Export_Control_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Export_Control_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Export Control Form</label>
        <referenceTo>Export_Control_Form__c</referenceTo>
        <relationshipLabel>Device - Export Control Junctions</relationshipLabel>
        <relationshipName>Device_Export_Control_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Device - Export Control Junction</label>
    <nameField>
        <displayFormat>D-{0000000000}</displayFormat>
        <label>Device - Export Control Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device - Export Control Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Export_Control_Form__c.object
<CustomObject>
    <description>Device&apos;s Export Control Form</description>
    <label>Export Control Form</label>
    <nameField>
        <displayFormat>EXP{YYYY}{MM}{000000}</displayFormat>
        <label>Export Control Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Export Control Form</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/IP_Declaration_Form__c.object
<CustomObject>
    <description>Device Manager&apos;s IP Declaration Form</description>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>IP Declaration Form</relationshipLabel>
        <relationshipName>IP_Declaration_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>IP Declaration Form</label>
    <nameField>
        <displayFormat>IPD{YYYY}{MM}{000000}</displayFormat>
        <label>IP Declaration Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Declaration Form</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Program_Team_Member__c.object
<CustomObject>
    <description>The individual team members for Opportunity Program and Device records.</description>
    <fields>
        <fullName>Is_FAE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FAE ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <description>The parent Opportunity Program for the team member.</description>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Opportunity Program Team Members</relationshipLabel>
        <relationshipName>Opportunity_Program_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>The team role of the team member.</description>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Administrator</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Backup Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Business Planner</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Engineer</fullName>
                </value>
                <value>
                    <fullName>Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Customer Tapeout Engineer</fullName>
                </value>
                <value>
                    <fullName>DE - Customer Support</fullName>
                </value>
                <value>
                    <fullName>DE - Enablements</fullName>
                </value>
                <value>
                    <fullName>DE - IP Technical</fullName>
                </value>
                <value>
                    <fullName>Design Win Team</fullName>
                </value>
                <value>
                    <fullName>DE - Tapeout</fullName>
                </value>
                <value>
                    <fullName>Fab Planner</fullName>
                </value>
                <value>
                    <fullName>Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Primary Account Manager</fullName>
                </value>
                <value>
                    <fullName>Primary Customer Service Rep</fullName>
                </value>
                <value>
                    <fullName>Primary Field Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Marketing</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Engineer</fullName>
                </value>
                <value>
                    <fullName>Regional Channel Manager</fullName>
                </value>
                <value>
                    <fullName>Strategic Marketing</fullName>
                </value>
                <value>
                    <fullName>TD PI / YE</fullName>
                </value>
                <value>
                    <fullName>Field Design Center Engineer</fullName>
                </value>
                <value>
                    <fullName>Primary Factory AE</fullName>
                </value>
                <value>
                    <fullName>Physical Design Engineer</fullName>
                </value>
                <value>
                    <fullName>ASIC Packaging Applications Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The individual program team member.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Program Team Members</relationshipLabel>
        <relationshipName>Opportunity_Program_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Program Team Member</label>
    <nameField>
        <displayFormat>OPTM-{000000000}</displayFormat>
        <label>OPTM Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Program Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DeviceExpToCustomerController.cls
/*
  Author: Anirban Roy
  Description: This is the controller for the DeviceExpToCustomerVF component.
  History:
    ARoy        06062013    - code creation.                       
*/

public class DeviceExpToCustomerController {
    
    public Id oppProgId {get;set;}
    public Id deviceId {get; set;}
    public String objectType {get; set;}
    public String emailType {get; set;}
    
    public DeviceExpToCustomerController() {}
    
    public String getFaeDetail(){ 
        String result = '';   
        try{
                  
            String noOppProgFAEInfo = EnvironmentVariable.get('NO_OPP_PROG_FAE_INFO');
            set<String> sOppProgTeamRole = new set<string> {EnvironmentVariable.get('OPPTY_PROG_TM_ROLE_FAE'),
                                                           EnvironmentVariable.get('OPPTY_PROG_TM_ROLE_FTS'),
                                                           EnvironmentVariable.get('OPPTY_PROG_TM_ROLE_PFTS')};
            
            sOppProgTeamRole.remove(null);
            //Get the User information for the Opportunity_Program__c and Team Role = 'Field Application Engineer'
            List<Opportunity_Program_Team_Member__c> oppProgTeamMember = [SELECT User__r.Name,User__r.Email
                                                                            FROM Opportunity_Program_Team_Member__c
                                                                            WHERE Opportunity_Program__c = :oppProgId
                                                                            AND (    Team_Role__c in :sOppProgTeamRole 
                                                                                OR (Team_Role__c = 'Account Manager' AND Is_FAE__c = TRUE)
                                                                                OR (Team_Role__c = 'Primary Account Manager' AND Is_FAE__c = TRUE) )];
        
            for(Opportunity_Program_Team_Member__c oppTM : oppProgTeamMember){
                result = result + oppTM.User__r.Name + ': ' + oppTM.User__r.Email+ ', ';
            }
                        
            if(result.length() > 0){
                result = result.removeEnd(', ');
            }else {
                result = noOppProgFAEInfo;
            }
            
        }catch (Exception e) {
            result = 'Error: ' + e.getMessage();
            
        }
        
        return result;
    }
    
    public string getTargetId(){
        String result = '';
        if(!String.isBlank(objectType)){
            if(objectType == 'ECF'){
                //soql = 'Select Export_Control_Form__c from  Device_Export_Control_Junction__c  where Device__c = \'' + deviceId + '\' limit 1';
                result = EnvironmentVariable.get('EXPOSE_DEVICE_ECF_PATH').replace('{0}',deviceId);
            }
                
            else if(objectType == 'IDF'){
                String soql = 'Select id from  IP_Declaration_Form__c  where Device__c = \'' + deviceId + '\' limit 1';
                list<Sobject> queryResult = database.query(soql);
                if(queryResult.size() > 0) {
                    String idfId = (string)queryResult[0].get('id');
                    result = EnvironmentVariable.get('EXPOSE_DEVICE_IPD_PATH').replace('{0}',idfId);
                }
            }
            
            String portalUrl = EnvironmentVariable.get('SFDC_CUSTOMER_PORTAL');
            if(result != ''){
                result = portalUrl + result;
            }else{
                result = portalUrl + '/' + deviceId;
            }
        }
        system.debug(result);
        return result;
    }
    
   
}