objects/Design_Execution__c.object
<CustomObject>
    <description>This object will store the Design Execution records. Object is having Master-Detail relationship with Option object.</description>
    <fields>
        <fullName>Actual_Date__c</fullName>
        <label>IDR Actual Date</label>
        <type>Date</type>
    </fields>
    <label>Design Execution</label>
    <nameField>
        <displayFormat>DE-{0000}</displayFormat>
        <label>Design Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DesignExecution_DataFactory.cls
/**
* Author: Sandesh Singh
* Project: DIW 
* Description: This data factory class will be used to Design Execution data in different Test classes
**/

@isTest
public class DesignExecution_DataFactory {
	public static Design_Execution__c createDesignExection(Map<String,Object> fieldValueMap)
     {
        // Create Design Execution with default data that is required, this will handle cases where required fields are not set
        Design_Execution__c deOBJ = new Design_Execution__c();
        deOBJ.Actual_Date__c = system.today();
        
        for(String DesignExectuionfieldName:fieldValueMap.keySet())
        {
          deOBJ.put(DesignExectuionfieldName, fieldValueMap.get(DesignExectuionfieldName));        
        }
       system.debug('Design Exectuion' +deOBJ);
       insert deOBJ;
       return deOBJ;
     
     }
}