objects/Device__c.object
<CustomObject>
    <description>This object holds the device information originally stored in Siebel.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated based on the Opportunity Programs Opportunity Account value.</description>
        <inlineHelpText>The Account under which the Opportunity resides. Populated by System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Confidence_Level_Tapeout__c</fullName>
        <description>FAE/FTS’s confidence level of the tapeout will be materialized</description>
        <inlineHelpText>FAE/FTS’s confidence level of the tapeout will be materialized.
Required in Design In Stage</inlineHelpText>
        <label>Confidence Level - Tapeout</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Sourcing__c</fullName>
        <description>Identify device sourcing. 1st Source, 2nd Source
Do not pick NONE.</description>
        <inlineHelpText>Identify device sourcing. 1st Source, 2nd Source
Do not pick NONE.</inlineHelpText>
        <label>Device Sourcing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Source</fullName>
                </value>
                <value>
                    <fullName>First Source</fullName>
                </value>
                <value>
                    <fullName>Second Source</fullName>
                </value>
                <value>
                    <fullName>Multi Source</fullName>
                </value>
                <value>
                    <fullName>NONE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Application__c</fullName>
        <description>To identify the End Application of the device</description>
        <inlineHelpText>To identify the End Application of the device</inlineHelpText>
        <label>End Application</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Body</fullName>
                </value>
                <value>
                    <fullName>Powertrain</fullName>
                </value>
                <value>
                    <fullName>Driver Information</fullName>
                </value>
                <value>
                    <fullName>Safety &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Others - Automotive</fullName>
                </value>
                <value>
                    <fullName>Broadband Client</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Others - CCS</fullName>
                </value>
                <value>
                    <fullName>Desktop PC</fullName>
                </value>
                <value>
                    <fullName>Set Top Box</fullName>
                </value>
                <value>
                    <fullName>Video Games</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>Others - Consumer</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Security &amp; Energy</fullName>
                </value>
                <value>
                    <fullName>Smart Card</fullName>
                </value>
                <value>
                    <fullName>Others - IMS</fullName>
                </value>
                <value>
                    <fullName>Cell Handset</fullName>
                </value>
                <value>
                    <fullName>Mobile PC</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>Others - Mobility</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
                <value>
                    <fullName>Others - AD</fullName>
                </value>
                <value>
                    <fullName>Machine Learning</fullName>
                </value>
                <value>
                    <fullName>IoT - Automotive</fullName>
                </value>
                <value>
                    <fullName>IoT - Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>Indicate Fab where this device produce</description>
        <inlineHelpText>Indicate Fab where this device produce</inlineHelpText>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <inlineHelpText>If unsure, refer Opportunity or Opportunity Program objects.</inlineHelpText>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Compute, Connect, Store (CCS)</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial,Medical &amp;Scientific</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Testchip</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Opportunity Programs Opportunity. Automatically populated from Trigger. (For reporting purpose).</description>
        <inlineHelpText>Auto populated by system.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Opportunity Program this device is related to.</description>
        <inlineHelpText>The Opportunity Program under which the Device resides</inlineHelpText>
        <label>Opportunity Program</label>
        <referenceTo>Opportunity_Program__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <inlineHelpText>Identify Tapeout type. Do not pick Retrofit.</inlineHelpText>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Retrofit</fullName>
                </value>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>Full Layer Retrofit</fullName>
                </value>
                <value>
                    <fullName>TD Test Chip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Device ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Non_Wafer_Revenue__c.object
<CustomObject>
    <description>This is a related object used to capture the non-wafer revenue associated with the device for forecasting.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>IF( ISBLANK(Device__c) , Opportunity__r.Account.Name,  Device__r.Account__r.Name)</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confidence_Level_Tapeout__c</fullName>
        <formula>TEXT(Device__r.Confidence_Level_Tapeout__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confidence Level - Tapeout</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The device that the non-wafer revenue supports</description>
        <label>Device</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Device__c.Opportunity2__c</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Device__c</referenceTo>
        <relationshipName>Non_Wafer_Revenues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <formula>IF(ISBLANK(Device__c) , Text(Opportunity__r.Market_Segment__c),Text(Device__r.Market_Segment__c))</formula>
        <label>Market Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <formula>TEXT(  Device__r.Tapeout_Type__c )</formula>
        <label>Tapeout Type</label>
        <type>Text</type>
    </fields>
    <label>Non Wafer Revenue and Adjustment</label>
    <nameField>
        <displayFormat>NWR-{00000}</displayFormat>
        <label>Non-Wafer Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Wafer Revenue and Adjustments</pluralLabel>
    <recordTypes>
        <fullName>MPW</fullName>
        <active>true</active>
        <label>MPW</label>
    </recordTypes>
    <recordTypes>
        <fullName>NRE</fullName>
        <active>true</active>
        <label>NRE</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reticle</fullName>
        <active>true</active>
        <label>Reticle</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Program__c.object
<CustomObject>
    <description>This object mirrors information from its related Opportunity record and has some additional editable fields.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account of the Opportunity this device is tied up. This is automatically populated during the Opportunity Program generation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Programs</relationshipLabel>
        <relationshipName>Opportunity_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>The Opportunity Market Segment.</description>
        <formula>TEXT(Opportunity__r.Market_Segment__c)</formula>
        <inlineHelpText>Read-Only Field : Only editable at the Opportunity level</inlineHelpText>
        <label>Market Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tapeout_Type__c</fullName>
        <label>Tapeout Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single Product</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle MPW</fullName>
                </value>
                <value>
                    <fullName>Customer MPW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Program</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NWRFormControllerTest.cls
@isTest
(seeAllData=false)
public class NWRFormControllerTest{

    @TestSetup static void testdata() 
    {
      DataUtilTest.loadEnvironmentVariables();
    }
    
    static testMethod void testRun1(){
        
        Test.startTest();
        
        Schema.DescribeSObjectResult nfrSchema = Schema.SObjectType.Non_Wafer_Revenue__c; 
        Map<String,Schema.RecordTypeInfo> nfrRecordTypeInfo = nfrSchema.getRecordTypeInfosByName();
        
        Id recordTypeId;
        if(nfrRecordTypeInfo .get('MPW').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('MPW').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('NRE').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('NRE').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('Reticle').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('Reticle').getRecordTypeId();
        }
        
        
        String acccountId = DeviceUtilTest.createAccount();
        String opportunitytyId = DeviceUtilTest.createOpp(acccountId, '0.10UM');
        String opportunitytyProgramId = DeviceUtilTest.createOppProg(acccountId, opportunitytyId);
        
        Device__c deviceObj = new Device__c();
        deviceObj.Name = 'TestDevice' + DateTime.now().getTime();
        deviceObj.Account__c = acccountId;
        deviceObj.Opportunity2__c = opportunitytyId;
        deviceObj.Opportunity_Program__c = opportunitytyProgramId;
        deviceObj.Tapeout_Type__c = 'Customer MPW';
        deviceObj.Device_Sourcing__c = '1st Source';
        deviceObj.End_Application__c = 'Body';
        deviceObj.Market_Segment__c = 'Automotive';
        deviceObj.Confidence_Level_Tapeout__c = '100';
        deviceObj.Fab__c = 'FAB 2';
        deviceObj.Original_Forecasted_Tapeout_Date__c = Date.newInstance(2016,3,20);
        deviceObj.Semiconductor_Device__c = 'Analog Amplifier';
        insert deviceObj;
        
        Non_Wafer_Revenue__c nwrObj = new Non_Wafer_Revenue__c();
        
        if(deviceObj != null && deviceObj.Opportunity2__c  != null){
            
            nwrObj.Opportunity__c = deviceObj.Opportunity2__c;
        }
        //insert nwrObj;
        
        Test.stopTest();
        
        PageReference pageRef = Page.NWRForm;
        Test.setCurrentPage(pageRef);
        Test.setCurrentPageReference(pageRef);
        
        if(deviceObj != null && deviceObj.Id  != null){
        
            pageRef.getParameters().put('Did', String.valueOf(deviceObj.Id));
        }
        
        if(recordTypeId != null){
            
            pageRef.getParameters().put('RecordType', recordTypeId);
        }
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(nwrObj);
        NWRFormController nWRFormController = new NWRFormController(standardController);
        
        PageReference pageReference = nWRFormController.save();
    }
    
    static testMethod void testRun2(){
        
        Test.startTest();
        
        Schema.DescribeSObjectResult nfrSchema = Schema.SObjectType.Non_Wafer_Revenue__c; 
        Map<String,Schema.RecordTypeInfo> nfrRecordTypeInfo = nfrSchema.getRecordTypeInfosByName();
        
        Id recordTypeId;
        if(nfrRecordTypeInfo .get('MPW').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('MPW').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('NRE').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('NRE').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('Reticle').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('Reticle').getRecordTypeId();
        }
        
        
        String acccountId = DeviceUtilTest.createAccount();
        String opportunitytyId = DeviceUtilTest.createOpp(acccountId, '0.10UM');
        String opportunitytyProgramId = DeviceUtilTest.createOppProg(acccountId, opportunitytyId);
        
        Device__c deviceObj = new Device__c();
        deviceObj.Name = 'TestDevice' + DateTime.now().getTime();
        deviceObj.Account__c = acccountId;
        deviceObj.Opportunity2__c = opportunitytyId;
        deviceObj.Opportunity_Program__c = opportunitytyProgramId;
        deviceObj.Tapeout_Type__c = 'Customer MPW';
        deviceObj.Device_Sourcing__c = '1st Source';
        deviceObj.End_Application__c = 'Body';
        deviceObj.Market_Segment__c = 'Automotive';
        deviceObj.Confidence_Level_Tapeout__c = '100';
        deviceObj.Fab__c = 'FAB 2';
        deviceObj.Original_Forecasted_Tapeout_Date__c = Date.newInstance(2016,3,20);
        deviceObj.Semiconductor_Device__c = 'Analog Amplifier';
        insert deviceObj;
        
        Non_Wafer_Revenue__c nwrObj = new Non_Wafer_Revenue__c();
        
        if(deviceObj != null && deviceObj.Opportunity2__c  != null){
            
            nwrObj.Opportunity__c = deviceObj.Opportunity2__c;
        }
        
        insert nwrObj;
        
        Test.stopTest();
        
        PageReference pageRef = Page.NWRForm;
        Test.setCurrentPage(pageRef);
        Test.setCurrentPageReference(pageRef);
        
        if(deviceObj != null && deviceObj.Id  != null){
        
            pageRef.getParameters().put('Did', String.valueOf(deviceObj.Id));
        }
        
        if(recordTypeId != null){
            
            pageRef.getParameters().put('RecordType', recordTypeId);
        }
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(nwrObj);
        NWRFormController nWRFormController = new NWRFormController(standardController);
        
        PageReference pageReference = nWRFormController.save();
    }
    
    static testMethod void testRun3(){
        
        Test.startTest();
        
        Schema.DescribeSObjectResult nfrSchema = Schema.SObjectType.Non_Wafer_Revenue__c; 
        Map<String,Schema.RecordTypeInfo> nfrRecordTypeInfo = nfrSchema.getRecordTypeInfosByName();
        
        Id recordTypeId;
        if(nfrRecordTypeInfo .get('MPW').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('MPW').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('NRE').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('NRE').getRecordTypeId();
        }
        else if(nfrRecordTypeInfo .get('Reticle').getRecordTypeId() != null){
            
            recordTypeId = nfrRecordTypeInfo .get('Reticle').getRecordTypeId();
        }
        
        
        String acccountId = DeviceUtilTest.createAccount();
        String opportunitytyId = DeviceUtilTest.createOpp(acccountId, '0.10UM');
        String opportunitytyProgramId = DeviceUtilTest.createOppProg(acccountId, opportunitytyId);
        
        Device__c deviceObj = new Device__c();
        deviceObj.Name = 'TestDevice' + DateTime.now().getTime();
        deviceObj.Account__c = acccountId;
        deviceObj.Opportunity2__c = opportunitytyId;
        deviceObj.Opportunity_Program__c = opportunitytyProgramId;
        deviceObj.Tapeout_Type__c = 'Customer MPW';
        deviceObj.Device_Sourcing__c = '1st Source';
        deviceObj.End_Application__c = 'Body';
        deviceObj.Market_Segment__c = 'Automotive';
        deviceObj.Confidence_Level_Tapeout__c = '100';
        deviceObj.Fab__c = 'FAB 2';
        deviceObj.Original_Forecasted_Tapeout_Date__c = Date.newInstance(2016,3,20);
        deviceObj.Semiconductor_Device__c = 'Analog Amplifier';
        insert deviceObj;
        
        Non_Wafer_Revenue__c nwrObj = new Non_Wafer_Revenue__c();
        
        if(deviceObj != null && deviceObj.Opportunity2__c  != null){
            
            nwrObj.Opportunity__c = deviceObj.Opportunity2__c;
        }
        
        if(recordTypeId != null){
            
            nwrObj.RecordTypeId = recordTypeId;
        }
        
        nwrObj.Non_Wafer_Revenue_Type__c = 'MPW';
        
        insert nwrObj;
        
        Blob blobData = Blob.valueOf('Test Data');
        Attachment attachmentObj = new Attachment(Name = 'Test', ParentId = nwrObj.Id, Body = blobData);
        insert attachmentObj;
        
        Note noteObj = new Note(Title = 'Test', ParentId = nwrObj.Id, Body = 'Test');
        insert noteObj;
        
        Test.stopTest();
        
        PageReference pageRef = Page.NWRForm;
        Test.setCurrentPage(pageRef);
        Test.setCurrentPageReference(pageRef);
        
        pageRef.getParameters().put('clone', '1');
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(nwrObj);
        NWRFormController nWRFormController = new NWRFormController(standardController);
        
        PageReference pageReference = nWRFormController.save();
    }
}