objects/DRT__c.object
<CustomObject>
    <fields>
        <fullName>DRT_Package_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created for the workflow DRT_WF_Sync_DRT_OracleDB.</description>
        <label>DRT Package Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated with the DRT</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>DRTs</relationshipLabel>
        <relationshipName>DRTs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The Status of the DRT</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Synced_with_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created for the workflow DRT_WF_Sync_DRT_OracleDB.</description>
        <label>Synced with Oracle DB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tech_Geo__c</fullName>
        <description>Tech Geo</description>
        <inlineHelpText>Tech Geo</inlineHelpText>
        <label>Tech Geo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRT</label>
    <nameField>
        <label>DRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRTs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Mask_Set_Title__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Synced_with_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synced with Oracle DB</label>
        <type>Checkbox</type>
    </fields>
    <label>Mask Set Title</label>
    <nameField>
        <label>Mask Set Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Set Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DRTHandlerUtilityExtnTest.cls
/**
 * Created Date: 24-Oct-2016
 * By: Swift TEAM
 *
 */
@isTest
private class DRTHandlerUtilityExtnTest {
    
    @testSetup
    static void setupTestData() {
        initialData();
    }

    static testMethod void test_getLayerUniqueIdentifier() {
        DRT__c objDRTDetail = [select id,Tech_Geo__c,Mask_Set_Title__c from drt__c limit 1];
        DRTHandlerUtilityExtn.getLayerUniqueIdentifier(objDRTDetail, 'LV', 'AZ', '123');
    }
    
    public static void initialData() {
        Mask_Set_Title__c mst = SwiftDataUtilityTest.createMST( 'ZIN789');
        insert mst;
        
        DRT__c drt1 = new DRT__c( Name='testFrame', Synced_with_Oracle_DB__c=false, DRT_Package_Sync__c=false, Status__c='Active', Mask_Set_Title__c = mst.Id, Tech_Geo__c = '0.028UM' );          
        insert drt1;
    }
}