objects/DRT__c.object
<CustomObject>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated with the DRT</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>DRTs</relationshipLabel>
        <relationshipName>DRTs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Geo__c</fullName>
        <description>Tech Geo</description>
        <inlineHelpText>Tech Geo</inlineHelpText>
        <label>Tech Geo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DRT</label>
    <nameField>
        <label>DRT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DRTs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Mask_Set_Title__c.object
<CustomObject>
    <label>Mask Set Title</label>
    <nameField>
        <label>Mask Set Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Set Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DRTHandlerUtilityExtn.cls
public without sharing class DRTHandlerUtilityExtn {
    
    public static string getLayerUniqueIdentifier(DRT__c objDRTDetail, String layerNo, String retroMaskRev, String retroROMCode) {
            
        Pattern techGeoPattern = Pattern.compile('(\\d*\\.\\d+)(.*)');
        String rCode = retroROMCode == '---' ? '' : retroROMCode;
        String indentifier = objDRTDetail.Mask_Set_Title__c + layerNo + retroMaskRev + rCode;

        if(!string.isBlank(objDRTDetail.Tech_Geo__c)) {
            decimal dcmtechgeo;
            
            if(!string.isBlank(objDRTDetail.Tech_Geo__c)) {
                Matcher pm = techGeoPattern.matcher(objDRTDetail.Tech_Geo__c);
                if(pm.matches() && !string.isBlank(pm.group(1))) dcmtechgeo = Decimal.valueOf(pm.group(1));
            }

            indentifier += (dcmtechgeo!=null) ? string.valueOf(dcmtechgeo) : '';
        }
            
        return indentifier;
    }
}