objects/Environment_Variable__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Environment variables used across all custom codes.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Environment Variable</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reason_for_Loss_Dropped__c</fullName>
        <inlineHelpText>Reason of opportunity Loss or Dropped.
This field is mandatory when Opportunity Stage change to 7. Loss or 8. Dropped</inlineHelpText>
        <label>Reason for Loss/Dropped</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low Priority Customer</fullName>
                </value>
                <value>
                    <fullName>No Capacity to Support</fullName>
                </value>
                <value>
                    <fullName>Pricing too low</fullName>
                </value>
                <value>
                    <fullName>Require High Cap Ex</fullName>
                </value>
                <value>
                    <fullName>Technology does not match</fullName>
                </value>
                <value>
                    <fullName>Unsupported Market Segment</fullName>
                </value>
                <value>
                    <fullName>Bad Relationship</fullName>
                </value>
                <value>
                    <fullName>Capacity</fullName>
                </value>
                <value>
                    <fullName>Customer End Opportunity Loss</fullName>
                </value>
                <value>
                    <fullName>Decided not to Pursue</fullName>
                </value>
                <value>
                    <fullName>Missed Milestone/Commitments</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Technology - Customer Assembly</fullName>
                </value>
                <value>
                    <fullName>Technology - Design Enablement</fullName>
                </value>
                <value>
                    <fullName>Technology - Process Gap</fullName>
                </value>
                <value>
                    <fullName>Production Readiness</fullName>
                </value>
                <value>
                    <fullName>Customer Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Process EOL</fullName>
                </value>
                <value>
                    <fullName>Device EOL</fullName>
                </value>
                <value>
                    <fullName>IP Gap</fullName>
                </value>
                <value>
                    <fullName>Misaligned to Corporate Strategy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SurveyFor__c</fullName>
        <formula>IF(TEXT(StageName ) = &quot;10. Void&quot;, &quot;Void&quot;, 
 IF(TEXT(StageName ) = &quot;9. Dropped&quot;, &quot;Dropped&quot;, 
  IF(TEXT(StageName ) = &quot;8. Lost&quot;, &quot;Lost&quot;, 
   IF(TEXT(StageName ) = &quot;7. Revenue&quot;, &quot;Revenue&quot;, 
    IF(TEXT(StageName ) = &quot;6. First Product TO&quot;, &quot;Won&quot;, &quot;&quot;
    )
   )
  )
 )
)</formula>
        <label>SurveyFor</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityStageController.cls
/*……………………………………………………………………………..
Type Name: OpportunityStageController 
Author: IBM
Created Date: 25th-July-2017
Reason: This class is used for opportunity survey
Test Class: OpportunityStageController_Test
Change History:
Author: 
Modified Date: 
………………………………………………………………………………..*/

public with sharing class OpportunityStageController {

    public opportunity oOpportunity { get; set; }
    public string oppId {get;set;}
    public string Stage{get; set;}
    public string reasonForLostDropped {get;set;}
    public string headerMessage {get;set;}

    public OpportunityStageController (ApexPages.StandardController stdController) {
         try{
             	oOpportunity = (opportunity)stdController.getRecord();
				oppId=oOpportunity.id;
                if (oppId != null) {
                    oOpportunity = [select id, ownerid from opportunity where id = :oppId ];
                    headerMessage= Environment_Variable__c.getInstance('Lost').value__c;
                    headerMessage+= Environment_Variable__c.getInstance('Dropped').value__c;
                    headerMessage+= Environment_Variable__c.getInstance('Dropped_v1').value__c;
                    headerMessage+= Environment_Variable__c.getInstance('Void').value__c;
                }
        Stage = 'Lost';   
        }catch(Exception Ex){
            system.debug('Exception'+ex);
         }
        
        
    }
    
    public List<SelectOption> getClosedStages() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Lost','8. Lost'));
        options.add(new SelectOption('Dropped','9. Dropped'));
        options.add(new SelectOption('Void','10. Void'));
        return options;
    }
    
    /* public List<SelectOption> getReasonForLostDroppedValues() {
         List<SelectOption> options = new List<SelectOption>();
         Schema.DescribeFieldResult fieldResult = Opportunity.Reason_for_Loss_Dropped__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry oValue : ple)
        {
            options.add(new SelectOption(oValue.getLabel(), oValue.getValue()));
        }       
        return options;
    }*/
    
    public PageReference Next() {
        PageReference pageRef = new PageReference('/apex/OpportunitySurvey');
        pageRef.getParameters().put('SurveyFor__c',Stage);
        pageRef.getParameters().put('Record_Owner__c',oOpportunity.ownerid);
        pageRef.getParameters().put('Opportunity__c',oOpportunity.Id);
        if(Stage=='Lost' || Stage =='Dropped')
            pageRef.getParameters().put('RFLD',reasonForLostDropped);
         return pageRef;
    }
}