objects/ERP_Device__c.object
<CustomObject>
    <fields>
        <fullName>Back_Side_Grind__c</fullName>
        <label>Back Side Grind</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Burn_In__c</fullName>
        <label>Burn-In</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chips_per_Wafer__c</fullName>
        <label>Chips per Wafer</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deliverable_Type__c</fullName>
        <label>Deliverable Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CHIP</fullName>
                </value>
                <value>
                    <fullName>WAFER</fullName>
                </value>
                <value>
                    <fullName>MODULE</fullName>
                </value>
                <value>
                    <fullName>SIGE9HP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fabs</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 1</fullName>
                </value>
                <value>
                    <fullName>FAB 2</fullName>
                </value>
                <value>
                    <fullName>FAB 3</fullName>
                </value>
                <value>
                    <fullName>FAB 3E</fullName>
                </value>
                <value>
                    <fullName>FAB 5</fullName>
                </value>
                <value>
                    <fullName>FAB 6</fullName>
                </value>
                <value>
                    <fullName>FAB 7</fullName>
                </value>
                <value>
                    <fullName>FAB 8</fullName>
                </value>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>FAB 11</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Level_of_Metal__c</fullName>
        <label>Last Level of Metal</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Levels_Of_Metal__c</fullName>
        <label>Levels Of Metal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mask_Layer_Count__c</fullName>
        <label>Mask Layer Count</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module_Test_Flag__c</fullName>
        <label>Module Test Flag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_ID__c</fullName>
        <externalId>true</externalId>
        <label>Option ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <description>Red Part Number. Generated in PLM.</description>
        <externalId>true</externalId>
        <inlineHelpText>Red Part Number. Generated in PLM.</inlineHelpText>
        <label>Part Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_wafer__c</fullName>
        <label>Wafer Test Flag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wafer_Diameter__c</fullName>
        <label>Wafer Diameter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ERP Device</label>
    <nameField>
        <label>ERP Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Process__c.object
<CustomObject>
    <fields>
        <fullName>Wafer_Size__c</fullName>
        <label>Wafer Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RTAT_Slot__c.object
<CustomObject>
    <description>This represents the slot in the fab that the new product&apos;s lot will run it.   
It will show all the inputs needed to build the RTAT schedules
It will be linked to the lot&apos;s 3 possible schedules:
  WAFER Build Fab Schedule
  Wafer Finish Schedule
  Module Build Schedule</description>
    <fields>
        <fullName>Conversion_Lot_Number__c</fullName>
        <label>Conversion Lot Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Device_for_Slot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The ERP Device that will provide input to create the Slot&apos;s schedules</description>
        <label>ERP Device</label>
        <referenceTo>ERP_Device__c</referenceTo>
        <relationshipLabel>RTAT Slot</relationshipLabel>
        <relationshipName>RTAT_Slot</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <description>FAB 9= BTV, FAB 10=EFK, XFAB=ALTIS</description>
        <label>Fab</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Wafer_Size__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FAB 9</fullName>
                </value>
                <value>
                    <fullName>FAB 10</fullName>
                </value>
                <value>
                    <fullName>XFAB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>General_Comments__c</fullName>
        <description>Field for notes, comments or directions</description>
        <label>General Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Charge_Code__c</fullName>
        <label>Internal Charge Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MPW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Multi Part Wafer?</description>
        <inlineHelpText>Multipart wafer</inlineHelpText>
        <label>MPW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mfg_Instructions__c</fullName>
        <description>Instructions for Manufacturing</description>
        <label>Mfg Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SAP_Order_Number__c</fullName>
        <description>Enter the order number from SAP</description>
        <label>SAP Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slot_Status__c</fullName>
        <description>Current status of the slot</description>
        <inlineHelpText>ACTIVE = work in progress
PUBLISHED = Complete and mailed
CANCELLED = Not to be used</inlineHelpText>
        <label>Slot Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                    <default>true</default>
                    <label>ACTIVE</label>
                </value>
                <value>
                    <fullName>PUBLISHED</fullName>
                </value>
                <value>
                    <fullName>CANCELLED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Slot_Type__c</fullName>
        <label>Slot Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PROTO</fullName>
                </value>
                <value>
                    <fullName>EUH</fullName>
                </value>
                <value>
                    <fullName>PROD RTAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Slot_Yield_Factor__c</fullName>
        <description>Slot yield factor, only applied to wafers, not chips or modules</description>
        <label>Slot Yield Factor</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Technology__c</fullName>
        <label>Technology</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Technology</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wafer_Size__c</fullName>
        <description>Size of wafers in millimeters</description>
        <label>Wafer Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>200MM</fullName>
                </value>
                <value>
                    <fullName>300MM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RTAT Slot</label>
    <nameField>
        <label>RTAT Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTAT Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RTAT_Wafer_Fab_Schedule_Inputs__c.object
<CustomObject>
    <description>Collects the inputs required to create the Wafer Fab Schedule</description>
    <fields>
        <fullName>Levels_of_Metal__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of levels of metal</description>
        <label>Levels of Metal</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTAT_Slot__c</fullName>
        <description>The parent RTAT Slot that contains this wafer fab schedule&apos;s inputs</description>
        <label>RTAT Slot</label>
        <referenceTo>RTAT_Slot__c</referenceTo>
        <relationshipLabel>RTAT Wafer Fab Sched Inputs</relationshipLabel>
        <relationshipName>RTAT_Wafer_Fab_Sched_Inputs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wafer_Build_Location__c</fullName>
        <label>Wafer Build Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BURLINGTON</fullName>
                </value>
                <value>
                    <fullName>ALTIS</fullName>
                </value>
                <value>
                    <fullName>FSK 300MM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RTAT Wafer Fab Sched Input</label>
    <nameField>
        <label>Wafer Fab Schedule Inputs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTAT Wafer Fab Sched Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Business_Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CMOS Platforms</fullName>
    </customValue>
    <customValue>
        <fullName>ASIC</fullName>
    </customValue>
    <customValue>
        <fullName>RF</fullName>
    </customValue>
    <customValue>
        <fullName>A&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>SiPh</fullName>
    </customValue>
    <customValue>
        <fullName>Foundry</fullName>
        <isActive>false</isActive>
        <label>Foundry</label>
    </customValue>
    <description>GLOBALFOUNDRIES Business Unit
CMOS Platforms
ASIC
Foundry
RF
A&amp;D</description>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

globalValueSets/Technology.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1K5PAXE</fullName>
    </customValue>
    <customValue>
        <fullName>1KW5PAE</fullName>
    </customValue>
    <customValue>
        <fullName>7TG</fullName>
    </customValue>
    <customValue>
        <fullName>7TG E1 E2</fullName>
    </customValue>
    <customValue>
        <fullName>BICM5S0</fullName>
    </customValue>
    <customValue>
        <fullName>BIFET4S</fullName>
    </customValue>
    <customValue>
        <fullName>BIFETHP</fullName>
    </customValue>
    <customValue>
        <fullName>BIMOSP6</fullName>
    </customValue>
    <customValue>
        <fullName>BIMSP6C</fullName>
    </customValue>
    <customValue>
        <fullName>BIMSP6X</fullName>
    </customValue>
    <customValue>
        <fullName>BMSP6C9</fullName>
    </customValue>
    <customValue>
        <fullName>CIMG7HY</fullName>
    </customValue>
    <customValue>
        <fullName>CIMG7SF</fullName>
    </customValue>
    <customValue>
        <fullName>CIMG7ST</fullName>
    </customValue>
    <customValue>
        <fullName>CM7FRAM</fullName>
    </customValue>
    <customValue>
        <fullName>CM8SEPC</fullName>
    </customValue>
    <customValue>
        <fullName>CM8SEPD</fullName>
    </customValue>
    <customValue>
        <fullName>CMHV7SF</fullName>
    </customValue>
    <customValue>
        <fullName>CMMS6SF</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS5S5</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS5S6</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS6S2</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS6SF</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS6X0</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS7S0</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS7SF</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS8S0</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS8SB</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS8SE</fullName>
    </customValue>
    <customValue>
        <fullName>CMOS90B</fullName>
    </customValue>
    <customValue>
        <fullName>SIGE8XP</fullName>
    </customValue>
    <description>List of technologies used by Fab 9/10</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

classes/RTATMilestoneEditDeleteTest.cls
/*
 * Author: Elizabeth Button
 * Test class for RTATMilestoneEditDelete apex class
 * Created April 24th, 2017
 *  
*/

@isTest
private class RTATMilestoneEditDeleteTest {
        
     @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
     }
    
    static Id createERPDevice() {
        
        ERP_Device__c erpDevice = new ERP_Device__c();
        erpDevice.Technology__c = 'SIGE8XP';
        erpDevice.Fab__c = 'FAB 9';
        erpDevice.Product_Type__c = 'Foundry';
        erpDevice.Deliverable_Type__c = 'WAFER';
        erpDevice.Name = 'MOSIS 910';
        erpDevice.Part_Number__c = '0000001KG304';
        erpDevice.Level__c = '27';
        erpDevice.Option_ID__c = 'OPT043516';
        erpDevice.Opportunity_ID__c = 'OPP029770';
        erpDevice.Business_Unit__c = 'RF';
        erpDevice.Burn_In__c = 'N';
        erpDevice.Test_wafer__c = 'N';
        erpDevice.Back_Side_Grind__c = 'Y';
        erpDevice.Levels_Of_Metal__c = 8;
        erpDevice.Last_Level_of_Metal__c = 'MA';
        erpDevice.Mask_Layer_Count__c = '52';
        erpDevice.Wafer_Diameter__c = 200;
        erpDevice.Chips_per_Wafer__c = 1;
        erpDevice.Module_Test_Flag__c = 'N';
        
        insert erpDevice;
        return erpDevice.Id;
        
    }
    
    static id createRTATSLOT(Id ERPDeviceId)
    {
        RTAT_Slot__c rtatSlot = new RTAT_Slot__c();
        rtatSlot.Name = 'MyTestSlotERB';
        rtatSlot.ERP_Device_for_Slot__c = ERPDeviceId;
        rtatSlot.Conversion_Lot_Number__c = '000222333';
        rtatSlot.SAP_Order_Number__c = '009030303030';
        rtatSlot.Internal_Charge_Code__c = 'My ICC num';
        rtatSlot.Mfg_Instructions__c = 'Some comments';
        rtatSlot.General_Comments__c = 'More comments';
        rtatSlot.Slot_Status__c = 'ACTIVE';
        rtatSlot.Slot_Type__c = 'EUH';
        rtatSlot.Slot_Yield_Factor__c = 75;
        rtatSlot.MPW__c = true;
        rtatSlot.Wafer_Size__c = '200MM';
        
        insert rtatSlot;
        return rtatSlot.Id;        
        
    }
    
    static Id createWafFabSched(Id RTATSlotId)
    {
        RTAT_Wafer_Fab_Schedule_Inputs__c wfs = new RTAT_Wafer_Fab_Schedule_Inputs__c();
        wfs.Name = 'MySampleWFSbyERB';
        wfs.Wafer_Build_Location__c = 'BURLINGTON';
        wfs.RTAT_Slot__c = RTATSlotId;
        wfs.RIT_Type__c = 'AB';
        wfs.LOM_or_Mask_Layers__c = 'Levels of Metal';
        wfs.RIT_A_Quality__c = 'PQ';
        wfs.RIT_A_Speed__c = 'TURBO';
        wfs.RIT_A_Wafer_Start_Quantity__c = 8;
        wfs.RIT_B_Quality__c = 'PQ';
        wfs.RIT_B_Speed__c = 'TURBO';
        wfs.RIT_B_Wafer_Start_Quantity__c = 8;
        wfs.Mask_House_CCDESK_date__c = Date.parse('07/03/2017');
        wfs.Mask_Build_TAT__c = 3;
        wfs.RIT_A_BTV_Fab_Transit_Time__c = 0.0;
        wfs.Fab_Prep_TAT__c = 0;
        wfs.Base_RIT_A_TAT__c = 21.5;
        wfs.ProcOptionNamesRITA__c = 'MPW;BR;';
        wfs.ProcOptionTATsRITA__c = '0;1';
        wfs.Base_RIT_B_TAT__c = 20;
        wfs.ProcOptionNamesRITB__c = 'AV;';
        wfs.ProcOptionTATsRITB__c = '1;8';        
        
        insert wfs;
        return wfs.Id;
        
    }
    static id createMilestone(Id idWFS, String proc, double dd, Date dt, boolean bb)
    {
        RTAT_Sched_TAT_Adjust__c mt = new RTAT_Sched_TAT_Adjust__c();
        mt.Parent_Waf_Fab_Schedule__c = idWFS;
        mt.Process__c = proc;
        mt.Adjustable_TAT__c = bb;
        mt.Total_TAT__c = dd;
        mt.End_Date__c = dt;
        insert mt;        
        return mt.Id;
        
    }
    
    static id createMilestoneWithSubProc(Id idWFS, String proc, double dd, Date dt, boolean bb)
    {
        RTAT_Sched_TAT_Adjust__c mt = new RTAT_Sched_TAT_Adjust__c();
        mt.Parent_Waf_Fab_Schedule__c = idWFS;
        mt.Process__c = proc;
        mt.Subprocess__c = 'MySubProc Sample';
        mt.Adjustable_TAT__c = true;
        mt.Subprocess_TAT__c = dd;
        //mt.End_Date__c = dt;
        insert mt;        
        return mt.Id;
        
    }
    static testMethod void runTest() {
        
        Test.startTest();
        
        //Create ERPDevice;
        Id idERPDevice = createERPDevice();
        //Create RTATSlot
        Id idRTATSlot = createRTATSlot(idERPDevice);
        //Create Waf Fab Schedule
        Id idWFS = createWafFabSched(idRTATSlot);
        //Create Milestones
        Date myDate = date.newinstance(2017, 7, 3);
        Id idMilestone1 = createMilestone(idWFS, 'first Milestone', 0, myDate, false);
        myDate = myDate.addDays(1);
        Id idMilestone1a = createMilestone(idWFS, 'first Milestone', 1, myDate, true);
        myDate = myDate.addDays(1);
        Id idMilestoneSub2 = createMilestone(idWFS, 'Second Milestone', 1, myDate, true);
        myDate = myDate.addDays(1);
        Id idMilestoneSub3 = createMilestone(idWFS, 'Second Milestone', 1, myDate, true);
        myDate = myDate.addDays(1);
        Id idMilestone2 = createMilestone(idWFS, 'Second Milestone', 1, myDate, false);
        myDate = myDate.addDays(1);
        Id idMilestone4 = createMilestone(idWFS, 'Third Milestone', 1, myDate, true);
        
        RTAT_Sched_TAT_Adjust__c myMilestone = [SELECT Id, Parent_Waf_Fab_Schedule__c FROM RTAT_Sched_TAT_Adjust__c 
                                                                WHERE Id = :idMilestone4 LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(myMilestone);
        
        RTATMilestoneEditDelete tatAdj = new RTATMilestoneEditDelete(sc);
        
               
        List<RTAT_Sched_TAT_Adjust__c> listMilestones = tatAdj.getMilestones();
        
               
        if (listMilestones.size() > 0)
        {
            for (Integer jj = 0; jj< listMilestones.size(); jj++)
            {    
               //get the first one.
               RTAT_Sched_TAT_Adjust__c milestone = listMilestones.get(jj);
               milestone.addDays__c = 2;
               listMilestones.set(jj, milestone);
               tatAdj.setMilestones(listMilestones);
               
            }
            tatAdj.adjust();
        } 
        
        RTAT_Wafer_Fab_Schedule_Inputs__c myWFSI = tatAdj.getWafFabSched();
        
        tatAdj.save();
        tatAdj.junk();
        tatAdj.junky();
        tatAdj.junk2();
        tatAdj.junk3();
        tatAdj.junk4();
        
        Test.stopTest();
    }

}