objects/Error_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom error codes and messages used across all custom codes.</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Codes</label>
</CustomObject>

objects/GMPL_BX009__c.object
<CustomObject>
    <fields>
        <fullName>PLC_Next_Gate__c</fullName>
        <description>Next PLC review gate before move the next PLC Phase.
Concept -&gt; PC0
Requirement &amp; Definition -&gt; PC1
Feasibility &amp; Planning -&gt; PC2
Execution -&gt; PLR
Ramp -&gt; PRR
Manufacturing -&gt; EOL
EOL</description>
        <label>PLC Next Gate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCCB</fullName>
                </value>
                <value>
                    <fullName>PC0</fullName>
                </value>
                <value>
                    <fullName>PC1</fullName>
                </value>
                <value>
                    <fullName>PC2</fullName>
                </value>
                <value>
                    <fullName>PCR</fullName>
                </value>
                <value>
                    <fullName>PLR</fullName>
                </value>
                <value>
                    <fullName>PRR</fullName>
                </value>
                <value>
                    <fullName>EOL</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GMPL</label>
    <nameField>
        <displayFormat>GMPL-{00000}</displayFormat>
        <label>GMPL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GMPLs</pluralLabel>
    <recordTypes>
        <fullName>BX009</fullName>
        <active>true</active>
        <description>This record type is for the object when it is BX009.</description>
        <label>BX009</label>
    </recordTypes>
    <recordTypes>
        <fullName>GMPL</fullName>
        <active>true</active>
        <description>This record type is for the object when it is GMPL.</description>
        <label>GMPL</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/POR_Change_Review__c.object
<CustomObject>
    <description>PLC Program POR Change Review:  
Out of bounds escalation of POR changes</description>
    <fields>
        <fullName>PCR_Status__c</fullName>
        <description>Status of the PCR</description>
        <inlineHelpText>Status of the PCR</inlineHelpText>
        <label>PCR Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>BCCB Review</fullName>
                </value>
                <value>
                    <fullName>PC Review</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Affected__c</fullName>
        <description>The GMPL program which affected by PCR</description>
        <label>Program Affected</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>GMPL_BX009__c.PLC_Next_Gate__c</field>
                <operation>equals</operation>
                <value>PLR</value>
            </filterItems>
            <filterItems>
                <field>GMPL_BX009__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>GMPL</value>
            </filterItems>
            <infoMessage>PCR required Program with PLC Next Gate = PLR</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>GMPL_BX009__c</referenceTo>
        <relationshipName>Product_Change_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>POR Change Review</label>
    <nameField>
        <displayFormat>PCR-{000000}</displayFormat>
        <label>PCR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POR Change Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PORChangeReviewController.cls
/*
    Author: Anirban Roy
    Description: This is the controller extension class for POR Change Review for creation of POR Change Review.  
    History:
        ARoy        06032014    - code creation.
        ARoy		06092014	- code modified to add validation on POR creation based on PLC Next Gate as PLR.
*/

public class PORChangeReviewController {
	
	// Variable Declaration
	private ApexPages.StandardController controller; 
	private String porLkp = EnvironmentVariable.get('POR_GMPL_LKP_ID');
    
    // Constructor
    public PORChangeReviewController(ApexPages.StandardController controller){
        this.controller = controller;
    }   
    
    // Method to validate the creation of PCR only when PCR Status = 'Closed' or no PCR exists
    public PageReference init(){        
        
        // GMPL/BX009 lookup id and name from POR Change Review
        String porId = ApexPages.currentPage().getParameters().get(porLkp+'_lkid');
        String porName = ApexPages.currentPage().getParameters().get(porLkp);         
        
        // Query to get the GMPL/BX009 to check the PLC Next Gate Status = 'PLR'
        List<GMPL_BX009__c> gmplList = [select		Id
		        									, PLC_Next_Gate__c
		        						from 		GMPL_BX009__c
		        						where		Id = :porId
		        						and			PLC_Next_Gate__c = 'PLR'
		        					   ];
        
        // Error message shown if the PLC Next Gate is not PLR
        if(gmplList == null || gmplList.size() == 0){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Error_Codes__c.getInstance('POR_CR_VLD_ON_PLC_NEXT_GATE').Message__c));
            return null;
        }
        // Query to get POR Change Review where PCR Status != 'Closed'
        List<POR_Change_Review__c> porList = [select	id
        									  from		POR_Change_Review__c
        									  where		Program_Affected__c = :porId
        									  and		PCR_Status__c != 'Closed'       									 			
        									 ];
        
        // Check for existing POR with PCR Status as Open/BCCB Review/PC Review.      
        if(porList != null && porList.size() > 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Error_Codes__c.getInstance('POR_CREATE_VALIDATION').Message__c));
            return null;
        }else{
            // Return to the POR Change Review edit page
            String retUrl = ApexPages.currentPage().getParameters().get('retURL');
            system.debug('retUrl***************'+retUrl);
            PageReference pr = new PageReference('/'+POR_Change_Review__c.sObjectType.getDescribe().getKeyPrefix()+'/e?retURL='+retUrl+'&nooverride=1&'+porLkp+'='+porName);
            pr.setRedirect(true);
            return pr;
        }                
        
    }
    
    // Cancel functionality
    public PageReference cancel(){
        return controller.cancel();
    }
}