objects/eWSR_Form__c.object
<CustomObject>
    <fields>
        <fullName>Equivalent_Quantity__c</fullName>
        <label>Equivalent Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_loop_Short_loop__c</fullName>
        <label>Full loop/Short loop</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full loop</fullName>
                    <default>true</default>
                    <label>Full loop</label>
                </value>
                <value>
                    <fullName>Short Loop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lot_Quantity_No_of_Wafers__c</fullName>
        <label>Wafer Quantity (No of Wafers)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Remaining_Quantity__c</fullName>
        <label>Remaining Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>eWSR Form</label>
    <nameField>
        <displayFormat>eWSR-{YYYY}-{0000}</displayFormat>
        <label>eWSR Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eWSR Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/eWSRInlineErrorMessageExt.cls
/*
    Author: Abhita Bansal
    Description: This Class is used to Show the Error message on View Page whenever the Lot Quantity is greater than Remaining Quantity 
    History: 
    ABansal     12/4/2014 - Code Creation
    ABansal     12/4/2014 - Change the Logic to show the Message dynamic
    ABansal     12/9/2014 - Update the Logic
    ABansal     12/10/2014 - Revert back the changes
*/
public with sharing class eWSRInlineErrorMessageExt{
    
    private ApexPages.StandardController controller{get;set;}
    public Boolean section{get; set;}
    public Integer remQuantity{get;set;}
    public String query{get;set;}
    
    public eWSRInlineErrorMessageExt(ApexPages.StandardController stdcontroller) {
        Decimal formRemQuan;
        section =  false;        
        String id = System.currentPagereference().getParameters().get('id');
        eWSR_Form__c forms = [Select Message__c, recordTypeId, Equivalent_Quantity__c, Remaining_Quantity__c, 
                              Lot_Quantity_No_of_Wafers__c, Full_loop_Short_loop__c from eWSR_Form__c where Id=:id Limit 1];
        RecordType recName = [Select Name from RecordType where id =:forms.recordTypeId Limit 1];
            
            if(recName.Name == eWSRConstantsVariablesClass.FAB7RECORDTYPE){
                if(forms.Full_loop_Short_loop__c == 'Short Loop'){
                    formRemQuan  = forms.Remaining_Quantity__c - forms.Equivalent_Quantity__c;
                }
                else{
                  formRemQuan = forms.Remaining_Quantity__c - forms.Lot_Quantity_No_of_Wafers__c;
                }                  
              }
              else{
                 formRemQuan = forms.Remaining_Quantity__c - forms.Lot_Quantity_No_of_Wafers__c;
              }
        if(forms.Message__c != null){
            remQuantity = Integer.valueOf(formRemQuan);
            section = true;
        }             
    }    
}