objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Process_Family__c</fullName>
        <label>Process Family</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process_Geometry__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Super Low Power</fullName>
                </value>
                <value>
                    <fullName>Super High Performance</fullName>
                </value>
                <value>
                    <fullName>Low Power eDRAM</fullName>
                </value>
                <value>
                    <fullName>Interposer</fullName>
                </value>
                <value>
                    <fullName>SOI</fullName>
                </value>
                <value>
                    <fullName>MEMS</fullName>
                </value>
                <value>
                    <fullName>High Performance / Low Voltage</fullName>
                </value>
                <value>
                    <fullName>Low Power / Ultra Low Leakage</fullName>
                </value>
                <value>
                    <fullName>Photonics</fullName>
                </value>
                <value>
                    <fullName>Generic / Nominal</fullName>
                </value>
                <value>
                    <fullName>XM</fullName>
                </value>
                <value>
                    <fullName>CMOS</fullName>
                </value>
                <value>
                    <fullName>CSOI</fullName>
                </value>
                <value>
                    <fullName>NVRAM</fullName>
                </value>
                <value>
                    <fullName>RF CMOS</fullName>
                </value>
                <value>
                    <fullName>SiGe</fullName>
                </value>
                <value>
                    <fullName>SiPh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityProcess__c.object
<CustomObject>
    <fields>
        <fullName>FAB__c</fullName>
        <label>FAB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Family__c</fullName>
        <label>Process Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_ID__c</fullName>
        <label>Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpportunityProcess</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>OpportunityProcess Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityProcess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetOpportunityProcessTest.cls
/*
Author:  Yash Kumar
    Description: Creates Opportunity Process test class 
    
    History:
        Yashkumar 12052013    - code creation.
*/

@isTest
private class GetOpportunityProcessTest {

   
     static testMethod void OpportunityProc() {
      test.startTest();
        
        
            OpportunityProcess__c oppprces =new OpportunityProcess__c();
          
            oppprces.Geometry__c ='0.028UM';
                    oppprces.Process_Family__c ='Super Low Power';
                    oppprces.FAB__c ='FAB 1';
                    oppprces.Process_ID__c='434-343-34';
                    
            
            
            insert oppprces;
            
     
     }
    

}