objects/FAB__c.object
<CustomObject>
    <label>FAB</label>
    <nameField>
        <label>Fab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FABS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MPW_Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAB</fullName>
                    <default>true</default>
                    <label>FAB</label>
                </value>
                <value>
                    <fullName>TD</fullName>
                </value>
                <value>
                    <fullName>IP</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>ASIC R&amp;D</fullName>
                </value>
                <value>
                    <fullName>RF_ASIC_A&amp;D Protos</fullName>
                </value>
                <value>
                    <fullName>Lighting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fab__c</fullName>
        <label>Fab</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_1_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Budget Owner 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Step_1_Approver_1M</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_1_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Budget Owner 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Step_1_Approver_2M</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_1_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPW Business Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Step_1_Approver_3M</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MPW Approval Matrix</label>
    <nameField>
        <displayFormat>MPWAM-{0000000}</displayFormat>
        <label>MPW Approval Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPW Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MPWApprovalMatrixTabControllerTest.cls
/*
    Author: Abhita Bansal
    Created Date: 21/08/2015 
    Description: Test class for MPWApprovalMatrixTabController
*/
@isTest
public class MPWApprovalMatrixTabControllerTest {
    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
     public static testMethod void myApprovalMatrixTabMethod() {
    
        List<User> userAppMatrix = [select Id from User where Profile.Name = 'GF PIYE Platform' and isActive = true limit 3];
    
        MPW_Approval_Matrix__c mpwAppMatrix = new MPW_Approval_Matrix__c();
        mpwAppMatrix.Category__c = 'FAB';
        mpwAppMatrix.Fab__c = 'Fab7';
        mpwAppMatrix.Geometry__c = '40nm';
        mpwAppMatrix.Step_1_Approver_1__c = userAppMatrix[0].Id;
        mpwAppMatrix.Step_1_Approver_2__c = userAppMatrix[1].Id;
        mpwAppMatrix.Step_1_Approver_3__c = userAppMatrix[2].Id;
        
        insert mpwAppMatrix;
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWApprovalMatrixTabVF'));
        System.currentPageReference().getParameters().put('sortField','Geometry__c');
        
        MPWApprovalMatrixTabController appMatrixClass = new MPWApprovalMatrixTabController();
        appMatrixClass.addNew();
        appMatrixClass.sortRecords();
        appMatrixClass.getHasPrevious();
        appMatrixClass.getHasNext();
        appMatrixClass.previous();
        appMatrixClass.next();
        appMatrixClass.first();
        appMatrixClass.last();
        appMatrixClass.getMPWApprovalMatrixRecords();
        
        Test.stopTest() ;  
    }
}