objects/GF_Task__c.object
<CustomObject>
    <description>FV2 : This object is used for GF Tasks.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>FV2:Due date for the task created</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>FV2:Subject for the task created</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FV2:Look up to Team Room object</description>
        <label>Team Room</label>
        <referenceTo>Team_Room__c</referenceTo>
        <relationshipLabel>GF Tasks</relationshipLabel>
        <relationshipName>GF_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assignTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>FV2:Look up to user object</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GF_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GF Task</label>
    <nameField>
        <label>GF Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GF Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Room__c.object
<CustomObject>
    <description>Team Room provide added functions for work groups to collaborate, share documents, notes and meeting minutes.</description>
    <label>Team Room</label>
    <nameField>
        <label>Team Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Room_Meeting_Minutes__c.object
<CustomObject>
    <description>This object is used to capture Meeting Minutes for the Team Room</description>
    <fields>
        <fullName>Meeting_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date the Meeting or Conference Call Took Place</description>
        <inlineHelpText>Date the Meeting or Conference Call Took Place</inlineHelpText>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <description>Enter the Frequency of the Meeting</description>
        <label>Meeting Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                    <default>true</default>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Non-Periodical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Room__c</fullName>
        <label>Team Room</label>
        <referenceTo>Team_Room__c</referenceTo>
        <relationshipLabel>Team Room Meeting Minutes</relationshipLabel>
        <relationshipName>Team_Room_Meeting_Minutes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Room Meeting Minute</label>
    <nameField>
        <displayFormat>TRMM-{YYYY}-{MM}-{DD}-{000}</displayFormat>
        <label>Team Room Meeting Minutes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Room Meeting Minutes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clsTaskGFCalActivityProvider.cls
/*
Type Name: clsTaskGFCalActivityProvider
Author: Cognizant Technology Solutions
Created Date: 22-5-2013
Reason: Displays the open tasks of the logged in user in the calendar component. 
Change History:
Author: 
Modified Date: 
Reason: 
……..
……..
*/



public class clsTaskGFCalActivityProvider implements GFCalActivityProvider
{
    String typeName = 'ot';
    String typeLabel = 'Open Task';
    String backgroundColor = '#CCFFCC';

    /*
    public List<GFCalActivity> findActivities(String id)
    {
       List<GFCalActivity> al = new List<GFCalActivity>();
       GFCalActivity a = null;
       
       List<Team_Room_Meeting_Minutes__c> mlist = [SELECT Id, Name, Meeting_Type__c,Meeting_Date__c from Team_Room_Meeting_Minutes__c where Team_Room__c = :id order by Meeting_Date__c desc LIMIT 500];
       for(Team_Room_Meeting_Minutes__c trm:mlist)
       {
           a = new GFCalActivity();
           a.setId(trm.Id);
           a.setType(typeName);
           a.setSubject(trm.Name);
           a.setBackgroundColor(backgroundColor);
           a.setStartDate(trm.Meeting_Date__c);
           if(trm.Meeting_Type__c != null)
           {
               a.put('meetingType',trm.Meeting_Type__c);
           }
          
           al.add(a);
       }
       return al;
    }
    */
    
    /**
        The method is used to find all the open tasks of the logged in user.
        
        @method name: findActivities
        @parameter:   String 
        @return :     List<GFCalActivity>
    **/
    public List<GFCalActivity> findActivities(String id)
    {
       List<GFCalActivity> al = new List<GFCalActivity>();
       GFCalActivity a = null;              
                   
       List<GF_Task__c> openTaskList = new List<GF_Task__c>();              
       openTaskList = [SELECT Id, 
                              Name,
                              subject__c, 
                              Due_Date__c                              
                         from GF_Task__c
                        where assignTo__c =: UserInfo.getUserId()
                          and Due_Date__c > TODAY
                          and Status__c <> 'Completed'                        
                     order by Due_Date__c desc 
                        LIMIT 500];                         
      
       if(!openTaskList.isEmpty())
       {
           for(GF_Task__c trm : openTaskList)
           {
               a = new GFCalActivity();
               a.setId(trm.Id);
               a.setType(typeName);
               a.setSubject(trm.subject__c);
               a.setBackgroundColor(backgroundColor);
               a.setActivityDate(trm.Due_Date__c);          
               a.setStartDate(trm.Due_Date__c);
               a.setEndDate(trm.Due_Date__c);
               
               /*
               if(trm.Meeting_Type__c != null)
               {
                   a.put('meetingType',trm.Meeting_Type__c);
               }
               */               
               al.add(a);
           }
       }         
       return al;
    }
    
    /**
        The method is used to get the properties of the open task - color/label for display in the calendar component.
        
        @method name: getActivityTypes
        @parameter:   none
        @return :     List<GFCalActivityType>
    **/
    public List<GFCalActivityType> getActivityTypes()
    {
       List<GFCalActivityType> tl = new List<GFCalActivityType>();
       GFCalActivityType type = new GFCalActivityType();
       type.setTypeCode(typeName);
       type.setTypeLabel(typeLabel);
       type.setBackgroundColor(backgroundColor);
       tl.add(type);
             
       //tl.add(new GFCalActivityType('mmtypeweekly','meetingType','Weekly','Weekly Meetings',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypedaily','meetingType','Daily','Daily Meetings',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypebiweekly','meetingType','Bi-Weekly','Bi-Weekly Meetings',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypemonthly','meetingType','Monthly','Monthly',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypequarterly','meetingType','Quarterly','Quarterly Meetings',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypeAnnual','meetingType','Annual','Annual Meetings',backgroundColor));
       //tl.add(new GFCalActivityType('mmtypenonperiod','meetingType','Non-Periodical','Non Periodical',backgroundColor));

       return tl;
    }
}