objects/GMPL_BX009__c.object
<CustomObject>
    <fields>
        <fullName>Geometry__c</fullName>
        <description>Geometry of Program in nm as defined in Program Name Taxonomy
Program Name:    AAA-BBBB-CCCC-DDDD

Where AAA= Geometry 180, 90, 65, 55, 28, 20, etc</description>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>350</fullName>
                </value>
                <value>
                    <fullName>250</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>153</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>140</fullName>
                </value>
                <value>
                    <fullName>130</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>86</fullName>
                </value>
                <value>
                    <fullName>65</fullName>
                </value>
                <value>
                    <fullName>55</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>32</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>MFG</fullName>
                </value>
                <value>
                    <fullName>RD</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GMPL</label>
    <nameField>
        <displayFormat>GMPL-{00000}</displayFormat>
        <label>GMPL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GMPLs</pluralLabel>
    <recordTypes>
        <fullName>GMPL</fullName>
        <active>true</active>
        <description>This record type is for the object when it is GMPL.</description>
        <label>GMPL</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MPW_Geometry_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geometry_ID__c</fullName>
        <label>Geometry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Process_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Process Type</label>
        <type>Checkbox</type>
    </fields>
    <label>MPW Geometry Mapping</label>
    <nameField>
        <label>Geometry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPW Geometry Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MPWGMPLProNameCustLookControllerTest.cls
/*
    Author: Abhita Bansal
    Created Date: 27/08/2015 
    Description: Test class for MPWGMPLProjectNameCustomLookupController
*/
@isTest
public class MPWGMPLProNameCustLookControllerTest {

    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    private static MPW_Geometry_Mapping__c utilDataGMMethod() {
        
        MPW_Geometry_Mapping__c mpwGeoMap = new MPW_Geometry_Mapping__c();
        mpwGeoMap.Name = '28nm';
        mpwGeoMap.Geometry_ID__c = '0.028UM';   
        mpwGeoMap.Use_Process_Type__c = true; 
        mpwGeoMap.Active__c = true;
        insert mpwGeoMap;
        
        return mpwGeoMap;
    }
    
    private static GMPL_BX009__c utilDataGMPLMethod() {
        
        GMPL_BX009__c gmplBX = new GMPL_BX009__c();
        gmplBX.Geometry__c = '28nm';
        insert gmplBX;
        
        return gmplBX;
    }
    
    public static testMethod void myGMPLProjectNameMethod() {
        
        MPW_Geometry_Mapping__c mpwGeoMap = utilDataGMMethod();
        GMPL_BX009__c gmplBX = utilDataGMPLMethod();
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWGMPLProjectNameCustomLookupVF'));  
        System.currentPageReference().getParameters().put('geo','28nm');
        System.currentPageReference().getParameters().put('sear','GMPL');
        
        MPWGMPLProjectNameCustomLookupController appMatrixClass = new MPWGMPLProjectNameCustomLookupController();
        appMatrixClass.searchGMPL();
        
        Test.stopTest();
    } 
    
    public static testMethod void myGMPLProjectNameMethod1() {
    
        MPW_Geometry_Mapping__c mpwGeoMap = utilDataGMMethod();
        GMPL_BX009__c gmplBX = utilDataGMPLMethod();
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWGMPLProjectNameCustomLookupVF'));  
        System.currentPageReference().getParameters().put('geo','28nm');
        
        MPWGMPLProjectNameCustomLookupController appMatrixClass = new MPWGMPLProjectNameCustomLookupController();
        appMatrixClass.searchGMPL();
        
        Test.stopTest();
    }    
}