objects/ICC_Test_Report_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ICC Test Report Name</label>
</CustomObject>

objects/Report_Subscription__c.object
<CustomObject>
    <description>FV2 : Used to store the My Subscription Report URL in MyWafers Page.</description>
    <fields>
        <fullName>Interval__c</fullName>
        <description>FV2 : Used for showing in the My Report Subscription</description>
        <label>Interval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Report_ID__c</fullName>
        <label>Report ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <description>FV2 : Used for showing in the My Report Subscription</description>
        <label>Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Report Subscription</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Report Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ICC_NewSubscriptionTest.cls
/*
Test class for ICC_NewSubscription class
Author: Rahul Majumder
*/

@isTest(seeAlldata = true)
public class ICC_NewSubscriptionTest
{
       
    private static testmethod void test_NewSubscription()
    {
        //ICC_Test_Report_Name__c CS_reportName = [Select Name FROM ICC_Test_Report_Name__c LIMIT 1];
        Report_Subscription__c testRS = new Report_Subscription__c(Report_Id__c = [select id from Report WHERE DeveloperName = 'ICC_Test_Coverage_Subscription_Report' ].id, Interval__c = 'Daily');
        
               
        ApexPages.StandardController sc = new ApexPages.StandardController(testRS);
        ICC_NewSubscription testNewSub = new ICC_NewSubscription(sc);
    
        PageReference pageRefNew = Page.ICC_New_Subscription;
        //pageRef.getParameters().put('id', String.valueOf(testAccountPlanInsert.Id));
        Test.setCurrentPage(pageRefNew);   
        
        testNewSub.rtSubr.Report_Type__c = 'Custom';
        testNewSub.getReports();
        testNewSub.rtSubr.Report_Type__c = 'Standard';
        testNewSub.getReports(); 
        ApexPages.currentPage().getParameters().put('retURL', '001');
        testNewSub.fetchReportsOfSeletedReportType();
        testNewSub.save();
        
        testNewSub.rtSubr.Interval__c = 'Daily';
        //testNewSub.fetchDataTypeOfFields('Account');
        
        Map<String, String> testMapFields = ICC_ReportSubscriptionUtility.fetchDataTypeOfFields('Account');
        
        testNewSub.rtSubr.Interval__c = null;
        testNewSub.rtSubr.Report_Id__c = null;
        testNewSub.save();
        
        Test.startTest();
       Id batchJobId = Database.executeBatch(new ICC_Batch_RefreshSubscrptnSOQL_Standard(), 200);
       Test.stopTest();
       
       ICC_User_Report_Subscriptions testUS = new ICC_User_Report_Subscriptions();
        testUS.refreshAllSubscriptionSOQLs();
        testUS.deleteReportSubscription();
           
    }
    
    private static testmethod void test_USerSubscriptions()
    {
        ICC_User_Report_Subscriptions testUS = new ICC_User_Report_Subscriptions();
        testUS.refreshAllSubscriptionSOQLs();
        testUS.deleteReportSubscription();
    }
}