objects/IP_Request__c.object
<CustomObject>
    <description>This object is to capture information for new IP requests by both internal and external users.</description>
    <fields>
        <fullName>RFQ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFQ</label>
        <referenceTo>RFQ__c</referenceTo>
        <relationshipLabel>IP Requests</relationshipLabel>
        <relationshipName>IP_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the New IP Request</description>
        <inlineHelpText>Status of the New IP Request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Accepted for Review</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IP Request</label>
    <nameField>
        <displayFormat>IP REQ - {0000}</displayFormat>
        <label>IP Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IP_Sizing_Option__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Adjustment__c</fullName>
        <label>Brand Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Comments__c</fullName>
        <label>Cost Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Evaluator__c</fullName>
        <label>Evaluator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPRequestName__c</fullName>
        <formula>IP_Sizing__r.IP_Request__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPRequestName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IP Request</label>
        <referenceTo>IP_Request__c</referenceTo>
        <relationshipLabel>IP Sizing Options</relationshipLabel>
        <relationshipName>IP_Sizing_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Development_Cost__c</fullName>
        <label>Internal Development Cost</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Support_Cost__c</fullName>
        <label>Internal Support Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RFQ__c</fullName>
        <formula>IP_Sizing__r.IP_Request__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RFQ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Change Control</fullName>
                </value>
                <value>
                    <fullName>Bid Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Pending Brand Finance</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Conditional Approval</fullName>
                </value>
                <value>
                    <fullName>Fall Plan</fullName>
                </value>
                <value>
                    <fullName>Move to Development</fullName>
                </value>
                <value>
                    <fullName>No Development Required</fullName>
                </value>
                <value>
                    <fullName>Development Complete</fullName>
                </value>
                <value>
                    <fullName>Exception Bid</fullName>
                </value>
                <value>
                    <fullName>Executive Forum</fullName>
                </value>
                <value>
                    <fullName>No Bid</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Development_Cost__c</fullName>
        <label>Total Development Cost</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_License_Porting_Support_Fees__c</fullName>
        <label>3rd Party License/Porting/Support Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Royalty__c</fullName>
        <label>3rd Party Royalty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Use_Fees__c</fullName>
        <label>3rd Party Use Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>IP Sizing Option</label>
    <nameField>
        <displayFormat>IPO-{0000000000}</displayFormat>
        <label>IP Sizing Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Sizing Options</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RFQ__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Preliminary Sizing</fullName>
                </value>
                <value>
                    <fullName>Final Sizing</fullName>
                </value>
                <value>
                    <fullName>Ready for B &amp; P</fullName>
                </value>
                <value>
                    <fullName>Submitted to Customer</fullName>
                </value>
                <value>
                    <fullName>Ready for BNP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RFQ</label>
    <nameField>
        <displayFormat>{YYYY}-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RFQ_IPR__c.object
<CustomObject>
    <fields>
        <fullName>IP_Request__c</fullName>
        <label>IP Request</label>
        <referenceTo>IP_Request__c</referenceTo>
        <relationshipLabel>RFQ&apos;s</relationshipLabel>
        <relationshipName>RFQ_IPR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RFQ__c</fullName>
        <label>RFQ</label>
        <referenceTo>RFQ__c</referenceTo>
        <relationshipLabel>IPR&apos;s</relationshipLabel>
        <relationshipName>RFQ_IPR</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RFQ-IPR</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>RFQ-IPR No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQ-IPR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GetIPSizingOptionsRec.cls
/**
@Author < Nikhil bajaj >
@name < IPSizingOptions vf>
@CreateDate < 1/5/2016 >
@Description < This class is  showing ipsizingoptions records in rfq vf page>
@Version <1.0>*/
public class GetIPSizingOptionsRec {
   Public List<RFQ_IPR__c> IPR_in_rfq_ipr{set;get;}
    Set<String> iprset = new Set<String>();
    Public List<IP_Sizing_Option__c> ipsizingoptions{set;get;}
    Public List<IP_Sizing_Option__c> IPR_in_sizingoptions{set;get;}

    public GetIPSizingOptionsRec(ApexPages.StandardController controller) {
        Id currentpageId =ApexPages.currentPage().getParameters().get('id');
        showIPSizOP(currentpageId);

    }
    
    Public  void showIPSizOP(Id currentpageId){
       //getting iprequest  from rfqipr using rfq id
        IPR_in_rfq_ipr = [select IP_Request__r.Name from RFQ_IPR__c where RFQ__c =:currentpageId] ;
        for(RFQ_IPR__c rfqipr : IPR_in_rfq_ipr){
            if(rfqipr.IP_Request__c!=null && rfqipr.IP_Request__r.Name!=null){
            iprset.add(rfqipr.IP_Request__r.Name);
            }
         }
         
         //getting iprequest from  ip_sizingoption where status is move to development
         IPR_in_sizingoptions=[select IPRequestName__c from IP_Sizing_Option__c where IPRequestName__c in:iprset and Status__c=:'Move to Development'];
         for(IP_Sizing_Option__c option: IPR_in_sizingoptions){
             if(option.IPRequestName__c!=null){
                 iprset.add(option.IPRequestName__c);
                    
              }
          }
             
        ipsizingoptions =[select id,Name,IPRequestName__c ,Evaluator__c, Total_Development_Cost__c,Internal_Development_Cost__c,Internal_Support_Cost__c,Material__c,X3rd_Party_License_Porting_Support_Fees__c,X3rd_Party_Use_Fees__c,X3rd_Party_Royalty__c, Brand_Adjustment__c,Cost_Comments__c from IP_Sizing_Option__c where IPRequestName__c in :iprset and Status__c=:'Move to Development'];
    }
}