objects/Lot_Instruction__c.object
<CustomObject>
    <description>Junction Object to relate the Lot Request Object to the Manufacturing Lot. Prrovides instructions for the lot.</description>
    <fields>
        <fullName>Manufacturing_Lot__c</fullName>
        <inlineHelpText>Manufacturing Lot Tagged for Request</inlineHelpText>
        <label>Lot ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. Please refine your search.</errorMessage>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Manufacturing_Lot__c.Account_Name__c</valueField>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Last_Ship_Date__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Manufacturing_Lot__c.Active_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Lot Ids are filtered based on the Account selection at Lot Instruction level and which are not yet shipped.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Manufacturing_Lot__c</referenceTo>
        <relationshipLabel>Lot Instructions</relationshipLabel>
        <relationshipName>Request_to_Lot_Tags</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Lot_Request__r.Stage__c)</formula>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <label>Lot Instruction</label>
    <nameField>
        <displayFormat>LotInstr-{000000}</displayFormat>
        <label>Lot Instructions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LotInstructionUtil.cls
/**
* Author        :   Ravikiran Nadella
* Description   :  this class has Logic to exceute when Lot id is 
changed  on lot instructions by planners  .
* History       :
Initials        Date                Description
-----------------------------------------------------------------------------------------

RNadella        27/11/2015          Created the class                                   
**/
public class LotInstructionUtil{

/*This Method is used to update the Changed lot information on the
     Lot instructions */
    public static void updateLotId(Map<id,Lot_Instruction__c>linstNewMap,Map<id,Lot_Instruction__c>linstOldMap){
        
        List<String> lotIDList = new List<String>();
        list<string> cLotidList = new List<String>();
        Set<Id> lotInstIds = new Set<Id> ();
        
        for(Lot_Instruction__c linst:linstNewMap.values()){
             
        if(linst.Stage__c=='Pending Planner Response' && (linst.Manufacturing_Lot__c != linstOldMap.get(linst.id).Manufacturing_Lot__c) ){
            lotInstIds.add(linst.Manufacturing_Lot__c);
            lotInstIds.add(linstOldMap.get(linst.id).Manufacturing_Lot__c);
            }
        }
        
       
        Map<id,Manufacturing_Lot__c>NameMap = new Map<id,Manufacturing_Lot__c>([select id,name from Manufacturing_Lot__c 
                                                                                  where id in :lotInstIds ]);
        
        
        for(Lot_Instruction__c linst:linstNewMap.values()){
            if(null<>NameMap.get(linst.Manufacturing_Lot__c)){
                if(NameMap.get(linst.Manufacturing_Lot__c).name.contains('.')){
                lotIDList=NameMap.get(linst.Manufacturing_Lot__c).name.split('\\.');
                }else{
                
                lotIDList.add(NameMap.get(linst.Manufacturing_Lot__c).name);
                }
                 id oldId = linstOldMap.get(linst.id).Manufacturing_Lot__c;
                if(NameMap.get(oldId).name.contains('.')){
                 cLotidList=NameMap.get(oldId).name.split('\\.');
                 system.debug('cLotidList split' +cLotidList);
                }else{
                
                cLotidList.add(NameMap.get(oldId).name);
                }
                
                system.debug('lotIDList' +lotIDList);
                system.debug('cLotidList' +cLotidList);
                
                if(lotIDList[0]!=cLotidList[0]){
                    linst.addError(system.label.Changed_Manufacturing_Lot);
                    
                }
                
            }
        }
        
    }


}