objects/Lot_Request__c.object
<CustomObject>
    <description>This Object is used to manage lot requests to include expedite, but eventually other instructions as well.</description>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Request</fullName>
                    <default>true</default>
                    <label>New Request</label>
                </value>
                <value>
                    <fullName>Acknowledged by CSR</fullName>
                </value>
                <value>
                    <fullName>Submitted by CSR</fullName>
                </value>
                <value>
                    <fullName>Submitted for Review by Expedite Manager</fullName>
                </value>
                <value>
                    <fullName>Resubmitted by CSR</fullName>
                </value>
                <value>
                    <fullName>Resubmitted by Expedite Manager</fullName>
                </value>
                <value>
                    <fullName>Fully Approved</fullName>
                </value>
                <value>
                    <fullName>Under Execution</fullName>
                </value>
                <value>
                    <fullName>Closed - Fully Executed</fullName>
                </value>
                <value>
                    <fullName>Closed - Partially Executed</fullName>
                </value>
                <value>
                    <fullName>Closed - Failed to Execute</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled by Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Cancelled Internally</fullName>
                </value>
                <value>
                    <fullName>Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Void (Mistaken Entry)</fullName>
                </value>
                <value>
                    <fullName>Pending Planner Response</fullName>
                </value>
                <value>
                    <fullName>Closed-Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lot Service Request</label>
    <nameField>
        <displayFormat>LReq-{0000000}</displayFormat>
        <label>Lot Service Request Form</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LotRequest_RecordTypeUpdate.cls
public class LotRequest_RecordTypeUpdate{
    //Commenting the class for Deletion from Production
    public LotRequest_RecordTypeUpdate(){
         
    }
        
    /*
    Lot_Request__c lotReq = new Lot_Request__c();
     
    public LotRequest_RecordTypeUpdate(ApexPages.StandardController controller){
        lotReq = (Lot_Request__c)controller.getRecord();
    }
    public pageReference changeRecordType(){
        
        Id LotRecordTypeId= Schema.SObjectType.Lot_Request__c.getRecordTypeInfosByName().get('Pricing Review Lot Request').getRecordTypeId();
        lotReq.RecordTypeId = LotRecordTypeId;
        lotReq.Stage__c = 'Submitted for Repricing';
        database.update(lotReq);
        
        PageReference pageRef = new PageReference('/'+lotReq.id);
        pageRef.setRedirect(true);
        return pageRef;
    }
    */
}