objects/Manufacturing_Lot__c.object
<CustomObject>
    <description>Manufacturing Lot is an Object to maintain the Lots of GLOBALFOUNDRIES.</description>
    <fields>
        <fullName>Current_Lot_Die_Quantity__c</fullName>
        <description>CURRENT_LOT_DIE_QTY</description>
        <label>Current Lot Die Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Wafer_Quantity_In_Lot__c</fullName>
        <description>Mapped to CURRENT_LOT_QTY</description>
        <label>Current Wafer Quantity In Lot</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manufacturing Lot</label>
    <nameField>
        <label>Manufacturing Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Lot</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WaferWriteOff_ManufacturingLot__c.object
<CustomObject>
    <fields>
        <fullName>Die_Qty__c</fullName>
        <label>Die Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Lot__c</fullName>
        <label>Manufacturing Lot</label>
        <referenceTo>Manufacturing_Lot__c</referenceTo>
        <relationshipLabel>WaferWriteOff_ManufacturingLot</relationshipLabel>
        <relationshipName>WaferWriteOff_ManufacturingLot</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wafer_Qty__c</fullName>
        <label>Current Wafer/Chip Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wafer_Write_Off_Status__c</fullName>
        <formula>TEXT(Wafer_Write_Off__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wafer Write Off Status</label>
        <type>Text</type>
    </fields>
    <label>WaferWriteOff_ManufacturingLot</label>
    <nameField>
        <displayFormat>WM{0000000000}</displayFormat>
        <label>WWOML Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaferWriteOff_ManufacturingLot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WaferWriteOffManufacturingLotUpdate.cls
/*
    Author: Zymark Ambat
    Description: This Class updates WaferWriteOff_ManufacturingLot__c records.
    History: 
        ZAmbat      02272015    - Code creation.
*/

public class WaferWriteOffManufacturingLotUpdate {
    public static void updateWaferWriteOffManufacturingLot(Set<Id> lotIds) {
        List<WaferWriteOff_ManufacturingLot__c> tempList = retrieveRecords(lotIds);
        if (tempList.size() > 0) {
            for (WaferWriteOff_ManufacturingLot__c w : tempList) {
                w.Wafer_Qty__c = w.Manufacturing_Lot__r.Current_Wafer_Quantity_In_Lot__c;
                w.Die_Qty__c = w.Manufacturing_Lot__r.Current_Lot_Die_Quantity__c;
            }
        
            update tempList;
        }
    }

    public static void deleteWaferWriteOffManufacturingLot(Set<Id> lotIds) {
        List<WaferWriteOff_ManufacturingLot__c> tempList = retrieveRecords(lotIds);
        if (tempList.size() > 0) {
            delete tempList;
        }
    }
    
    static List<WaferWriteOff_ManufacturingLot__c> retrieveRecords(Set<Id> lotIds) {
        return [SELECT    Id
                          , Wafer_Qty__c
                          , Die_Qty__c
                          , Manufacturing_Lot__r.Current_Lot_Die_Quantity__c
                          , Manufacturing_Lot__r.Current_Wafer_Quantity_In_Lot__c
                FROM      WaferWriteOff_ManufacturingLot__c
                WHERE     Manufacturing_Lot__c IN :lotIds
                          AND Wafer_Write_Off_Status__c IN ('Draft', 'Rejected')];        
    }
}