objects/Mask_Set_Title__c.object
<CustomObject>
    <label>Mask Set Title</label>
    <nameField>
        <label>Mask Set Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Set Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MRS__c.object
<CustomObject>
    <fields>
        <fullName>Created_at_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created at Oracle DB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Sync_with_Oracle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First_Sync_with_Oracle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>MRSs</relationshipLabel>
        <relationshipName>MRSs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>MRS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MRS_Chip_Details__c.object
<CustomObject>
    <fields>
        <fullName>Created_at_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created_at_Oracle_DB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Sync_with_Oracle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First_Sync_with_Oracle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRS__c</fullName>
        <label>MRS</label>
        <referenceTo>MRS__c</referenceTo>
        <relationshipLabel>MRS Chip Details</relationshipLabel>
        <relationshipName>MRS_Chip_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <formula>MRS__r.Mask_Set_Title__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mask_Set_Title</label>
        <type>Text</type>
    </fields>
    <label>MRS Chip Details</label>
    <nameField>
        <label>Chip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRS Chip Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MRS_Layer_Association__c.object
<CustomObject>
    <fields>
        <fullName>Created_at_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created_at_Oracle_DB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Sync_with_Oracle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First_Sync_with_Oracle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRS__c</fullName>
        <label>MRS</label>
        <referenceTo>MRS__c</referenceTo>
        <relationshipLabel>MRS Layer Association</relationshipLabel>
        <relationshipName>MRS_Layer_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>MRS Layer Association</label>
    <nameField>
        <label>Mask Layer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRS Layer Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MRS_Layer_Chip_Association__c.object
<CustomObject>
    <fields>
        <fullName>Created_at_Oracle_DB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created_at_Oracle_DB</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Sync_with_Oracle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First_Sync_with_Oracle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRS_ID__c</fullName>
        <formula>CASESAFEID(Chip__r.MRS__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MRS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title_Id__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <externalId>true</externalId>
        <label>Mask Set Title Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MRS Layer Chip Association</label>
    <nameField>
        <label>MRS_Layer_Chip_Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRS Layer Chip Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notes__c.object
<CustomObject>
    <description>This object is used to store the disapprove reason</description>
    <fields>
        <fullName>First_Sync_with_Oracle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First_Sync_with_Oracle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRS_ID__c</fullName>
        <formula>MRS_Layer_Association__r.MRS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MRS_ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRS_Layer_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used for tracking the comments entered by user while proceeding Hold in Hold/Resume Layer page.</description>
        <label>MRS Layer Association</label>
        <referenceTo>MRS_Layer_Association__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title_Id__c</fullName>
        <formula>ParentId__r.Mask_Set_Title_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mask_Set_Title_Id</label>
        <type>Text</type>
    </fields>
    <label>Notes</label>
    <nameField>
        <displayFormat>note-{0000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MRSpackageSyncHandler.cls
/*
Author: Cognizant
Company: Cognizant Tech Solutions
Description: sfdc - .net Integration Webservice
History:
created     29/5/2014     
*/
public class MRSpackageSyncHandler{

    //Method to invoke sync of MRS child objects
    public static void invokeMRSchldSync(set<id> mrsIds){
        list<MRS_Chip_Details__c> lstMRSChip =  new list<MRS_Chip_Details__c>([select id from MRS_Chip_Details__c where MRS__c in :mrsIds]);
        list<MRS_Layer_Association__c> lstMRSLayer =  new list<MRS_Layer_Association__c>([select id from MRS_Layer_Association__c where MRS__c in :mrsIds]);
        

        if(lstMRSChip.size()>0){
            for(MRS_Chip_Details__c rec :lstMRSChip){
                rec.First_Sync_with_Oracle__c=true;
            }
            update lstMRSChip;
        }

        if(lstMRSLayer.size()>0){
            for(MRS_Layer_Association__c rec :lstMRSLayer){
                rec.First_Sync_with_Oracle__c=true;
            }
            update lstMRSLayer;
        }
    }
    
    //Method to invoke sync of MRS Layer Chip object records
    public static void syncMRSLayerChip(set<string> mrsIds){
        list<MRS_Chip_Details__c> lstMRSChip = new list<MRS_Chip_Details__c>();
        list<MRS_Layer_Association__c> lstMRSlayer = new list<MRS_Layer_Association__c>(); 
        list<MRS_Layer_Chip_Association__c> lstlayerChip = new list<MRS_Layer_Chip_Association__c>();
        set<id> setMRSchip = new set<id>();
        set<id> setMRSlayer = new set<id>();
        set<id> setupdateMRS = new set<id>();
        lstMRSChip = [select MRS__c from MRS_Chip_Details__c where Created_at_Oracle_DB__c=false  and MRS__c in :mrsIds];
        lstMRSlayer = [select MRS__c from MRS_Layer_Association__c where Created_at_Oracle_DB__c=false  and MRS__c in :mrsIds];
        set<string> setMRSlayeroutofsync = new set<string>();
        //
        //
        
        if(lstMRSChip!=null && lstMRSChip.size()>0){
            for(MRS_Chip_Details__c chip:lstMRSChip){
                setMRSchip.add(chip.MRS__c);
                //
            }
        }
        
        if(lstMRSlayer!=null && lstMRSlayer.size()>0){
            for(MRS_Layer_Association__c layer :lstMRSlayer){
                setMRSlayer.add(layer.MRS__c);
                //
            }
        }
        list<string> lstIds = new list<string>(); 
        lstIds.addALl(mrsIds);
        for(id objID :lstIds){
            if(setMRSchip!=null && !setMRSchip.isEmpty()){
               if(setMRSchip.contains(objID))
                   setMRSlayeroutofsync.add(objID);
            } 
            if(setMRSlayer!=null && !setMRSlayer.isEmpty()){
               if(setMRSlayer.contains(objID)) 
                   setMRSlayeroutofsync.add(objID);
                }    
            if(setMRSlayeroutofsync.isEmpty() || (!setMRSlayeroutofsync.isEmpty() && !setMRSlayeroutofsync.contains(objID)))
                setupdateMRS.add(objID); 
                
        }
        //
        
        if(setupdateMRS!=null && !setupdateMRS.isEmpty()){
        set<string> setMST = new set<string>();
        set<string> setMSToutofSync = new set<string>();
                
        for(MRS__c mrs: [select Mask_Set_Title__c from MRS__C where id in :setupdateMRS]){
            if(mrs.Mask_Set_Title__c!=null){
            setMST.add(string.valueOf(mrs.Mask_Set_Title__c).substring(0,15));
            setMST.add(string.valueOf(mrs.Mask_Set_Title__c));
            }
        }
        for(MRS__c mrs: [select Mask_Set_Title__c from MRS__C where id in :setMRSlayeroutofsync]){
            if(mrs.Mask_Set_Title__c!=null){
                setMSToutofSync.add(string.valueOf(mrs.Mask_Set_Title__c).substring(0,15));
                setMSToutofSync.add(string.valueOf(mrs.Mask_Set_Title__c));
            }
        }
        
         lstlayerChip=[select id from MRS_Layer_Chip_Association__c where Mask_Set_Title_Id__c  in :setMST and Mask_Set_Title_Id__c  NOT in :setMSToutofSync];  
         //
         if(lstlayerChip!=null && lstlayerChip.size()>0){
             for(MRS_Layer_Chip_Association__c lc :lstlayerChip){
                 lc.First_Sync_with_Oracle__c = true;    
                 // 
             }
             //
             update lstlayerChip;
         }  
        }
        
    }
    
    //****
    //Method to invoke sync of MRS Note object records
    public static void syncMRSNotes(set<string> mrsIds){
        list<MRS_Layer_Chip_Association__c> lstlayerChip = new list<MRS_Layer_Chip_Association__c>();
        list<Notes__c> lstNotes = new list<Notes__c>();
        set<id> setMRSlayerChip = new set<id>();
        set<id> setupdateMRS = new set<id>();
        
        set<string> setMST = new set<string>();
        for(MRS__c mrs: [select Mask_Set_Title__c from MRS__C where id in :mrsIds]){
            if(mrs.Mask_Set_Title__c!=null){
              setMST.add(string.valueOf(mrs.Mask_Set_Title__c).substring(0,15));
              setMST.add(string.valueOf(mrs.Mask_Set_Title__c));
            }
        }
        lstlayerChip = [select MRS_ID__c from MRS_Layer_Chip_Association__c where Created_at_Oracle_DB__c=false  and Mask_Set_Title_Id__c  in :setMST];
        set<string> setMRSlayeroutofsync = new set<string>();
              
        if(lstlayerChip !=null && lstlayerChip.size()>0){
            for(MRS_Layer_Chip_Association__c layer :lstlayerChip){
                setMRSlayerChip.add(layer.MRS_ID__c);
                
            }
        }
        list<string> lstIds = new list<string>(); 
        lstIds.addALl(mrsIds);
        for(id objID :lstIds){
             
            if(setMRSlayerChip!=null && !setMRSlayerChip.isEmpty()){
               if(setMRSlayerChip.contains(objID)) 
                   setMRSlayeroutofsync.add(objID);
                }    
            if(setMRSlayeroutofsync.isEmpty() || (!setMRSlayeroutofsync.isEmpty() && !setMRSlayeroutofsync.contains(objID)))
                setupdateMRS.add(objID); 
                
        }
        //
        
        if(setupdateMRS!=null && !setupdateMRS.isEmpty()){
         lstNotes=[select id from Notes__c where MRS_ID__c in :setupdateMRS and MRS_ID__c NOT in :setMRSlayeroutofsync];  
         //
         if(lstNotes!=null && lstNotes.size()>0){
             for(Notes__c lc :lstNotes){
                 lc.First_Sync_with_Oracle__c = true;    
                 // 
             }
             //
             update lstlayerChip;
         }  
        }
        
    }
}