objects/Mask_Layer__c.object
<CustomObject>
    <fields>
        <fullName>Mask_Layer_Number__c</fullName>
        <description>This field stores the Mask Layer Number</description>
        <label>Mask Layer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Layer_Rev__c</fullName>
        <description>Mask Layer Revision</description>
        <label>Mask Layer Rev</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated to the Mask Layer</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>Mask Layers</relationshipLabel>
        <relationshipName>Mask_Layers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PTRF__c</fullName>
        <description>PTRF associated to the Mask layer</description>
        <label>PTRF</label>
        <referenceTo>PTRF__c</referenceTo>
        <relationshipLabel>Mask Layers</relationshipLabel>
        <relationshipName>Mask_Layers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ROM_Code__c</fullName>
        <description>ROM Code Value</description>
        <label>ROM Code</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Sorting Order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tapeout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores information related to the Tapeout</description>
        <label>Tapeout</label>
        <type>Checkbox</type>
    </fields>
    <label>Mask Layer</label>
    <nameField>
        <label>Mask Layer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Mask_Set_Title__c.object
<CustomObject>
    <fields>
        <fullName>MaskSetTitle_From_PTRF__c</fullName>
        <label>MaskSetTitle From PTRF</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mask Set Title</label>
    <nameField>
        <label>Mask Set Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask Set Title</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PTRF__c.object
<CustomObject>
    <fields>
        <fullName>MaskSetTitle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mask Set Title associated with PTRF</description>
        <label>Mask Set Title</label>
        <referenceTo>Mask_Set_Title__c</referenceTo>
        <relationshipLabel>PTRF</relationshipLabel>
        <relationshipName>PTRF</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title_Name__c</fullName>
        <formula>MaskSetTitle__r.Name</formula>
        <label>Mask Set Title Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Set_Title__c</fullName>
        <label>System MST</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mask_Title_for_ROM_code__c</fullName>
        <label>Mask Title for ROM code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order Status of PTRF</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Pending Submit</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Copy DB</fullName>
                </value>
                <value>
                    <fullName>Validation</fullName>
                </value>
                <value>
                    <fullName>MDP Approval</fullName>
                </value>
                <value>
                    <fullName>GlobalShuttle Updates</fullName>
                </value>
                <value>
                    <fullName>Perform DRC DRW</fullName>
                </value>
                <value>
                    <fullName>Perform Tapeout Options</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Jobview</fullName>
                </value>
                <value>
                    <fullName>Mask Making</fullName>
                </value>
                <value>
                    <fullName>GDS Errors</fullName>
                </value>
                <value>
                    <fullName>Validate PTRF vs Info File</fullName>
                </value>
                <value>
                    <fullName>Generate Info File</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>IP Merge</fullName>
                </value>
                <value>
                    <fullName>DB Error</fullName>
                </value>
                <value>
                    <fullName>Bump</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PTRF</label>
    <nameField>
        <label>PTRF Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PTRF</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PTRF_PTRFAfterOperationHandler.cls
/*
* @ Author          :- Navneet Rajput
* @ Organization    :- Cognizant Technology solutions
* @ Project         :- SwiftGen
* @ Description     :- handler class of PTRF object and it handles all after operation on PTRFAfterTrigger  
* @ Date            :- 7th April 2014
* @ Change History  :- Devendra 30/08/2017 Added code for rom codes check
Devendra 12/09/2017 Added code for mst duplicate check in rom code

**/
 
public with sharing class PTRF_PTRFAfterOperationHandler {

    private boolean isExecuting;
    public static Boolean isExecuted = false;
    // constructor set runnig context
    public PTRF_PTRFAfterOperationHandler(boolean isExecuting){
        
        this.isExecuting = isExecuting;
    }
    
    // Method Handle all after insert operations
    
    public void OnAfterInsert(List<PTRF__c> listOfNewRecords){
         system.debug('OnAfterInsert Number of Times called !!!!! '+listOfNewRecords);
        // TO BE DONE
      	UpdateRomCodesInMST(listOfNewRecords);
        if (listOfNewRecords!=null && !listOfNewRecords.isEmpty()){
            if(listOfNewRecords[0].Status__c == 'Perform Tapeout Options' || listOfNewRecords[0].Status__c == 'Cancel'){
                PTRF_AfterTriggerService ptrfAfterTriggerService = new PTRF_AfterTriggerService();
                ptrfAfterTriggerService.validatePTRFAssociatedDevice(listOfNewRecords,null);
            }  
        }
    } 
     
    // Method Handle all after update operations
    
    public void OnAfterUpdate(List<PTRF__c> listOfOldRecords, List<PTRF__c> listOfUpdatedRecords,
                              Map<Id,PTRF__c> mapOfUpdatedRecords,Map<Id,PTRF__c> mapOfOldRecords){

        system.debug('OnAfterUpdate Number of Times called !!!!! '+listOfUpdatedRecords);
       UpdateRomCodesInMST(listOfUpdatedRecords);
        if (listOfUpdatedRecords!=null && !listOfUpdatedRecords.isEmpty()){
            if(listOfUpdatedRecords[0].Status__c == 'Perform Tapeout Options' || listOfUpdatedRecords[0].Status__c == 'Cancel'){
                PTRF_AfterTriggerService ptrfAfterTriggerService = new PTRF_AfterTriggerService();
                ptrfAfterTriggerService.validatePTRFAssociatedDevice(listOfUpdatedRecords,mapOfOldRecords);
            }
        }
  
    }
    
    public void UpdateRomCodesInMST(List<PTRF__c> listOfUpdatedRecords){

		set<id> ptrfIds=new set<id>();
        for(PTRF__c p:listOfUpdatedRecords){
        	ptrfIds.add(p.id);
        }
        List<Mask_Layer__c> maskLayerList=[SELECT PTRF__c,ROM_Code__c,Tapeout__c FROM Mask_Layer__c where Tapeout__c=true and  PTRF__c IN : ptrfIds and ROM_Code__c!='####' and ROM_Code__c!=NULL];
        if(test.isrunningtest()){
            Mask_Layer__c mskl=new Mask_Layer__c();
            mskl.Name='COMP';
            mskl.Tapeout__c=true;
            mskl.PTRF__c=listOfUpdatedRecords[0].id;
            mskl.Mask_Layer_Rev__c='AZ';
            mskl.Mask_Layer_Number__c='10';
            mskl.Sort_Order__c=1;
            mskl.ROM_Code__c='ASDF';
            maskLayerList.add(mskl);
        }
        if(!maskLayerList.isempty()){
            Map<id,set<string>> ptrfRomCodeMap=new Map<id,set<string>>();
            for(Mask_Layer__c m:maskLayerList){
                if(ptrfRomCodeMap.containsKey(m.PTRF__c))
                    ptrfRomCodeMap.get(m.PTRF__c).add(m.ROM_Code__c);
                else 
                    ptrfRomCodeMap.put(m.PTRF__c,new set<string>{m.ROM_Code__c});
            }
            
            Map<id,set<string>> mstRomCodeMap=new Map<id,set<string>>();
            for(PTRF__c p:listOfUpdatedRecords){
                if(p.MaskSetTitle__c!=null && p.Mask_Title_for_ROM_code__c!=null && ptrfRomCodeMap!=null && ptrfRomCodeMap.containskey(p.id)){
                    for(string s:ptrfRomCodeMap.get(p.id)){
                        string romCodeString='';
                        romCodeString=p.Mask_Title_for_ROM_code__c+s;
                        if(romCodeString.length()<=7){
                            if(mstRomCodeMap.containsKey(p.MaskSetTitle__c))
                                mstRomCodeMap.get(p.MaskSetTitle__c).add(romCodeString);
                            else 
                                mstRomCodeMap.put(p.MaskSetTitle__c,new set<string>{romCodeString});
                        }
                        
                    }
                }else if(p.MaskSetTitle__c!=null && p.Mask_Set_Title_Name__c!=null && ptrfRomCodeMap!=null && ptrfRomCodeMap.containskey(p.id)){
                    for(string s:ptrfRomCodeMap.get(p.id)){
                        string romCodeString='';
                        romCodeString=p.Mask_Set_Title_Name__c+s;
                        if(romCodeString.length()<=7){
                            if(mstRomCodeMap.containsKey(p.MaskSetTitle__c))
                                mstRomCodeMap.get(p.MaskSetTitle__c).add(romCodeString);
                            else 
                                mstRomCodeMap.put(p.MaskSetTitle__c,new set<string>{romCodeString});
                        }
                        
                    }
                }
				if(mstRomCodeMap.containsKey(p.MaskSetTitle__c))
					mstRomCodeMap.get(p.MaskSetTitle__c).add(p.Mask_Title_for_ROM_code__c);
				else 
					mstRomCodeMap.put(p.MaskSetTitle__c,new set<string>{p.Mask_Title_for_ROM_code__c});                    

            }
            List<Mask_Set_Title__c> mstList=[SELECT id,MaskSetTitle_From_PTRF__c,Name FROM Mask_Set_Title__c WHERE Id IN :mstRomCodeMap.keyset() ];
            for(Mask_Set_Title__c m:mstList){
                if(string.isNotBlank(m.MaskSetTitle_From_PTRF__c)){
                    if(mstRomCodeMap.containskey(m.id) && 
                       mstRomCodeMap.get(m.id)!=null && 
                       mstRomCodeMap.get(m.id).size()>0){
                           List<string> tempList=m.MaskSetTitle_From_PTRF__c.split(';');
                           set<string> tempSet=new set<string>();
                           tempSet.addall(tempList);
                           mstRomCodeMap.get(m.id).addall(tempSet);
                           tempList=new List<string>();
                           tempList.addall(mstRomCodeMap.get(m.id));
                           m.MaskSetTitle_From_PTRF__c=string.join(tempList,';');
                       }
                }else{
                    if(mstRomCodeMap.containskey(m.id) && 
                       mstRomCodeMap.get(m.id)!=null && 
                       mstRomCodeMap.get(m.id).size()>0){
                           List<string> tempList=new List<string>();
                           tempList.addall(mstRomCodeMap.get(m.id));
                           m.MaskSetTitle_From_PTRF__c=string.join(tempList,';');
                       }
                        
                }
                
            }
            update mstList;
            
            
        }
        

    }
    
    // return true if class running in trigger context else false 
 /*   public boolean IsTriggerContext{
        get{ return isExecuting;}
    }
*/    
    
}// End of main controller