objects/MPW_Config_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geometry__c</fullName>
        <label>Geometry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>10nm</fullName>
                </value>
                <value>
                    <fullName>14nm</fullName>
                </value>
                <value>
                    <fullName>20nm</fullName>
                </value>
                <value>
                    <fullName>22nm</fullName>
                </value>
                <value>
                    <fullName>28nm</fullName>
                </value>
                <value>
                    <fullName>40nm</fullName>
                </value>
                <value>
                    <fullName>0.11/0.13um</fullName>
                </value>
                <value>
                    <fullName>0.15um</fullName>
                </value>
                <value>
                    <fullName>0.18um</fullName>
                </value>
                <value>
                    <fullName>0.35um</fullName>
                </value>
                <value>
                    <fullName>65/55nm</fullName>
                </value>
                <value>
                    <fullName>0.16UM</fullName>
                </value>
                <value>
                    <fullName>12/14nm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>MPW Config Settings</label>
    <nameField>
        <label>Process Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPW Config Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MPWConfigSettingsTranxControllerTest.cls
/*
    Author: Abhita Bansal
    Created Date: 24/08/2015 
    Description: Test class for MPWConfigSettingsTranxController
*/
@isTest
public class MPWConfigSettingsTranxControllerTest {

    @testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables();
    }
    
    public static testMethod void myConfigSettingsTranxMethod() {
        
        MPW_Config_Settings__c mpwConfigSet = new MPW_Config_Settings__c();
        mpwConfigSet.Name = '28LP';
        mpwConfigSet.Geometry__c = '28nm';
        mpwConfigSet.Active__c = true;
        
        insert mpwConfigSet;
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWConfigSettingsTabVF'));        
        System.currentPageReference().getParameters().put('id',mpwConfigSet.Id);
        System.currentPageReference().getParameters().put('tranx','Edit');
        System.currentPageReference().getParameters().put('returnURL','/apex/MPWConfigSettingsTabVF?sfdc.tabName='+System.Label.MPW_Process_Tab_Id);
        
        MPWConfigSettingsTranxController appMatrixClass = new MPWConfigSettingsTranxController(new ApexPages.Standardcontroller(new MPW_Config_Settings__c()));
        appMatrixClass.save();
        appMatrixClass.edit();
        appMatrixClass.cancel();
        appMatrixClass.backToList();
        appMatrixClass.getProcessTypes();
        appMatrixClass.getEditGeometry();
        appMatrixClass.getEditProcess();
        appMatrixClass.getEditRule();
        appMatrixClass.getShowEdit();
        appMatrixClass.getShowSave();
        appMatrixClass.getShowCancel();
        appMatrixClass.getEditActive();
        
        Test.stopTest();
    }
    
    public static testMethod void myConfigSettingsTranxMethod1() {
        
        MPW_Config_Settings__c mpwConfigSet = new MPW_Config_Settings__c();
        mpwConfigSet.Name = '28LP';
        mpwConfigSet.Geometry__c = '28nm';
        mpwConfigSet.Active__c = true;        
        mpwConfigSet.Rule__c = '109a';
        
        insert mpwConfigSet;
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWConfigSettingsTabVF'));
        System.currentPageReference().getParameters().put('from', 'MPWProcessDM');
        System.currentPageReference().getParameters().put('id',mpwConfigSet.Id);
        System.currentPageReference().getParameters().put('tranx','Edit');
        System.currentPageReference().getParameters().put('link','true');
        System.currentPageReference().getParameters().put('returnURL','/apex/MPWConfigSettingsTabVF?sfdc.tabName='+System.Label.MPW_Process_DM_Tab_Id);
        
        MPWConfigSettingsTranxController appMatrixClass = new MPWConfigSettingsTranxController(new ApexPages.Standardcontroller(new MPW_Config_Settings__c()));
        appMatrixClass.save();
        appMatrixClass.cancel();
        
        Test.stopTest();
    }
    
    public static testMethod void myConfigSettingsTranxMethod2() {
        
        MPW_Config_Settings__c mpwConfigSet = new MPW_Config_Settings__c();
        mpwConfigSet.Name = '28LP';
        mpwConfigSet.Geometry__c = '28nm';
        mpwConfigSet.Active__c = false;
        
        insert mpwConfigSet;
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MPWConfigSettingsTabVF'));        
        System.currentPageReference().getParameters().put('id',mpwConfigSet.Id);
        System.currentPageReference().getParameters().put('tranx','Edit');
        System.currentPageReference().getParameters().put('returnURL','/apex/MPWConfigSettingsTabVF?sfdc.tabName='+System.Label.MPW_Process_Tab_Id);
        
        MPWConfigSettingsTranxController appMatrixClass = new MPWConfigSettingsTranxController(new ApexPages.Standardcontroller(new MPW_Config_Settings__c()));
        appMatrixClass.save();
        
        Test.stopTest();
    }
}