objects/MRS__c.object
<CustomObject>
    <label>MRS</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>MRS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MRS_Layer_Association__c.object
<CustomObject>
    <fields>
        <fullName>MRS__c</fullName>
        <label>MRS</label>
        <referenceTo>MRS__c</referenceTo>
        <relationshipLabel>MRS Layer Association</relationshipLabel>
        <relationshipName>MRS_Layer_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>MRS Layer Association</label>
    <nameField>
        <label>Mask Layer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRS Layer Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MRS_Layer_Chip_Association__c.object
<CustomObject>
    <label>MRS Layer Chip Association</label>
    <nameField>
        <label>MRS_Layer_Chip_Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRS Layer Chip Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MRSBatchRetryMSIHTest.cls
/**
This test class covers:
- MRSBatchRetryMSIH
- MRSBatchRetryMSIHSchedulable
- MRSMSIHScheduleDispatcher

Cover triggers:
- MRS_SWIFT_BDEL
- MRS_Layer_Association_SWIFT_BDEL
- MRS_Layer_Chip_Association_SWIFT_BDEL
 */
@isTest
private class MRSBatchRetryMSIHTest {
    
    @testSetup 
    static void init() {
        SwiftDataUtilityTest.customSystemData();
        MRS_Layer_Association_SWIFT_AINS_Test.initialData();
    }

    //test for MRSBatchRetryMSIHSchedulable & MRSMSIHScheduleDispatcher
    static testMethod void test1() {
        Test.startTest();
        Datetime sysTime = System.now().addMinutes(1);
	    String cronExpression = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
	    MRSMSIHScheduleDispatcher scheduledBatch = new MRSMSIHScheduleDispatcher();
	    System.schedule( '1MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
	    System.schedule( '2MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
	    System.schedule( '3MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
	    System.schedule( '4MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
	    System.schedule( '5MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
	    System.schedule( '6MRSBatchRetryMSIHS-' + sysTime, cronExpression, scheduledBatch );
        Test.stopTest();
    }
    
    static testMethod void test2() {
        delete [select id from mrs_layer_chip_association__c limit 1];    
    }
    
    static testMethod void test3() {
        delete [select id from mrs_layer_association__c limit 1];    
    }
    
    static testMethod void test4() {
        delete [select id from mrs__c limit 1];    
    }
   
}