objects/R_Team_Room_Account__c.object
<CustomObject>
    <description>This objects is used for Team Room Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is used for storing Master Detail relationship to Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>R Team Room Accounts</relationshipLabel>
        <relationshipName>R_Team_Room_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Restricted_Team_Room__c</fullName>
        <description>This field is used for storing Master Detail relationship to Team Room.</description>
        <label>Restricted Team Room</label>
        <referenceTo>Restricted_Team_Room__c</referenceTo>
        <relationshipLabel>R Team Room Accounts</relationshipLabel>
        <relationshipName>R_Team_Room_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>R Team Room Account</label>
    <nameField>
        <displayFormat>TRA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Team Room Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/R_Team_Room_Member__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for adding Account Team members to Team room</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>R Team Room Members</relationshipLabel>
        <relationshipName>R_Team_Room_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Restricted_Team_Room__c</fullName>
        <description>Parent &quot;Restricted Team Room&quot; to which member belongs</description>
        <label>Restricted Team Room</label>
        <referenceTo>Restricted_Team_Room__c</referenceTo>
        <relationshipLabel>R Team Room Members</relationshipLabel>
        <relationshipName>R_Team_Room_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Team_Room_Role__c</fullName>
        <description>This field is used for storing Team Room Role.</description>
        <label>Team Room Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moderator</fullName>
                </value>
                <value>
                    <fullName>Internal Member</fullName>
                </value>
                <value>
                    <fullName>External Member</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R_Team_Room_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>R Team Room Member</label>
    <nameField>
        <displayFormat>TRM-{0000000000}</displayFormat>
        <label>R Team Room Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Team Room Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Restricted_Team_Room__c.object
<CustomObject>
    <description>Restricted Team Room provide added functions for work groups to collaborate, share documents, notes and meeting minutes.</description>
    <label>R Team Room</label>
    <nameField>
        <label>Restricted Team Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>R Team Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/R_TeamRoomAccoountHelper.cls
/*
Type Name: R_TeamRoomAccoountHelper Class
Author: Global Foundries(Dinesh Suggala)
Created Date: 20/6/2017
Reason: This Class is having following methods
        @OndeletingAccDeleteMembersaAndShares (On Deleting Account it will delete related members of the respective account)

Change History:
Author: 
Modified Date: 
Reason: 
……..
……..
*/

public Class R_TeamRoomAccoountHelper{
 
 public void OndeletingAccDeleteMembersaAndShares(List<R_Team_Room_Account__c> rtacclist){
 
  set<Id> accountset=new set<Id>();
  set<Id> teamroomid=new set<Id>(); 
  
  for(R_Team_Room_Account__c r: rtacclist){
   accountset.add(r.Account__c);
   teamroomid.add(r.Restricted_Team_Room__c);
  }                                                      
  
  system.debug('accsetclass'+accountset);
  system.debug('teamroomsetclass'+teamroomid);
  List<R_Team_Room_Member__c> deletememblist=[Select Id,User__c, Restricted_Team_Room__c,Team_Room_Role__c,Account__c
                                                        From R_Team_Room_Member__c where Restricted_Team_Room__c=: teamroomid and Account__c=:accountset];
 
  if(deletememblist.size()>0){
  delete deletememblist; 
  }
 }
  

}