objects/Report_Subscription__c.object
<CustomObject>
    <description>FV2 : Used to store the My Subscription Report URL in MyWafers Page.</description>
    <fields>
        <fullName>Report_ID__c</fullName>
        <label>Report ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Report Subscription</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Report Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ICC_Test_CleanUp_ReportSubscriptions.cls
@isTest(seeAllData = true)
public class ICC_Test_CleanUp_ReportSubscriptions
{
    private testMethod static void test()
    {
        try{
            Report_Subscription__c testRS = new Report_Subscription__c(Report_ID__c = 'xxxxxxxxx');
            insert testRS;
            ICC_CleanUp_ReportSubscriptions.cleanseData();
        }
        catch(Exception e)
        {
            ApplicationLogWrapper alw = new ApplicationLogWrapper();
            alw.source = ICC_Test_CleanUp_ReportSubscriptions.class.getName();
            alw.sourceFunction ='test()';
            alw.ApplicationName='ICC';
            alw.referenceInfo = 'Bug';
            alw.logMessage = 'Error Message='+e.getMessage()+' At Line Number='+e.getLineNumber()+' Stack Trace='+e.getStackTraceString();
            alw.debugLevel = 'Error';
            alw.logCode = e.getTypeName();
            alw.ex = e.getCause();
            GlobalUtility.logMessage(alw);
        }
    }
}