objects/Reticle__c.object
<CustomObject>
    <fields>
        <fullName>Invalid_Reason__c</fullName>
        <label>Invalid Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_id__c</fullName>
        <label>Job id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Reticle</label>
    <nameField>
        <label>Reticle Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Reticle_Datawarehouse__c.object
<CustomObject>
    <fields>
        <fullName>Invalid_Reason__c</fullName>
        <label>Invalid Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Reticle Datawarehouse</label>
    <nameField>
        <label>Reticle Datawarehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticle Datawarehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ROS_BATCH_DeleteInvalidReticle.cls
/*
    Author:         Ankit Singhal
    Company:        Cognizant Technology Solution
    Description:        
    History:
    
    Ankit Singhal   26082013     -     Class Creation
    CTS             10 OCt 2013        Add Varibale pass Current Cycle.
                 
    */
global class ROS_BATCH_DeleteInvalidReticle implements Database.Batchable<sObject> {
    private String invalidDataJobId;
    private List<Reticle_Datawarehouse__c> lRetDwh;
    
    public ROS_BATCH_DeleteInvalidReticle(String jobId) {
        invalidDataJobId = jobId;
        // lRetDwh = lRetDwhParam;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('SELECT Id, Invalid__c, Invalid_Reason__c FROM Reticle__c WHERE Job_Id__c = \'' + invalidDataJobId + '\'');
    }

    global void execute(Database.BatchableContext BC, List<Reticle__c> lReticleDataDel) {
        // TODO: UPDATE INVALID REASON
        // ROS_ReticleDatawareHouseBatchHelper.updateInvalidReason(lReticleDataDel, lRetDwh);
        Database.delete(lReticleDataDel);
    }
    
    global void finish(Database.BatchableContext BC) {

    }
}