objects/Reticle__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Inactive_Formula__c</fullName>
        <description>This formula field calculates actual inactive days as a difference between TODAY and &apos;Inactive Days Start Date&apos;.</description>
        <formula>IF(NOT(ISBLANK(Inactive_Days_Start_Date__c)),
   (TODAY() - Inactive_Days_Start_Date__c),
   IF(NOT(ISBLANK(Day_Inactive__c)), 
      (TODAY() - (DATEVALUE(LastModifiedDate) - Day_Inactive__c)),
      (TODAY() - DATEVALUE(LastModifiedDate))
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inactive Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Device_ID__c</fullName>
        <label>Customer Device ID</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition_Date__c</fullName>
        <label>Disposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FabStr__c</fullName>
        <label>Fab</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GlobalFoundries_Device_ID__c</fullName>
        <label>GF Device ID</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ROS_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ROS Cycle</label>
        <referenceTo>ROS_Cycle__c</referenceTo>
        <relationshipLabel>Reticles</relationshipLabel>
        <relationshipName>Reticles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROS_Status__c</fullName>
        <label>Disposition Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Return</fullName>
                    <color>#FFFF66</color>
                    <label>Return</label>
                </value>
                <value>
                    <fullName>Scrap</fullName>
                    <color>#FF0000</color>
                    <label>Scrap</label>
                </value>
                <value>
                    <fullName>Keep</fullName>
                    <color>#33CC00</color>
                    <label>Keep</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reticle_Type__c</fullName>
        <label>Reticle Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADV BIN</fullName>
                </value>
                <value>
                    <fullName>BINARY</fullName>
                </value>
                <value>
                    <fullName>COG</fullName>
                </value>
                <value>
                    <fullName>EPSM</fullName>
                </value>
                <value>
                    <fullName>PSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reticle_workflow_Status__c</fullName>
        <label>Reticle Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending to Notify Customer</fullName>
                </value>
                <value>
                    <fullName>Pending for Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Pending Witness Arrival Date</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form,Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for Fab&apos;s Follow-up</fullName>
                </value>
                <value>
                    <fullName>Pending Debit Note</fullName>
                </value>
                <value>
                    <fullName>Pending for Shipment</fullName>
                </value>
                <value>
                    <fullName>Shipped Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending HS Code Assignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Formula field to show the status of Reticle to Customer on Customer Portal</description>
        <formula>IF(AND(ISPICKVAL(ROS_Status__c,&apos;Scrap&apos;),ISPICKVAL(Reticle_workflow_Status__c,&apos;Closed&apos;)), &apos;Scrapped&apos;,IF(AND(ISPICKVAL(ROS_Status__c,&apos;Return&apos;),ISPICKVAL(Reticle_workflow_Status__c,&apos;Closed&apos;)),&apos;Shipped Out&apos;,&apos;Fab&apos;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Reticle</label>
    <nameField>
        <label>Reticle Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ROS_Cycle__c.object
<CustomObject>
    <label>ROS Cycle</label>
    <nameField>
        <label>ROS Cycle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROS Cycles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ROS_ControllerSearchReticlePortalUsers.cls
/**
* Company       :   Cognizant Technologies PTE Ltd.
* Description   :   Class to return the reticles in system mode for Portal Users
* History       :   

        Initials        Date                Description
-----------------------------------------------------------------------------------------
        Nikhil Jain     31/03/2014          Created the Class
**/

public without sharing class ROS_ControllerSearchReticlePortalUsers{ 
    
    public static List<Reticle__c> queryReticlesSystemMode(String query){
        return database.Query(query);
    }
    
    public static Database.QueryLocator queryReticlesSystemMode2(String query){
        return database.getQueryLocator(query);
    }
    
    public static boolean returnDispositionType(List<Reticle__c> LselectedReticles){
        boolean isSuccess = true;
        try{
            update LselectedReticles;
        }catch(Exception e){
            isSuccess = false;
            ROS_Util.InsertException(e,'ROS_ControllerSearchReticlePortalUsers.returnScrap','ROS');
        }
        return isSuccess;
    }
    
    
    //for displaying Reticles to Portal User
    public String UserType{get;set;}
    public Reticle__c reticleRecord{get;set;}
    public ROS_ControllerSearchReticlePortalUsers(ApexPages.StandardController controller){
        UserType =  ROS_Util.UserType();
    }
    public void displayReticle(){
        Id reticleId = ApexPages.currentPage().getParameters().get('id');
        reticleRecord = new Reticle__c();
        if(UserType == 'Customer'){
            List<Reticle__c> lstReticle = [SELECT id,name,Account__c,GlobalFoundries_Device_ID__c,Device_ID__c,Region__c,
                                                  Status__c,Reticle_Type__c,Day_Inactive_Formula__c,FabStr__c,Reticle_workflow_Status__c,
                                                  ROS_Status__c,Disposition_Date__c,ROS_Cycle__c
                                            FROM Reticle__c 
                                            WHERE id =:reticleId];
            if(lstReticle != NULL && lstReticle.size()>0){
                reticleRecord = lstReticle[0];
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Reticle not found.'));
            }
        }
    }
}