objects/Reticle__c.object
<CustomObject>
    <fields>
        <fullName>Day_Inactive__c</fullName>
        <label>Inactive Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inactive_Days_Start_Date__c</fullName>
        <description>This field stores date, when Inactive Days field on reticle record should have been 0.</description>
        <label>Inactive Days Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <formula>IF( Day_Inactive__c &gt; 365, false, true )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reticle_workflow_Status__c</fullName>
        <label>Reticle Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending to Notify Customer</fullName>
                </value>
                <value>
                    <fullName>Pending for Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Pending Witness Arrival Date</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form</fullName>
                </value>
                <value>
                    <fullName>Pending for EUC Form,Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for STF Obsolescence</fullName>
                </value>
                <value>
                    <fullName>Pending for Fab&apos;s Follow-up</fullName>
                </value>
                <value>
                    <fullName>Pending Debit Note</fullName>
                </value>
                <value>
                    <fullName>Pending for Shipment</fullName>
                </value>
                <value>
                    <fullName>Shipped Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending HS Code Assignment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reticle</label>
    <nameField>
        <label>Reticle Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reticles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ROS_BATCH_UpdateReticleInactiveDays.cls
/*
    Company:        Cognizant Technology Solution
    Description:    This batch class will update inactive days field on reticle if actual inactive days value is 366.
    History:

    CTS    18/03/2014    Class Creation
*/

global class ROS_BATCH_UpdateReticleInactiveDays implements Database.Batchable<sObject> {

    public ROS_BATCH_UpdateReticleInactiveDays() {
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date inactiveStartDate = date.today().addDays(-366);
        return Database.getQueryLocator('SELECT Id, Day_Inactive__c ' +
                                        'FROM   Reticle__c ' +
                                        'WHERE  IsActive__c = true AND ' +
                                               'Reticle_workflow_Status__c != \'Closed\' AND ' +
                                               'Inactive_Days_Start_Date__c = :inactiveStartDate');
    }

    global void execute(Database.BatchableContext BC, List<Reticle__c> listReticle) {
        if(listReticle != null && !listReticle.isEmpty()) {
            //update reticle inactive days
            for(Reticle__c reticle : listReticle) {
                reticle.Day_Inactive__c = 366;
            }

            Database.SaveResult[] srList = Database.update(listReticle, false);

            for(Database.SaveResult sr : srList) {
                if(!sr.isSuccess()) {
                    // Operation failed, so get all errors
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Reticle fields that affected this error: ' + err.getFields());        
                    }
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}