objects/RMA__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <label>Assign To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fab</fullName>
                    <default>true</default>
                    <label>Fab</label>
                </value>
                <value>
                    <fullName>Turnkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CN_DN_Number__c</fullName>
        <label>CN/DN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disposition_of_Wafers__c</fullName>
        <label>Disposition of Wafers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Return to GF</fullName>
                </value>
                <value>
                    <fullName>Return to GF and to Scrap at Customer Site</fullName>
                </value>
                <value>
                    <fullName>To Scrap at Customer Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lot_Device_To_Return__c</fullName>
        <label>Lot/Device (To Return)</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <label>RMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_DNCN__c.object
<CustomObject>
    <description>This object is maintained for storing the Credit/Debit Note for Duplicate check when creating RMA request. These DN/CN will not be associated to any RMA record, instead would have issued for a particular Invoice no.</description>
    <fields>
        <fullName>CN_DN_Number__c</fullName>
        <label>CN/DN Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>RMA DN/CN</label>
    <nameField>
        <label>Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA DN/CN</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RMA_BATCH_UpdateDNCNTest.cls
@isTest(SeeAllData= false)
private class RMA_BATCH_UpdateDNCNTest{

    @testSetup static void testdata(){
        DataUtilTest.loadEnvironmentVariables();
        Account acc = RMA_TestDataUtility.createAccount();
        RMA__c rmaRec = RMA_TestDataUtility.createRMA(1, acc); 
        
        rmaRec.Assign_to__c = 'Fab';
        rmaRec.Disposition_of_Wafers__c = 'Return to GF';
        rmaRec.Lot_Device_To_Return__c  = 'testLot1;';
        update rmaRec;
        
        rmaRec = [select id,Name from rma__c limit 1][0];
        rmaRec.Name='RMA_Test';
        update rmaRec;
        
        RMA_DNCN__c rmadncn=new RMA_DNCN__c();
        rmadncn.CN_DN_Number__c='CNDNTest';
        rmadncn.Name='RMA_Test';
        rmadncn.Transaction_Date__c=System.Today();
        rmadncn.Invoice_Number__c ='INVTest';
        rmadncn.Job_Id__c= NULL;
        insert rmadncn;
    }
       
    public static testmethod void DNCNTestMethod(){
        RMA_BATCH_UpdateDNCN batch=new RMA_BATCH_UpdateDNCN();
        test.startTest();
            ID jobID=Database.executeBatch(batch);
        test.stopTest();
        
        Rma__c rmaRec = [select id,Name,CN_DN_Number__c from rma__c where Name='RMA_Test' limit 1][0];
        System.assertEquals('CNDNTest;',rmaRec.CN_DN_Number__c);
        RMA_DNCN__c dncnrec= [select id,Name,CN_DN_Number__c,Job_Id__c from RMA_DNCN__c where Name='RMA_Test' limit 1][0];
        System.assertEquals(dncnrec.Job_Id__c, jobID);
    }      
    
}