objects/RMA_PRF_CAR_Particulars__c.object
<CustomObject>
    <description>Objects used to store CAR, PRF and Failure Code data associated to the RMA.</description>
    <fields>
        <fullName>Car__c</fullName>
        <label>Car #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot__c</fullName>
        <label>Lot #</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipName>RMA_PRF_CAR_Particulars</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>RMA Particular</label>
    <nameField>
        <displayFormat>RMA Particular-{000000}</displayFormat>
        <label>RMA Particular Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Particulars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RMA_Return_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Final_RMA_Wfr_Qty_To_Issue_CN_SO__c</fullName>
        <formula>IF( !ISBLANK(TEXT(Existing_Form_Factor__c)),
	Existing_Form_Factor_Quantity__c,
	IF(ISPICKVAL(RMA_By__c,&apos;Wafer&apos;),
		IF(NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 9&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 10&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;ALTIS&apos;)), 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;1&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;2&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;3&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;4&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;5&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;6&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;7&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;8&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;9&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;10&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;11&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;12&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;13&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;14&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;15&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;16&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;17&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;18&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;19&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;20&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;21&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;22&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;23&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;24&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Regional_Personnel_Recommended__c, &quot;25&quot;), 1,0),
			Wafer_Qty_Fab_9_10_Regional_Validation__c
		),
		IF(ISPICKVAL(RMA_By__c,&apos;Die&apos;),
			Die_Quantity_Regional_Validated__c,
			Module_Quantity_Regional_Validated__c
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity (To Issue CN/SO)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot_Number__c</fullName>
        <label>Lot #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Number__c</fullName>
        <label>PO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Return Invoices</relationshipLabel>
        <relationshipName>RMA_Return_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Wfr_Qty_after_validation__c</fullName>
        <formula>IF( !ISBLANK(TEXT(Existing_Form_Factor__c)),
	Existing_Form_Factor_Quantity__c,
	IF(ISPICKVAL(RMA_By__c,&apos;Wafer&apos;), 
		IF(NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 9&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 10&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;ALTIS&apos;)),
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;1&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;2&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;3&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;4&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;5&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;6&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;7&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;8&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;9&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;10&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;11&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;12&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;13&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;14&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;15&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;16&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;17&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;18&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;19&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;20&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;21&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;22&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;23&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;24&quot;), 1,0) + 
		IF(INCLUDES( Wafer_Id_Fab_Validated__c, &quot;25&quot;), 1,0),
			Wafer_Qty_Fab_9_10_Fab_Validation__c
		),
		IF(ISPICKVAL(RMA_By__c,&apos;Die&apos;),
		Die_Quantity_Fab_Validated__c ,
		Module_Quantity_Fab_Validated__c 
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity (FAB validation)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wafer_Id_Fab_Validated__c</fullName>
        <label>Wafer Id (Fab Validated)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wafer_Quantity__c</fullName>
        <formula>IF( !ISBLANK(TEXT(Existing_Form_Factor__c)),
	Existing_Form_Factor_Quantity__c,
	IF(	ISPICKVAL(RMA_By__c,&apos;Wafer&apos;),
		IF(NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 9&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;FAB 10&apos;)) &amp;&amp; NOT(ISPICKVAL(Fab_Group__c,&apos;ALTIS&apos;)),
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;1&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;2&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;3&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;4&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;5&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;6&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;7&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;8&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;9&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;10&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;11&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;12&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;13&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;14&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;15&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;16&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;17&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;18&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;19&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;20&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;21&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;22&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;23&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;24&quot;), 1,0) + 
			IF(INCLUDES( Wafer_Id_CSR_Submission__c, &quot;25&quot;), 1,0),
			Wafer_Qty_Fab_9_10_CSR_Submission__c
		),
		IF(ISPICKVAL(RMA_By__c,&apos;Die&apos;),
			Die_Quantity__c,
			Module_Quantity__c
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity (CSR Submission)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RMA Return Invoice</label>
    <nameField>
        <displayFormat>LI-{00000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Return Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMA_CAR_and_Invoice_Details_For_STM.cls
public class RMA_CAR_and_Invoice_Details_For_STM{

    public String rmaRecId{get;set;}
    
    
    public List<RMA_PRF_CAR_Particulars__c> getlstRMACAR(){
        return [select Car__c,Lot__c from RMA_PRF_CAR_Particulars__c where RecordTypeId =: RMA_Constants.PRFCAR_CAR and RMA__c =: rmaRecId];
    }
    
    public List<RMA_Return_Invoice__c> getlstRMAReturnInvoice(){
        return [select Invoice_Number__c,Invoice_Date__c,Purchase_Order_Number__c,Lot_Number__c,Wafer_Quantity__c,Total_Wfr_Qty_after_validation__c,
                Final_RMA_Wfr_Qty_To_Issue_CN_SO__c,Wafer_Id_Fab_Validated__c,Wafer_Id_Regional_Personnel_Recommended__c,
                Wafer_Id_CSR_Submission__c,Wafer_Die_Unit_Price__c, RMA__r.Workflow_Stage__c, RMA__r.RMA_Category__c from RMA_Return_Invoice__c where RMA__c =: rmaRecId];
    }


}