objects/RMA__c.object
<CustomObject>
    <label>RMA</label>
    <nameField>
        <label>RMA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Audit_log__c.object
<CustomObject>
    <description>This object is used to log all the events that occur in RMA process flow i.e. from the stage RMA raised till the closure of RMA.</description>
    <fields>
        <fullName>Cc__c</fullName>
        <label>Cc</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <label>Email Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <description>Audit logs are captured for each RMA. This field acts as a reference to RMA.</description>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>Audit log</relationshipLabel>
        <relationshipName>RMA_Audit_logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>This field is used in mail log to capture subject of mail.</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>RMA Audit log</label>
    <nameField>
        <displayFormat>RMA-Audit-{0000000000}</displayFormat>
        <label>RMA Audit log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Audit logs</pluralLabel>
    <recordTypes>
        <fullName>Mail_Log</fullName>
        <active>true</active>
        <label>Mail Log</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMA_MailLogInboundEmailHandler.cls
/**
* Author: Surendranadh Nune
* Company: GlobalFoundries,India
* Project: Return Material Authorization
* Description: This class is used to log emails sent from Workflows and Apex.
* History:
*    SurendranadhNune 04012016  -   Created.
*    NJain - 23Aug16 -  Included the NULL check for TO and CC Addresses. 
*                       Removing the log for noreply@salesforce.com entry from TO address    
**/
public class RMA_MailLogInboundEmailHandler implements Messaging.InboundEmailHandler {
    
    public Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email,Messaging.InboundEnvelope env){           
        try{  
            if(!email.subject.startsWith('Resend:')){
                string tempMatch='';
                boolean taskMatchFound = false;
                String rmaRegex = '(RMA[a-zA-Z0-9-]{13})';
                Pattern rmaPattern = Pattern.compile(rmaRegex);
                Matcher rmaMatcher = rmaPattern.matcher(email.subject);
                while (rmaMatcher.find()){
                    if(rmaMatcher.group(0) != NULL && rmaMatcher.group(0) != ''){
                        if(tempMatch.length() < rmaMatcher.group(0).length()){
                            tempMatch = rmaMatcher.group(0);
                            taskMatchFound = True;
                        }
                        break;
                    }
                }

                List<RMA__c> rmaList = new List<RMA__c>([SELECT ID FROM RMA__C WHERE Name like :tempMatch+'%']);
    
                if(!rmaList.isEmpty()){
                    RMA_Audit_log__c auditLog = new RMA_Audit_log__c(RecordTypeId  = RMA_Utility.getRecordTypeId('RMA_Audit_log__c', RMA_Constants.MAIL_LOG), 
                                                                     rma__c = rmaList[0].id);
                    auditLog.From__c = email.fromAddress;
                    if(email.toAddresses != NULL){
                        auditLog.To__c  = string.valueOf(JSON.serialize(email.toAddresses)).replace('"','').replace('[','').replace(']','').replace(',',', '); 
                        auditLog.To__c = auditLog.To__c.replace('noreply@salesforce.com','');
                    }
                    if(email.ccAddresses != NULL){
                        auditLog.CC__c  = string.valueOf(JSON.serialize(email.ccAddresses)).replace('"','').replace('[','').replace(']','').replace(',',', ');
                    }
                    auditlog.Subject__c = email.subject;  
                    auditlog.email_body__c= email.htmlbody;
                    insert auditlog;
                }
            }
        }catch(Exception e){
			GlobalUtility.logMessage('Error', RMA_MailLogInboundEmailHandler.class.getName(), 'handleInboundEmail', '','Mail Log',
                                      'Error Message='+e.getMessage()+' At Line Number='+e.getLineNumber()+' Stack Trace='+e.getStackTraceString(), 
                                      '','RMA',e, NULL);
        }
        return null;                                               
    }
}