objects/SFDC_Project__c.object
<CustomObject>
    <description>SFDC Project</description>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority_Sequence__c</fullName>
        <label>Priority Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SFDC Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDC Portfolio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_Project_Milestone__c.object
<CustomObject>
    <description>An SFDC Project Milestone.</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <referenceTo>SFDC_Project_Stage__c</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone2</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Project_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Stage Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User Request</fullName>
                </value>
                <value>
                    <fullName>Approved for Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment &amp; Vendor Evaluation</fullName>
                </value>
                <value>
                    <fullName>Recommendation</fullName>
                </value>
                <value>
                    <fullName>Approved for Implementation</fullName>
                </value>
                <value>
                    <fullName>Implementation Planning</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Build &amp; Deploy</fullName>
                </value>
                <value>
                    <fullName>Post-Deployment Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC Project</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SFDCMilestoneExtTest.cls
/*
    Author: Win
    Created Date: Feb/25/2013 
    Description: Test class for SFDCMilestoneExt
    Test cases: 
    1. 
*/

@isTest
public class SFDCMilestoneExtTest{

    static testMethod void doTest1(){
        test.startTest();
        //initialize variables, populate data structures
        
        SFDC_Project__c newPro = new SFDC_Project__c(Name='red',Overall_Status__c='Red',Priority_Sequence__c=0);
        insert newPro;
        
        SFDC_Project_Stage__c newStage = new SFDC_Project_Stage__c(Name='Test Stage',Name__c='User Request');
        insert newStage;
        
        newStage.SFDC_Project__c = newPro.id;
        update newStage;
        
        SFDC_Project_Milestone__c milestone = new SFDC_Project_Milestone__c (Name='Test Milestone', Stage__c = newStage.id);
        insert milestone;
        
        ApexPages.StandardController controller = new ApexPages.StandardController(milestone);
        
        SFDCMilestoneExt ext = new SFDCMilestoneExt(controller);
        ext.getImplementationStageName();
        ext.getStage();
        
        test.stopTest();

    }
}