objects/SWIFT_Application_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Component_Name__c</fullName>
        <label>Apex Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Debug_Level__c</fullName>
        <label>Debug Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error/Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Payload__c</fullName>
        <label>Integration_Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Auto_Retry__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this log will be auto retry by time based workflow + trigger</description>
        <label>Is Auto Retry?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_ID__c</fullName>
        <description>Message ID of the Inbound Web Service request from the interfacing system.</description>
        <label>Message ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retry_Status__c</fullName>
        <label>Retry Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N.A.</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Queue</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SWIFT Application Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Sequence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SWIFT Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MRSDeselectionUtils.cls
/*
SWGP-882: [PTRF WS] PTRF Layer Chip Deselection
Test class is:
- MRSDeselectionServiceTest
*/
public class MRSDeselectionUtils {
    
    public class NotificationResponse {
        public String transactionStatus {get;set;}
        public String transactionErrorMessage {get;set;}
        public String messageId {get;set;}
        public String ptrfNumber {get;set;}
        public List<LayerChipResponse> layerChipList {get;set;}
        public List<PTRFMaskLayerResponse> ptrfMaskLayerList {get;set;}
        public List<PTRFChipResponse> ptrfChipList {get;set;}
    }
    
    public class LayerChipResponse {
        public String status {get;set;}
        public String errorMessage {get;set;}
        public Integer no {get;set;}
        public String sfdcId {get;set;}
        public String layerNumber {get;set;}
        public String revision {get;set;}
        public String chipName {get;set;}
        public String romCode {get;set;}
    }
    
    public class PTRFMaskLayerResponse {
        public String status {get;set;}
        public String errorMessage {get;set;}
        public Integer no {get;set;}
        public String layerNumber {get;set;}
        public String revision {get;set;}
        public String romCode {get;set;}
    }
    
    public class PTRFChipResponse {
        public String status {get;set;}
        public String errorMessage {get;set;}
        public Integer no {get;set;}
        public String chipName {get;set;}
        public String chipType {get;set;}
    }
    
    public static SWIFT_Application_Log__c logUnhandledException(Exception e, String wsMsg, String msgId, String className, String methodName, String ptrfNumber, String errorMsg){
        
        if(wsMsg.length() > 32000) wsMsg   = wsMsg.subString(0,32000);
        
        SWIFT_Application_Log__c log    = new SWIFT_Application_Log__c(
            Debug_Level__c              = 'ERROR',     
            Apex_Component_Name__c      = className,     
            Method__c                   = methodName,
            Integration_Payload__c      = wsMsg,     
            Error_Message__c            = errorMsg,     
            Stack_Trace__c              = e.getStackTraceString(),
            Message_ID__c               = msgId + ' | ' + ptrfNumber
        );

        if(e != null && e.getMessage().containsIgnoreCase('unable to obtain exclusive access')) {
            log.Is_Auto_Retry__c = true;
            log.Retry_Status__c = 'New';
        }
        
        insert log; 
        return log;
    }
    
    public static SWIFT_Application_Log__c logRequestResponse(String request, String response, String errorMsg, String msgId, String className, String methodName, String ptrfNumber){
        
        if(request.length() > 32000)    request  = request.subString(0,32000);
        if(response.length() > 32000)   response = response.subString(0,32000);
        
        SWIFT_Application_Log__c log    = new SWIFT_Application_Log__c(
            Debug_Level__c              = 'DEBUG', 
            Apex_Component_Name__c      = className     , 
            Method__c                   = methodName,    
            Integration_Payload__c      = request, 
            Stack_Trace__c              = response, 
            Error_Message__c            = errorMsg,
            Message_ID__c               = msgId + ' | ' + ptrfNumber
        );
        
        insert log; 
        return log;
    }
}