objects/VoC__c.object
<CustomObject>
    <description>Voice of the Customer</description>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Enter short comments. Longer comments can be entered in the post after saving the record.</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <inlineHelpText>Who was contacted?</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>VoCs</relationshipLabel>
        <relationshipName>VoCs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>VoC</label>
    <nameField>
        <displayFormat>VOC-{000000}</displayFormat>
        <label>VOC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VoCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VoC_Score__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technology Roadmap</fullName>
                </value>
                <value>
                    <fullName>Fab Operations</fullName>
                </value>
                <value>
                    <fullName>Assurance of Supply</fullName>
                </value>
                <value>
                    <fullName>Design Enablement</fullName>
                </value>
                <value>
                    <fullName>Capacity</fullName>
                </value>
                <value>
                    <fullName>Attentiveness</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Ease of Doing Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <formula>VoC__r.Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade_5_best__c</fullName>
        <label>Grade (5 best)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VoC__c</fullName>
        <label>VoC</label>
        <referenceTo>VoC__c</referenceTo>
        <relationshipName>Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>VoC Score</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VoC Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/VoCAreaTrend__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Api_Name__c</fullName>
        <label>Api Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>VoCAreaTrend</label>
</CustomObject>

classes/VoCScoreTriggerUtil.cls
public class VoCScoreTriggerUtil{

    public static void manageTrends(List<VoC_Score__c> newRec, Map<Id,VoC_Score__c> oldRecMap, String event){
        Set<ID> contactId = new Set<ID>();
        List<VoC_Score__c> listToProcess = new List<VoC_Score__c>();
        Map<ID,Map<String,Decimal>> mapContactsVoCScore = new Map<ID,Map<String,Decimal>>();
        Map<ID,Map<String,Decimal>> mapContactsVoCCOunt = new Map<ID,Map<String,Decimal>>();        
        List<Contact> contactList = new List<Contact>();
        Map<String,VoCAreaTrend__c> vocTrend = VoCAreaTrend__c.getAll();        
        Map<Id,Contact> contactToUpdate = new Map<Id,Contact>();
        Set<Id> vcsId = new Set<Id>();  
         
        if(oldRecMap != null && !oldRecMap.isEmpty() && event == 'update'){        
            for(VoC_Score__c vcs : newRec){            
                if(vcs.Grade_5_best__c != oldRecMap.get(vcs.id).Grade_5_best__c){
                    contactId.add(vcs.contact_Id__c);                    
                    listToProcess.add(vcs); 
                    vcsId.add(vcs.id);                                    
                }                
            }            
        }
        else{
            for(VoC_Score__c vcs : newRec){
                contactId.add(vcs.contact_id__c);
                listToProcess.add(vcs);                                              
            }
        }                                   
        
        for(VoC_Score__c vcs : [SELECT id, Area__c, Comments__c, Grade_5_best__c, Score__c, VoC__c, contact_id__c, VoC__r.contact__c FROM voc_score__c where voc__r.contact__c in : contactId and id not in: vcsId]){                                    
                if(!mapContactsVoCScore.containsKey(vcs.contact_id__c)){
                    mapContactsVoCScore.put(vcs.contact_id__c,new map<String,Decimal>());                           
                }            
                if(!mapContactsVoCScore.get(vcs.contact_id__c).containsKey(vcs.Area__c)){
                        mapContactsVoCScore.get(vcs.contact_id__c).put(vcs.Area__c,0);                    
                }
                if(!mapContactsVoCCOunt.containsKey(vcs.contact_id__c)){
                    mapContactsVoCCOunt.put(vcs.contact_id__c,new map<String,Decimal>());                           
                }            
                if(!mapContactsVoCCOunt.get(vcs.contact_id__c).containsKey(vcs.Area__c)){
                        mapContactsVoCCOunt.get(vcs.contact_id__c).put(vcs.Area__c,0);                    
                }           
            mapContactsVoCScore.get(vcs.contact_id__c).put(vcs.Area__c,mapContactsVoCScore.get(vcs.contact_id__c).get(vcs.Area__c) + Integer.valueOf(vcs.Grade_5_best__c)); 
            mapContactsVoCCOunt.get(vcs.contact_id__c).put(vcs.Area__c,mapContactsVoCCOunt.get(vcs.contact_id__c).get(vcs.Area__c) + 1);           
        }
        
        for(VoC_Score__c vcs : listToProcess){
            Contact con;
            Decimal oldAvg;
            Decimal newAvg;
            
            if(!mapContactsVoCScore.isEmpty() && !mapContactsVoCCOunt.isEmpty() && mapContactsVoCScore.get(vcs.contact_id__c).get(vcs.Area__c) != null && mapContactsVoCCOunt.get(vcs.contact_id__c) != null){
                 if(event == 'insert' || event == 'update'){     
                     oldAvg = mapContactsVoCScore.get(vcs.contact_id__c).get(vcs.Area__c)/mapContactsVoCCOunt.get(vcs.contact_id__c).get(vcs.Area__c);
                     newAvg = (mapContactsVoCScore.get(vcs.contact_id__c).get(vcs.Area__c) + Integer.valueOf(vcs.Grade_5_best__c))/(mapContactsVoCCOunt.get(vcs.contact_id__c).get(vcs.Area__c) + 1);                
                 }
                 else{
                     if(mapContactsVoCCOunt.get(vcs.contact_id__c).get(vcs.Area__c) - 1 != 0){
                         newAvg = (mapContactsVoCScore.get(vcs.contact_id__c).get(vcs.Area__c) - Integer.valueOf(vcs.Grade_5_best__c))/(mapContactsVoCCOunt.get(vcs.contact_id__c).get(vcs.Area__c) - 1); 
                     }
                     else{
                         newAvg = 0;
                     }               
                 }
            }
            else{
                 if(event == 'insert' || event == 'update'){                 
                     oldAvg = 0;
                     newAvg = Integer.valueOf(vcs.Grade_5_best__c); 
                 }               
            }
            
            if(contactToUpdate != null && !contactToUpdate.containsKey(vcs.contact_id__c)){
                    contactToUpdate.put(vcs.contact_id__c,new Contact()); 
                    con = new Contact(id = vcs.contact_id__c);
                    con.put(vocTrend.get(vcs.Area__c).Api_Name__c,newAvg); 
                    contactToUpdate.put(vcs.contact_id__c,con);                     
            }
            else{
                contactToUpdate.get(vcs.contact_id__c).put(vocTrend.get(vcs.Area__c).Api_Name__c,newAvg);                
            }            
                        
            if(event == 'insert' || event == 'update'){ 
                vcs.score__c = Integer.valueOf(vcs.Grade_5_best__c); 
            }           
        }
        
        if(!contactToUpdate.isEmpty()){
            upsert contactToUpdate.values();
        }
    }
    
    public static void fetchVoCScoreListOnVoCDelete(List<VoC__c> delVoCList){
        Set<Id> vocId = new Set<Id>();
        
        for(VoC__C vc: delVoCList){
            vocId.add(vc.id);
        }
        
        List<VoC_Score__c> vocScoreList = [SELECT id, Area__c, Comments__c, Grade_5_best__c, Score__c, VoC__c, contact_id__c, VoC__r.contact__c FROM voc_score__c WHERE voc__c =: vocId];
        if(!vocScoreList.isEmpty()){
            manageTrends(vocScoreList,null,'delete');
        }
    }          
}