objects/Waiver_Rule_List__c.object
<CustomObject>
    <fields>
        <fullName>Final_Stage__c</fullName>
        <label>Final Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Die_Name__c</fullName>
        <description>data here comes from the integration</description>
        <label>Prime Die</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiver_Collaborator__c</fullName>
        <label>Waiver Collaborator</label>
        <referenceTo>Wavier_Collaborator__c</referenceTo>
        <relationshipLabel>Waiver Rule Lists</relationshipLabel>
        <relationshipName>Waiver_Rule_Lists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Waiver Rule List</label>
    <nameField>
        <displayFormat>DRC-{000000}</displayFormat>
        <label>Rule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiver Rule Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wavier_Collaborator__c.object
<CustomObject>
    <fields>
        <fullName>Prime_Die_Name__c</fullName>
        <label>Prime Die Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Waiver Collaborator</label>
    <nameField>
        <displayFormat>Collaborator-{0000}</displayFormat>
        <label>Waiver Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiver Collaborator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DWC_SetOfFinalStatusCtrl_test.cls
@isTest(SeeAllData=false)
public class DWC_SetOfFinalStatusCtrl_test {
    
    static testMethod void mySetOfFinalStatusMethod(){
        
		Wavier_Collaborator__c waiverColl = DesignCollaboratorTestData.getWaiverCollaborator0();
        Waiver_Rule_List__c  waiverCollList = new Waiver_Rule_List__c();
        waiverCollList.Final_Stage__c = 'Open';
        waiverCollList.Prime_Die_Name__c = 'Test';
        waiverCollList.Waiver_Collaborator__c = waiverColl.Id;
        insert waiverCollList;
        
        Set<String> setofStatus = new Set<String>();
        setofStatus.add(waiverCollList.Final_Stage__c);      
        String collabId = String.valueOf(waiverColl.Id);
        
        Test.startTest();
        DWC_SetOfFinalStatusCtrl dSetFinalStatus = new DWC_SetOfFinalStatusCtrl();
        DWC_SetOfFinalStatusCtrl.updateReleaseToCustFlag(collabId,setofStatus);
        dSetFinalStatus.init();
        Test.stopTest();
        System.assertEquals(setofStatus,setofStatus);
    }    
}