objects/Waiver_Rule_List__c.object
<CustomObject>
    <fields>
        <fullName>MantisId__c</fullName>
        <formula>Text(Waiver_Collaborator__r.MantisId__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MantisId</label>
        <type>Text</type>
    </fields>
    <label>Waiver Rule List</label>
    <nameField>
        <displayFormat>DRC-{000000}</displayFormat>
        <label>Rule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiver Rule Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wavier_Collaborator__c.object
<CustomObject>
    <fields>
        <fullName>MantisId__c</fullName>
        <label>MantisId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTSR_Number__c</fullName>
        <externalId>true</externalId>
        <label>PTSR Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTSR_Service_Type__c</fullName>
        <label>PTSR Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DRC Service Request</fullName>
                </value>
                <value>
                    <fullName>DFM Service Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PTSR_Status__c</fullName>
        <label>PTSR Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiver_Status__c</fullName>
        <label>Aggregated Waiver Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved,Exceptional arrangement</fullName>
                </value>
                <value>
                    <fullName>Approved,Customer agree to take risk</fullName>
                </value>
                <value>
                    <fullName>WEA</fullName>
                </value>
                <value>
                    <fullName>WCR</fullName>
                </value>
                <value>
                    <fullName>FCF</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PW</fullName>
                </value>
                <value>
                    <fullName>pWO</fullName>
                </value>
                <value>
                    <fullName>pOC</fullName>
                </value>
                <value>
                    <fullName>FD</fullName>
                </value>
                <value>
                    <fullName>VCP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Waiver Collaborator</label>
    <nameField>
        <displayFormat>Collaborator-{0000}</displayFormat>
        <label>Waiver Collaborator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waiver Collaborator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DRC_JsonGeneratorTest.cls
/*
    @Author :- SUHAS BARGI
*/
@isTest(SeeAllData=false)
private class DRC_JsonGeneratorTest {  
	
	/*@testSetup static void testdata() {
        DataUtilTest.loadEnvironmentVariables(); 
    }*/

static testMethod void myJsonGeneratorTestMethod() { 
    
     Test.startTest(); 
    Wavier_Collaborator__c waiverColl = DesignCollaboratorTestData.getWaiverCollaborator0();
    waiverColl.MantisId__c=545454;
    waiverColl.PTSR_Service_Type__c='DRC Request Type';
    waiverColl.PTSR_Number__c='PTSR1234';
    waiverColl.Waiver_Status__c='Pending';
    waiverColl.PTSR_Status__c='WCR';
    
    DRC_JsonGenerator jsonGen = new DRC_JsonGenerator();
    //jsonGen.objType='Wavier_Collaborator__c';
   
    DesignCollaboratorTestData.getWaiverRuleListForFDCCWCR(waiverColl.Id);
    List<Waiver_Rule_List__c> waiverRuleListForTest = new List<Waiver_Rule_List__c>();
    waiverRuleListForTest=DesignCollaboratorTestData.getWaiverRuleList(waiverColl.Id);
   
    DRC_JsonGenerator.getJsonRequest(waiverRuleListForTest, waiverColl);
    DRC_JsonGenerator.getJsonRequestForRevert(waiverRuleListForTest, waiverColl);
    Test.stopTest();
    

}
    
    
    
}