objects/Waivers__c.object
<CustomObject>
    <description>Object used to store waiver record for different  milestone.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiver_Applied_to_with_values_as_below__c</fullName>
        <label>Waiver applied quality level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P Level Only</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Waivers</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Waivers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Waiver_TriggerHandler.cls
/*************************************************************************************************************************************************************
@ Class:          Waiver_TriggerHandler
@ Version:        1.0
@ Author:         Mallika
@ Purpose:        This Handler class is handling the events of Waiver Triggers.
--------------------------------------------------------------------------------------------------------------------------------------------------------------
**************************************************************************************************************************************************************/
public class Waiver_TriggerHandler extends TriggerHandler{
   
    public Waiver_TriggerHandler(){
       
    }
    
    /*********************************************************************************************************************************************************
    @ Method:         afterupdate
    @ Version:        1.0
    @ Author:         Mallika
    @ Purpose:        This method is calling all the method which needs to be triggered in after update event.
    **********************************************************************************************************************************************************/    
    public override void afterUpdate(){
        
        if(trigger.isupdate){
          for(Waivers__c Waiver: (List<Waivers__c>)trigger.new)
          {
           if((Waiver.Approval_Status__c == 'Approved')&& (Waiver.Waiver_Applied_to_with_values_as_below__c=='' || Waiver.Waiver_Applied_to_with_values_as_below__c==null))  {
        
           Waiver.addError('please fill required field for approval Waiver applied quality level Steps to follow > Click Back button > Cancel Waiver approval > Unlock record > fill Waiver applied quality level as P level Only/All');
         
           }
          }
        
        }
      
        
    }
}